### ISSUE TITLE
the yuv image interface discussion

### ISSUE THREAD

**Issue by JerryShih** [servo/webrender#1001]
Currently, webrender uses 3 different image keys for a planer yuv image(there are 3 y, u and v channels).
```
    pub fn push_yuv_image(&mut self,
                          rect: LayoutRect,
                          clip: ClipRegion,
                          y_key: ImageKey,
                          u_key: ImageKey,
                          v_key: ImageKey,
                          color_space: YuvColorSpace)
```
I'm considering use one image key for the 3 of y, u and v channels. It would be less error prone and would facilitate gecko integration. For this change, we need to do a bit more complicated in the resource cache(but I think it's probably not too much).

@nical @sotaroikeda @kvark @glennw 
Any idea for this change?

**Comment by glennw** [comment]
My initial reaction is that it will actually turn out to be quite complicated inside WR, and I'd prefer to avoid it.

But that's just an initial reaction - it's hard to say for sure without seeing some kind of prototype / patch, which might prove me wrong!

**Comment by nical** [comment]
I am keen on having the yuv planes as well as the color space associated with the image (during creation and update of the image object) for yuv images and thus associated to the same ImageKey, instead of being associated to the display item, if that can be done without complicating the code too much.

I suppose it would boil down to having resource cache items potentially associated to several texture cache items. It would take one to prototype this to see if the implementation ends up being enough simple I guess.

If it is too complicated that's not a big deal, really. It would just be nice.

**Comment by JerryShih** [comment]
I have done the all implementations with this idea, but code is not clear. And it doesn't resolve the original problem for integrating gecko with WR. In gecko, we try to map a externalImage id to a textureHost. In some video case, a textureHost could contain more than one channel data(e.g. format yuv have 3 channel, and nv12 have 2 channel). So, I change to add a parameter called channel_index in ExternalImageData and ExternalImageHandler. Then, we could use both ExternalImageId and channel_index to get the specific image channel data.

```
 pub struct ExternalImageData {
     pub id: ExternalImageId,
+    pub channel_index: u8,
     pub image_type: ExternalImageType,
 }
```

```
 pub trait ExternalImageHandler {
     /// Lock the external image. Then, WR could start to read the image content.
     /// The WR client should not change the image content until the unlock()
     /// call.
-    fn lock(&mut self, key: ExternalImageId) -> ExternalImage;
+    fn lock(&mut self, key: ExternalImageId, channel_index: u8) -> ExternalImage;
     /// Unlock the external image. The WR should not read the image content
     /// after this call.
-    fn unlock(&mut self, key: ExternalImageId);
+    fn unlock(&mut self, key: ExternalImageId, channel_index: u8);
 }
```
