### ISSUE TITLE
Improve BlobImageRenderer serialization

### ISSUE THREAD

**Issue by nical** [servo/webrender#1017]
We have a naive BlobImageRenderer implementation in Gecko in which _everything_ is serialized (including images, font data, paths, etc.) each time a blob image is created or updated. This is far from ideal.
I would like to extend the BlobImageRenderer interface so that it can get access to some of the data stored in the resource cache, in particular font data and images.

As part of that I would also like to add path objects to WebRender's API which would be stored in the resource cache (but wouldn't have a display item that can use them yet until someone has a crack at implementing SVG features in WebRender) to avoid re-serializing paths every time a blob image is updated. The API for paths would be similar to images (retained objects with add_path/update_path/delete_path methods on the RenderApi).

Thoughts?

**Comment by kvark** [comment]
Isn't this a dupe of #402?

**Comment by nical** [comment]
The overlap is only the addition of retained path objects. This issue focuses on making BlobImageRenderer not prohibitively expensive to use (I expect most of the wins to be in reusing the images and font data) while #402 pursues the more long term goal of supporting SVG primitives in WebRender proper.

**Comment by glennw** [comment]
@nical Is this still relevant?

**Comment by nical** [comment]
It'd still be nice to have path objects in the resource cache but I don't think it's critical. We can revisit whenever the time's right.
