### ISSUE TITLE
Optimize array allocation

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1029]
Profiling on OSX shows that we spend a large chunk of time (54% IIRC) in the routine that doubles the allocated storage for `Vec`. We should make a pass over the code and try to re-use the original storage in as many spaces as possible. Another way to address it is to use `Vec::with_capacity` constructors.

The issue can't be fixed once and for all, so a completion criterion would be:
  - making a pass over all the code, especially the `FrameBuilder::add_primitive` path
  - profiling CPU again and checking how much the time dropped

cc @jrmuizel

**Comment by glennw** [comment]
We have ```Vec``` recycling now, and I haven't seen resizing in the profiles for a long time.
