### ISSUE TITLE
During a transition on opacity, pixel ratio is wrong 

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#103]
![ese](https://cloud.githubusercontent.com/assets/373579/11532230/cb2f235a-9902-11e5-90fa-d0112ebceb07.gif)

In the following example, when the transition starts, the text is scaled up. It doesn't appear to happen with a pixel ratio of 1, so I think it's specific to retina displays.

```html
<style>

  div {
    margin: 100px;
    width: 200px;
    height: 200px;
    background: red;
    transition: opacity 1s linear;
  }

  div:hover {
    opacity: 0.5;
  }

</style>

<div>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>
```

**Comment by glennw** [comment]
@paulrouget There is a blending problem with the text (I think I know what this is) on this test, but I can't reproduce the pixel ratio issue. Can you confirm this?

**Comment by paulrouget** [comment]
No pixel ratio issue anymore.

**Comment by paulrouget** [comment]
Nope, sorry, I'm wrong.

The pixel ratio issue is still here.

**Comment by paulrouget** [comment]
<img width="258" alt="screen shot 2016-02-08 at 07 19 33" src="https://cloud.githubusercontent.com/assets/373579/12879500/5cdb8a44-ce34-11e5-9af4-5cc8079fbc90.png">

**Comment by glennw** [comment]
No longer occurring.
