### ISSUE TITLE
Consider moving the IPC boundary in Servo from WR to the constellation.

### ISSUE THREAD

**Issue by emilio** [servo/webrender#1049]
See the conversation in #991 and linked IRC log. This is split from that.

This will allow us to move all the IPC complexity back into Servo, and probably tidy the API a bit (also making it more efficient where IPC is not needed).

cc @nical @staktrace

**Comment by jrmuizel** [comment]
Gecko currently avoids using WebRender through IPC and the current IPC code in WebRender is not very efficient (see https://github.com/servo/webrender/pull/1041). The simplification that could come from removing the ipc stuff from webrender would be nice.

**Comment by atouchet** [comment]
The IPC API was removed from WebRender. Is this issue still relevant?

**Comment by jdm** [comment]
Nope.
