### ISSUE TITLE
inset shadow + border radius: crash

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#105]
<img width="840" alt="screen shot 2015-12-02 at 16 48 12" src="https://cloud.githubusercontent.com/assets/373579/11535524/8e508f3e-9914-11e5-8003-1c5473f2f24e.png">

```html
<style>

  .a {
    width: 400px;
    height: 400px;
    background-color: red;
  }

  .b {
    width: 300px;
    height: 20px;
    margin: 50px;
    border-radius: 1000px;
    box-shadow: inset 0 0 0 2px #0F0;
  }

</style>


<div class="a">
  <div class="b">
  </div>
</div>
```

**Comment by pcwalton** [comment]
This actually crashes both GPU drivers on my MacBook Pro. Exciting!

**Comment by glennw** [comment]
@paulrouget The test above looks the same for me in WR vs. non-WR now - could you confirm on mac? It's wrong in both cases - I'm not sure if that's an issue on the Servo or WR side.

**Comment by paulrouget** [comment]
Erf, now it crashes my macbook. Like @pcwalton says.

**Comment by glennw** [comment]
No longer occurring.
