### ISSUE TITLE
Text blur produces artifacts

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1085]
Running the reftest from https://github.com/servo/webrender/pull/1084/commits/dd5b038bf62f0857d9dcc4d6444a5a8b449734ce gives me artifacts around the edges. The artifacts are not deterministic.

See: https://people-mozilla.org/~jmuizelaar/tmp/text-blur.png

**Comment by kvark** [comment]
Looks like we aren't properly bounding the sampling area for the blur, which is required given we have no borders added now.

**Comment by glennw** [comment]
I believe this is resolved with https://github.com/servo/webrender/pull/1488 - please re-open if still an issue.
