### ISSUE TITLE
Avoid calling glReadPixels directly in wrench

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1086]
It would be better if we had a decent API for this.

Thoughts:
glReadPixels returns flipped images. This is garbage.
The flip can be avoided using ANGLE_pack_reverse_row_order or MESA_pack_invert. On platforms where we don't have these extensions we could return an image with negative stride. Callers would need to handles this and flip as needed. This avoids flipping when we're just trying to compare the images.

**Comment by kvark** [comment]
I'd argue that this is a fault of GL coordinate system, not `glReadPixels`, but the point stays.
Calling `gl::read_pixels` directly should only be allowed from `device.rs`, which can be responsible for flipping it and hiding the logic of using the named extensions.

**Comment by glennw** [comment]
This got fixed.
