### ISSUE TITLE
Clip coordinates on items and in clip display items are specified in different coordinate systems

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#1090]
These should really be reworked to be the same in either case. We just need to decide what makes the most sense given the API and the internals of how clipping works.

**Comment by kvark** [comment]
I think basing off the reference frame makes sense, since it means using existing GPU layers for transformations.

**Comment by mrobinson** [comment]
@kvark If we use the reference-frame-relative approach is that it would also make sense to have all other coordinates relative to reference frames. This would require walking the display list and recalculating everything in Servo (not sure how it is in Gecko). I suppose we just need to decide if this is worth the cost.
