### ISSUE TITLE
thread 'RenderBackend' panicked at 'Each render task must allocate <= size of one target! (1601×1485)

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1122]
While running a gecko reftest with some local changes to the gecko-side code, I am able to trigger an assertion failure in webrender. It might very well be that I'm doing something wrong on the gecko side, but given the assertion that's failing I think this is likely a bug on the webrender side. Note that I'm using webrender at cset 3dd68f54e12bd5abf8ef41de4d4ec851620f7e4e. I was able to save a binary recording which reproduces the assertion if I run `wrench replay --play wr-record-3.bin`. I don't know if that's useful but you can get the wr-record-3.bin [here](https://people-mozilla.org/~kgupta/tmp/wr-record-3.bin).

**Comment by kvark** [comment]
Thanks @staktrace ! I'm able to repro the issue with your recordings.

It's a task failing to allocate RT space for a large mask. We don't currently handle this case nicely. Perhaps, we need to be able to split the large primitives in order to avoid this situation.

**Comment by glennw** [comment]
There's two pieces of code that are supposed to prevent this occurring:

1) Intermediate render targets are always allocated to be the same size as the current framebuffer.
2) Clip mask task rects are intersected with the current screen rect.

Between them, this should in theory ensure that a task is never allocated a rect larger than the size of one layer in the intermediate render target array.

Perhaps there's a bug / regression in how that code works, or a logic bug that I haven't considered in that?
