### ISSUE TITLE
Where the tags goes?

### ISSUE THREAD

**Issue by lygstate** [servo/webrender#1138]

**Comment by KiChjang** [comment]
Can you give more details as to what problem you're seeing here?

**Comment by lygstate** [comment]
@KiChjang I am talking about https://github.com/servo/webrender/releases

**Comment by KiChjang** [comment]
It's still not clear to me what you're trying to achieve here.

**Comment by lygstate** [comment]
@KiChjang  Yes

**Comment by jrmuizel** [comment]
> @KiChjang Yes

Why?

**Comment by KiChjang** [comment]
@lygstate This is a lot of back-and-forth. Could you please explain the problem that you're seeing right now, and how adding tags on every version update would help alleviate it?
