### ISSUE TITLE
Is it webrender ready to be used outside of servo?

### ISSUE THREAD

**Issue by siriux** [servo/webrender#1145]
I'm considering to use webrender in a project but first I would like to know if you think it's ready (or if it will be any time soon) to be used outside of servo in a real application. 

On the documentation says that it can be used in other applications, but it's not published on crates.io and there is no mention on api stability or the future of the project independently from servo.

Thanks for your great work !

**Comment by kvark** [comment]
@siriux it's being used by Gecko too, as a part of the Quantum Renderer project. Both Servo and Gecko constantly keep up with master branch here and link to specific git revisions. The API changes quite often still, so we are not at the point of publishing and stabilizing it yet.

I'd be very interested to see other applications using WR as well. Moreover, I don't think publishing some versions on `crates.io` will disrupt the usual Gecko/Servo workflow in any way, but I suppose @glennw might have other considerations. Either way, you must be prepared for constant headache of breaking changes ;)

**Comment by siriux** [comment]
Thanks for the info, it will be really useful to decide if I go with it.

Frequent breaking changes is a little bit scary, so I'll try to research more the alternatives and prototype something with webrender before deciding.

**Comment by nical** [comment]
I'd like that we fix the crate names before thinking about publishing on crates.io. ```webrender_traits``` is terribly confusing for a crate that barely contains any trait. I think that there were discussions about calling it ```webrender_types``` or ```webrender_api``` I don't remember exactly.

Once we publish on crates.io, we don't need to break the api there continuously (as in we don't need to publish versions on crates.io every day), we can just publish versions when major things land.

**Comment by glennw** [comment]
Closing this since it's not actionable by itself.
