### ISSUE TITLE
Using varying structs can cause shader errors

### ISSUE THREAD

**Issue by rlhunt** [servo/webrender#1157]
I get shader errors on my windows machine when using structs as in/out between VS and FS shaders.

We replaced one of the instances of this in #1136 , which fixed my startup crash. But I still get errors for other shaders, usually `ps_border` with `flat varying RectWithSize vBorderRect`.

This is happening to me with WebRender on ANGLE, I believe it happens to others on OpenGL. 

It would suck to go back to using untyped vec4's for all these cases, so it'd be nice to find a workaround. There might not be one and we might have to revert parts of c31376b.

**Comment by rlhunt** [comment]
@kvark @glennw thoughts?

**Comment by sotaroikeda** [comment]
I also faced the problem on my laptop.

**Comment by kvark** [comment]
I don't see a prospect of workaround, let's revert the `varying` structs to regular vectors, for now at least.
@nical - to document this in the driver bug registry ;)

**Comment by CAfromCA** [comment]
If you ever need to test against an Intel HD Graphics 3000 (Sandy Bridge iGPU), I have one and am willing to help.
