### ISSUE TITLE
switching from "visibility:hidden" to "visibility:visible", iframe size is wrong for a short period of time

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#116]
It's hard to tell if it's a webrender-specific issue or not. Maybe non-webrender builds are not fast enough to show the problem.

While an iframe switch from `visibility:hidden` to `visibility:visible` (or `display:none` to `display:block`), for a very short period of time (one frame), the size of its content is wrong. The 3 following screenshots are 3 consecutive frames:

<img width="320" alt="screen shot 2015-12-10 at 09 11 22" src="https://cloud.githubusercontent.com/assets/373579/11710308/710f617e-9f1e-11e5-85d5-a4ef70834dbb.png">

```html
<style>
  iframe {
    display: block;
    border-width: 0;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    position: absolute;
  }
  iframe.s {
    visibility: hidden; /* or display: none */
  }
</style>

<iframe mozbrowser="true" src="http://firefox.com"></iframe>

<script>
  setInterval(() => document.querySelector("iframe").classList.toggle("s"), 500);
</script>
```

**Comment by paulrouget** [comment]
It doesn't happen if I use `opacity:0` instead of `display:none` or `visibility:hidden`.

**Comment by paulrouget** [comment]
Still happening.

**Comment by glennw** [comment]
Fixed by https://github.com/servo/servo/pull/9813
