### ISSUE TITLE
Travis doesn't run the same code for all jobs.

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1162]
Travis runs `git fetch origin +refs/pull/1155/merge`. The value of this ref varies over time and will change if a job starts at a different time. Ideally, we'd checkout by commit id instead of name to ensure that all subjobs run with the same code.

Here's an example of this happening: https://travis-ci.org/servo/webrender/builds/225371510

The mac build failed trying to build examples/scrolling.rs which is not in the other build jobs.

**Comment by glennw** [comment]
@jrmuizel  Is there anything we can actually do here?

**Comment by jrmuizel** [comment]
I'm not sure. Maybe there's some way to get travis to behave better?

**Comment by kvark** [comment]
Upstream issue https://github.com/travis-ci/travis-ci/issues/6337
Sadly, Travis team doesn't seem to be excited to fix it.

**Comment by jrmuizel** [comment]
Given the upstream issue we can probably close this.
