### ISSUE TITLE
Use rayon's thread pool.

### ISSUE THREAD

**Issue by nical** [servo/webrender#1178]
The rayon crate offers a strict superset of what the threadpool crate provides, and the implementation is pretty much state of the art (compared to threadpool which is essentially a big mutex around a single mpsc channel that all of the workers contend on).
Plus, rayon has a lot of very nice things.

**Comment by nical** [comment]
Hm, I got a bit carried away: spawn_async (the feature in rayon that corresponds to what we use in threadpool) is marked as unstable, so we may want to wait a little.

**Comment by emilio** [comment]
On Tue, May 02, 2017 at 05:02:18AM -0700, Nicolas Silva wrote:
> Hm, I got a bit carried away: spawn_async (the feature in rayon that
> corresponds to what we use in threadpool) is marked as unstable, so we
> may want to wait a little.

I think even though it's under the unstable feature flag, it compiles
perfectly fine on rust stable. Indeed stylo uses the unstable scope()
API from rayon, and we don't have problems in m-c.

**Comment by nical** [comment]
Neat! I'll look into it then.

**Comment by nical** [comment]
Done in #1202 .
