### ISSUE TITLE
MYSTERY: extra 0's after DisplayList in the ipc payload, for Servo

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1196]
I'm still investigating details but it's definitely the result of #1181. There's a now-commented-out assertion in channel.rs that will fail almost always (4/5ths of Servo reftests, in addition to just launching it on whatever page). 

The assertion is basically checking that in parsing the payload, we consumed all of its bytes. This fails because some number of 0's (non-constant, but possibly deterministic) will show up at the end of the payload. This Is Scary. Commenting out the assertion makes everything "work", as the payload appears to be in perfect condition.

It's possible there's just some state somewhere else that needs to be updated, but I certainly can't find it.

I can repro this on macos, haven't had a chance to test it on other platforms. Wrench seemed to work fine.

**Comment by pcwalton** [comment]
I seem to recall that Mach (which is used for IPC on Mac) rounds up messages to some quantum. If shmem is being used to transfer the payload, that *definitely* rounds up to some quantum (4096 bytes, most likely, as that's the x86 page size).

**Comment by Gankro** [comment]
Any idea why we wouldn't have ever tripped this before? I didn't see any logic which would perfectly round our payloads.

**Comment by Gankro** [comment]
Just tested on linux: doesn't seem to have this problem.

Sounds like some mach nonsense.

**Comment by Gankro** [comment]
Looks like the bug is https://github.com/servo/ipc-channel/issues/83

**Comment by mrobinson** [comment]
Is this fixed by https://github.com/servo/webrender/pull/1231?

**Comment by kvark** [comment]
Looks like it, nice!
