### ISSUE TITLE
Shader compilation error on some windows hardware

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1206]
In [this try push](https://treeherder.mozilla.org/#/jobs?repo=try&revision=db7e9f22bb8ab7da5820bdd071cedde86d894219) the windows 8 mochitest-bc failures happen because WR fails to startup. The log has this shader compilation error:

```
WebRender - OpenGL version new OpenGL ES 3.0 (ANGLE 2.1.0.dec065540d5f)
...
08:11:31     INFO - GECKO(4672) | Failed to link shader program: C:\fakepath(2369,1-2): error X3004: undeclared identifier 's3'
08:11:31     INFO - GECKO(4672) | Warning: D3D shader compilation failed with default flags. (vs_5_0)
08:11:31     INFO - GECKO(4672) |  Retrying with skip validation
08:11:31     INFO - GECKO(4672) | C:\fakepath(2369,1-2): error X3004: undeclared identifier 's3'
08:11:31     INFO - GECKO(4672) | Warning: D3D shader compilation failed with skip validation flags. (vs_5_0)
08:11:31     INFO - GECKO(4672) |  Retrying with skip optimization
08:11:31     INFO - GECKO(4672) | C:\fakepath(2369,1-2): error X3004: undeclared identifier 's3'
08:11:31     INFO - GECKO(4672) | Warning: D3D shader compilation failed with skip optimization flags. (vs_5_0)
08:11:31     INFO - GECKO(4672) | Failed to create D3D shaders.
```

Note however that this compilation failure happens pretty late in the log. AFAICT WebRender is initialized numerous times before that successfully. It might just be a shader that we're loading lazily and only gets loaded by particular tests.

Also note that the regular mochitest suite in the same try push must be running on different hardware because it seems to start WR just fine.

**Comment by mephisto41** [comment]
I had same problem here. mark [1] and [2] fixed problem but I didn't know why. Maybe dump the d3d shader code which is generated by ANGLE to see what happened here.

[1]: https://github.com/servo/webrender/blob/master/webrender/res/ps_border_edge.vs.glsl#L45
[2]: https://github.com/servo/webrender/blob/master/webrender/res/ps_border_edge.vs.glsl#L48

**Comment by mephisto41** [comment]
This is compiled shader for ```write_color```

void _write_color_float4(in float4 _color, in float _style, in bool _flip)
{
float2 _modulate = {0, 0};
switch (ivec1(_style)) {
case (6):
s3;
if (_flip)
{
(s3 = float2(1.3, 0.69999999));
}
else
{
(s3 = float2(0.69999999, 1.3));
}
(_modulate = s3);
break;
;
case (7):
s4;
if (_flip)
{
(s4 = float2(0.69999999, 1.3));
}
else
{
(s4 = float2(1.3, 0.69999999));
}
(_modulate = s4);
break;
;
default:
(_modulate = float2(1.0, 1.0));
break;
;
}
;
(_vColor0 = vec4((_color.xyz * _modulate.x), _color.w));
(_vColor1 = vec4((_color.xyz * _modulate.y), _color.w));
}

**Comment by mephisto41** [comment]
Looks like ANGLE code generator generated s3 and s4 without type.

**Comment by mephisto41** [comment]
ANGLE will replace declaration with symbol for statement of switch-case in [1] which I don't know why. I have a workaround that surround the statement by bracket. I'll upload patch. 

[1]: https://github.com/google/angle/blob/d7b1ab5893953b97fe5dc1b3087a9b4b50ec45ee/src/compiler/translator/RemoveSwitchFallThrough.cpp#L41
