### ISSUE TITLE
Figure out WebRender clamping of scroll offset

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1213]
For gecko integration it would make my life a lot easier if WR offered a way to set a scroll position and didn't clamp it to the scroll bounds, or alternatively, allowed the caller to have more control over what it considers the scroll bounds.

Right now the `scroll_nodes` function in clip_scroll_tree.rs and the `set_scroll_origin` function in `clip_scroll_node.rs` both do a bit of clamping on the scroll position provided, but assume the minimum allowed scroll position is 0 and the maximum is the size of content rect minus the size of the viewport. For one thing this won't work for RTL pages, because on RTL pages you should start off at a scroll offset of x=0 and then scroll into negative x values for overflowing content.

But more relevant to APZ, we want to be able to set negative scroll offsets in webrender because the display list we send to WR already has a scroll offset baked into it, and a negative scroll offset would allow scrolling upwards/leftwards from that baked-in scroll offset. In other words, there is a mismatch between the displaylist that gecko produces and what WR assumes it's getting, and in order to scroll properly we need to be able to give WR negative scroll offsets. The other option of changing what gecko produces seems much more risky and error-prone.

/cc @mrobinson

**Comment by mrobinson** [comment]
I'd like to tackle this in two phases. In the first phase, I will allow arbitrary positioning and in the second I will handle properly clipping content that scrolls from outside the "normal" clipping rectangle. My reasoning for this is that @glennw is planning or reworking how combined clips work in the ClipScrollTree, so it makes sense to handle clipping later. On the other hand, we can probably support some types of scrolled content now.
