### ISSUE TITLE
Semi-transparent gradient stops rendered opaque

### ISSUE THREAD

**Issue by pyfisch** [servo/webrender#1219]
I have made a few test-cases for gradients: https://pyfisch.org/stuff/testcases-gradients.html

They render fine in Servo with Webrender except for testcase 15 where I use two stops with a value of `rgba(255, 255, 255, .5)`. This should be translucent but is rendered as solid white with servo. (The intersection of the two gradients should be brighter then the rest)

Since I did not find a point where the alpha value is "forgotten" in servo I looked in webrender and found this file: https://github.com/servo/webrender/blob/8516d6c04235e684d9bf9c783ba4fc99dab3bf02/webrender/res/ps_gradient.fs.glsl It appears to min/max alpha values. Maybe this causes semi-transparent stops to be rendered as opaque?

**Comment by kvark** [comment]
cc @rlhunt

**Comment by rlhunt** [comment]
Does Servo premultiply the alpha of the gradient color stops? Gecko does [this](http://searchfox.org/mozilla-central/source/layout/painting/nsCSSRenderingGradients.cpp#1015) before the display list is given to WebRender. This could be done on the WebRender [side](https://github.com/servo/webrender/blob/master/webrender_traits/src/display_list.rs#L670) but isn't. It doesn't really matter too much either way.

**Comment by pyfisch** [comment]
Servo does not premultiply the alpha of gradient stops. Is it possible to send a PR to webrender to premultiply gradient stops or should this be changed in servo?

**Comment by mstange** [comment]
Is this fixed now?

**Comment by rlhunt** [comment]
This should be fixed now.

**Comment by pyfisch** [comment]
Yes it is.
