### ISSUE TITLE
Add inline blob images

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1236]
Sometimes, blob images will be small enough that it makes more sense to just include them inline in the displaylist instead of having separate images for them. This lets us avoid doing the ipc work to add/remove the images.

It would probably be worth confirming that this shows up in profiles before starting work on it.

**Comment by Gankro** [comment]
update: unclear what workload would best demonstrate this

**Comment by glennw** [comment]
Do we still want to consider doing this? It seems like it would complicate how we handle display list encoding...

**Comment by nical** [comment]
Adding/removing/updating images and fonts is now batched and mostly bundled into the same ipc message as the display list. I don't think we need this as much anymore.

Jeff, don't hesitate to reopen if you think otherwise.
