### ISSUE TITLE
DisplayListBuilder function push_text should accept float for blur_radius

### ISSUE THREAD

**Issue by pyfisch** [servo/webrender#1244]
[The push_text method](http://doc.servo.org/webrender_traits/struct.DisplayListBuilder.html#method.push_text) takes `Au` for `blur_radius` unlike `push_box_shadow` which takes a `f32`. The `Au` is always converted to `f32` internally. For consistency can I change the accepted type?

**Comment by kvark** [comment]
It does seem like a bug in `push_text` to me. We should use `f32` for the blur radius consistently.
