### ISSUE TITLE
Add a good glyph rasterization benchmark.

### ISSUE THREAD

**Issue by nical** [servo/webrender#1245]
It would be great to be able to measure the performance of glyph rasterization when there are lots of glyphs to rasterize on the same frame from wrench.

**Comment by kvark** [comment]
On a side note, let's bring the naming to some consistency. I suggest saying "glyph rasterization" to avoid semantic collision with the actual glyph rendering.

**Comment by nical** [comment]
Side note, to give an idea of what some of the numbers can look like:
When rendering the hacker news front page, we tend to request a dozen bags of 3 to 30-ish glyphs in the same frame. Most of the glyph requests are closer to 5 but it is during page load or when scrolling quickly (so when we are most subject to blow the frame budget up) that we run into the bigger glyph requests.
It would be better to model the benchmark on more demanding pages, but this already gives an idea of the order of magnitudes.

**Comment by glennw** [comment]
@nical It looks like we have a glyph rasterizing benchmark now. Please re-open if still needed.
