### ISSUE TITLE
A lot of time spent in webrender::texture_cache::TextureCache::insert

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1266]
I see this stand out quite a bit in profiles of Firefox scrolling cnn.com and a huge amount scrolling https://perfht.ml/2qxbfmr.

**Comment by jrmuizel** [comment]
The profile linked above doesn't actually show the problem it's just a website that reproduces the problem.

Most of the time is being inside TexturePage::coalesce

**Comment by kvark** [comment]
Our `coalesce` function is called way too many times and is expensive whenever anything changes. We should optimize both the function implementation and reduce the number of times it's called. I'm looking at it.
