### ISSUE TITLE
Support full color glyphs

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1273]
This is needed for Emoji

**Comment by LifeIsStrange** [comment]
Maybe I am saying bullshit because I'm not a programmer but couldn't webrender just use Cairo for this since it support it ?
 http://www.phoronix.com/scan.php?page=news_item&px=Cairo-1.15.8-Colored-Emoji

**Comment by jrmuizel** [comment]
At least on Mac these already work. On Linux it's probably not worth taking a cairo dependency just so we can decode the png's in the fonts.

**Comment by glennw** [comment]
I think it's relatively simple for Linux - we just need to tell FreeType we want color glyphs to be supported, and then handle the image glyph type. I'm not sure what's involved for Windows yet.

**Comment by glennw** [comment]
@lsalzman This is complete on all platforms, I think?

**Comment by glennw** [comment]
@lsalzman Anything else to do here?

**Comment by lsalzman** [comment]
This is done.
