### ISSUE TITLE
Add support for position:sticky

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1277]
Gecko currently supports position:sticky in the compositor. In order to not regress this behaviour when switching to WR we'll need WR to support it as well.

/cc @mrobinson 

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1366295

**Comment by mrobinson** [comment]
I can work on this one!

**Comment by mrobinson** [comment]
Sorry for the delay. I've posted a PR for this.
