### ISSUE TITLE
Remove use of stacking context local_bounds from make_polygon

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1283]
It would be good to remove ```local_bounds``` from the StackingContext structure (and the associated public APIs).

It doesn't really have any meaning, now that we collect the bounding rect from the clip-scroll groups that make up a stacking context.

There's one piece of code that currently reads the ```local_bounds``` field in the ```make_polygon``` function.

Could we modify how that function works to not require the local bounds?

**Comment by glennw** [comment]
cc @kvark @mrobinson

**Comment by mrobinson** [comment]
@glennw I suppose this will be replaced by an offset?

**Comment by glennw** [comment]
@mrobinson Yes, that's what I was thinking.

**Comment by kvark** [comment]
It appears that we need to calculate local bounds specifically when traversing stacking context anyway, based on the children that are not `ContextIsolation::Items`.
