### ISSUE TITLE
Linux: Fractional length border edges lose some pixels

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1288]
If you run this test from gecko `layout/reftests/backgrounds/background-tiling-zoom-1-ref.html` in Servo or in gecko with `layers.advanded.border-layers`, some of the borders will have missing or extra pixels near the corners.

This shows up in `try` on linux, as well as when run locally on the toronto office's "hawkman" machine (Ubuntu), although the two have different artifacts. I haven't been able to reproduce this on macos.

Seems like some sort of rounding issue in the shaders, as the test case has divs with fractional widths.

![png image 800 x 1000 pixels](https://cloud.githubusercontent.com/assets/1136864/26371600/2eb12bf8-3fc9-11e7-8c70-7c97cf33fa0a.png)

**Comment by Gankro** [comment]
It's possible this is related to https://github.com/servo/webrender/issues/1279, or at least a fix for one will fix both.

**Comment by glennw** [comment]
I opened this test in Linux and was unable to reproduce - I didn't see any of the errors above, they looked pixel-perfect when zooming as well.

**Comment by kvark** [comment]
@Gankro please remind me tomorrow. I recall you were able to reproduce it. Now we just need to capture it :)

**Comment by Gankro** [comment]
Yeah I'll double check it on hawkman. I expect this has gone away since y'all have rewritten the border shaders like twice since I filed this bug?
