### ISSUE TITLE
Handle degenerate borders?

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1289]
Webrender fails to pass this reftest in gecko: `layout/reftests/border-radius/corner-3.html` which states that it tests "when only some of the corners have a border-radius and the border-radius is greater than the sum of the border width and the element's content area width/height".

However gecko itself even fails to handle this generalization (which safari and chrome can):

<details>
<summary>Click To View Test Case</summary>

```html
<!doctype html>
<html>
<head>
  <title>Test when only some of the corners have a border-radius and the border-radius is greater than the sum of the border width and the element's content area width/height</title>
  <style>

#plain {
  width: 0px;
  height: 100px;
  border: 15px solid rgba(0,0,255,0.5);
  border-radius: 0 30px 30px 0;
  position: absolute;
  left: 10px;
  top: 10px;
}

#rainbow {
  width: 0px;
  height: 100px;
  border: 15px solid;
  border-top-color: rgba(255,0,0,0.5);
  border-right-color: rgba(0,255,0,0.5);
  border-left-color: rgba(255,0,255,0.5);
  border-bottom-color: rgba(0,0,255,0.5);
  border-radius: 0 30px 30px 0;
  position: absolute;
  left: 60px;
  top: 10px;
}

  </style>
</head>
<body>
  <div id="plain"></div>
  <div id="rainbow"></div>
</body>
</html>
```
</details>

Here's how this renders in some browsers (firefox is vanilla gecko):

![borders copy](https://cloud.githubusercontent.com/assets/1136864/26375561/77a21940-3fd7-11e7-9821-f3da25ff1f47.png)

**Comment by Gankro** [comment]
@jrmuizel has suggested that, at least in gecko, this is probably a case we should punt to some other strategy than a native webrender border. Handling all of these weird corner cases is likely to be Very Hard.

**Comment by glennw** [comment]
@Gankro Should we close this? Do we expect to need any WR work for this?

**Comment by glennw** [comment]
@Gankro re-ping - should we close this one?

**Comment by Gankro** [comment]
Oh sorry, missed the initial ping. Uhh so yeah this is really low priority under our current plan. Let's close this as wontfix for the forseeable future.
