### ISSUE TITLE
Small artifacts in thin white borders

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1297]
`gecko/layout/reftests/bugs/1156129-1.html` fails because a thin white curved border on a white background anti-aliases to include some non-white pixels.

https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=https://queue.taskcluster.net/v1/task/FkcLuDANTRKocplDYA828g/runs/0/artifacts/public/logs/live_backing.log&only_show_unexpected=1

**Comment by glennw** [comment]
@Gankro It'd be worth checking if this still occurs once https://github.com/servo/webrender/pull/1975 makes its way into a Gecko build.

**Comment by Gankro** [comment]
Looks like we removed the fails-if annotation some time ago
