### ISSUE TITLE
Some box shadows aren't drawn correctly.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#130]
Loading http://thany.nl/apps/BoxShadows/ with WR shows several incorrect box-shadow renderings.

**Comment by glennw** [comment]
@pcwalton I was looking for a good box shadow test page to check the current state of the box-shadow before I switch how it does clipping and came across this. It has a few layout bugs, but it's fairly easy to compare a heap of box shadow examples to other browser implementations.

**Comment by pygy** [comment]
Inset shadows look fine, but outer ones are all made of a solid rectangle, no tapering, no rounding.

**Comment by glennw** [comment]
Fixed by #1841. We can open specific bugs if there are any more correctness issues.
