### ISSUE TITLE
Split scrolling and clipping into two node types in the ClipScrollTree

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#1316]
Currently the ClipScrollTree uses a single type of node to represent clips and scrolling regions with clips. This is an evolutionary design from a simpler version of the API. This means that we are treating clips like they have the potential to scroll, which leads to extra work and, ultimately, a more confusing API. Once they are split into two trees, our internals will match Gecko and we will be able to more efficiently share clips between display items (even merging duplicate clips entirely).

**Comment by mrobinson** [comment]
cc @glennw @staktrace

**Comment by glennw** [comment]
@mrobinson This sounds good! Is it something you're working towards now?

**Comment by mrobinson** [comment]
@glennw I've started working on this locally, though the calculation of the local_combined_clip_rect is pretty complicated. If you've made good progress eliminating that, it would make sense to wait until it has landed.

**Comment by glennw** [comment]
@kvark has kindly offered to take over the work I was doing on combined_local_clip_rect - but I'm happy to pick it up again if @kvark needs to work on something else.

**Comment by mrobinson** [comment]
I think that it's going to be a lot easier to keep clipping and scrolling in the same tree, but split out the nodes types. This removes a lot of unnecessary complication. The first step is here: https://github.com/servo/webrender/pull/1364.

**Comment by mrobinson** [comment]
#1364 has landed, so I'm going to close this issue.

**Comment by glennw** [comment]
Closing as suggested above.
