### ISSUE TITLE
Add support to wrench for loading YUV images.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1321]
It would be good to have test coverage for the various YUV formats.

**Comment by glennw** [comment]
cc @JerryShih

**Comment by JerryShih** [comment]
@glennw @nical 

It's good to have that, but we might have some troubles with some hardware specific buffer formats. With that format, the stride or the internal format of that buffer might be unknown. We should create a draw target to draw that buffer to target and read back as rgba buffer. Thus, we could save the buffer into file.
Anyway, we could do that for the regular image and "external buffer" type(the external cpu raw buffer).
