### ISSUE TITLE
ps_image shader compilation failure with ambiguous function _intersect_rect

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1332]
Same deal as #1324, but a different function. Log is at https://treeherder.mozilla.org/logviewer.html#?job_id=103827367&repo=try&lineNumber=2287

**Comment by staktrace** [comment]
@kvark - we're hitting shader compilation crashes in the wild too - https://bugzilla.mozilla.org/show_bug.cgi?id=1370104 so it would be good to fix this soon and push a new WR update into gecko.

**Comment by kvark** [comment]
I believe this is fixed in 9143f1d565f20086b1b00c9ee132cfbe30c658da

**Comment by staktrace** [comment]
Confirmed fixed, thanks!
