### ISSUE TITLE
Expose font data/fonts to blob renderer

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1358]
Gecko needs this to avoid resending the fonts all the time.

If we don't expose the fonts and only expose the font data we need some way to know about font key deletions so that we can remove our own Font objects when they no longer correspond to the keys.

Thoughts?

**Comment by nical** [comment]
What I have in mind is to have a list of the ids of the resources that the blob image depends on at the beginning of the recording. Then, when requesting a blob image (or a tile of a blob image), we go through these ids and get the data from the resource cache, and send it along with the rest of the information to the worker thread.
To do that we have to extend [BlobImageRenderer::request](https://github.com/servo/webrender/blob/76fd3add2366e6a3ba1ce02f0004f3552aa20143/webrender_traits/src/image.rs#L145) to take a `FontStore`, similar to the `ImageStore` already in the method signature.

We can easily make this work somewhat naively for font data, we may need more smarts for actual fonts depending on how skia's font cache works, I'm  not sure yet.
We can just notify the blob render for every font key that we delete, or store a flag in the font templates to say whether the blob renderer needs to be notified of the deletion.

**Comment by jrmuizel** [comment]
I've put a pull request up that does this here: https://github.com/servo/webrender/pull/1365
