### ISSUE TITLE
More coordinate spaces

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1371]
We are doing a lot of jumps between scrolled/reference frame/stacking context spaces. The logic is very easy to get confused with, and the type system is not protecting us nearly enough. Example:
```rust
            let viewport_rect = &clip_node.local_viewport_rect
                     .translate(&clip_node.reference_frame_relative_scroll_offset)
                     .translate(&-scroll_node.reference_frame_relative_scroll_offset)
                     .translate(&-stacking_context.reference_frame_offset)
                     .translate(&-scroll_node.scrolling.offset);
```

List of spaces:
  - [x] Layer
  - [x] ScrollLayer
  - [ ] ReferenceFrameNoScroll (relative to the reference frame but without the scrolling applied, this is how our node's  `local_viewport_rect` are stored...)
  - [ ] ReferenceFrame
  - [ ] StackingContext

Also see https://github.com/servo/euclid/issues/214
cc @mrobinson @nical

**Comment by gw3583** [comment]
I think this is covered by the introduction of the Picture coordinate space in https://github.com/servo/webrender/pull/2995 (and some other recent patches). Please re-open if you feel there is more specific work we should do here.
