### ISSUE TITLE
Some corners in Servo's transparent rects demo have seams

### ISSUE THREAD

**Issue by trishume** [servo/webrender#1384]
Some of the rectangles in the transparent rects demo with the Servo nightly from 2017/06/14 have seams on the corners on a 2014 rMBP with both the Nvidia GT 750m and the Iris Pro. Which rectangles have seams on the corners does not change between frames. All rectangles also have weird white line artifacts on the corners.

### Nvidia GT 750M
<img width="252" alt="screen shot 2017-06-14 at 10 07 40 pm" src="https://user-images.githubusercontent.com/887610/27166464-a795deb4-514f-11e7-8fa9-1f73bfc6061f.png">

### Nvidia GT 750M after window resize
After resizing the window to full screen, which doesn't actually change the demo, everything starts flickering wildly with black rectangles.
<img width="370" alt="screen shot 2017-06-14 at 10 22 51 pm" src="https://user-images.githubusercontent.com/887610/27166515-1a3d835e-5150-11e7-887a-3d225e641998.png">

### Intel Iris Pro
<img width="510" alt="screen shot 2017-06-14 at 10 21 37 pm" src="https://user-images.githubusercontent.com/887610/27166532-47a53f12-5150-11e7-9d10-04642f16263b.png">

**Comment by kvark** [comment]
cc @glennw 
looks like a border rendering code, perhaps it's transparency is not working correctly with `device_pixel_ratio != 1` case

**Comment by glennw** [comment]
https://github.com/servo/webrender/pull/2016 claims this is fixed.

**Comment by kvark** [comment]
Notice how I changed "fixed XXX" to "related to XXX" in the description. This issue definitely needs to be retested though.
