### ISSUE TITLE
Deduplicate the bitflags dependency

### ISSUE THREAD

**Issue by SimonSapin** [servo/webrender#1391]
https://github.com/servo/webrender/pull/1359 will likely land with this tidy error silenced:

```
./Cargo.lock:1: duplicate versions for package "bitflags"
	found dependency on version 0.7.0
	but highest version is 0.8.2
	try upgrading with ./mach cargo-update -p bitflags:0.7.0
	The following packages depend on version 0.7.0:
		clap
		cocoa
		png
		webrender
		xml-rs
```

**Comment by Eijebong** [comment]
- [ ] https://github.com/brendanzab/gl-rs/pull/419
- [x] https://github.com/PistonDevelopers/image-png/pull/56
- [ ] https://github.com/kbknapp/clap-rs/pull/966 (needs a release)
- [ ] https://github.com/servo/cocoa-rs/pull/163
- [ ] https://github.com/servo/core-graphics-rs/pull/86
