### ISSUE TITLE
Support for unifying inner clip rectangle

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1400]
Current implementation is limited by this bit:
```rust
                // TODO(gw): local inner is only valid if there's a single clip (for now).
                // This can be improved in the future, with some proper
                // rectangle region handling.
                if sources.len() > 1 {
                    local_inner = None;
                }
```
Removing it causes a failure in "inset-border-radius-ref.yaml". I don't think it will be difficult to investigate and fix.
cc @glennw

**Comment by kvark** [comment]
![reftestbeauty](https://user-images.githubusercontent.com/107301/27300992-ae4c2778-54ff-11e7-927f-f62160b4e2f6.png)

**Comment by glennw** [comment]
@kvark I think this is resolved by the recent clip changes by @mrobinson. Should we close this?
