### ISSUE TITLE
Support backface-visibility: hidden

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1419]
With CSS 3D transforms, you can choose to have your element disappear once its backside turns towards the camera. This is done using `backface-visibility: hidden`.

In Gecko, ever since [bug 1375672](https://bugzilla.mozilla.org/show_bug.cgi?id=1375672), we now filter out such layers if their backside faces the camera, i.e. we don't even pass them to webrender to draw. However, we do that on the main thread. This only works if the transforms are known on the main thread; it breaks down once off-main-thread transform animations get involved and an element turns to its backside mid-animation.

I think it would make more sense to do the hiding in webrender, because webrender has all the up-to-date transforms for the frame that it's drawing.

cc @kvark @jrmuizel

**Comment by kvark** [comment]
I suspected there be a config flag for that! Should be fairly easy to support in WR, and it would totally make sense. Thanks for filing the issue!

**Comment by mephisto41** [comment]
@kvark Are you working on this? If not, can I take it? Thanks.

**Comment by kvark** [comment]
@mephisto41 I'm not currently working on this, no. But last time I estimated, the task appeared to be more difficult than I originally estimated. Please feel free to take a stab at it!

**Comment by glennw** [comment]
This should be supported since https://github.com/servo/webrender/pull/1606 - please open specific bugs if there is remaining issues / bugs.
