### ISSUE TITLE
Facebook news feed takes quite a bit of time in Gecko/WebRender

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1427]
I tried profiling this on Windows but didn't get great results from CodeXL. What I saw there seemed to roughly match what I see on OS X.

On the RenderBackend thread we're spending 64% of time in build_scene() and 34% in render()

In build_scene() most of the time is in flatten_item() of which 20% is memmove, 10% in ClipScrollTree::add_node(), 10% in deserialize(), 9% in BuiltDisplayItemListIter::next()

render() has 36% in LayerRectCalculationAndCullingPass() and 8% in mask_cache::MaskCacheInfo::update

I suspect part of the high cost here comes from the crappy display lists that Gecko is producing.

To reproduce this I ran Gecko trunk with the following prefs:
gfx.webrender.enabled = true
gfx.webrenderest.enabled = true
webrender.blob-images = true
layers.force-active = true

**Comment by glennw** [comment]
I suspect you're right about the display lists. I've been profiling quite a few sites in Servo recently, and I typically see around 20-30% of the time in build_scene() and 70-80% in render(). Seeing that much time in build_scene() for FB does sound like there may be a heap of extra clips / stacking contexts / masks perhaps coming from the Gecko DLs. Is there a way to dump the Gecko DL to text to see what it looks like?

**Comment by glennw** [comment]
@jrmuizel Are you able to check if this is still an issue?

**Comment by gw3583** [comment]
This is probably fixed...
