### ISSUE TITLE
Filter out clip items in local space

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1436]
Current implementation does smart filtering in screen space, but we can do even better if we take the local inner clips of items that we know to be in the same reference frame:
```rust
/// Filter out all the clip instances that don't contribute to the result
        let mut inner_rect = Some(task_rect);
        let clips: Vec<_> = raw_clips.iter()
                                     .chain(extra_clip.iter())
                                     .filter(|&&(_, ref clip_info)| {
            match clip_info.bounds.inner {
                Some(ref inner) if !inner.device_rect.is_empty() => {
                    inner_rect = inner_rect.and_then(|r| r.intersection(&inner.device_rect));
                    !inner.device_rect.contains_rect(&task_rect)
                }
                _ => {
                    inner_rect = None;
                    true
                }
            }
        }).cloned().collect();
```

**Comment by glennw** [comment]
@kvark @mrobinson Is this still relevant (I think it is)?

**Comment by mrobinson** [comment]
I think as part of handling multiple ClipChains (#1964) we are going to need to do something like this in order to avoid masking in every situation. So maybe we should just close this bug in favor of that one.

**Comment by glennw** [comment]
I believe this is handled now (based on the comment above). Please re-open if work remains here.
