### ISSUE TITLE
mutliple colored text blurs cause chaos

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1437]
https://gankro.github.io/blah/webtests/shadows.html

left: firefox nightly (no webrender)

right: recent servo build
<img width="230" alt="screen shot 2017-06-29 at 1 55 06 pm" src="https://user-images.githubusercontent.com/1136864/27709996-fd8f4722-5cd2-11e7-832d-a3b4d461a500.png">

**Comment by glennw** [comment]
This appears to be resolved now, please re-open if you're still seeing issues.
