### ISSUE TITLE
Clipping issues with rotated content

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#1438]
I see artifacts when I load this page in servo.
```
<div style="width: 800px; background: pink; transform: rotate(30deg);">
<div style="margin-left: 100px; overflow: hidden; width: 300px; height: 300px; background: grey; border-radius: 30px;">
<div style="left: -20px; width: 400px; height: 1000px; background: blue">
</div>
</div>
</div>
```

Gecko:
![firefox](https://user-images.githubusercontent.com/13536/27710295-1be800dc-5cd4-11e7-9a17-383410eda5bd.png)

Servo:
![servo](https://user-images.githubusercontent.com/13536/27710310-235febc2-5cd4-11e7-9cbb-550da935ed00.png)

**Comment by mrobinson** [comment]
cc @kvark

**Comment by glennw** [comment]
Fixed by https://github.com/servo/webrender/pull/1773
