### ISSUE TITLE
Reduce the clip mask target space

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1439]
The solution proposed in Hawaii was to split the mask into 4 regions, excluding the inner rectangle. The pixel shaders of primitives that are masked would then calculate the exact sub-region they want to be sampling. This would slightly increase the mask sampling cost, but fortunately we are not doing the masking for a whole lot of rendered pixels.

cc @glennw

**Comment by glennw** [comment]
@kvark I think we can close this as part of #2146? Or do you foresee more work here related to this?

**Comment by kvark** [comment]
Yes, more work, but as a follow-up to your PR.
