### ISSUE TITLE
Preserve3D baking space

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1447]
We bake each preserve-3D stacking context in screen space as of a43b0c2ae7ee136e6d68178c9efe879854fd5473 in order to get proper text rendering and anti-aliasing of the contents. However, this only works when preserve-3D forms isolated branches of the SC tree. This appear to not always be the case...

Consider the following tree: a 3D context `A` may contain 2D context `B` that contains another 3D context `C`. Baking of `C` should not be made in screen space but rather in `B` space, since `B` will participate in plane-splitting with `A` contents/children and is rotated in general case.

The quality-focused solution would probably involve having separate baking paths for screen space versus local space, and we'll fall-back to the latter if former is not an option (like in the example above). This is unfortunately going to increase the implementation complexity.

cc @glennw

**Comment by glennw** [comment]
We have *some* support for this now - each Picture can specify a RasterizationSpace internally. However, we need to expose this properly and make sure it works with clip masks etc.

**Comment by kvark** [comment]
Fixed by #3030
