### ISSUE TITLE
Bad texture cache behaviour with large mask images

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1452]
Loading https://github.com/matklad/fall/commit/931293e4fc423ac6a2b763bde156d9632fbf4787 in Gecko with webrendest turned on causes about 1GB of A8 texture cache. This is presumably from large MaskLayers.

**Comment by nical** [comment]
This isn't really actionable on webrender's side other than general improvements to the texture cache tracked by #1486. I think that most of the work related to masks and texture cache needs to happen in gecko (by not generating mask images for rounded rectangles which seems to be the issue with that link).
