### ISSUE TITLE
Transformed text should probably be rasterized transformed

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1453]
Currently it looks like we just transform the rasterized bitmap. Browsers do a transformed rasterization. An example of this is here: https://jrmuizel.github.io/tests/transformed-text.html

Servo gives a blurry mess, Gecko and Chrome give proper subpixel AA

**Comment by kvark** [comment]
Related to #1451

**Comment by nical** [comment]
Also related to #1542

**Comment by glennw** [comment]
@lsalzman Can this be closed now?

**Comment by lsalzman** [comment]
Yes, this is fixed.
