### ISSUE TITLE
Is there any way to be notified when a specific display list has been rendered?

### ISSUE THREAD

**Issue by ferjm** [servo/webrender#1458]
I need to know when a **specific** display list has been rendered.

The use case I am working on is the implementation of Progressive Web Metrics in Servo. There are two metrics ([Time to First Paint and Time to First Contentful Paint](https://github.com/WICG/paint-timing#definition)) that requires the analysis of the display lists before sending them to WebRender and waiting for the display lists to be painted before actually setting the values of these metrics.

My questions is:

Is there any existing mechanism to know when a **specific** display list has been rendered? I have seen that we have this `RenderNotifier.new_frame_ready` callback, but unfortunately it does not provide any information about the rendered frame. If no other existing mechanism is available, would it be possible to add the pipeline and frame identifiers to `RenderNotifier.new_frame_ready`?

**Comment by ferjm** [comment]
CC @glennw @kvark

**Comment by glennw** [comment]
After calling ```render()``` you could call ```current_epoch()``` - this will allow you to know which display list generation / epoch has been send to OpenGL. Technically, you may also want to wait for the swap buffers to occur before querying the current epoch. I think this should provide what you are looking for.

**Comment by glennw** [comment]
(FWIW this is the same technique we use in the reftest harness to ensure that we have actually drawn the layout epoch that we care about).

**Comment by ferjm** [comment]
Thank you @glennw! I was able to use this technique in https://github.com/servo/servo/pull/17876 and it is working as expected. Thanks!
