### ISSUE TITLE
Test failures in Servo

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1463]
Testing current master WR against Servo (using the ```webrender-update``` branch from @mrobinson) results in the following failures:

```
  ▶ FAIL [expected PASS] /css-transforms-1_dev/html/css-transforms-3d-on-anonymous-block-001.htm
  └   → /css-transforms-1_dev/html/css-transforms-3d-on-anonymous-block-001.htm 4b32b3c3565704823cfdc33a094a2d884ec64a37
/css-transforms-1_dev/html/reference/css-transforms-3d-anonymous-block-ref.htm 78f7de60570ffbe0bd28c328d0d0a4ac8f0b7890
Testing 4b32b3c3565704823cfdc33a094a2d884ec64a37 == 78f7de60570ffbe0bd28c328d0d0a4ac8f0b7890

  ▶ FAIL [expected PASS] /css-transforms-1_dev/html/transform-table-006.htm
  └   → /css-transforms-1_dev/html/transform-table-006.htm a1d9c59dbc037dcec8d718f001d9cd6c172229e4
/css-transforms-1_dev/html/reference/transform-blank-ref.htm dc2714f619cd897009842f49c63a53740d124455
Testing a1d9c59dbc037dcec8d718f001d9cd6c172229e4 == dc2714f619cd897009842f49c63a53740d124455
```

I haven't looked into them to see if they are related to the clip/scroll changes, or some other PR that's landed in WR since the last update.

**Comment by glennw** [comment]
cc @kvark @mrobinson @staktrace

**Comment by mrobinson** [comment]
I'm pretty sure these regression are not due too the clipping changes. BTW I have the Servo update baking here: https://github.com/servo/servo/pull/17649.

**Comment by glennw** [comment]
@mrobinson In the reftest output for those images, it looks like complete lines of text are getting clipped out. I'll investigate further today to see if I can track down the cause.

**Comment by glennw** [comment]
The test failures are bugs / missing features that are being exposed by the fix in https://github.com/servo/webrender/pull/1426. Since the fix is correct in this case, I think it's fine to mark those tests as expected failures (since they were accidentally passing previously) and get this WR update reviewed / merged.
