### ISSUE TITLE
What needs to happen after a resize?

### ISSUE THREAD

**Issue by RoyJacobs** [servo/webrender#1473]
This feels like an extremely obvious question, apologies if this is the case.

I'm currently extending a Webrender example by listening to the Glutin "resize" event. I'm rendering a rect that's the same size as the window.

Once I receive the resize event I:
* Build a new display list with a rect that has the new layout size (but with the same PipelineId)
* Call `api.set_display_list` with an increased epoch
* Call `api.generate_frame`
* Call `renderer.update`
* Call `renderer.render(new_size)`

Expected result:
The rectangle covers the entire window

Perceived result:
The background color is filled across the entire window, but the rectangle only covers the original window size.

I'm clearly missing an obvious notification or update somewhere. The documentation is (understandably) fairly sparse, can you point me in the right direction? Also, please let me know if there are more appropriate places to ask these questions.

**Comment by kvark** [comment]
@RoyJacobs thanks for filing the issue! I believe this is the appropriate place to ask.

The easiest way to solve this (for me) would be capturing the frame with RenderDoc and looking at the states to see what has not been updated properly. I'd be happy to check it myself if you publish your code in a branch somewhere.

**Comment by glennw** [comment]
@RoyJacobs You'll also need to call ```api.set_window_parameters```. I think that should fix the problem you're seeing.

**Comment by RoyJacobs** [comment]
I can confirm calling `api.set_window_parameters` does the trick. Thanks!

Is there a good place to find these implicit requirements? The examples are not using this call for instance. I guess it's time to start figuring out how Servo works, perhaps? :)
