### ISSUE TITLE
Shadow offsets don't actually offset the content

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1479]
It appears that it only offsets the clipped/masked region:

From reftests/text/shadow-complex.yaml (with offset on red shadow set to [10, 10]) (mesa).

<img width="150" alt="screen shot 2017-07-13 at 11 12 17 am" src="https://user-images.githubusercontent.com/1136864/28173783-74fc3c58-67bd-11e7-8b60-20ed9e96f045.png">

(Note the T at the start)

From running servo on https://gankro.github.io/blah/webtests/text.html (macos sierra):

<img width="655" alt="screen shot 2017-07-13 at 10 37 51 am" src="https://user-images.githubusercontent.com/1136864/28173796-7d161b3e-67bd-11e7-869e-8de15dd0d28f.png">

(Note the `m` on "cillum")

**Comment by Gankro** [comment]
Note: I tried messing around with the bounds/local_rect a bunch and nothing happened. I assume you intended to place the content according to it, but forgot to, since the only place you seem to factor in `offset` is in translating that rect.

**Comment by glennw** [comment]
I'll look into these today.

**Comment by kvark** [comment]
Fixed by #1482
