### ISSUE TITLE
LineDisplayItem to support text-decoration-style

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1480]
Discussing with @glennw on irc, here's our plan for supporting text-decorations, and their resulting shadows.

Add:

```rust
struct LineDisplayItem {
  baseline: f32, // LayerPixel
  start: f32,
  end: f32,
  orientation: Vertical | Horizontal, // toggles whether above values are interpreted as x/y values

  width: f32, // same units as borders? 
  // I don't *think* we need to distinguish font-weight from font-size here? (looking at gecko)
  color: Color,
  style: Solid | Dotted | Dashed | Wavy,
}
```

Producers of these items will figure out appropriate position, style, and ordering. Also in the case of a `text-decoration-style: double`, they will just emit two of these. So in total a span of text might have up to 6 LineDisplayItems pushed in with it.

In the backend, these will get converted into glyphs stored in the glyph cache, to be tiled for the length of the line (very short lines may get a dedicated glyph?). This unifies all text shadow rendering under "I render shadows of glyphs", which is nice and clean.

# Alternatives

## Attach LineDisplayItem to TextDisplayItem

This doesn't really clarify anything, other than hardcoding how many lines we can handle. Note that we can't just have a single list of LineDisplayItems, because line-through needs to come after glyphs, while underline and overline come before. Having lines be "loose" optimizes for the common case of 0 to 1 decoration lines, and makes it easy to support the different orderings. (note that the shadow rendering pass can ignore these orderings because it converts everything to the same color)

Note also that lines may span multiple TextDisplayItems because of font/color changes mid-text-span (mixing languages, emoji), and so this would reduce the amount of lines we actually need to move around.

## Overload borders

Borders already have a notion of dotted/dashed/solid, so reusing them here might make sense.

Borders are more complex than decorations (bloat) and have configurations we don't want to support in shadows. At the same time they don't have the "wavy" style text-decorations *do* need to support and that we don't want to support in borders.

(similarly, boxes only handle the solid/double cases)

## Support double lines directly

More complex than necessary to avoid minimal bloat since double-lines are incredibly rare.

**Comment by glennw** [comment]
This happened.
