### ISSUE TITLE
Text shadows draw over the actual text?

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1481]
Running servo on master:

<img width="203" alt="screen shot 2017-07-13 at 7 13 00 pm" src="https://user-images.githubusercontent.com/1136864/28191747-44ecf0d2-6800-11e7-8df3-9c0b1b0dfcf2.png">

That's a green and red shadow for black text

In Gecko the black is clearly on top:

<img width="204" alt="screen shot 2017-07-13 at 7 20 36 pm" src="https://user-images.githubusercontent.com/1136864/28191778-663f6f80-6800-11e7-913b-5dd42a20a287.png">

Easy local test case: remove the transparency from the text in `reftests/text/shadow-complex.yaml`:

<img width="156" alt="screen shot 2017-07-13 at 7 25 07 pm" src="https://user-images.githubusercontent.com/1136864/28191894-08a55c6c-6801-11e7-9a97-5c133402b9eb.png">

**Comment by kvark** [comment]
Fixed by #1482
