### ISSUE TITLE
Fast-clear optimization

### ISSUE THREAD

**Issue by nical** [servo/webrender#1495]
Under certain conditions, it is way faster to clear using glClear than using rectangles. We currently do the latter since PR #1011, where it was measured to be faster at least on intel hadrware.

I don't think we were getting the fast-clear optimizations. On intel hardware you only get it with certain special colors like `[0.0, 0.0, 0.0, 0.0]` or `[1.0, 1.0, 1.0, 1.0]` (I suspect we were clearing with a dark red color by default most of the time). There is probably other states that can turn the optimization off but the magic color values is the only thing I could find in intel's Graphics API developer’s guide.

Fast-clear is a nice bandwidth saving optimization, It would be worth reconsidering glClear in some cases or understand why we are not getting fast-clear if the performance is still not where we expect it to be.

**Comment by kvark** [comment]
@nical 

#1011 didn't replace `glClear` with rectangles, it just enabled scissoring (which is now behind an option btw). Whether or not the hardware is able to do the fast clears with scissoring is an open question, hence my original concerns on the PR. But so far, @glennw 's benchmarks have been convincing enough.

Here are the recommendations I found related from Intel's guide:
> Use the provided API functions for clear, copy, and update needs. Do not implement your own version of the API calls in the 3D pipeline.

- [x] we still use `glClear`

> Enable hardware fast clear as specified, and utilize 0 or 1 for each channel in the clear color for color or depth

- [x] most of the time, our clear color consists of 0 and 1s

**Comment by glennw** [comment]
I think we are getting fast clears where possible. Please re-open if there's further specific work for this.
