### ISSUE TITLE
Need a way to disable RenderBackend::render_on_scroll

### ISSUE THREAD

**Issue by sotaroikeda** [servo/webrender#1497]
Gecko with webrender does not need "render on scroll", it just spend cpu time. It is nice if we could disable it.

Gecko expects to generate new frames only with ApiMsg::GenerateFrame, since gecko generates new frames with v-sync timings. It is done by [WebRenderBridgeParent::CompositeToTarget()](https://dxr.mozilla.org/mozilla-central/source/gfx/layers/wr/WebRenderBridgeParent.cpp#1082). Frame scrolling is also controled by CompositeToTarget(). Then there is no necessity to do render on scroll by webrender. It just consumes cpu time.

gecko already does not handle new_scroll_frame_ready event by [Bug 1377688](https://bugzilla.mozilla.org/show_bug.cgi?id=1377688).

**Comment by kvark** [comment]
We could certainly add a flag into `RendererOptions` to prevent `render_on_scroll` ever flipping on.
