### ISSUE TITLE
Glyph cache optimizations / ideas

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1503]
A general list of ideas for improving glyph cache performance:

* We currently have way too many hash table lookups - e.g. the resource cache expiry times are maintained in a separate hash from the items. We could combine some of these hash lookups, and also could consider using a freelist in place of the hashmap in some cases.
* The glyph cache currently uses a fairly complex allocator to minimize wasted space in the atlas. Instead, it's probably worth switching to some kind of slab allocator (with different block sizes per texture page) - this will mean no fragmentation / coalescing, and make allocating items in the cache much faster. The trade-off is more texture memory used for the glyph cache, but if we choose the block sizes carefully this shouldn't be a big deal.
* The hash table to look up a glyph key is quite expensive. Since the actual used glyph keys are typically a small subset of the u32 char index, we could consider something like a page table structure to remove the hashing overhead.
* Since the cost of rasterizing a glyph on the CPU is significantly higher than the cost of uploading a glyph to the GPU, we could consider having 2-4 glyph caches, which are independent of each other (can duplicate glyphs in GPU memory), so that the text run processing can be trivially distributed across CPU threads.

**Comment by glennw** [comment]
cc @kvark

**Comment by Gankro** [comment]
As part of this I'm working on adding a list of all glyphs to the end of the display list, so that those can be uploaded in parallel.

**Comment by glennw** [comment]
These optimizations have been applied - text processing generally doesn't show up near the top of the profile now.
