### ISSUE TITLE
Have a notion of transaction

### ISSUE THREAD

**Issue by nical** [servo/webrender#1505]
Currently each pipeline will send a bunch of messages to add/remove/update resources, set the display list and generate the frame. A pipeline, when doing something that causes a frame to be rendered, can race with resources being updated in another pipeline and produce a frame with only a portion of the other pipeline's updates that are meant to show up in the same frame.

In Gecko we have a notion of transaction which contains all of the changes that need to be visible at the same time. I think that it would be worth having a similar model in webrender, where several api messages could be sent together and applied "atomically" in one spin of the render backend's loop.

In practice what I am proposing is just to send vectors of api messages instead of sending them one by one.

Thoughts @glennw @kvark @jrmuizel ?

**Comment by kvark** [comment]
> A pipeline, when doing something that causes a frame to be rendered, can race with resources being updated in another pipeline and produce a frame with only a portion of the other pipeline's updates that are meant to show up in the same frame.

I see this relating heavily with resource snapshots that we'll need for APZ. Thus, I believe we should touch on that topic during the APZ call (whenever we manage to schedule it...), and the issue to be postponed until our asynchronous backend architecture is cleared out.

**Comment by glennw** [comment]
I do like the idea in general of introducing transactions - it does seem likely to be a useful addition. But we can certainly discuss the details as part of the (to be rescheduled) APZ discussions.

**Comment by nical** [comment]
It is mostly superficially related. I would rather start by looking for a solution to this simple problem (how we expose atomicity of updates in the api) and adjust it as needed when we talk about the threading architecture (which is more about how we internally implement some aspects of this atomicity while preserving APZ). I prefer iterating small steps at a time than postponing too many things until we have a complete and precise design (which we actually had and decided to start over). Things don't need to be set in stone, as long as we make forward progress.

**Comment by glennw** [comment]
@nical Yup, that sounds like a good idea to me. Thanks!

**Comment by nical** [comment]
Fixed in #1532.
