### ISSUE TITLE
Text rendering is broken on Android

### ISSUE THREAD

**Issue by MortimerGoro** [servo/webrender#1517]
See https://github.com/servo/servo/issues/17851 (images attached + specific WR update info)

**Comment by MortimerGoro** [comment]
@glennw @kvark any idea about what could cause this problem?

**Comment by kvark** [comment]
Thanks for finding the regression range! It corresponds to this [WR range](https://github.com/servo/webrender/compare/181759db5be23d05b6dab273db36475edde18bdc...891670e5233650843d6189d1b72f202da3837ae8)

**Comment by MortimerGoro** [comment]
More info after testing on more mobile devices:

This error only seems to happen on the Google Pixel (Adreno 530).

It works ok in Nexus 4 (Adreno 320) and Galaxy S7 (Mali-T880)

**Comment by glennw** [comment]
@MortimerGoro Is this resolved now with those driver bug workarounds?

**Comment by glennw** [comment]
I *think* this is resolved now. @MortimerGoro please re-open if that's not the case.

**Comment by MortimerGoro** [comment]
Sorry for the delay, I was on a trip.

Yes, this is resolved with the driver bug workarounds.
