### ISSUE TITLE
Support drawing subpixel text on to transparency on OS X

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1544]
OS X supports this and we'll need it to support subpixel AA on vibrant backgrounds. OS X allows setting an approximate background color with the CGContextSetFontSmoothingBackgroundColor private API.

Here's the, still open, corresponding issue in QT https://bugreports.qt.io/browse/QTBUG-39463

**Comment by glennw** [comment]
@jrmuizel @mstange I think this can be closed now?

**Comment by glennw** [comment]
@mstange Can this be closed?

**Comment by mstange** [comment]
Yes, this was fixed by #1974.
