### ISSUE TITLE
Massive Memory Usage?

### ISSUE THREAD

**Issue by rep-nop** [servo/webrender#1555]
I downloaded Nightly to test out Webrender and the other new features, but after a while I noticed my tabs were freezing up, (especially) the Twitch video player. I then went to task manager and noticed that Nightly had pushed me to 90%+ memory usage with the main culprit being the Twitch tab from what I could tell. (along with high CPU usage)

[Here's a screenshot of the Nightly memory usage](https://cdn.discordapp.com/attachments/273539705595756544/343903868012199947/unknown.png)

After disabling Webrender and restarting Nightly the problem has gone away and things are very performant again.

Info:
- Windows 10, 64-bit
- Nightly v57.0a1 (2017-08-06) (64-bit)
- webrender & webredest enabled (also have Stylo enabled)

Let me know if there's any more information needed!

**Comment by glennw** [comment]
Possibly related to https://github.com/servo/webrender/issues/1486 - we need to investigate what's going into the texture cache to use that amount of memory (I think ImageKeys may be getting re-created every frame for masks?).

**Comment by sotaroikeda** [comment]
It is also tracked by [Bug 1378528](https://bugzilla.mozilla.org/show_bug.cgi?id=1378528)

**Comment by rep-nop** [comment]
@sotaroikeda ah, didn't see that. I did do a search on bugzilla but must have missed it.

**Comment by nical** [comment]
The discussions about this are happening in #1486 (and [bug 1378528](https://bugzilla.mozilla.org/show_bug.cgi?id=1378528) as Sotaro pointed out).
