### ISSUE TITLE
Recording/replay infrastructure doesn't really handle blob images

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1567]
We have a couple of different options:
1. Record the blobs and have a mechanism to play them back.
2. Record the results of the blob rendering requests and return them when asked. Return checkerboard otherwise.
3. Record the blobs as though they were regular images.

**Comment by glennw** [comment]
@kvark @jrmuizel Since blobs are correctly handled in the new capture model, I guess we can close this one?

**Comment by kvark** [comment]
Unless someone has a strong use case for the old recording to support blobs/external images (and be fixed/maintained in general, since it doesn't appear to work at this moment), we should close this.

**Comment by glennw** [comment]
They can re-open if there is a strong case.
