### ISSUE TITLE
text-shadows are desaturated/faint

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1568]
![screen shot 2017-08-10 at 11 59 46 am](https://user-images.githubusercontent.com/1136864/29179796-a30a8976-7dc3-11e7-806e-49458611e638.png)

from left to right:
* chrome
* firefox
* firefox+webrendest (with my text patches)
* servo

Strangely highlighting the text in firefox fixes this (I can't check in Servo since that doesn't work). It's possible this is just triggering a different path? But the fact that Servo and Webrender produce the same results makes it seem like webrender is doing something strange here.

**Comment by Gankro** [comment]
This is probably a dupe of https://github.com/servo/webrender/issues/1373

**Comment by Gankro** [comment]
Also for reference my comments about selection were just some unrelated bug sending multiple copies of shadows on text-selection.

**Comment by glennw** [comment]
@Gankro I think this will probably be fixed by https://github.com/servo/webrender/pull/1716 - so would be worth checking once it lands.

**Comment by glennw** [comment]
@Gankro Is still still an issue?

**Comment by Gankro** [comment]
Looks basically as good as gecko now.

Webrender (Gecko but no subpixel):
<img width="694" alt="screen shot 2017-10-02 at 11 10 43 pm" src="https://user-images.githubusercontent.com/1136864/31108456-5d251baa-a7c7-11e7-9a23-8ed9ae9a1fda.png">

Webrendest:
<img width="696" alt="screen shot 2017-10-02 at 11 13 30 pm" src="https://user-images.githubusercontent.com/1136864/31108457-5d26d6e8-a7c7-11e7-8fb6-b03f1b8230c4.png">

**Comment by Gankro** [comment]
We're a bit fainter here but I think that can be chalked up to us blurring so much more (still need to decide the right solution on that)
