### ISSUE TITLE
Expose a hit-test API in webrender

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1575]
Gecko tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1389146

For Gecko/APZ we want webrender to expose a hit-testing API. The API would take a point and return these two pieces of information: (1) the innermost scrollable frame that contains the point. This will needs to take into account any applied animated/async transforms. (2) the event region information associated with the point. How we do this is still up in the air, but #411 is tracking providing webrender with the event region information. This will likely be on a per-display-item granularity.

**Comment by mrobinson** [comment]
I think Servo wants this too, though for Servo we'd also want to return an id associated with the display item that is hit.

**Comment by staktrace** [comment]
If we had an id per display item and just returned the id we could probably use that as a starting point in gecko. We can keep the scrollable frame info and event region info in a map keyed by the display item id and then do a lookup there with the hit-test results.

**Comment by LifeIsStrange** [comment]
If this can help : https://www.w3.org/wiki/Hit_Testing

**Comment by staktrace** [comment]
I'm not sure if I'm interpreting what you said correctly. Do you mean having an entirely parallel list of rects, completely separate from the WR display items? Or do you mean augmenting the WR display items with additional rects? I'm ok with the latter, because there are definitely cases (e.g. HTML elements with opacity:0 styling) where an element needs to participate in hit-testing but doesn't actually draw anything visually to the screen. In those cases it makes sense to add additional rects or dummy "invisible" WR display items or something.

However if you're talking about an entirely separate, parallel list of rects, I'm not sure that's a great idea. For one thing it seems inefficient because it's a bunch of duplicated data as most of the rects will be derivable from the corresponding WR display items. But even beyond performance concerns, using a list of rectangles means you can't hit-test against rounded corners. That was one of the advantages we expected to gain by using WR for hit-testing.

**Comment by mrobinson** [comment]
@staktrace Thanks for the feedback. I'm going with the approach that hit testing data is stored inside of the main display list. Additionally, I think the way to go for "invisible" hit testing regions is to insert transparent rectangles. These rectangles will be ignored for painting purposes but used for hit testing. I have a version of this working now, but need to add support for rounded rectangles.
