### ISSUE TITLE
Can / should we replace image tiling with texture arrays?

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1583]
The texture cache refactoring has now landed. This means that all items in the texture cache sample from a texture array.

Potentially, we could remove most of the CPU code that deals with image tiling, and place images that are too large into a texture array with slices instead.

Pros:
 * Simpler / faster CPU code (no splitting primitives etc), no need for tiled image map.

Cons:
 * Shader would need to select layer slice.
 * Need to allocate enough layers up front to hold the entire image, which might (?) be wasteful in some scenarios.

Another way could be to use a texture array, but still submit a different primitive for each slice. This would avoid the FS needing to select the right slice, but allow batching of draw calls across tile slices.

It's not really clear to me at this point if it makes sense to consider this, or if it doesn't really gain us anything. Thoughts?

**Comment by glennw** [comment]
cc @kvark @nical @jrmuizel

**Comment by nical** [comment]
I am not sure if using texture arrays here implies large-ish tiles or if we can control the tile size. I like the idea of simplifying code, but we can have very long and thin images and these would cause a lot of wasted space (unless we use a texture array with very small textures).
For example the current image tiling code caters to the silly but existing pattern of using a very long one-pixel-wide image repeated background image optimally (in terms of memory allocation at least).

My preference would be to keep the cpu tiling code for now, but reconsider what to do with it if some day removing it gives us avenues for optimization.

**Comment by glennw** [comment]
I think this isn't relevant any more. We have a more detailed plan for efficiently handling image tiling now.
