### ISSUE TITLE
Add non-gating gecko builds to WebRender CI

### ISSUE THREAD

**Issue by metajack** [servo/webrender#1589]
In order to spot breaking API changes, I think we should set up a new Travis CI job in the matrix that builds Gecko with the version of WR a PR is for. We should not gate on this build, but it will be helpful to expose when breaking changes are happening.

**Comment by metajack** [comment]
cc @edunham @larsbergstrom @jonathandturner

**Comment by metajack** [comment]
cc @Manishearth

**Comment by glennw** [comment]
I'm not sure we need this now - we are (reasonably) careful about ensuring a gecko try run before merging anything that changes functionality and/or API these days. Should we close this or is it still useful to have? @jrmuizel @staktrace @kvark

**Comment by staktrace** [comment]
I'm fine with closing this. I've given this some thought and doing it in an automated way is going to be a bunch of effort and probably not worth it.
