### ISSUE TITLE
Handle big size of instance property in gpu_cache.

### ISSUE THREAD

**Issue by JerryShih** [servo/webrender#1590]
@kvark @glennw @nical 

If we have a big size of glyph(using dl::push_text()), we could hit the assert at [1].

Here is the STR:
1. turn on WR in gecko and open view-source:https://tobias-kluge.de/css/bootstrap.css
2. hit crash.

There are two problem here.
a) gecko should not send all glyph data into WR. The glyph data should be culled before sending the push_text(). In this case, gecko send all glyph data to WR even though a lot of glyph are not seen.

b) if a page really contain so many glyph on the screen, WR should split this glyph array into several batches. Otherwise, we hit the MAX_VERTEX_TEXTURE_WIDTH limit in WR.

[1]
https://hg.mozilla.org/mozilla-central/annotate/c01aa84ded7e/gfx/webrender/src/gpu_cache.rs#l252

**Comment by glennw** [comment]
Yup, we definitely need to handle (b) internally in WR. Thanks for posting a repro!

**Comment by JerryShih** [comment]
#1597 will handle the (b)

**Comment by JerryShih** [comment]
#1597 was merged.
