### ISSUE TITLE
panic in request_image()

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1611]
This is with tiling turned on in Gecko:
https://github.com/servo/webrender/blob/1a5129396ad2fe9e34ff9ebae203d0119558b261/webrender/src/resource_cache.rs#L439

I'll try to investigate more into what's causing it.

**Comment by glennw** [comment]
It sounds like tiling was enabled when the image template was created, but then an image was requested without any tile offset supplied.

**Comment by jrmuizel** [comment]
It looks like this is caused by asking for tiling on an image that used for as a mask. I don't believe we support tiled masks yet so we end up panic. It probably wouldn't hurt to panic earlier or implement tiled masks, but in the mean time it's easy for Gecko to work around this.

**Comment by Gankro** [comment]
bugzilled https://bugzilla.mozilla.org/show_bug.cgi?id=1435896

**Comment by nical** [comment]
IIRC the associated gecko bug is closed (Bugzilla down right now). There is also an issue specifically for tiled masks.
