### ISSUE TITLE
Slow startup on macOS

### ISSUE THREAD

**Issue by trishume** [servo/webrender#1615]
On OSX the Webrender examples take around 2.5s to start on my 2014 15" rMBP. This occurs both with my GT750m and my Intel Iris Pro.

The call that takes most of the time is `webrender::renderer::Renderer::new(gl, opts).unwrap();`. If I comment it and everything after, startup is instant, but uncommenting just that line makes it slow again.

According to apitrace, creating the Webrender renderer involves ~3500 GL calls. This may be the cause of the problem.

Regardless, if just initializing Webrender makes app startup slower than Safari's, that doesn't bode well for browser startup time for Servo and soon Firefox. Personally, I'm working on small tasks towards a GUI framework based on Webrender, and this is unfortunate.

I might do some profiling myself and see what I can do. I understand if this isn't a priority for Mozilla yet. Just noting it here since now is when I have the data.

**Comment by glennw** [comment]
@trishume The reason for this is that the examples enable the ```precache_shaders``` option when initializing WR.

What this does is pre-compile every single shader permutation on startup - we do this in the example to ensure that our CI machines catch any shader syntax errors.

In Servo (and I assume in Gecko, too) we set the ```precache_shaders``` option to false. This results in a dramatically quicker startup time, and each shader is only compiled on first use.

**Comment by glennw** [comment]
As a follow up, we are also planning to implement shader caching, on platforms that support it in the future as well.

**Comment by trishume** [comment]
Cool thanks for the info! I turned off `precache_shaders` and startup is fast now.
