### ISSUE TITLE
Way to change device pixel ratio at runtime

### ISSUE THREAD

**Issue by trishume** [servo/webrender#1616]
On macOS, when a window is dragged between a Retina display and an external non-Retina display or vice-versa, the device pixel ratio changes. I don't see any API to update Webrender's pixel ratio after creating the renderer.

Is the correct solution to recreate the renderer when the device pixel ratio changes, or to add a feature to Webrender to update the ratio?

**Comment by glennw** [comment]
We should support changing it at runtime.

It should be trivial to do (we already modify it internally to handle pinch zoom, so most of the pipeline supports it now).

I think what we'd probably want to do is extend ```SetWindowParameters``` message to include a device pixel ratio, and plumb that through to set the ```device_pixel_ratio``` field.
