### ISSUE TITLE
Select glyph based on subpixel offset in vertex shader.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1632]
Currently, we handle subpixel positioning of glyphs (along the layout axis direction), by selecting which glyph to use on the CPU based on the subpixel offset.

Instead, we should do this:
 * When a glyph is requested, we rasterize all four subpixel variations at once [1], and place them into a single location in the texture cache[2].
 * Use the vertex shader to select which of the subpx variations to use (by modifying the UV rect passed to the FS).

This has several benefits:
* Correctness - right now, we base the subpx selection on the CPU on the local space position of the glyph. This means it is incorrect if the stacking context has a transform or scroll offset with subpx positioning. The vertex shader has access to the exact world space position of the vertex, so can select the correct glyph taking into account the final transform matrix.
* Performance - This simplifies a lot of the CPU code that deals with glyph positioning. The CPU code that truncates and selects the right glyph is in a very hot path on most pages, and this could be completely removed.
* Performance - Since all subpx variations are in a single texture cache entry, this reduces the number of entries and hashing costs associated with maintaining the glyph and texture caches.
* Performance - we should be able to remove some vector allocations as a result of these changes.

[1] Once a glyph is used, it's likely that somewhere on the page will require each of the subpx variations, so this shouldn't add any overhead in most normal cases.
[2] If we arrange the four glyphs in a 2x2 configuration, this will keep the allocation sizes square-ish enough to work well with the texture cache slab allocator.

**Comment by glennw** [comment]
cc @kvark @nical

**Comment by gw3583** [comment]
It turns out that we want to do the subpixel selection based on the local position anyway (otherwise we get 'swimming' of glyphs within a word in some animation cases). Although this code is still in a hot spot, we can handle that by caching text runs between frames and display lists.
