### ISSUE TITLE
The texture cache does not update profile counters anymore.

### ISSUE THREAD

**Issue by nical** [servo/webrender#1637]
Since #1572 the texture cache info in the profiler view is not updated, making it look like there is no image allocated, which creates some confusion like in this bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1394806#c0

I think that this info was useful and it'd be nice to get it back somewhere (be it in the HUD profiler view or the web debugger). If we are not going to restore it the profiler view we should we should remove it to avoid the confusion.

**Comment by nical** [comment]
cc @glennw

**Comment by glennw** [comment]
Sure - I'll update the profile counters to reflect the new texture cache state, and also add them to the web debugger at the same time.
