### ISSUE TITLE
Handle the zero length of data for external raw data.

### ISSUE THREAD

**Issue by JerryShih** [servo/webrender#1646]
@kvark @glennw @nical 
If we pass a empty slice to the wr, we will pass a nullptr data to device.update_pbo_data()[1]. Then, we might see the previous content in texture cache for that area.
In this case, I would like to create a small 1x1 texture and blit this texture to the corresponding texture cache area for initialization.

[1]
https://github.com/servo/webrender/blob/91671498bc1b454d9e271df79ca41fc94d3ef309/webrender/src/renderer.rs#L1662

**Comment by kvark** [comment]
>If we pass a empty slice to the wr, we will pass a nullptr data to device.update_pbo_data()[1]

Could you expand on the specific of where and how you pass the empty slice exactly?

I don't think `update_pbo_data` ever gets a nullptr. According to [playground](https://play.rust-lang.org/?gist=12c5a0a0c3d888e459b76dcda122f065&version=stable), an empty slice pointer resolves to 1.

**Comment by JerryShih** [comment]
@kvark 
Sorry, not the addr but the size.
https://play.rust-lang.org/?gist=72e634c90b5b56dae46532a7eca48205&version=stable

**Comment by JerryShih** [comment]
Since the size is 0, we will not upload any data into that pbo. Then, we will see the old content for that area.
Gecko might pass a nullptr to the ExternalImageHandler. Then, we construct a empty slice for this nullptr and pass it to update_pbo_data().

**Comment by kvark** [comment]
@JerryShih 

Why would Gecko pass zero data into `ExternalImageSource::RawData` ?

Clearly, WR is missing any checks to ensure that the amount of external data matches the transfer operation with do with PBO. I'd just add an assert/error in there, but you are saying that this case (with zero size) is legitimate?

**Comment by nical** [comment]
I think that @JerryShih  is referring to an error scenario where we fail to map the shared memory in the gecko side and end up with an external image callback that doesn't have anything to give to webrender.

I think that the use case is legit, although it could probably be worked around in gecko (by allocating a small buffer and pass ing a pointer to that instead of the shared memory). From where I stand (from far away, so take with a grain of salt) it would feel cleaner to me if we had a way for the external image callback to fail (doesn't need to be zero size) and handle that in webrender (probably just not render the thing or sample from a placeholder texture). 

Maybe Jerry also has other use cases in mind.

**Comment by kvark** [comment]
@nical that makes sense, thanks for clarification! Having an ability to fail is definitely better than awkwardly returning zero data :)

**Comment by JerryShih** [comment]
@kvark @nical 
Using other error code/enum instead of zero data is also good. It's easy to do that.

For other external image type, it's easy to handle the failed case for the external image callback. But it's hard to do with ExternalImageSource::RawData. The RawData uses the regular texture_cache. It might just reference a sub-area of one texture-array in texture-cache. And the texture_id is already in the batch-data. So, it's not easy to skip that primitive drawing from a batch list. So, another approach is that we could still reference the same area of that texture-array but fill a clear color for that area.
Currently, if we do nothing for that zero data, there is no crash or error occurred. But we will see the old texture data in that area.
For pbo related functions, there is no one which could accept a nullptr for initialization(unlike texImage2D). So, we need to clear that area manually.

**Comment by kvark** [comment]
@JerryShih 
>  But it's hard to do with ExternalImageSource::RawData. The RawData uses the regular texture_cache. It might just reference a sub-area of one texture-array in texture-cache. And the texture_id is already in the batch-data.

Can we mark the texture as "incomplete" (by having a flag in it, for example) and then skip any batches where this texture is used during rendering?

**Comment by nical** [comment]
I am unsure about skipping the entire batch. My worry is that we might end up with odd bug reports where something very obvious disappears because it is in the same batch as something less visible that we failed to upload to the same batch.

I would prefer to draw a placeholder thing (even if that's just fully transparent, and the primitive is not visible in the end).

**Comment by kvark** [comment]
@nical I wrote this with an assumption that the batch contains only items using this texture (in which case it would make sense to discard it as a whole), but this is not accurate: the texture is just a region in the texture cache, so discarding it would indeed hide some of the valid calls, which is undesirable.

It does appear to me that something like [glClearBufferSubData](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glClearBufferSubData.xhtml) on the PBO (with the usual PBO->texture transfer left intact) would be the simplest solution.

**Comment by JerryShih** [comment]
@nical @kvark 

> @nical I wrote this with an assumption that the batch contains only items using this texture (in which case it would make sense to discard it as a whole), but this is not accurate: the texture is just a region in the texture cache, so discarding it would indeed hide some of the valid calls, which is undesirable.

Yes, maybe only one region in that texture cache is not valid. We should not drop the whole batch.

> It does appear to me that something like glClearBufferSubData on the PBO (with the usual PBO->texture transfer left intact) would be the simplest solution.

Unfortunately, there is only opengl 4.1 on mac now. So, we can't use glClearBufferSubData()(gl 4.3). I try to avoid the temporary array(which might raise the memory usage peak) for pbo buffer initialization, but I haven't found a good way.

This is what I tried before:
a) create a small 1x1 texture and bind to a fbo
b) binding to the dest texture in texture_cache
c) call glCopyTexImage2D() to copy data from fbo to dest texture.
This approach needs some fbo bindings. That could make gpu pipeline stall.

So, I will still try to create a local buffer for the pbo initialization first.

**Comment by kvark** [comment]
@JerryShih ok, I suppose it's not a performance critical path, so we can afford doing wasted work with PBOs here just to keep the implementation clean and non-intrusive.

**Comment by glennw** [comment]
I believe this is resolved now. Please re-open if more work is required.
