### ISSUE TITLE
Add a page to the web debugger that displays the clip-scroll tree.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1650]

**Comment by lqd** [comment]
I'd like to take a stab at this :)

**Comment by glennw** [comment]
@lqd Great! I'd suggest starting with looking at ```print_node``` and then porting that to be serializable to a JSON object (see some of the other web debugger pages with the ```debugger``` feature).

After that, it would be a case of writing the Vue template in the debugger to display it (should be able to use the existing pages as a reference).

**Comment by lqd** [comment]
@glennw yeah I have already done the Vue etc — but was wondering about a couple things (the reason why I pinged you on irc) and basically those questions were answered by your mentioning `print_node` :)
Just to be sure, as I'm not that familiar with WR or its clipscroll tree, my thoughts were that this serialization work should be done in the `render_backend`, serializing/traversing the clip_scroll_tree of each document's frame, right ?

**Comment by glennw** [comment]
@lqd Yep, that sounds reasonable - there are a couple of existing commands (the one that serializes the display lists) that could be useful as a reference.

**Comment by lqd** [comment]
This issue was indeed fixed by #1669 :)
