### ISSUE TITLE
Add screenshot reading to the debugger.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1672]
It would be great to be able to pull screenshots across to the debugger - of the framebuffer, render targets and texture cache.

Basically this would involve handling the message in ```renderer```, calling glReadPixels to get the data, serializing that across the socket (either as binary or base64), and then assembling that as an image in the web debugger (I guess via a data uri).

An initial implementation could just allow viewing the images. Eventually it'd be great to have a image viewer component in the debugger that can pan / zoom on the image - this would make it really easy to debug issues at the pixel level.

**Comment by nc4rrillo** [comment]
I'm working on this.

**Comment by glennw** [comment]
Awesome! Let me know if anything's not clear from the description :)

**Comment by kvark** [comment]
Not sure if it's worth going that far in the GPU debugging support instead of just integrating with RenderDoc so that we can hit "capture" from our UI.

**Comment by nc4rrillo** [comment]
I can work on that as well 👍. Seems fairly straightforward.
