### ISSUE TITLE
Ensure that warn! output is visible in client outputs.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1677]

**Comment by kvark** [comment]
I don't think it's necessarily a responsibility of WR. `log` crate defines standard ways to process the output, and one casual example of the consumer is `env_logger`. Servo hooks up to the log stream as well.

**Comment by glennw** [comment]
There's an existing bug (from @nical I think) about providing an interface for C++ clients to access a logging stream (perhaps via callback). This is probably related to that.

**Comment by nical** [comment]
In gecko we have various ways to log warnings. The one that I am interested in having some plumbing for in webrender is the gfxCriticalError/gfxCriticalNote that saves the log in the crash reports. We tend to use it sparingly, only in places where we are likely to crash soon and the logged information would helps with investigating the issue. It is super useful.

**Comment by kvark** [comment]
@nical sounds good. Could you create a Bugzilla item for this?

**Comment by nical** [comment]
There we go: https://bugzilla.mozilla.org/show_bug.cgi?id=1399389

**Comment by staktrace** [comment]
See also https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Gecko_Logging#Rust

**Comment by JerryShih** [comment]
I have some updates for this in https://bugzilla.mozilla.org/show_bug.cgi?id=1399389.

**Comment by gw3583** [comment]
The associated bugzilla bugs are fixed.
