### ISSUE TITLE
Implement support for text-writing modes (rotated glyphs)

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1690]
This is a fairly experimental API, but basically there will be ways to draw "hello" vertically with the actual glyphs rotated. I think gecko currently implements this by applying a rotation transform on the DrawTarget.

This is what we look like running in gecko right now, because we ignore DrawTarget transforms:

<img width="780" alt="screen shot 2017-09-11 at 2 03 55 pm" src="https://user-images.githubusercontent.com/1136864/30290110-4706ae78-96fc-11e7-9806-c55b19e8e4fc.png">

This is what gecko looks like without webrender:

![screen shot 2017-09-11 at 2 20 24 pm](https://user-images.githubusercontent.com/1136864/30290157-65f80728-96fc-11e7-8990-4179009488ea.png)

Low priority; this stuff is still being developed in the CSS specs. 

Part of https://github.com/servo/servo/issues/2560

**Comment by Gankro** [comment]
I assume support for this in webrender will amount to adding a `RotateNone | RotateLeft | RotateRight` enum to text runs, which will tell the backend to render the glyphs rotated. Glyph positioning won't be affected; layout should handle that part for us.

**Comment by Gankro** [comment]
Alternatively we could handle this with transforms on stacking contexts, but afaict we try to avoid that?

**Comment by Gankro** [comment]
Oh, screenshots are from this reftests in gecko:

`layout/reftests/w3c-css/submitted/writing-modes-3/logical-physical-mapping-001.html`

**Comment by Gankro** [comment]
Discussing this, we need rotation transforms to interact well with subpixel AA, so it's possible support for this should just amount to applying a rotation transform to the whole text-run. This is incidentally how gecko does it, so it would be trivial to writing the gecko side of such an impl.

However we would need to be able to transform the glyphs without transforming lines, but still being able to apply a shadow. I'm not sure if a stacking context within a shadow is legal. If it's not, making this a special case might be better.

**Comment by kvark** [comment]
> we need rotation transforms to interact well with subpixel AA

Given that subpixel AA relies on the fact of LCD's 3x1 led representation per pixel, I don't see how rotating an AA-produced text would give you proper subpixel AA? It sounds like we need to rasterize it rotated from the start.

**Comment by mstange** [comment]
> It sounds like we need to rasterize it rotated from the start.

Yes, and I think that's what the plan is in #1542, at least for stationary transforms (which will probably be determined by Gecko). If the transform is animated, we should rasterize the glyph unrotated but without subpixel AA.

**Comment by lsalzman** [comment]
@glennw This is fixed now, can we close?
