### ISSUE TITLE
Text snapping(?) still suboptimal

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1704]
Looking at `layout/reftests/w3c-css/submitted/selectors4/dir-style-01b.html` on macos.

Left: gecko
Right: webrendest-layers-free gecko

![screen shot 2017-09-14 at 11 42 42 am](https://user-images.githubusercontent.com/1136864/30439537-0fbba1ce-9942-11e7-8857-38a746f75ebe.png)

You can see many of the glyphs are too close together (because one is exactly one pixel off?).

I would be surprised if this was a bug in the gecko layout code. It could be that gecko needs to send more font info? Or it could just be our text-snapping logic.

**Comment by mstange** [comment]
This is #1270.

**Comment by Gankro** [comment]
Dupe
