### ISSUE TITLE
Glyphs are all over the place on my integrated GPU

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1728]
After the most recent [webrender update in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1400216), which included #1715, text rendering is now completely garbled on my machine while using the integrated GPU.

When switching to the discrete GPU, text rendering is fixed.

Integrated:
<img width="935" alt="screen shot 2017-09-20 at 9 08 11 am" src="https://user-images.githubusercontent.com/961291/30645387-9d2bb2ce-9de3-11e7-869f-648651d4b241.png">

Discrete:
<img width="935" alt="screen shot 2017-09-20 at 9 08 20 am" src="https://user-images.githubusercontent.com/961291/30645393-a30f6d2a-9de3-11e7-80a1-a47f5ce120fb.png">

I'm on macOS 10.12.6 (16G29), my integrated GPU is an Intel HD Graphics 530 1536 MB.

**Comment by mstange** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1401633

**Comment by glennw** [comment]
@mstange Was the text working fine on your mac previous to that update? Do you have a git SHA1 regression range I could take a look at?

**Comment by mstange** [comment]
Text is working fine on the integrated GPU with 1407b1e1cd0631527f2e686b16aed38c0feabaaf and broken with 68e2e7cd0e39d216bb6c35dfb353dc0700bb6948 .

For 1407b1e1cd0631527f2e686b16aed38c0feabaaf I tested the macOS build from the first try push in https://bugzilla.mozilla.org/show_bug.cgi?id=1400216#c4 (which is at https://queue.taskcluster.net/v1/task/B-4OuL9RTNOUpW3_4CkDUA/runs/0/artifacts/public/build/target.dmg ).

**Comment by glennw** [comment]
Wow, that's really strange. The only related change I can see in that range is the subpx text PR, which has only a minor shader change (https://github.com/servo/webrender/commit/ec26fb9221502d21126a52a7a227f54bc48f7c72).

If it's easy to do, it would be handy to revert that locally and confirm that is trigger what is (probably) a driver bug. Otherwise, I have a mac laptop being shipped to me now - so hopefully I'll receive that within the next week or so and be able to reproduce locally.

**Comment by paulrouget** [comment]
Same here. Just regular Servo.

Intel Iris Graphics 550 1536 MB

<img width="1136" alt="screen shot 2017-09-21 at 15 26 11" src="https://user-images.githubusercontent.com/373579/30698539-8cd4147a-9ee2-11e7-9138-e3a97b8c223b.png">

**Comment by mstange** [comment]
Yes, backing out ec26fb9 fixes it.

The smallest shader change I found that triggers the bug is to change `trunc(glyph.x)` to `trunc(glyph.x + 0.01)`.

**Comment by mstange** [comment]
And this change "fixes" the bug:

```diff
diff --git a/gfx/webrender/res/prim_shared.glsl b/gfx/webrender/res/prim_shared.glsl
--- a/gfx/webrender/res/prim_shared.glsl
+++ b/gfx/webrender/res/prim_shared.glsl
@@ -276,17 +276,17 @@ Glyph fetch_glyph(int specific_prim_addr
                   int glyph_index,
                   int subpx_dir) {
     // Two glyphs are packed in each texel in the GPU cache.
     int glyph_address = specific_prim_address +
                         VECS_PER_TEXT_RUN +
                         glyph_index / 2;
     vec4 data = fetch_from_resource_cache_1(glyph_address);
     // Select XY or ZW based on glyph index.
-    vec2 glyph = mix(data.xy, data.zw, bvec2(glyph_index % 2 == 1));
+    vec2 glyph = mix(data.xy, data.zw, bvec2(glyph_index % 2 != 0));

     // In subpixel mode, the subpixel offset has already been
     // accounted for while rasterizing the glyph.
     switch (subpx_dir) {
         case SUBPX_DIR_NONE:
             break;
         case SUBPX_DIR_HORIZONTAL:
             // Glyphs positioned [-0.125, 0.125] get a
```

Don't ask me why. This seems like a shader compiler bug.

**Comment by leeoniya** [comment]
logged it here: https://github.com/servo/webrender/wiki/Driver-issues#1728-1368---shader-compiler-bug-when--is-used-inline-as-function-arg

hopefully i got the description right

**Comment by mstange** [comment]
My guess would be that the circumstances in which this bug happens include an equality comparison between integers if the result of that comparison gets casted to a float.

**Comment by glennw** [comment]
@mstange is going to open a PR with a work around for this apparent driver bug :)
