### ISSUE TITLE
[RFC] Change public item APIs to support a local clip rect only.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1742]
We change the public display item APIs to support a local clip rect only. Any clips in addition to that (e.g. rounded rects, image masks etc) must be defined via a clip item and the clip ID for the item.

This seems like it would cover the common cases easily, without having to create a heap of clip items in the DL. It's also really easy for WR to handle the simple local clip rect case.

This could potentially allow us to both simplify and improve the performance of several areas of WR - DL serialization time, clip stack generation etc.

Thoughts @mrobinson @jrmuizel @staktrace @kvark @nical ?

**Comment by jrmuizel** [comment]
I gathered some statistics on the number of clips vs the number of items using this patch: https://pastebin.mozilla.org/9067953

gmail: 2678 for 2897 items
gmail: 974 for 1124 items
cnn: 263 for 963 items
nytimes: 668 for 1243 items
facebook: 718 for 1549 items
arstechnica: 408 for 812 items
twitter: 331 for 1281 items
instagram: 260 for 442 items

Given these results it's probably fair to say that there is rarely more than 2 display items per clip. Perhaps we need to look at representing them differently in Gecko. @mattwoodrow @mstange

**Comment by jrmuizel** [comment]
Gmail: 2223 clips 7 rounded
Github: 250 clips 45 rounded
Facebook: 442 clips 93 rounded

**Comment by glennw** [comment]
@jrmuizel So, based on that sample - ```local_clip_rect``` in the display item (for WR at least, probably Gecko too), and other clips as clip items?

**Comment by glennw** [comment]
I wonder how many of those clips being generated for gmail are redundant...

**Comment by mrobinson** [comment]
This was part of the original plan when I simplified the previous design into the current `LocalClip` design. The reason that I didn't go all the way here and eliminate rounded rectangles from `LocalClip` was due to the fact that:

 1. WebRender uses per-item rounded rectangle clips internally anyway.
 2. Removing them from Servo proved to be quite tricky when I tried.

I still think this is a good idea though, as long as we can do it in a clean way.

**Comment by jrmuizel** [comment]
Some quick statistics on items that share a clip from Gmail:
 142 was valid Border
   1 was valid BoxShadowInner
   2 was valid BoxShadowOuter
   2 was valid ButtonBorderBackground
   2 was valid CanvasBackgroundColor
   1 was valid FieldSetBorder
 209 was valid Image
 469 was valid LayerEventRegions
   1 was valid TableBorderCollapse
 440 was valid Text
   1 was valid nsDisplaySVGGeometry

So it looks like clip sharing mostly happens with LayerEventRegions and Text

**Comment by jrmuizel** [comment]
<details>
<summary>
Some more statistics based on a patch like this:
</summary>

```patch
+  nsDisplayItem* i = (nsDisplayItem*)aPtr;
+  if (i->mWasValid) {
+    printf_stderr("was valid %s\n", i->Name());
+    mValidCount++;
+  }
+  if (i->mClip == nullptr) {
+    mNoClipCount++;
+  } else {
+    bool snap;
+    if (i->mClip->IsRectAffectedByClip(i->GetBounds(this, &snap))) {
+    } else {
+      mRedundantCount++;
+    }
+  }
+  mItemCount++;
```

</details>

github: itemCount 790 valid 538 clip count 248 round 74 redundant 573 noclip 111
gmail: itemCount 2629 valid 1200 clip count 2148 round 82 redundant 1760 noclip 475
itemCount 3251 valid 1552 clip count 2803 round 20 redundant 2064 noclip 446
twitter: itemCount 242 valid 147 clip count 62 round 7 redundant 144 noclip 76
reddit: itemCount 896 valid 688 clip count 420 round 24 redundant 744 noclip 60
instagram: itemCount 265 valid 139 clip count 128 round 20 redundant 160 noclip 88
facebook: itemCount 1221 valid 569 clip count 530 round 102 redundant 479 noclip 539

**Comment by glennw** [comment]
Could you clarify what those stats mean? Most of them make sense but they don't necessarily add up in the way I'd expect, so I'm probably mis-interpreting some of the numbers.

There are a huge number of redundant clips, esp. on gmail though, right? Is that something we can change Gecko to filter out?

**Comment by glennw** [comment]
Oh, I just realized - having new clips breaks primitive runs. So that's an extra win WR gets from removing redundant clips, in addition to the serialization overhead and clip-scroll tree size.

We can probably do a better job of filtering redundant clips earlier in WR - but that would still have serialization overhead I guess, unless we can somehow do it in the DL builder?

**Comment by glennw** [comment]
As a follow up to the previous comment - every time we encounter a new clip ID in the tree (that breaks a primitive run), we currently re-traverse the clip-scroll tree to build the clips for this node in the tree.

We can (and will) make this *much* more efficient in WR. It's an interesting observation though - this will likely explain a very large portion of the CPU time spent processing Gecko DLs at the moment.

The right long term fix is probably to (a) Reduce the number of clips in the DL and (b) make WR handling of building the clip hierarchy more efficient.

**Comment by jrmuizel** [comment]
I'm not exactly sure how to interpret my numbers either. The redundancy that I'm measuring is in the loosest sense. i.e. Does the clip intersect with the display item. Having a high number here isn't necessarily wrong (e.g. scrolling or a large amount of sharing could make it correct). I'll try to look at the clip situation on a page like gmail more closely with @mstange tomorrow to see what we can do on the Gecko side.

**Comment by jrmuizel** [comment]
@mstange and I took a look at the gmail display list and discovered what looks like a bug that will cause more clip allocations than needed. @mstange will try to debug it later today.

**Comment by jrmuizel** [comment]
The bug we thought we had wasn't, but we think we see a new one.

**Comment by jrmuizel** [comment]
Looking here http://searchfox.org/mozilla-central/source/layout/painting/nsDisplayList.cpp#3258 it seems like we unconditionally create a new clip for every BackgroundColor display item.

**Comment by jrmuizel** [comment]
So I switched to doing analysis directly on a dump of the display list to get more meaningful results:
On this example we have 3368 display items and 1542 clips.
Of the 1315 items with unique clips, 809 of them are BackgroundColor items, 257 Background and 197 LayerEventRegions. @mstange had a plan for dealing with the BackgroundColor items that we'll try out tomorrow. We haven't looked at the other ones yet.

**Comment by glennw** [comment]
I just realized something. I recall @staktrace saying that Gecko doesn't really use per-item clips in WR at all - is that right?

If that's the case, this will be a major source of GPU slowdowns in Gecko relative to Servo. Right now, WR can only take advantage of inner opaque pass optimizations of rounded rects where the clip is on the item, rather than a clip node.

Nothing needs to be changed on the Gecko side if this is the case - it's entirely an issue in WR that we need to fix. I will bump up the priority a bit though, assuming what I said above is correct?

**Comment by jrmuizel** [comment]
We definitely don't currently use per-item rounded clips.

**Comment by glennw** [comment]
OK, that means every rounded rectangle is going through the alpha pass, and getting no benefit from the z-buffer rejection. Once we handle this use case in WR, we should see some *serious* GPU time improvements.

**Comment by kvark** [comment]
😨 😨 😨

**Comment by jrmuizel** [comment]
We're going to do some further investigation into what the Gecko side should do here: https://bugzilla.mozilla.org/show_bug.cgi?id=1406516

**Comment by mrobinson** [comment]
I investigated why it's complicated to remove complex LocalClips from Servo. The reason is that ClipScrollNodes are created and assigned during the stacking context assignment pass and are done on a per-Flow basis. Complex LocalClip nodes are done based on a per-display-item basis. For instance, the border needs one clip and the background needs another. Allowing creation of ClipScrollNodes during the final phase of display list construction is possible, but requires a bit of reworking in how Servo create ClipScrollNodes. I had this on the todo list anyway, so I'm hoping to have it completed in the next day or two.

**Comment by mrobinson** [comment]
I think it is totally possible to use ClipScrollNodes in Servo now and remove this from the LocalClip API.
