### ISSUE TITLE
Webrender mishandling shadows/transparency on emoji (color glyphs)

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1747]
This crashes webrender:

```text
data:text/html,<html><head><meta charset="utf8"></head><body style="text-shadow: 0px 0px 1px black;">🙃</body></html>
```

This fails to render as transparent in webrender:

```text
data:text/html,<html><head><meta charset="utf8"></head><body style="color:rgba(0,0,0,0.1);">🙃</body></html>
```

Seems related? text-shadows bypassing a safety guard that causes the second one to be opaque?

backtrace:

```
thread 'WebRender:Worker#5' panicked at 'assertion failed: `(left == right)` (left: `4`, right: `8`)', /Users/ABeingessner/dev/gecko/gfx/webrender/src/platform/macos/font.rs:426
stack backtrace:
   0:        0x11a82a993 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h884a721e113c3303
   1:        0x11a836e53 - std::panicking::default_hook::{{closure}}::h7a7d734b2824d103
   2:        0x11a836a9c - std::panicking::default_hook::h3eb11bd6cbfdc331
   3:        0x11a838fc7 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
   4:        0x11a838e64 - std::panicking::begin_panic::h69fe06a9d67b6165
   5:        0x11a838dd2 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
   6:        0x11a14d1e5 - webrender::glyph_rasterizer::GlyphRasterizer::request_glyphs::{{closure}}::{{closure}}::he3c67689b6433db9
   7:        0x11a115f52 - rayon::iter::internal::bridge_producer_consumer::helper::he869ddeb5dd1c5df
   8:        0x11a0fc509 - std::panicking::try::do_call::h3b50a9cff7cadfa3
Redirecting call to abort() to mozalloc_abort
```

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1401798

**Comment by Gankro** [comment]
The shadow crash only happens with Apple's emoji font. For instance, there's no problem with applying shadows to mozilla's emoji font: http://mozilla.github.io/fxemoji/dist/FirefoxEmoji/index.html

Although we still don't apply transparency.

**Comment by Gankro** [comment]
I removed the assertion for fun, and got this haunting specter:
![screen shot 2017-09-25 at 4 04 46 pm](https://user-images.githubusercontent.com/1136864/30828490-d3a8eaa2-a20b-11e7-822d-e66fb7b9e389.png)

**Comment by Gankro** [comment]
This patch (which screws up almost everything else) gets the shadow right:

```
diff --git a/gfx/webrender/src/platform/macos/font.rs b/gfx/webrender/src/platform/macos/font.rs
index a7bb1c2fcbbc..0caf35f0abf6 100644
--- a/gfx/webrender/src/platform/macos/font.rs
+++ b/gfx/webrender/src/platform/macos/font.rs
@@ -511,7 +511,7 @@ impl FontContext {
                 height: metrics.rasterized_height as f64,
             },
         };
-        cg_context.fill_rect(rect);
+        // cg_context.fill_rect(rect);
 
         // Set the text color
         cg_context.set_rgb_fill_color(0.0, 0.0, 0.0, 1.0);
@@ -543,10 +543,11 @@ impl FontContext {
 
                 pixel[3] = match font.render_mode {
                     FontRenderMode::Subpixel => 255,
+                    FontRenderMode::Mono => pixel[0],
                     _ => {
-                        assert_eq!(pixel[0], pixel[1]);
-                        assert_eq!(pixel[0], pixel[2]);
-                        pixel[0]
+                    //    assert_eq!(pixel[0], pixel[1]);
+                    //    assert_eq!(pixel[0], pixel[2]);
+                        pixel[3]
                     }
                 }; // end match
             } // end row
```

In effect, it draws the glyph on a transparent background, and then uses the alpha channel to hit-test the shape, which is what we want.

**Comment by Gankro** [comment]
Doing the filling in a transparent rect (or skipping the fill_rect) only when doing Subpixel stuff gets pretty good results, but also some baffling behaviours:

* Shadows render on top of emoji (*only emoji* ???)
* If zoomed in and blur is low (~0.01) you can see that the tops of some of the shadows (top right) are getting cut off and showing up in another text run (the one to the left)

This suggests this patch is Doing A Bad, but hopefully this is enough for you to figure out what to do.
![screen shot 2017-09-25 at 5 22 39 pm](https://user-images.githubusercontent.com/1136864/30831714-7d53709a-a216-11e7-9c16-103cc0e21b6d.png)

**Comment by mstange** [comment]
It looks like emoji glyphs are drawn with the wrong compositing mode (multiply instead of over?). For example, `data:text/html,<meta charset="utf8"><body style="background:blue">%F0%9F%99%83` looks wrong and it doesn't involve text shadow.

**Comment by mstange** [comment]
That explains why the shadow appears to be "on top" of the glyph (it's not, it's just shining through). It doesn't explain why there is garbage from other pieces of text appearing.

**Comment by Gankro** [comment]
Confirmed fixed.

I think the transparency thing is on the gecko side.
