### ISSUE TITLE
most fonts don't render? (all platforms)

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1748]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402585

filing here too just so everyone sees it. Not sure if it's a gecko or webrender bug yet.

**Comment by glennw** [comment]
OK, this seems to be an issue in the Gecko code.

The regression range was https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=176e16629030869dfd6e31e240006f9ea70be2ba&tochange=754a0d9a44ea5208b6b204e06033e008a6c17b52

This line https://hg.mozilla.org/integration/autoland/rev/754a0d9a44ea#l5.12 seems to always be failing. This results in no font instances being added, which means that WR drops the text runs with an unknown font instance.

cc @lsalzman
