### ISSUE TITLE
Shouldn't be applying color to emoji (colored glyphs)

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1749]
If you set `color: #0366d6` on my good friend https://gankro.github.io/blah/webtests/text.html the emoji turn purple (at least on macos). Webrender should be ignoring the RGB color values attached to colored fonts. Although it does need to respect the alpha.

You can also see this on reactions in github issues. (which I will add to this issue as an easy example)

Possibly the same root cause as #1747

**Comment by Gankro** [comment]
Interestingly, doesn't happen for mozilla's emoji: http://mozilla.github.io/fxemoji/dist/FirefoxEmoji/index.html

So it looks like a funky interaction with apple's emoji set. Did font variations suddenly unlock this...?

**Comment by glennw** [comment]
@Gankro I think this one can be closed?

**Comment by Gankro** [comment]
I agree, I was just waiting for this land upstream in gecko (a few more hours) before checking the box.

**Comment by kvark** [comment]
@Gankro for the reference, please post the associated Gecko issue here

**Comment by Gankro** [comment]
There isn't one, which is why I was using this for it 😅

(we can't test it in this repo, so it made sense to do final verification once it was integrated with something that can)

**Comment by Gankro** [comment]
Confirmed fixed.
