### ISSUE TITLE
No provider of glPushGroupMarkerEXT found

### ISSUE THREAD

**Issue by antoyo** [servo/webrender#1755]
Hello.
When doing my gtk+ binding for servo, I had to comment [this line in epoxy](https://github.com/antoyo/epoxy-rs/blob/master/build/main.rs#L66) in order to make it work.
Otherwise, the application aborts with the following error:
```
No provider of glPushGroupMarkerEXT found.  Requires one of:
    GL extension "GL_EXT_debug_marker"
Redirecting call to abort() to mozalloc_abort
```

Is it normal that I needed to comment this line?
If not, what can I do to fix this issue?
Thanks.

**Comment by kvark** [comment]
Thanks for filing this issue!

I'm not familiar with `epoxy`. Currently, WR works with `gleam` that requests the extension in `build.rs`. It is able to not find the extension, in which case the call to `self.ffi_gl_.PushGroupMarkerEXT.is_loaded()` would return `false` and we aren't going to use any markers. Would there be a way in `epoxy` to make the extension optional?

**Comment by antoyo** [comment]
Yeah sure.
I don't really know OpenGL and how it's used in Rust, so I was wondering what is this extension (and what are extensions in general).
I'm not familiar with `epoxy` either. I just know that it's used by gdk.
Do you think this extension is needed in some cases for `epoxy`?
Or can I just disable it without providing a way of activating it?
Thanks for your help.

**Comment by glennw** [comment]
Extensions are optional additions to the GL API that may or may not be supported, depending on vendor / platform / driver etc.

In this case, the extension we're using insert debugging tags in the GL command buffer that is useful when viewing debug traces in GPU debugging tools. It's only used for debugging - so it shouldn't affect any functionality if you don't have this on your platform.

**Comment by kvark** [comment]
@glennw I guess we could have a `profile` feature for enabling markers and such.

**Comment by glennw** [comment]
Probably a reasonable idea - I guess it's probably a performance win to not be issuing all those timer queries in a release build :)

**Comment by glennw** [comment]
We now use the ```query``` feature to disable this in builds that don't want the profiler.
