### ISSUE TITLE
Implement Partial Ligatures?

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1757]
https://bugzilla.mozilla.org/show_bug.cgi?id=1403261

http://manishearth.net/sand/ligature_coloring.html

http://robert.ocallahan.org/2006/10/partial-ligatures_24.html

This one is a bit wonky, only gecko implements it. Edge kinda tries but just picks one color.

**Comment by jrmuizel** [comment]
Yes. That sounds reasonable to me.

**Comment by glennw** [comment]
In most cases, a local clip rect should probably do the job and be cheaper than using a clip mask too.

I'll close for now - feel free to re-open if we need to do some WR work here.
