### ISSUE TITLE
Consider restructuring parts of ClipScrollNode

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1759]
It seems like ClipScrollNode has several fields that aren't relevant to all types.

For example, I think the ```content_size``` and ```local_viewport_rect``` fields aren't relevant for ```ReferenceFrame``` nodes.

Could we move some of these fields into the appropriate ```NodeType``` enum field?

**Comment by glennw** [comment]
cc @mrobinson

**Comment by mrobinson** [comment]
@glennw We might be able to get rid of one of  `local_clip_rect` / `local_viewport_rect` entirely.

**Comment by glennw** [comment]
This happened - we can open more specific bugs for further planned changes to the clip-scroll tree structure.
