### ISSUE TITLE
Consider using different glyph masks for dark and bright text on macOS, in order to match native font rendering

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1767]
https://bugzilla.mozilla.org/show_bug.cgi?id=1410971

(Some of the text below is liberally stolen from @lsalzman's email to the Skia team.)

Somewhere between 10.9 and 10.11, Apple changed the apparent weighting of fonts when rendering with LCD smoothing depending on whether the foreground color of the text is light or dark. Light text now renders thinning than it used to, while dark text renders the same as it always has.

If WebRender wants to match this, it'll need to rasterize every glyph twice; once with bright text and once with dark text. Then it needs to select the correct mask based on the text color.

This is something that Firefox lost when we switched from CoreGraphics to Skia, because Skia does not implement this brightness-based shape switching. As a consequence, bright text on dark backgrounds appears thicker than in Safari. With the switch to WebRender, we have the option to restore the native behavior.

More details on how this seems to work:

On 10.9, if you render a glyph as white foreground on black background, decode the gamma to linear, it gives you the same result as if you render black foreground on white background, decode the gamma to linear, then invert the result.

However, on 10.11, this no longer holds true. The white foreground on black background case is less heavily dilated than it used to be, so the inverted black-on-white is no longer the same as white-on-black.

We further verified by animated text foreground color, and there is a single distinct pop once the text color reaches a certain threshold, so we're pretty sure there are only two sets of weightings being chosen between here.

We did a lot of playing around with the threshold condition, and we're pretty sure given R, G, B between 0..1: If min(R,G,B) < 1/3 or R+G+B < 2, then use the normal dark text weighting. Otherwise, use the light text weighting.

It seems this strategy was introduced to deal with a perceptual glitch like outlined here: http://www.lighterra.com/articles/macosxtextaabug/

**Comment by glennw** [comment]
@mstange When a text run is using subpixel AA on mac, it is already rasterized once for each different color, in order to apply the gamma lut (see https://github.com/servo/webrender/blob/9c5f8682e75839ad8c26480b89f87bbb37aa7894/webrender/src/platform/macos/font.rs#L574).

So it shouldn't actually be any extra cost, and we already have the color information being passed through to the glyph rasterizer.

So I *think* this should be a relatively simple thing to add to WR (apart from working out the actual mechanics of the stuff you've mentioned above).

**Comment by mstange** [comment]
Oh, perfect!

**Comment by LifeIsStrange** [comment]
I'm just saying probably something obvious, but it would be nice to allow this feature on other operating systems, by default or with a toggle.
But maybe it's only possible on macOS ?

**Comment by pcwalton** [comment]
cc me, as this is relevant to Pathfinder (it ought to look native).
