### ISSUE TITLE
Transparent -apple-sytem font unusably bad

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1778]
All of the github title/menu bar uses this, toggling to opaque on hover.

Chrome:
![screen shot 2017-09-29 at 1 34 10 pm](https://user-images.githubusercontent.com/1136864/31028287-4a4e6d96-a51b-11e7-8d65-684485f07000.png)

Vanilla Firefox Nightly:
![screen shot 2017-09-29 at 1 35 35 pm](https://user-images.githubusercontent.com/1136864/31028285-4a11d9da-a51b-11e7-874d-fcf08e642e20.png)

Webrendest Firefox Nightly (wr@7a5f60aff33010a44d6acbdc67f27f1f63678b5d):
![screen shot 2017-09-29 at 1 34 22 pm](https://user-images.githubusercontent.com/1136864/31028284-4a116090-a51b-11e7-865d-48956e110591.png)

Webrendest Firefox Tip (wr@9c5f8682e75839ad8c26480b89f87bbb37aa7894):
![screen shot 2017-09-29 at 1 34 47 pm](https://user-images.githubusercontent.com/1136864/31028286-4a11f62c-a51b-11e7-8104-e1519246453e.png)

Note that even the previous Webrendest Firefox Nightly was bad (no subpixel aa), but now it's just incredibly bad.

**Comment by mstange** [comment]
This is probably due to #1811.

**Comment by Gankro** [comment]
Not sure what exactly fixed it, but the text now looks great and has (accurate?) subpixel-aa.

![screen shot 2017-10-19 at 1 01 04 pm](https://user-images.githubusercontent.com/1136864/31783826-a2b942dc-b4cd-11e7-8af7-2c6084cd7789.png)

**Comment by mstange** [comment]
This was fixed by https://github.com/changm/gamma-lut-rs/pull/3 and by #1886.
