### ISSUE TITLE
The first browser window paint takes 1.7 seconds on my machine

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1802]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423671

Profile: https://perfht.ml/2fOV42Y

The first 0.6 seconds of this seem to be initialization of the timer query machinery, and the remaining 1.1 seconds seem to be mostly shader compilation on the shaders' first use.

I'm not sure if timer queries are the actual problem here, or if the call to `glBeginQuery` is just the first thing that requires GL initialization (`IOAccelResourceCreate`), but in a profile without webrender, `IOAccelResourceCreate` only takes 2 milliseconds: https://perfht.ml/2fRIa4r

During this time we show an empty window.

**Comment by mstange** [comment]
I got this perf profile by
 1. Creating a Firefox profile called `webrender` with the relevant prefs flipped (webrender+webrendest+blob-images),
 2. Installing the Gecko profiler add-on from https://perf-html.io/ ,
 3. Launching Firefox from the command line using `MOZ_PROFILER_STARTUP=1 MOZ_PROFILER_STARTUP_FILTERS=GeckoMain,Compositor,Renderer /Applications/FirefoxNightly.app/Contents/MacOS/firefox -P webrender`, and
 4. Capturing the profile using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd> as soon as the window had been rendered.

**Comment by pcwalton** [comment]
I wonder if we should cache shader binaries from run to run.

**Comment by mstange** [comment]
WebRender runs in the parent process or in the GPU process (if available), so it shouldn't be affected by sandboxing unless we start sandboxing the GPU process.

**Comment by LifeIsStrange** [comment]
@TRowbotham AMD and Intel have landed a shader cache on Linux since a few months.
Source: https://www.phoronix.com/scan.php?page=search&q=shader%20cache
And for Windows I only know that AMD has a shader cache since ~2 years (the crimson driver release if I remember well).

**Comment by glennw** [comment]
I believe we added shader binary caching. Do we know if this is still an issue?

**Comment by jrmuizel** [comment]
Mac doesn't have shader binary caching so this is still an issue. We're also still impacted by this on startup on Windows. We probably want to precompile the shaders at build time in both cases.
1. On mac we can run glsl -> glsl optimizer.
2. On Windows we can precompile to d3d bytecode.

**Comment by gw3583** [comment]
We have done quite a bit of work here to optimize shader parsing time, and make use of the shader compiler cache if available on platform.
