### ISSUE TITLE
constructing font atlas without factoring in StackingContexts is broken

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1804]
We need to factor in scale transforms when constructing the font atlas, or else we get a blurry mess (with subpixel aa!)

Webrender:
<img width="832" alt="screen shot 2017-10-04 at 1 02 21 pm" src="https://user-images.githubusercontent.com/1136864/31188973-c0912204-a904-11e7-9903-9e04d0e3dc49.png">

Chrome:
<img width="745" alt="screen shot 2017-10-04 at 1 02 48 pm" src="https://user-images.githubusercontent.com/1136864/31188984-c7cdc9aa-a904-11e7-9621-9b67e7e8219b.png">

(ignore that chrome messed up the shadow here)

**Comment by Gankro** [comment]
In particular this means parallel glyph processing is mostly busted. A possible fix would be to have PushText consult the parent stacking context(s?)'s transforms to compute this for the backend?

**Comment by glennw** [comment]
This depends on https://github.com/servo/webrender/issues/1542.

**Comment by glennw** [comment]
@lsalzman @Gankro  I think this can be closed now?

**Comment by lsalzman** [comment]
Yes, this is fixed.
