### ISSUE TITLE
border-radius produces additional lines

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#1805]
Please feel free to edit the title of this issue.

https://bugzilla.mozilla.org/show_bug.cgi?id=1404158
* [Screenshot](https://bug1403976.bmoattachments.org/attachment.cgi?id=8913256)
* [Video](https://bug1404158.bmoattachments.org/attachment.cgi?id=8913466)
* [Testcase](https://bug1404158.bmoattachments.org/attachment.cgi?id=8913468)

> Nightly 58 x64 20170928100123 de_DE @ Debian Testing (KDE / Radeon RX480)
> gpu-process + layers force accel + webrender (layersfree) + webrendest
> Its looking like a "T" that's lying on the side. If I resize the window, the lines may hide and reappear.

Also seen on:
* Twitter (login button)
![screenshot_20171004_202358](https://user-images.githubusercontent.com/17962859/31192622-0abec34e-a942-11e7-82c3-6921b0ff3a05.png)
* Youtube (loading circle in the center of the video player)
![screenshot_20171004_202749](https://user-images.githubusercontent.com/17962859/31192823-94e397c0-a942-11e7-84db-c9a80f7d218d.png)

* Cloudflare (Caching page: Custom radio buttons have a horizontal line that flickers while scrolling)
![screenshot_20171004_202534](https://user-images.githubusercontent.com/17962859/31192682-3a76361c-a942-11e7-88a6-7c2237c1d4ff.png)

**Comment by subsevenx2001** [comment]
I found that the bogus lines disappeared after I bypass this if to make all pixel run in the if-block anyway. Maybe there is something wrong in the else block, I suspect it is some kind of rounding issue.
if (all(lessThan(local_pos * vClipSign, vClipCenter * vClipSign))) -> if (true)
https://dxr.mozilla.org/mozilla-central/source/gfx/webrender/res/ps_border_corner.glsl#335

**Comment by Darkspirit** [comment]
[Verified fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1404158#c16). Thank you! (Can we close this?)
