### ISSUE TITLE
Transformed text seems to stretch glyph image border pixels, creating fringes around glyphs

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1808]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405953

[Testcase](https://bug1405953.bmoattachments.org/attachment.cgi?id=8915469)

<img width="302" alt="webrender-text-fringes-2x" src="https://user-images.githubusercontent.com/961291/31213057-4bbf0cf2-a972-11e7-900e-9e48528e5b97.png">

**Comment by Gankro** [comment]
I'm pretty sure this is just subpixels. We currently render text before transforms, and with no regard for their existence.

**Comment by mstange** [comment]
I agree, this depends on #1542 and is just one of the things we should make sure works correctly once that's fixed. There will probably still be cases where we want to rasterize and then transform, and in those cases, this particular rendering error should not occur.

**Comment by Darkspirit** [comment]
Is this also fixed by https://github.com/servo/webrender/pull/1969 ? (They are "See Also"s in Bugzilla)

**Comment by mstange** [comment]
No, it's not. I'll remove it from the see also list.

**Comment by lsalzman** [comment]
This is fixed by PR #2058 with followup in PR #2093.
