### ISSUE TITLE
Text inside opacity has dark fringes (double-premultiplied?)

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1811]
`data:text/html,<html style="background:lightgray"><div style="opacity:0.9; color:white">Text`

<img width="150" alt="webrender-grayscale-text-in-opacity" src="https://user-images.githubusercontent.com/961291/31213879-b76db4ae-a976-11e7-8c85-34b8c942b2bc.png">

**Comment by glennw** [comment]
It's likely that this will be resolved by https://github.com/servo/webrender/pull/1816 - so we should test this again once that lands.

**Comment by Gankro** [comment]
May also be causing this slack to render bad:
<img width="272" alt="screen shot 2017-10-09 at 1 58 37 pm" src="https://user-images.githubusercontent.com/1136864/31351722-1e722d3e-acfa-11e7-8481-3e6d78971a96.png">

**Comment by mstange** [comment]
Now that #1816 has landed, the black fringes are no longer black, they're white. (!?) So there's regular opacity in the middle of the glyph, but it briefly gets brighter at the edge and then stops almost without AA.
Testcase: `data:text/html,<html style="background:lightgray"><div style="opacity:0.4; font-size: 4em; color:white">Text`
<img width="138" alt="screen shot 2017-10-10 at 6 35 57 pm" src="https://user-images.githubusercontent.com/961291/31413995-df10c3da-ade9-11e7-93a6-4ec56bbc4d4c.png">

And we still don't seem to be using subpixel AA for transparent text.

**Comment by glennw** [comment]
Do we know which platform(s) this occurs on? Is is mac-only?

**Comment by Gankro** [comment]
It only just got into gecko master, working on a windows build to see. (confirmed on mac)

**Comment by glennw** [comment]
Same as https://github.com/servo/webrender/issues/1839#issuecomment-335676472

**Comment by glennw** [comment]
Hmm, I can't actually reproduce this on Linux - it might be something else.

**Comment by glennw** [comment]
Yep, it's very noticeable on my mac, but definitely not occurring on Linux. I'll take a look at the font rasterizer - it may be setting the wrong background color for alpha text...

**Comment by glennw** [comment]
This appears to be related to the gamma LUT code. If I remove the grayscale gamma pre-blend call, it looks correct. I'll investigate further...

**Comment by glennw** [comment]
Filed https://github.com/changm/gamma-lut-rs/pull/3 which fixes the issue. We'll need to get that published and updated in WR to close this bug.
