### ISSUE TITLE
Add homu

### ISSUE THREAD

**Issue by notriddle** [servo/webrender#182]
Either homu.io or bors-servo, doesn't really matter. But this thing should have CI on it, considering how central it is (going to be) to Servo.

**Comment by larsbergstrom** [comment]
@glennw Should this repo be moved to the servo GH organization, as we have done for most of our other projects that went central? (gaol, ipc-channel, etc.)

**Comment by glennw** [comment]
@larsbergstrom Definitely! I was going to get it landed in master, then move it over as a follow up. But I can reverse the order of those if you'd prefer?

**Comment by larsbergstrom** [comment]
It's fine to wait and do it afterwards, if you'd prefer that workflow. Like @notriddle, I just wanted to make sure it was in the plans, since I assume there will be lots more PRs to come :-)

**Comment by larsbergstrom** [comment]
Done. See:
http://build.servo.org/homu/queue/webrender
http://build.servo.org/homu/queue/webrender_traits
