### ISSUE TITLE
Divide shadow blur_radius by 2?

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1827]
Gecko seems to do this internally for its shadow painting code, and our shadows seem a lot blurrier.

**Comment by glennw** [comment]
Does Gecko use a gaussian blur or approximate it with some kind of box filter blur? In the WR gaussian blur shader, I've picked an arbitrary constant for the sigma value, which affects the blurriness amount. It's possible that just tweaking this will be enough to get the results close enough.

**Comment by mstange** [comment]
Gecko uses three box blurs.

Here's the Gecko code + comments that deal with the blur radius for box-shadows:
http://searchfox.org/mozilla-central/rev/b53e29293c9e9a2905f4849f4e3c415e2013f0cb/layout/painting/nsCSSRendering.cpp#4268-4293
http://searchfox.org/mozilla-central/rev/b53e29293c9e9a2905f4849f4e3c415e2013f0cb/gfx/thebes/gfxBlur.cpp#221-226
http://searchfox.org/mozilla-central/rev/b53e29293c9e9a2905f4849f4e3c415e2013f0cb/gfx/2d/Blur.cpp#839-866
http://searchfox.org/mozilla-central/rev/b53e29293c9e9a2905f4849f4e3c415e2013f0cb/gfx/2d/Blur.cpp#293-336

And here's a post that dbaron wrote about the topic: https://dbaron.org/log/20110225-blur-radius

**Comment by kvark** [comment]
I got confused by the subject and initial discussion.

> Divide shadow blur_radius by 2

This is not about changing the blur radius. What Gecko does is dividing the radius by 2 to get the standard deviation, from which the blur kernel operates. The radius stays the same.

**Comment by glennw** [comment]
I believe this is fixed by #1920.
