### ISSUE TITLE
YAML reader confuses order of border colors

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1832]
The order should be "top right bottom left" (and that's what yaml_frame_writer.rs uses), but yaml_frame_reader reads it in the order of "top left bottom right".

https://github.com/servo/webrender/blob/59502ed15ade1441e4e86c1a64c2826baa937296/wrench/src/yaml_frame_reader.rs#L705-L720

**Comment by hgallagher1993** [comment]
Not sure if I can self assign but I'll take this anyway

**Comment by glennw** [comment]
@hgallagher1993 Thanks!

**Comment by glennw** [comment]
This happened.
