### ISSUE TITLE
text-decoration: wavy pattern flips when scrolled off screen

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1842]
If you zoom into https://gankro.github.io/blah/webtests/text.html and scroll horizontally so a wavy line is partially off screen, you'll visually see it vertically flip (peaks become troughs).

Haven't looked into it yet, just filing so I don't forget.

Other decorations appear fine (they're vertically symmetric).

**Comment by glennw** [comment]
I couldn't repro this, but I might not have been following the steps correctly. Does it still occur on your machine?

**Comment by Gankro** [comment]
Weird. I can still repro on macos, but I don't see it on windows (never tried before, since I assumed nothing platform-specific was involved). Gonna go check linux.

**Comment by Gankro** [comment]
Also not able to repro on linux... wat

**Comment by Gankro** [comment]
Appears to only happen with APZ disabled... possible wontfix?

**Comment by Gankro** [comment]
Ok, I can reproduce this even with APZ, with the following:

```
data:text/html,<div style="width: 10em;overflow: auto;height: 2em;white-space: nowrap;"><div style="text-decoration: underline wavy red;">ssdasd sda dsssdasdasd asdasdsda asd asdasdad asdasdas adasdasdsa asdsadasdas asdada asdasda asdasdasdad asdasd asdasdasdadadas asdasdad asdadasdasdad asdadadad sadasdadas asdasdads asdadas
```

Zoom in and scroll the inner scroll region horizontally. You will occasionally see the squiggle shift (meaning we just exceeded the APZ overdraw limit and repainted at a different position).

**Comment by Gankro** [comment]
Confirmed that example reproduces on windows

**Comment by mstange** [comment]
The problem here is that WebRender looks at the position of the first painted glyph in order to align the wavy pattern, but Gecko culls offscreen glyphs. So there needs to be a separate piece of information to let WebRender know how to align the wavy pattern.

**Comment by Gankro** [comment]
Ok I found the problem, it's in the gecko bindings, but the gecko bindings would be "right" if we solved a more fundamental issue (which I'll file a new bug for).

**Comment by mstange** [comment]
> The problem here is that WebRender looks at the position of the first painted glyph in order to align the wavy pattern, but Gecko culls offscreen glyphs. So there needs to be a separate piece of information to let WebRender know how to align the wavy pattern.

Just closing the loop on this one: I was totally wrong here. Gankro told me that webrender uses a bounding box which it gets from Gecko in order to position the wavy line, so the "separate piece of information" that I was calling for already exists.
