### ISSUE TITLE
linux: some glyphs are rendered offset up by ~1 pixel

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1847]
Live Examples:

https://gankro.github.io/blah/reftests/counter-style/system-symbolic.html
https://gankro.github.io/blah/reftests/counter-style/system-symbolic-ref.html

https://gankro.github.io/blah/reftests/counter-style/system-fixed.html
https://gankro.github.io/blah/reftests/counter-style/system-fixed-ref.html

(the first one actually visually changes a bit on macos for me...)

**Comment by Gankro** [comment]
Bugzilla twin: https://bugzilla.mozilla.org/show_bug.cgi?id=1407640

**Comment by Gankro** [comment]
Oh bluh, these tests are technically list bullets, which aren't actually properly fed into WR right now. So this is comparing wr to fallback gecko.

**Comment by Gankro** [comment]
This bug might be bogus, gonna come back to it, see if I can't find an example that's not just fallback vs not. Although considering linux has no AA it's a bit suspicious that fallback and not are off by a pixel?

**Comment by Gankro** [comment]
Yes, all examples are fallback-related. Closing as wontfix.

**Comment by glennw** [comment]
@Gankro FWIW, I *do* think there is some issue with Linux glyphs in WR that results in a 1px offset, *sometimes*. I haven't spent the time to look into it yet. I think that if we draw a text run with alpha AA, it is always (or sometimes) offset by 1px from the same text run drawn with subpixel AA? Not really sure, just mentioning it here in case you come across a useful test case.

**Comment by Gankro** [comment]
Won't find a good test on the linux CI, since it's all No-AA, sadly. And in the absence of CI, I'm pretty useless for finding linux bugs.

(would really like to spin up macos/windows CI to get any aa tests...)
