### ISSUE TITLE
Black screen since PR 184

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#185]
Since https://github.com/servo/webrender/pull/184, during the tab switching animation, browser.html turns black (osx).

**Comment by pcwalton** [comment]
Huh, I'm pretty sure I tested that animation. Perhaps I messed up when preparing the patch.

I suspect this will show up as a GL error in apitrace if I can reproduce. I had some issues in the patch with trying to use textures that were deleted that I had to fix. I bet it's something like that.

**Comment by paulrouget** [comment]
http://people.mozilla.org/~prouget/servo-apitrace-2016-02-17.trace

**Comment by paulrouget** [comment]
I see no error. But I'm not familiar with opengl and apitrace.

**Comment by glennw** [comment]
@paulrouget Do you want us to back that change out (it's a performance fix only) until @pcwalton is able to repro it, or is it not impacting your work much?

**Comment by paulrouget** [comment]
Not blocking us. We can wait.
