### ISSUE TITLE
The contrast() filter does not deal with premultiplied alpha correctly

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1854]
Testcase and more detailed description coming tomorrow.

**Comment by mstange** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1408116

[Testcase](https://bug1408116.bmoattachments.org/attachment.cgi?id=8917939)

Actual vs. expected rendering:
<img width="565" alt="screen shot 2017-10-12 at 2 39 36 pm" src="https://user-images.githubusercontent.com/961291/31513123-3c33632a-af5b-11e7-97bc-149cce2fc7b7.png">

I think it's worth making all color transform filters work the same: unpremultiply, apply a matrix, premultiply.  Here's the Gecko code that computes the color matrix for the different filter types: http://searchfox.org/mozilla-central/rev/31606bbabc50b08895d843b9f5f3da938ccdfbbf/gfx/src/FilterSupport.cpp#396-513

**Comment by Darkspirit** [comment]
This got fixed with the latest webrender update. (https://github.com/servo/webrender/compare/8a39cf24f493e894a66c2465dd310a2b2923e558...d490a74c438d987122c600afca6bb2247ab38637)
https://bugzilla.mozilla.org/show_bug.cgi?id=1408116#c2

**Comment by glennw** [comment]
Thanks!

**Comment by mstange** [comment]
This was fixed by #2048.
