### ISSUE TITLE
The Vulkan api (OpenGL successor) is released !! 

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/webrender#186]
https://www.khronos.org/
So you can begin to think in implementing it on webrender :)  this could give a x2 fps, and more efficiency

**Comment by frewsxcv** [comment]
Related Rust project: https://github.com/tomaka/vulkano

**Comment by marcoms** [comment]
Would Vulkan ever be considered for WebRender?

**Comment by glennw** [comment]
We would definitely consider it - I'd like to have a Vulkan port at sometime in the future. Closing this now - we can open a larger metabug when we start working on it.
