### ISSUE TITLE
Possible batching optimization

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1865]
(mostly a note to self for future)

For alpha batches, we currently check rectangle overlaps to ensure we don't reorder draw calls in a way that may affect blending.

However, each render task in a render target is guaranteed to be allocated to a non-overlapping rectangle.

We could take advantage of this to know that there is no overlap and avoid doing rectangle tests.

Additionally, we will probably *need* to do this for correctness if / when we switch to not having complete screen space rectangles for all primitives (e.g. for cached local primitives on a picture target).

**Comment by kvark** [comment]
For the record, I appreciate the optimization ideas here as issues as opposed to [wiki](https://github.com/servo/webrender/wiki/CPU-optimization-idea). Easier to look for and discuss.

**Comment by glennw** [comment]
This was completed as part of https://github.com/servo/webrender/commit/df6e685f0f0c1625acce8841b9990c0010ccaba8.
