### ISSUE TITLE
Associate epochs to resource updates (and animations?)

### ISSUE THREAD

**Issue by nical** [servo/webrender#1870]
We currently appear to only associate epochs to display list changes. In gecko we need the epoch infrastructure to track rendering of frames where other things changed (potentially without new display lists) such as updating an image (and maybe changing an animated property?).

[Bug 1407069](https://bugzilla.mozilla.org/show_bug.cgi?id=1407069) depends on this.

**Comment by nical** [comment]
One simple way to get at least what we need for bug 1407069 is to add an `UpdateEpoch(DocumentId, PipelineId, Epoch)` to ResourceUpdate. It doesn't feel super clean though.
Another way (probably nicer) could be to have a message that contains a ResourceUpdateQueue and a new epoch (kinda like SetDisplayList but without the display list).

**Comment by nical** [comment]
cc @kvarl @glennw @sotaroikeda

**Comment by jrmuizel** [comment]
Is bug 1407069 the right number?

**Comment by nical** [comment]
> Is bug 1407069 the right number?

Yep. In a nutshell, we temporarily hold strong references to texture hosts until a certain epoch is rendered to make sure we keep textures alive until after we are done using them in WebRender.

For video frames it is important to not rebuild the scene every frame so we only update the image keys when we can. This means that until there has been something that gets the epoch updated in webrender, video frames just pile up.
To generalize that we need some way to wait until a specific image update is rendered otherwise there is no way for a reftest to draw into a canvas and snapshot the result (unless it changes something else that affects layout just to get a displaylist rebuilt).
I don't know if we have similar needs for other things like scrolling to a certain position in a reftest.

**Comment by kvark** [comment]
>cc @kvarl

Issue sounds reasonable. Getting closer to explicit resource revisions, are we? ;)

**Comment by nical** [comment]
(oops sorry for butchering your handle!) This is only about extending the scene epochs rather than resources. It's mostly that (for gecko at least) updating an image is as important as updating the layout, so it should be part of the current epoch system. Otherwise it's hard to manage the lifetime of external images.

**Comment by gw3583** [comment]
@nical Is this still relevant?

**Comment by nical** [comment]
I think that we should be good now with the transaction api in place.
