### ISSUE TITLE
Transparent text does not use subpixel AA

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1881]
Not sure if this bug is already covered by a different issue, but I'll file it anyway:

At the moment, only text with an opaque text color uses subpixel anti-aliasing. Text which is slightly transparent does not.

Testcase: `data:text/html,<p style="color:rgba(0,0,0,0.9)">Text`

**Comment by glennw** [comment]
With the old subpixel blend method, this caused issues. But it should be easy to re-enable now.
