### ISSUE TITLE
box-shadow + border-radius doesn't work

### ISSUE THREAD

**Issue by glennw** [servo/webrender#189]
It currently sets a clip out rect around the visual box. Could we instead modify the box-shadow raster op shader to detect if inside the visual box and output 0?

cc @pcwalton

**Comment by jaredpetker** [comment]
I don't quite grok what you mean @glennw, I was looking for a ticket with regards to the fact that corner radii clipping doesn't seem to be supported for shadows, and only clips out a square, is this what you are referring to here as well?

**Comment by changm** [comment]
Here's a test case:

`<html>
<head>
<style>
div {
  box-shadow: 0px 0px 5px 0px #000000;
  width: 50px;
  height: 50px;
  border-radius: 20px;
}
</style>
</head>
<body>
<div></div>
</body>
</html>`

What it should look like:
<img width="93" alt="correct" src="https://cloud.githubusercontent.com/assets/1015726/23190232/8f5c8346-f84b-11e6-8c91-5f29c2bd0fb6.png">

What it actually looks like:
<img width="104" alt="incorrect" src="https://cloud.githubusercontent.com/assets/1015726/23190245/a323b106-f84b-11e6-9235-f2168e344fe6.png">
