### ISSUE TITLE
Optimize the blur shader

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1894]
The blur shader is slower than I would expect. We should do some profiling and make it faster.

Some possible areas to optimize:

* Consider using bilinear sampling to reduce the number of required texture fetches.
* Consider using texelFetch to directly fetch the requested texel (may be faster on some GPUs?).
* Consider making the loop static (either via a uniform variable, or statically compiled shaders for common / large blur radii).
* Consider a cheaper blur algorithm that gives acceptable quality results.
* Consider doing an initial down-sample to lower resolution for blurs with large areas and/or blur radii.

There's probably several other optimizations I haven't thought of too.

**Comment by glennw** [comment]
cc @mstange or @kvark since you guys might have an interest in working on this :)

**Comment by jrmuizel** [comment]
FWIW, SkGpuBlurUtils::GaussianBlur seems to contain Skia's blur implementation.
It looks pretty text book to me:
- clamps sigma to 4 and will downscale by powers of 2 to get rid of any remaining scale
- takes advantage of separability of blur and does a vertical and horizontal convolution separately
- for small sigma will do a single pass 2d convolution
- they manually unroll the sampling loop, by generating shader code as needed

**Comment by glennw** [comment]
We do the separable blur now, so that's handled.

I'm wary of generating shader code as needed, due to the shader compile times on some drivers - but it might be worth it.

Adding in some downscale render tasks before the blur occurs seems like it should be simple and effective.

**Comment by kvark** [comment]
A agree that variable kernel sizes are no-go. Thus, we need a set of fixed-size blurs (both 1D and 2D) and a way to go from a larger fixed size kernel to a smaller variable size, that will cover everything. More details to follow.

Obligatory - http://rastergrid.com/blog/2010/09/efficient-gaussian-blur-with-linear-sampling/

**Comment by metajack** [comment]
cc @metajack

**Comment by mephisto41** [comment]
I would like to work on this.

**Comment by ssylvan** [comment]
Might want to consider a kawase filter for large blur kernels see e.g. https://software.intel.com/en-us/blogs/2014/07/15/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms

It's not a true gaussian, but a pretty close approximation and much faster.

The "moving average" box filter mentioned is also pretty attractive in some ways (predictable cost so quite nice for large kernels.. but much slower for small kernel sizes).

**Comment by jrmuizel** [comment]
There's also "Dual filtering" which claims even better performance than Kawase: https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-26-50/siggraph2015_2D00_mmg_2D00_marius_2D00_notes.pdf

**Comment by ssylvan** [comment]
At the risk of going on a bit of a tangent, couldn't most simple cases be covered by a small number of precomputed blurred box corners (like, at build time)? So store alpha textures from 1x1 to 63x63 or something (probably don't need to go too big, at some point it's smooth enough for bilinear sampling). Maybe you're already doing that.

**Comment by mstange** [comment]
The Kawase and dual filtering methods are impressive but I wonder how well they do with respect to continuity as the blur radius changes. People sometimes animate the blur radius, and it would be good not to have "pops" between different discrete blur renderings during such animations.

> precomputed blurred box corners

For box shadows, the plan is to only compute only the corners we need, as we need them, and to cache them between frames. The rendering of a box shadow corner depends on the blur radius and the corner radius, and for elliptical corners you even have different x and y corner radii. So precomputing seems a bit tricky, unless you want to handle only square corners, for example. And for blur filters on generic inputs you can't really cache or precompute anything.

**Comment by ssylvan** [comment]
> unless you want to handle only square corners

Yeah I was suggesting looking at actual usage patterns to see if there's some subset of box filters that covers 99% of cases that can be precomputed (and then interpolated to cover minor variations).

**Comment by glennw** [comment]
I think we can call this solved, for now. I haven't seen blurs being the main bottleneck on anything I test for some time now.
