### ISSUE TITLE
Github Search left-border-corners have extra bright pixels

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1897]
![screen shot 2017-10-19 at 1 04 37 pm](https://user-images.githubusercontent.com/1136864/31784144-b014d17a-b4ce-11e7-82f4-cc26aa6fdf06.png)

```css
background-color: rgba(0, 0, 0, 0);
border-bottom-left-radius: 3px;
border-right-color: rgb(40, 46, 52);
border-right-style: solid;
border-right-width: 1px;
border-top-left-radius: 3px;
box-sizing: border-box;
color: rgba(255, 255, 255, 0.75);
display: table-cell;
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
font-size: 13px;
font-weight: 400;
line-height: 28px;
overflow-wrap: break-word;
padding-left: 8px;
padding-right: 8px;
text-decoration: none;
text-decoration-color: rgba(255, 255, 255, 0.75);
text-decoration-line: none;
text-decoration-style: solid;
vertical-align: middle;
white-space: nowrap;
width: 107.683px;
```

**Comment by Gankro** [comment]
Weird observation: removing the *right* border fixes this. Probably just nudging the shader in/out of some degeneracy.

**Comment by Gankro** [comment]
Ok no wait this is super messed up:

![screen shot 2017-10-19 at 1 18 29 pm](https://user-images.githubusercontent.com/1136864/31784581-3a8da560-b4d0-11e7-99ce-b6208121d721.png)

This is changing the `border-top-left-radius` to `10px`. The issue appears to be that the parent element *also* has `border-radius: 3px`, and we're messing up drawing one border over another?

We're probably not blending the AA properly (premultiplied alpha bug?)

**Comment by Gankro** [comment]
Further analysis: the bright colored pixels are using the color of the element (same as the text). Now starting to think gecko is sending something it shouldn't need to do a recording.

**Comment by mstange** [comment]
Reduced testcase:
`data:text/html,<div style="width: 200px; height: 40px; border-radius: 3px; border: 0px solid red; border-right: 1px solid black;">`
In the testcase, you can see red rounded corner artifacts on the left side of the element.

I think an adequate description of this bug would be: "Rounded corners between zero-width borders are not invisible".

The reason webrender even knows about the text color is that the default value of the CSS border property is `thin none currentColor`, where currentColor is the value of the CSS `color` property on that element. Github's CSS only overrides `border-color`, `border-style` and `border-width` for the right border side and leaves the other border sides at the default.
