### ISSUE TITLE
Wrench: Support For "Substituted" PropertyBindings

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#1898]
Binary recordings should (at least have an option to) replace PropertyBindings with actual values used for rendering the frame. Although this may mask bugs with PropertyBindings themselves, it would help debug glitches that are incidentally present in animations (as seen in the singular matrix example this week).

**Comment by glennw** [comment]
I think this is covered by https://github.com/servo/webrender/pull/1996 - please re-open if more work is needed here.
