### ISSUE TITLE
Incorrect text shadows with 0 blur on color emoji

### ISSUE THREAD

**Issue by lsalzman** [servo/webrender#1917]
In the text shadow with 0 blur case, we use the normal text shader. For color emoji, this shader samples the bitmap color data, and then multiplies by the shadow color, when it should just be simply the shadow color. We probably need to punt back to the text shadow shader somehow or modify the text shader somehow to handle this case.

**Comment by kvark** [comment]
I'm not sure I understand why the shadow application for blur=0 should be different (replace vs multiply) from the more general shadow case.
Also, this needs a corresponding Bugzilla issue.

**Comment by mstange** [comment]
It shouldn't be different. The bug is that it is different at the moment. The blur shader ignores R/G/B, the text shader respects it (which is incorrect for shadows).

**Comment by mstange** [comment]
I suggest closing this issue in favor of #1959 which has a screenshot and is easier to understand.

**Comment by glennw** [comment]
Fixed in #2223.
