### ISSUE TITLE
The scene is rebuilt everytime we scroll

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1921]
Github issue for https://bugzilla.mozilla.org/show_bug.cgi?id=1408174 since the code it's referencing is in WR proper and not the gecko side of things.

**Comment by jrmuizel** [comment]
It would be good to get this done for Austin. Do we have a good idea how to do so?

**Comment by nical** [comment]
Currently the animated property bindings are read while flattening the items during the scene building process. Glenn mentioned something in #1774 about reorganizing things to make it so we sample the animated properties while building the frame instead:

> Create a tree of Picture and PrimitiveRun structs during the frame flattening. During the render task creation, this tree is what gets walked, instead of the stacking context tree.

**Comment by glennw** [comment]
Yup, I'm working on the patch @nical mentioned above - I have all the (wrench) reftests passing except the plane splitting tests. I'm hoping to finish that up today - this task will be very easy to do once that patch lands.

**Comment by glennw** [comment]
Didn't quite get the picture tree patch finished today, but it's coming together very well. All the Servo/Gecko tests apart from plane splitting are working now. With a bit of luck, that patch should be ready early next week.
