### ISSUE TITLE
Need a clear-rect display item type

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1926]
This will be used by Firefox on macOS to make areas with vibrancy transparent. See #1416 for background.

I'm not sure how items of this type should behave with respect to transforms and clips. It would be easiest to just say that transforms and clips on are going to be ignored on these items, but that seems hacky and unexpected from an API user's perspective. And it's totally possible to make it respect transforms and clips.

Proposed implementation:
 - If there is no clip or transform, draw a rectangle with color (0, 0, 0, 0) and blending disabled.
 - If there is a clip or a transform, draw a rectangle subject to those things with color (0, 0, 0, 1) and blending set as:
```rust
  self.gl.blend_func(gl::ZERO, gl::ONE_MINUS_SRC_ALPHA);
  self.gl.blend_equation(gl::FUNC_ADD);
```
(i.e. operator dest-out)

**Comment by kvark** [comment]
Is there an associated FF issue?

> If there is a clip or a transform, draw a rectangle subject to those things with color (0, 0, 0, 1) and blending set as:

If `color.a == 0.0` and your dst factor is `gl::ONE_MINUS_SRC_ALPHA`, wouldn't that effectively be `gl::ZERO`?
