### ISSUE TITLE
Consider adding an API to specify root corner radii

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1927]
At the moment, on macOS, due to the way Firefox gets its OpenGL content to the screen, the window's bottom corners are square instead of rounded. It would be nice to have webrender apply rounded corners to its rendering on request.

The effects of this API would be slightly different compared to a rounded clip in the display list that is applied to the entire display list contents: The corner radius would also apply to WebRender's backdrop color, and the clipping can be implemented more efficiently. Instead of drawing all primitives with a certain clip, they can be drawn completely unclipped and then the corners can be erased at the very end.

**Comment by staktrace** [comment]
Bugzilla counterpart: https://bugzilla.mozilla.org/show_bug.cgi?id=1375298

**Comment by mstange** [comment]
We probably won't need this, assuming our plans to use CoreAnimation for the window pan out.

**Comment by mstange** [comment]
Update, over a year later: Yes indeed, we won't need this.
