### ISSUE TITLE
moires runs very slow

### ISSUE THREAD

**Issue by nightpool** [servo/webrender#193]
really amazing demo! I tried cloning servo and compiling it myself, but I'm pretty consistently getting 5 fps on the moire demo (on a pretty recent macbook pro).

 - I compiled with `./mach build --release`
 - I cloned moire.html from https://github.com/pcwalton/webrender-demos
 - I ran servo with `target/release/servo -Z wr-stats -w --resolution=1024x768 --pref dom.mozbrowser.enabled ../webrender-demos/moire.htm` (I copied it straight from the demo stream)

this is what I'm seeing: (note the 4 fps)
![](http://i.imgur.com/7TugZTP.jpg)

Interestingly, this seems to be limited to moires. Both spheres and transparent_rects run at ~60fps.

Any thoughts?

**Comment by glennw** [comment]
I think the moire demo relies on some fixes to the tesselator code landing (which pcwalton has locally). Without this fix the moire demo suffers from a huge amount of needless overdraw. Is that right @pcwalton ?

**Comment by dw** [comment]
I observed this too -- disabling WebRender causes the moire demo to run much more smoothly on a 2011 era Macbook (HD graphics 3000).

**Comment by glennw** [comment]
I checked with @pcwalton and this is due to the tesselator being disabled on master at the moment due to a bug - he is working on a fix for this which we should be able to merge soon :)
