### ISSUE TITLE
Scrolling questions

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#1938]
Hi, 
I'm working on a UI framework in WebRender and I'm running into an issue with scrolling.

I'm rebuilding the display list when the UI tree changes, (in this case I'm adding items to a list of items stacked vertically inside of a scrollable region). The new display list ends up having a bigger extent content rect for the same ClipId as a previous Display List as a result.

I currently:
- Build the Display List off thread with an incremented epoch, send it to WebRender when its ready
- Wakeup my event loop on my main thread when a `new_frame_ready` event comes in
- Composite the scene by calling `renderer.update()` and `renderer.render()` then flipping the window buffer.

Scrolling doesn't work unless I disable preserving frame state in `set_display_list`. If I start off with my content rect at a size larger than the viewport then it scrolls just fine, but if I try to send an update DisplayList the changes don't seem to carry over.

Debugging using the WR code I tracked it down to `apply_old_scrolling_state` in ClipScrollNode which replaces the Scroll Frame's ScrollingState with the one that was drained from the  previous frame's ClipScrollTree. 

If I make the following changes:
```
    pub fn apply_old_scrolling_state(&mut self, new_scrolling: &ScrollingState) {
        match self.node_type {
            NodeType::ScrollFrame(ref mut scrolling) => {
                let scroll_sensitivity = scrolling.scroll_sensitivity;
                scrolling.offset = new_scrolling.offset;
                //*scrolling = *new_scrolling;
                scrolling.scroll_sensitivity = scroll_sensitivity;
            }
```

Only applying the old offset fixes my issue though I'm unsure of what other ramifications it may have.

**Comment by mrobinson** [comment]
@nc4rrillo Thanks for reporting this issue. Can you tell me if the following change fixes things?

```diff
diff --git a/webrender/src/clip_scroll_node.rs b/webrender/src/clip_scroll_node.rs
index 55a356ee..a89a36c7 100644
--- a/webrender/src/clip_scroll_node.rs
+++ b/webrender/src/clip_scroll_node.rs
@@ -230,14 +230,16 @@ impl ClipScrollNode {
         self.children.push(child);
     }
 
-    pub fn apply_old_scrolling_state(&mut self, new_scrolling: &ScrollingState) {
+    pub fn apply_old_scrolling_state(&mut self, old_scrolling_state: &ScrollingState) {
         match self.node_type {
             NodeType::ScrollFrame(ref mut scrolling) => {
                 let scroll_sensitivity = scrolling.scroll_sensitivity;
-                *scrolling = *new_scrolling;
+                let scrollable_size = scrolling.scrollable_size;
+                *scrolling = *old_scrolling_state;
                 scrolling.scroll_sensitivity = scroll_sensitivity;
+                scrolling.scrollable_size = scrollable_size;
             }
-            _ if new_scrolling.offset != LayerVector2D::zero() => {
+            _ if old_scrolling_state.offset != LayerVector2D::zero() => {
                 warn!("Tried to scroll a non-scroll node.")
             }
             _ => {}
```

**Comment by nc4rrillo** [comment]
@mrobinson This fixes my issue :+1: 

Another change I have made locally that I'm wondering if it can get upstreamed is to enable drawing scrollbars for all scroll frames if the pref is set. Currently it only does it for the root frame. 

The change I made is here:
```
            for (clip_id, clip_node) in &self.clip_scroll_tree.nodes {
                if let NodeType::ScrollFrame(_) = clip_node.node_type {
                    let scrollbar_rect = LayerRect::new(LayerPoint::zero(), LayerSize::new(10.0, 70.0));
                    let info = LayerPrimitiveInfo::new(scrollbar_rect);

                    
                    context.builder.add_solid_rectangle(
                        ClipAndScrollInfo::simple(*clip_id),
                        &info,
                        &DEFAULT_SCROLLBAR_COLOR,
                        PrimitiveFlags::Scrollbar(*clip_id, 18.0),
                    );
                }
            }
```
in `flatten_root` in frame.rs

**Comment by mrobinson** [comment]
@nc4rrillo Thanks! I would like to make the scrollbar property a per-ScrollFrame setting.
