### ISSUE TITLE
Failed to compile shader: "brush_mask"

### ISSUE THREAD

**Issue by NiLSPACE** [servo/webrender#1939]
Ref: servo/servo#18974

As of a few days ago Servo started throwing the following errors in console:
```
Failed to compile shader: "brush_mask"
ERROR: 0:1183: 'constructor' :  cannot convert parameter 1 from 'float' to 'structure'
ERROR: 0:1182: '=' :  cannot convert from '2-component vector of highp float' to 'highp structure'
```
This only happens on my integrated Intel GPU.

Specs:
GPU: Intel HD Graphics 530
Driver version: 22.20.16.4735

**Comment by kvark** [comment]
Looking at the source at 37d531900bcb8e7c09c01759af12493abed8c0e3 using `apitrace`, the problem is within this function:
```glsl
PictureTask fetch_picture_task(int index) {
    ivec2 uv = get_fetch_uv(index, VECS_PER_RENDER_TASK);

    vec4 target_rect = TEXEL_FETCH(sRenderTasks, uv, 0, ivec2(0, 0));

    PictureTask task = PictureTask(RectWithSize(target_rect.xy, target_rect.zw));

    return task;
}
```

I'd bet on the driver being confused by the `PictureTask` construction here.

**Comment by nical** [comment]
I added [an entry](https://github.com/servo/webrender/wiki/Driver-issues#1939---) to the driver issues page with lots of blanks to fill in when this has been figured out.

**Comment by kvark** [comment]
@nical thanks! I was going to fill it up after we get more info/confirmation on what's going on.
