### ISSUE TITLE
WebRender's blur is much uglier

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1946]
Compare: FF w/ WebRender (things are much boxier)
<img width="172" alt="ff" src="https://user-images.githubusercontent.com/332653/32026856-f74ff8aa-b9b3-11e7-825a-5503b361d424.png">

vs Chrome:
<img width="171" alt="chrome" src="https://user-images.githubusercontent.com/332653/32026874-017b5c84-b9b4-11e7-9dce-e88e8db6487e.png">

Gecko without WebRender looks like Chrome

**Comment by glennw** [comment]
@jrmuizel Is it better with https://github.com/servo/webrender/pull/1920 applied (this is in the merge queue)?

**Comment by glennw** [comment]
#1920 has landed now - so it'd be worth checking if the results are any better with that.

**Comment by kvark** [comment]
The original screenshot looks as if our horizontal blur is not working correctly.

**Comment by glennw** [comment]
@jrmuizel Are you able to test this again (if the #1920 change has made its way into Gecko), or provide STR and I'll check it?

**Comment by jrmuizel** [comment]
Yeah this looks good now.
