### ISSUE TITLE
Shader validation misses some windows specific issues

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1950]
For one example, see https://github.com/servo/webrender/pull/1945#issuecomment-339787218.

We should take a look at how we are calling the shader validator - perhaps there is a different GLSL version or target we can set?

**Comment by kvark** [comment]
Is there an indication that the validation is supposed to handle this sort of issues?

**Comment by glennw** [comment]
I haven't looked into at all, as to whether it should handle this issue. This bug is basically a placeholder to do some investigation and see if there is a way to detect some issues that we are currently missing.

**Comment by gw3583** [comment]
Closing for now, since we haven't seen any validation issues for a long time. We can re-open if there are specifics to handle here.
