### ISSUE TITLE
Crash: "address register can't be src operand in direct addressing"

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#1968]
On Android:

```
[Rasterizing GlyphKey { index: 75, subpixel_offset: Half } as Subpixel with dimensions GlyphDimensions { left: 0, top: 32, width: 16, height: 32, advance: 13 }] [webrender::platform::unix::font]
ENCODE FATAL ERROR (vendor/qcom/proprietary/gles/adreno200/llvm/lib/Target/Oxili/QGPUMachineEncoder.cpp:843: address register can't be src operand in direct addressing
referenceTable GDEF length=814 1
referenceTable GSUB length=11364 1
referenceTable GPOS length=47302 1
referenceTable head length=54 1
```

any idea what might go wrong?

**Comment by glennw** [comment]
This is a driver bug when compiling a shader, unfortunately, by the looks. The only way to diagnose this would be to identify which shader it is (with some logging), and then find out what piece of code in the shader is triggering this error by trial and error.

It's also possible (but unlikely) there might be an android OS or driver update available. What OS version and device is this on?

**Comment by mfkl** [comment]
> What OS version and device is this on?
Android 7.1.2, Wileyfox Swift.

**Comment by paulrouget** [comment]
We updated the phone, but still.

Giving up. We used a different phone.
