### ISSUE TITLE
Very high draw call count on simple sites in Gecko.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1984]
For example, in HN the Gecko + WR is submitting around 275 draw calls per frame. In Servo, this is typically less than 10.

Investigating now since this is likely to be a simple bug and a significant performance win once fixed.

**Comment by NiLSPACE** [comment]
For me the amount of draw calls is roughly the same, Gecko is just a little bit higher.

https://news.ycombinator.com has roughly 300 draw calls in Gecko while Servo has about 230. Perhaps it depends on the OS?

![image](https://user-images.githubusercontent.com/1160867/32430077-d8d3c32a-c2cd-11e7-8983-6bf563733b2d.png)

**Comment by glennw** [comment]
Yes, it turns out this is a recent regression rather than a Servo / Gecko difference. I'm working on a couple of fixes this week.
