### ISSUE TITLE
Yes, but what does your startup *do*? is slow

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1985]
I see it being really slow in Servo and Gecko:

https://jrmuizel.github.io/webrender/slow/Yes%2C%20but%20what%20does%20your%20startup%20*do*%3F%20%E2%80%93%20Terence%20Eden's%20Blog.html

I suspect this is just the large shadow radius at the top

**Comment by glennw** [comment]
Hopefully https://github.com/servo/webrender/pull/1961 and/or https://github.com/servo/webrender/issues/1984 will fix this, but I'll profile after they are sorted to confirm.

**Comment by pcwalton** [comment]
Just checked in Servo. This is fast now. Yay!

**Comment by glennw** [comment]
Confirmed in Gecko that it's holding 60fps quite easily. The main suspect remaining is that around half the time is spend generating clip masks. We're working on various improvements here.
