### ISSUE TITLE
Long GPU times on https://getpocket.cdn.mozilla.net/explore/trending even after #1961

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1993]
[This page](https://getpocket.cdn.mozilla.net/explore/trending) scrolls very slowly even on a Firefox build that includes the patch for #1961. It has some large blur radius box-shadows.

**Comment by jrmuizel** [comment]
This seems fixed.

**Comment by mstange** [comment]
It's a lot better than before, but with my integrated GPU it's still only scrolling at 38 FPS, and it's all bound on the GPU.

**Comment by glennw** [comment]
I'll keep it open then - sounds like it still has issues on some hardware at least.

**Comment by glennw** [comment]
This seems fixed for me too, with current Gecko. I get around ~120 fps with vsync disabled on my HD4600 GPU. Around half the time is spend clearing and generating clip masks, which mostly seem redundant, so there should be some big improvements to come here.

@mstange Do you think we can close this?

**Comment by mstange** [comment]
It's at ~43fps now. Let's wait for the clip mask improvements before we close it, and maybe also for box-shadow caching.

**Comment by mrobinson** [comment]
I did some digging into this. The issue seems to be that we are rendering some large ClipOut masks for a box shadow with a rounded rectangle. Removing that seems to make the GPU queries look a lot more equal. @glennw and I talked and we think that the best fix here would be to segment the box shadow to allow more of it to be rendered without a mask.

**Comment by kvark** [comment]
@mrobinson that also happens to be the case for #2100

**Comment by glennw** [comment]
I'm working on this now - https://github.com/servo/webrender/pull/2271 is some prep work. Following that, I'll expand the brush segmentation support to work with box-shadow pictures, which should significantly reduce the size of the clip out masks (and in the future, they can be shared as well).
