### ISSUE TITLE
marmalead is slow

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1995]
I see ~9 ms of gpu time that looks unrelated to shadows: https://jrmuizel.github.io/webrender/marmalead.zip

**Comment by Darkspirit** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1414910

**Comment by glennw** [comment]
This looks to be mostly similar to the issues drawing the chrome UI - that is, lots of blend composites being applied where they don't need to. I'll re-profile this one once that is sorted.

**Comment by glennw** [comment]
Most of the time here is spent in opacity blends (I suspect most of these can be collapsed into not using a surface, but I need to confirm) and also angle gradients, which are quite sub-optimal right now.

**Comment by glennw** [comment]
This is running well now, I'm seeing ~5ms GPU time. It can still be improved a lot, but it easily runs at 60 fps now.
