### ISSUE TITLE
Fast border paths are often not hit when they could be.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#2000]
WR doesn't detect fast border cases very well (such as a solid style on one edge, with none on the other edges). This has a small effect on draw call count and GPU times when drawing the Gecko chrome.

Instead of fixing this now, it probably makes sense to wait until borders are switched over to brush shaders and handle it at the same time.

**Comment by gw3583** [comment]
This is no longer an issue - border primitives are now persisted in the texture cache.
