### ISSUE TITLE
Share box shadow intermediate tasks where possible.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#2001]
We should add a cache key for box shadow render tasks, and the associated blurs / downsample tasks. This would save GPU time on pages that use a large number of box shadows with the same parameters.

The cache key for the box shadow task should include the parameters that define the shadow task (e.g. blur radius, border radii, box shadow clip mode).

The cache key for the blur and down-sample tasks could be something like (shadow key, stage index) where stage index is a number from 0..X, incrementing for each stage of the blur / downsample process.

**Comment by demo99** [comment]
I'll work on this.

**Comment by glennw** [comment]
@demo99 Great, thanks! If you set up a benchmark with several identical box shadows as a wrench yaml file, and then hit ```O``` that will show the render target debugger. It should be fairly clear to see from that if the intermediate surfaces are being shared.

**Comment by glennw** [comment]
This happened.
