### ISSUE TITLE
Support running wrench with ANGLE on Windows.

### ISSUE THREAD

**Issue by nical** [servo/webrender#2006]
It should prove handy whenever we'll get to debugging ANGLE/D3D specific bugs, and D3D11 tends to have much better tooling available than GL, for example pixel history and debugging in renderdoc.

**Comment by kvark** [comment]
Pretty sure this is already done. Wrench uses `glutin` for initialization, and that one checks for libEGL as of https://github.com/servo/glutin/pull/112 . All you need is to drop Angle's `libEGL.dll` in the folder with wrench executable.

**Comment by glennw** [comment]
This is a duplicate of #1432.
