### ISSUE TITLE
Heavily-downscaled images look bad

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2023]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405469

This can be seen with the header image at [https://www.reddit.com/r/firefox/](https://www.reddit.com/r/firefox/): The header [image file](https://b.thumbs.redditmedia.com/yRlXvjV2ZFDLGkklcn78T8KgfHS65c4X0bNID4p68UU.png) is 3,242px × 833px big and gets displayed at 175px x 45px, which is a downscale factor of 18.5 (or 9.25 on a HiDPI@2x display).

The downscaled image looks very pixellated with WebRender.

Maybe WebRender should be generating different mip map levels as required, using subsequent 0.5 scaling so that the pixellation doesn't occur?

**Comment by jrmuizel** [comment]
Shouldn't Gecko's high quality downscaling be taking care of this?

**Comment by kvark** [comment]
@jrmuizel 
Shouldn't Gecko's high quality downscaling be taking care of this?

Down-scaling can be expensive and maps to GPU somewhat nicely. Woudln't we want to do this in WR at the end of the day then anyway for performance reasons?

**Comment by atouchet** [comment]
Possibly related Servo bugs:

https://github.com/servo/servo/issues/11960
https://github.com/servo/servo/issues/17465

**Comment by kasper93** [comment]
> Down-scaling can be expensive and maps to GPU somewhat nicely. Woudln't we want to do this in WR at the end of the day then anyway for performance reasons?

Well, of course scaling is perfect task for WR. It just need to use proper interpolation, because like I stated in Bugzilla bug it currently is using Nearest Neighbour by the looks of that.

**Comment by glennw** [comment]
I added a ref test in https://github.com/servo/webrender/pull/2320 that can be used when working on this bug.

I think what we'll probably want to end up with is a render task that manually creates mip-mips for a given entry of the texture cache.

This seems like a reasonable guide with example code to creating mips manually for non-p2 textures - http://download.nvidia.com/developer/Papers/2005/NP2_Mipmapping/NP2_Mipmap_Creation.pdf.

**Comment by glennw** [comment]
@kvark Does the above make sense to you, or do you have other ideas?

**Comment by kvark** [comment]
@glennw makes sense. Your permanent render task cache comes handy :)

**Comment by glennw** [comment]
@kvark @nical One thing I'm unsure of is whether we choose to create mips for *all* items in the texture cache, or have some heuristic and try to create mips only where it makes sense. This could also complicate the shader and/or batching logic, depending on if we need to select a mode that use mips or not. Thoughts?

**Comment by kvark** [comment]
@glennw I believe we don't need this for most of the images, so should be doing on demand only.

**Comment by jrmuizel** [comment]
This was fixed on the Gecko side in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1183378. That fix is better than the mipmap generation.

**Comment by jrmuizel** [comment]
because it doesn't have problems like #2519. It's probably best to just disable MipMap generation for now.
