### ISSUE TITLE
Deserializer masks out signaling nans

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2027]
When @Gankro and I were looking at the deserialization code we noticed that it's masking out signaling NaNs. We don't need this protection. We don't know how to convince the byteorder crate of this.

**Comment by jrmuizel** [comment]
Here are the issues that caused this behaviour: https://github.com/BurntSushi/byteorder/issues/71 and https://github.com/rust-lang/rust/pull/39271

**Comment by Gankro** [comment]
I am working on submitting a patch to fix the *very* incorrect piece of llvm documentation that originally motivated this.

**Comment by jrmuizel** [comment]
Great. It might also be valuable for us to make sure there are tests in llvm that ensure that behaviour around signalling NaNs is sane.

**Comment by jrmuizel** [comment]
Here's the beginnings of some tests that show that signaling NaNs don't turn immediately into undef
```llvm
; RUN: opt < %s -O2 -S | FileCheck %s
target datalayout = "e-m:o-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.13.0"

; Function Attrs: norecurse nounwind readnone ssp uwtable
define float @f(float, float) {
  %3 = fdiv float %0, %1
  ret float %3
}

define float @f2(float, float) {
  %3 = fdiv float 0x7FF8000000000000, %1
  ret float %3
}

define float @f3(float, float) {
  %3 = fdiv float 0x7FF4000000000000, %1
  ret float %3
}

define float @f4(float, float) {
  %3 = fdiv float 5.000000e+00, %1
  ret float %3
}

define float @f6(float, float) {
  %3 = fdiv float %0, 0x7FF4000000000000 
  ret float %3
}

define float @f7(float, float) {
  %3 = fdiv float 5.0000e+000, 0x7FF4000000000000 
  ret float %3
}

define float @f8(float, float) {
  %3 = fdiv float 0x7FF8000000000000, 0x7FF4000000000000 
  ret float %3
}

define float @f9(float, float) {
  %3 = fdiv float 0x7FF4000000000000, 0x7FF8000000000000 
  ret float %3
}
```

**Comment by Gankro** [comment]
https://github.com/rust-lang/rust/pull/46012

**Comment by glennw** [comment]
@Gankro Is this bug still relevant to be open in the WR repo?

**Comment by jrmuizel** [comment]
Nope. We can close this.
