### ISSUE TITLE
Weird text bug

### ISSUE THREAD

**Issue by qwertychouskie** [servo/webrender#2029]
https://jacobspctuneup.tk/STK/newgui/mainmenu.html

How it looks
![](http://i.imgur.com/OLCcTPj.png)

How it should look
![](http://i.imgur.com/Qab3mRL.png)

FF Nightly 2107/11/11

```
gfx.webrender.enabled:true
gfx.webrender.blob-images:true
```

**Comment by kvark** [comment]
cc @lsalzman

**Comment by mstange** [comment]
This looks like a more extreme version of #1808.

**Comment by lsalzman** [comment]
It is very likely that between #2058 and #2095 this will be fixed. We should check this again once those two land in Firefox nightlies.

**Comment by qwertychouskie** [comment]
This seems fixed in the latest FF Nightly, thanks!
