### ISSUE TITLE
position:fixed elements painted outside of iframe

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#203]
a.html:
```html
<style>
  body {
    margin: 0;
  }
  iframe {
    position: absolute;
    top: 20px;
    left: 20px;
    width: 200px;
    height: 200px;
  }
</style>
<iframe src="b.html"></iframe> 
```

b.html:
```html
<style>
  div {
    position: fixed;
    width: 100px;
    height: 100px;
    background: red;
    left: 0px;
    top: 0px;
  }
</style>
<body>
  <div></div>
  <h1>content</h1>
</body>
```

<img width="593" alt="screen shot 2016-02-26 at 17 48 40" src="https://cloud.githubusercontent.com/assets/373579/13358789/51fa3e00-dcb1-11e5-810b-056c3610f1f4.png">

**Comment by glennw** [comment]
Branches with fixed layer per iframe here:

https://github.com/glennw/webrender/tree/fixed-layers
https://github.com/glennw/webrender_traits/tree/fixed-layers

Needs a bit more testing before I open PRs, but feel free to test in your use case with them in the meantime if you like.

**Comment by glennw** [comment]
This got fixed in https://github.com/servo/webrender/commit/4dea3fe85db703d24a2d6ed7883d3424256db5af
