### ISSUE TITLE
Shader compilation failure in ps_hardware_composite on linux+nvidia

### ISSUE THREAD

**Issue by nical** [servo/webrender#2036]
```
Failed to compile shader: "ps_hardware_composite"
0(6) : error C1013: function "main" is already defined at 0(1022)
```

I think that I had the issue when trying to load the ars technica front page.

**Comment by kvark** [comment]
Not seeing anything wrong with this shader. Perhaps you can play with it in order to reduce the case.

**Comment by nical** [comment]
Turns out I had some non-versioned ps_hardware_composite.vs/fs.glsl files in the res folder, probably remnants from a time where I tried a particular webrender revision with gecko that had these files while ps_hardware_composite had already moved to be single file in gecko.
Anyway, these extra files automatically got picked up by the shader includes thingy and the concatenated source ended up with two main functions per shader.
Removing these files from the res folder fixed the issue.
