### ISSUE TITLE
WR hit-testing produces incorrect results sometimes

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2037]
I have a local patchset that stands up gecko to use the WR hit-testing API. While getting it stood up I was running into an issue where the hit-test result was sometimes incorrect. I don't fully understand the coordinate spaces involved here, but I traced down the problem to the line at https://github.com/servo/webrender/blob/b8bda858646e30f9c4ed12c6a6b4233c9ff75ce8/webrender/src/clip_scroll_tree.rs#L196 - if I just use `point_in_clips = transformed_point` there without the subtraction it fixes the problem I was seeing.

It might be a bug on the gecko side but I figured I'd file this in case it's an obvious problem in the code here. I can try to make a standalone case to reproduce this if it's not obvious.

/cc @mrobinson

**Comment by kvark** [comment]
Your proposal fix sounds good to me. The code using it is `if !clip.contains(&point_in_clips)`, and `clip` is given in the local coordinates of the current clip node, if I'm not mistaken, so we shouldn't be subtracting `local_clip_rect`.

**Comment by glennw** [comment]
I suspect this *was* correct and that I probably accidentally broke it in https://github.com/servo/webrender/pull/1981/files - I changed the coordinate spaces of some of those rects when I removed the PackedLayer and ClipScrollGroup code. Does that sound right @mrobinson ?

**Comment by mrobinson** [comment]
@glennw That sounds right to me. Thanks for looking into this!
