### ISSUE TITLE
Implement drop-shadow filter

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2044]
This is needed for Facebook and MotionMark

**Comment by jrmuizel** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415034

**Comment by mephisto41** [comment]
I'll work on this.

**Comment by mephisto41** [comment]
https://github.com/mephisto41/webrender/tree/drop-shadow

wip, still need some works.

**Comment by mephisto41** [comment]
#2091 fix this.

**Comment by glennw** [comment]
Fixed by #2091.
