### ISSUE TITLE
Using/running webrender outside servo

### ISSUE THREAD

**Issue by matiasinsaurralde** [servo/webrender#205]
Hi, is it possible to use webrender outside servo?

**Comment by glennw** [comment]
I haven't tried for a while, but it should be possible. It doesn't depend on any of the servo crates (by design), although the interface is fairly heavily tied to how Servo generates display lists. Naturally, there's no guarantees on API stability etc :)

**Comment by kevinmehall** [comment]
I've been experimenting with this and got something working:
https://github.com/kevinmehall/webrender-experiments

I think I'm setting the clipping parameters wrong, and probably integrating with the glutin event loop suboptimally (it seems to lag about a frame behind the mouse). If you have any tips there or other suggestions, let me know.

Would you be interested in a PR adding something like this to the repo as a [cargo example](http://doc.crates.io/manifest.html#examples)?

**Comment by glennw** [comment]
@kevinmehall Yes, I'd merge a PR for that - nice work!

**Comment by matiasinsaurralde** [comment]
@kevinmehall It looks so great, I'll give it a try!

**Comment by glennw** [comment]
This repo exists as a sample of using WR outside of Servo - https://github.com/glennw/wr-sample.
