### ISSUE TITLE
Very large box shadows cause rendering bugs

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2061]
Testcase: `data:text/html,<div style="height:20px;box-shadow:0 0 2000px 2000px rgba(0,0,0,0.4)">`

Loading this page in a WebRender Firefox renders a blank tab and makes text in the tab bar disappear. I think unreasonably large box-shadow blurs should be clamped, or the shadow should be rendered without a blur. In this case, the blur achieves nothing, but I ran into a website that did this anyway.

**Comment by glennw** [comment]
Wow! Yes, clamping or ignoring the blur sounds reasonable. Do you have a suggested threshold value for blur radius we could use?

**Comment by mstange** [comment]
Gecko seems to allow a maximum stddev of 300: https://searchfox.org/mozilla-central/rev/c633ffa4c4611f202ca11270dcddb7b29edddff8/layout/painting/nsCSSRendering.cpp#4412-4428

**Comment by mstange** [comment]
Oh, I think that's the maximum radius (not stddev), and the variable `blurStdDev` is misnamed.

**Comment by glennw** [comment]
Added help wanted and easy tags - this is an easy task for a new contributor. We would need to clamp the blur radius, and add some wrench reftests for this case.

**Comment by glennw** [comment]
We might as well also apply the max spread radius that Gecko uses in the above code.

**Comment by mstange** [comment]
I think the max spread radius is only used when spreading has to be applied per-pixel. For most box-shadows, where the spread radius only affects the dimensions of the shape that's used for the shadow, the spread radius is not clamped.

Gecko uses per-pixel spreading only if a box-shadow is applied on an elements with -moz-appearance (where the shape is unknown and up to the platform). With WebRender, such elements currently fall back to Gecko rendering.

**Comment by glennw** [comment]
OK, that makes sense. Thanks!

**Comment by nc4rrillo** [comment]
Would this be more involved than `blur_radius = f32::min(blur_radius, MAX_BLUR_RADIUS)` inside of `add_box_shadow`?

**Comment by glennw** [comment]
I *think* that's probably all that's needed, yep!
