### ISSUE TITLE
Implement ClipSource::contains for missing ClipSource types

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2065]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1418830

It looks like some cases (perhaps only with gfx.webrender.hit-test set to true) we are entering ClipSource::contains with a ClipSource type that is not handled, so that function is panicking. We should handle whatever the missing case is.

**Comment by mrobinson** [comment]
I have a feeling this might be happening for image masks. I'll try to get a fix out for this.
