### ISSUE TITLE
Inset box shadow rendering bug

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#2068]
While browsing [this docs.microsoft.com page](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/) I noticed strange lines in the tree view on the left.

If you look at [this page](https://jsfiddle.net/3xjgekou/) you'll notice extra lines being drawn for inset box shadows compared to FF Nightly with WR off. 

Setting any of the values to non-zero causes the issue to go away.

**Comment by nc4rrillo** [comment]
Tested this on Linux with an Intel GPU and on Windows 10 with an nVidia GPU. Seems to be affected by the page zoom in FF.

**Comment by nc4rrillo** [comment]
I've tried to recreate this in a sample app but I can't trigger the weird behavior, wondering if its Gecko specific or if I have the conditions that trigger it wrong.

**Comment by nc4rrillo** [comment]
bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1419528

**Comment by Darkspirit** [comment]
This is a regression from Nightly's perspective: https://bugzilla.mozilla.org/show_bug.cgi?id=1419528#c2
(https://github.com/servo/webrender/compare/a624aa6d3b6006c510c8b14026567af4ac545d2f...7892f5364bc4d35c7a9b42949f0ace4cc54f8b3c)

**Comment by glennw** [comment]
These glitches often depend on the contents of the surface cache and the allocation patterns, so it might be quite difficult to hand-craft a test case. What I normally do in these cases is do a binary wrench recording (```export ENABLE_WR_RECORDING=1```) from Gecko - and then replay this file in wrench. If we can reproduce it that way, it's normally quite easy to reduce the test case and fix from there.

**Comment by glennw** [comment]
I think this is fixed by https://github.com/servo/webrender/pull/2307 - are you able to confirm?

**Comment by nc4rrillo** [comment]
Yes can confirm that fixed it.
