### ISSUE TITLE
Poor performance on low end surface tablet 

### ISSUE THREAD

**Issue by nical** [servo/webrender#2071]
Bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1419353

I tried WebRender on a windows 10 surface tablet equipped with an intel atom x7-z8700 CPU @ 1.6Ghz 2Go RAM GPU id 0x22b0 version 20.19.15.4424.

At best we get 30 fps on all of the pages that I tried including simple ones, with a lot of time (30ms+) attributed to the compositor according to webrender's built-in profiling ui (render backend stays around a reasonable ~3ms). I suppose that a lot of this time is actually spent waiting for the GPU but the gpu profile markers aren't enabled in gecko yet, I'll look again when they are hooked up.

Without WebRender, Firefox runs very smoothly on this device.

**Comment by nical** [comment]
Also, compiling shaders on this device seems to take forever.

**Comment by jrmuizel** [comment]
For the record that has a gen8 cherryview GPU which is relatively modern.
You should be able to get a useable profile with the gecko profiler on
Windows which I assume is what the machine is running?

**Comment by nical** [comment]
I am unfortunately unable to use the profiler when webrender is enabled on windows (on this computer and another one as well).

**Comment by glennw** [comment]
If we're seeing a lot of time in the compositor, and it's a reasonably modern GPU, my guess would be that we're either hitting a driver slow path, or perhaps one of the shaders is being horribly compiled (e.g. unrolling a loop badly). Could you try running with vsync disabled, and report the profiler numbers in that case?

**Comment by glennw** [comment]
Also, what resolution does that tablet run on, and do you have the GPU (or I guess that's implied by the CPU above, and I can just look it up).

Finally, are we definitely running WR under ANGLE in these builds, or could it be running native GL? (Gecko should output the GL renderer string on startup to the console, if you can access that on Windows).

**Comment by sotaroikeda** [comment]
If ANGLE is used on Windows, there could  be a problem of how to use SwapChain in ANGLE. [Bug 1418571](https://bugzilla.mozilla.org/show_bug.cgi?id=1418571) and [Bug 1419293](https://bugzilla.mozilla.org/show_bug.cgi?id=1419293) might be related.

**Comment by sotaroikeda** [comment]
And with D3D SwapChain,  PartialPresents  with small invalidation regions is effective like [CompositorD3D11::Present()](https://dxr.mozilla.org/mozilla-central/source/gfx/layers/d3d11/CompositorD3D11.cpp#1196)

**Comment by dralley** [comment]
The bugzilla is marked "resolved fixed", can this be closed?

**Comment by kvark** [comment]
Thanks for triaging!
