### ISSUE TITLE
Force transformed shader when property is involved

### ISSUE THREAD

**Issue by kvark** [servo/webrender#2083]
MotionMark's first test shows an interesting effect: batches of transformed rectangles are broken by (sometimes individual) instances which just happen to be aligned. We are trying to be too smart here.

I believe we should force the use of transformed shaders for objects having transformation in animated property (themselves, or in one of the parent reference frames). That would work within an assumption that Gecko/Servo actually recognizes those animations and passes them in properties to WR.

<img width="1152" alt="01-transformed" src="https://user-images.githubusercontent.com/107301/33146673-2a3eaf5a-cf93-11e7-9e35-ae9238dfe562.png">

**Comment by glennw** [comment]
Nice find! Of note - primitives that are switched over to brush shaders no longer have the distinction between transform for shader selection. Both transform and non-transform variants go through the same shader (this is what I've been working towards with the recent write_transform_vertex changes). If this is a major bottleneck for this test case, I could bump up the priority of that work?

**Comment by glennw** [comment]
@kvark The work above is complete for rectangles (they are drawn as brush shaders, so there is no shader change for transformed vs. identity rects). Can this be closed, given that has landed?

**Comment by kvark** [comment]
Thanks @glennw !
Ideally, we'd want to put a PR number here that addressed this.
