### ISSUE TITLE
Text batch breaks in MotionMark

### ISSUE THREAD

**Issue by kvark** [servo/webrender#2085]
MotionMark test 8 has lots of text drawn on top of each other. We don't end up batching it at all, since each text gets split into 2 sub-passes. We should either stop using multiple passes, or force them to participate in rendering as regular batches, so that we could batch all the pass-1 together, then all the pass-2 together, etc.

Note: ok, not "all" of it, but at least some non-intersecting parts.

<img width="1452" alt="08-text" src="https://user-images.githubusercontent.com/107301/33149982-aee141bc-cf9f-11e7-9a90-9cdc19cf682c.png">

**Comment by glennw** [comment]
We don't actually do 2-pass text at all anymore, except in the case of subpx on a transparent background (which I don't believe Gecko makes use of yet @mstange ?). If that's occurring, it would definitely be surprising. Could it be something to do with text shadows that's making it look like 2 pass?

**Comment by mstange** [comment]
Gecko does make use of it, but only for the text in the tabs and in sidebars, and only on Mac. (And it's three passes, not two.)

**Comment by glennw** [comment]
Yea, so I think we may be either mis-interpreting what's going on here, or there's a very unexpected bug going on :)

**Comment by kvark** [comment]
Added a screenshots to the subject. I'll take another look, maybe it's not about double-pass as I assumed.

**Comment by glennw** [comment]
Huh, interesting screenshot. Are you able to extract the shader source code? Are there shader changes occurring between those draw calls? If not, I wonder why those batches are being broken at all? That's definitely not what I'd expect to see...

**Comment by glennw** [comment]
Actually, I can do a apitrace here on Linux and see if that shows similar issues.

**Comment by glennw** [comment]
Ohhh the batch breaks are occurring due to the small color changes for every text run that is being drawn on top of the previous. That makes sense now. So what we really need to do here is make use of the dual source blending extension on machines that support it. That will drastically reduce batch breaks for almost all our target hardware. The opaque text pass you mentioned would also be a big win here.

**Comment by glennw** [comment]
We now use dual-source blending where it is available, so I don't think there's anything else to do here.
