### ISSUE TITLE
ps_blend.glsl could be using a mat3 instead of a mat4

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2088]
All the matrices generated in [ps_blend.glsl](https://github.com/servo/webrender/blob/master/webrender/res/ps_blend.glsl) only make use of the top left 3x3 square of the matrix. I think this matrix could use the `mat3` type instead, and the fragment shader could be doing `oFragColor = vec4(vColorMat * Cs.rgb, Cs.a)`, which should be a bit cheaper.

**Comment by doraemon96** [comment]
Is this still needed? Im guessing the file is now [brush_blend.glsl](https://github.com/servo/webrender/blob/master/webrender/res/brush_blend.glsl)

I could look into this in a week or so. If someone else wants to do it, be my guest

**Comment by glennw** [comment]
Yup, it's ```brush_blend.glsl``` now, and no-one else is working on it yet.

I'll assign to you (just so nobody else starts working on it).
