### ISSUE TITLE
Make hit-testing more robust to timing irregularities

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2099]
I've been working on a gecko mochitest to exercise the WR hit-testing API, and I've been getting intermittent failures. I'm not 100% sure about this yet but it seems like these failures happen when the hit-test message arrives at the render_backend between scene being built and the clip_scroll_tree being rebuilt. Conceptually this makes sense because it means WR might be in an inconsistent state as it has updated half of its data structures but not the other half. I'll add some more logging to confirm but assuming this is the case, does anybody have any thoughts on how to avoid this problem?

**Comment by glennw** [comment]
From a quick look at the source code, we call ```clip_scroll_tree.update_tree``` when building a frame for render, but not when doing a hit test. This would suggest your analysis is right - that it can be out of sync when a new scene arrives but before a render.

If that's the case, calling ```clip_scroll_tree.update_tree``` at the start of hit test - and probably adding a dirty tracker to ```update_tree``` so we don't update it again when we then go to render if not dirty might fix it?

Thoughts @mrobinson ?

**Comment by mrobinson** [comment]
Hrm. I wonder if the right thing to do here is to wait to update the hit test item list until we call `clip_scroll_tree.update_tree`. I will take a look at this tomorrow!

**Comment by mrobinson** [comment]
This is actually a bit tricky! Perhaps there's a clever way to handle this though. Ideally, hit testing should be done against the currently rendered frame. As far as I can tell though, the ClipScrollTree and the ClipStore are not retained after a `FrameBuilder::build(...)` is called. The ClipScrollTree can almost certainly be replaced by the vector of ClipScrollNodeData, but I'm still not sure how to handle new data in the ClipStore.

**Comment by staktrace** [comment]
@nical Does your transaction stuff affect this at all? I thought we had a design that would allow hit-testing to work against currently rendered frames while we are in the process of building the next frame. (I have some vague recollection of this from that google doc you made)

**Comment by nical** [comment]
I think it does. With the transactions, anything that is part of a transaction will be applied atomically in the sense that we don't go back to the render backend event loop in between the things of a given transaction.
I'll finish the transaction work in January since it's not in the P2/P1 list at the moment.

**Comment by staktrace** [comment]
Bugzilla bug to go with this: https://bugzilla.mozilla.org/show_bug.cgi?id=1425451

**Comment by staktrace** [comment]
So after investigating some more, I think we still have this problem, and the transaction stuff didn't really fix the underlying problem. That is, the build step (triggered by `SetDisplayList`) and the render step (triggered by `GenerateFrame`) still happen in separate transactions, so it's possible for a HitTest request to get handled in between.

I agree with @mrobinson that ideally the hit-test should be done against the currently rendered frame, but right now the ClipScrollTree gets clobbered on the `SetDisplayList` for the next frame. So the hit-test is operating on inconsistent data.

@mrobinson - any chance you can pick this up again in the near future? As a workaround I've written a patch that forces a render prior to the hit-test (if one is needed) so that at least the hit-test produces consistent results, although it's "rolling forward" to hit-test against the next frame, rather than hit-testing against the previous frame. I'll put up a PR with that patch - if we can't get to a proper fix here soon maybe it'll be worth merging that as it will unblock turning on the WR hit-test by default in gecko.

**Comment by staktrace** [comment]
#2333 has merged. Leaving this issue open for a more correct fix that will undo #2333 and instead do some sort of double-buffering for the clip scroll tree so that when `SetDisplayList` is called it doesn't clobber the one from the last rendered frame. Note that if we want to move the `build_scene` step onto a worker thread as opposed to leaving it on the render backend thread (which is what @nical was suggesting) then we'll need this change for that as well.
