### ISSUE TITLE
Too much GPU time on the Chrome addon store site

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2100]
On [https://chrome.google.com/webstore/detail/embark-new-tab-page/aeajehgeohhgjbhhbicilpenjfcbfnpg/reviews?hl=en](https://chrome.google.com/webstore/detail/embark-new-tab-page/aeajehgeohhgjbhhbicilpenjfcbfnpg/reviews?hl=en), scrolling the reviews is a bit slow.

**Comment by glennw** [comment]
This seems resolved after #1961. I see GPU times around 6-7ms with the review modal open, and around 4-6ms when that is closed. There's still a heap of performance wins available to come on this page, but they are general optimizations (e.g. border shader, batching performance etc).

**Comment by glennw** [comment]
@mstange Feel free to re-open if you'd rather verify on your machine after Gecko takes the next WR update.
