### ISSUE TITLE
Unusable UI errors on Linux Nouveau

### ISSUE THREAD

**Issue by romanstingler** [servo/webrender#2117]
On my system Running ArchLinux with latest FF nightly 

[system_info_archmob_1511863556.log](https://github.com/servo/webrender/files/1509359/system_info_archmob_1511863556.log)

when I set
– “gfx.webrender.enabled” to true,
– “gfx.webrender.blob-images” to true,
– “image.mem.shared” to true,
– “layers.acceleration.force-enabled” to true

I get following display error on Wayland (have not tested on X.org yet)

![screenshot from 2017-11-28 10-54-33](https://user-images.githubusercontent.com/5576250/33313454-f992609e-d42a-11e7-9273-1f11fa1ec2b5.png)

**Comment by romanstingler** [comment]
I tested it within an old Xorg session, same graphical issues

**Comment by nical** [comment]
Might be https://bugzilla.mozilla.org/show_bug.cgi?id=1421280 (or related).

**Comment by glennw** [comment]
Is this still occurring?

**Comment by romanstingler** [comment]
yes still happening 

`
Application Basics
------------------

Name: Firefox
Version: 59.0a1
Build ID: 20180110221942
Update Channel: nightly
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
OS: Linux 4.14.13-1-ARCH
Multiprocess Windows: 1/1 (Enabled by default)
Web Content Processes: 4/4
Stylo: content = true (enabled by default), chrome = false (disabled by default)
Google Key: Found
Mozilla Location Service Key: Found
Safe Mode: true

Crash Reports for the Last 3 Days
---------------------------------

All Crash Reports

Nightly Features
----------------

Name: Activity Stream
Version: 2018.01.05.1410-84fd2871
ID: activity-stream@mozilla.org

Name: Application Update Service Helper
Version: 2.0
ID: aushelper@mozilla.org

Name: Firefox Screenshots
Version: 25.0.0
ID: screenshots@mozilla.org

Name: Follow-on Search Telemetry
Version: 0.9.6
ID: followonsearch@mozilla.com

Name: Form Autofill
Version: 1.0
ID: formautofill@mozilla.org

Name: Photon onboarding
Version: 1.0
ID: onboarding@mozilla.org

Name: Pocket
Version: 1.0.5
ID: firefox@getpocket.com

Name: Presentation
Version: 1.0.0
ID: presentation@mozilla.org

Name: Shield Recipe Client
Version: 80
ID: shield-recipe-client@mozilla.org

Name: Web Compat
Version: 1.1
ID: webcompat@mozilla.org

Name: WebCompat Reporter
Version: 1.0.0
ID: webcompat-reporter@mozilla.org

Extensions
----------

Name: ADB Helper
Version: 0.11.2
Enabled: false
ID: adbhelper@mozilla.org

Name: Bloody Vikings!
Version: 0.9.4
Enabled: false
ID: bloodyvikings@ffs.bplaced.net

Name: BrowserStack
Version: 23.7
Enabled: false
ID: {6cc0f0f7-a6e2-4834-9682-24de2229b51e}

Name: DuckDuckGo Plus
Version: 2017.12.7
Enabled: false
ID: jid1-ZAdIEUB7XOzOJw@jetpack

Name: GNOME Shell integration
Version: 8.2.1
Enabled: false
ID: chrome-gnome-shell@gnome.org

Name: HTTPS Everywhere
Version: 2017.12.6
Enabled: false
ID: https-everywhere@eff.org

Name: NoScript
Version: 10.1.6.3
Enabled: false
ID: {73a6fe31-595d-460b-a920-fcc0f8843232}

Name: U2F Support Add-on
Version: 1.0.1
Enabled: false
ID: u2f4moz@prefiks.org

Name: uBlock Origin
Version: 1.14.22
Enabled: false
ID: uBlock0@raymondhill.net

Name: Valence
Version: 0.3.8
Enabled: false
ID: fxdevtools-adapters@mozilla.org

Graphics
--------

Features
Compositing: Basic
Asynchronous Pan/Zoom: wheel input enabled; scrollbar drag enabled; autoscroll enabled
WebGL 1 Driver WSI Info: -
WebGL 1 Driver Renderer: WebGL is currently disabled.
WebGL 1 Driver Version: -
WebGL 1 Driver Extensions: -
WebGL 1 Extensions: -
WebGL 2 Driver WSI Info: -
WebGL 2 Driver Renderer: WebGL is currently disabled.
WebGL 2 Driver Version: -
WebGL 2 Driver Extensions: -
WebGL 2 Extensions: -
GPU #1
Active: Yes
Description: nouveau -- NVA5
Vendor ID: nouveau
Device ID: NVA5
Driver Version: 3.0 Mesa 17.3.2

Diagnostics
AzureCanvasAccelerated: 0
AzureCanvasBackend: skia
AzureContentBackend: skia
AzureFallbackCanvasBackend: none
CairoUseXRender: 0
Device Reset: Trigger Device Reset
Decision Log
HW_COMPOSITING:
blocked by default: Acceleration blocked by platform
force_enabled by user: Force-enabled by pref
blocked by runtime: Acceleration blocked by safe-mode
OPENGL_COMPOSITING:
unavailable by default: Hardware compositing is disabled
WEBRENDER:
opt-in by default: WebRender is an opt-in feature
available by user: Enabled by pref
unavailable by runtime: Safe-mode is enabled
OMTP:
disabled by default: Disabled by default
blocked by runtime: OMTP blocked by safe-mode




Media
-----

Audio Backend: remote
Max Channels: 2
Preferred Channel Layout: stereo
Preferred Sample Rate: 48000
Output Devices
Name: Group
GT216 HDMI Audio Controller Digital Stereo (HDMI 2): /devices/pci0000:00/0000:00:03.0/0000:01:00.1/sound/card1
Built-in Audio Analog Stereo: /devices/pci0000:00/0000:00:1b.0/sound/card0
USB Audio Device Analog Stereo: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0/sound/card2
Input Devices
Name: Group
Monitor of GT216 HDMI Audio Controller Digital Stereo (HDMI 2): /devices/pci0000:00/0000:00:03.0/0000:01:00.1/sound/card1
Monitor of Built-in Audio Analog Stereo: /devices/pci0000:00/0000:00:1b.0/sound/card0
Built-in Audio Analog Stereo: /devices/pci0000:00/0000:00:1b.0/sound/card0
Monitor of USB Audio Device Analog Stereo: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0/sound/card2
USB Audio Device Analog Mono: /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0/sound/card2

Important Modified Preferences
------------------------------

accessibility.blockautorefresh: true
accessibility.browsewithcaret: true
accessibility.typeaheadfind: true
accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 0
browser.cache.disk.enable: false
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.enabled: false
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 3
browser.download.useDownloadDir: false
browser.places.smartBookmarksVersion: 8
browser.search.useDBForOrder: true
browser.sessionstore.upgradeBackup.latestBuildID: 20180110221942
browser.startup.homepage_override.buildID: 20180110221942
browser.startup.homepage_override.mstone: 59.0a1
browser.tabs.warnOnClose: false
browser.urlbar.lastSuggestionsPromptDate: 20170614
browser.urlbar.searchSuggestionsChoice: true
browser.urlbar.timesBeforeHidingSuggestionsHint: 0
browser.urlbar.usepreloadedtopurls.enabled: false
dom.apps.lastUpdate.buildID: 20160612030220
dom.apps.lastUpdate.mstone: 50.0a1
dom.apps.reset-permissions: true
dom.forms.autocomplete.formautofill: true
dom.mozApps.used: true
dom.push.userAgentID: d5b449439a5e4cfea7639d34d65d3262
extensions.lastAppVersion: 59.0a1
font.internaluseonly.changed: true
general.autoScroll: true
gfx.webrender.blob-images: true
gfx.webrender.highlight-painted-layers: true
image.mem.shared: true
layers.acceleration.force-enabled: true
media.benchmark.vp9.fps: 105
media.benchmark.vp9.versioncheck: 1
media.eme.enabled: true
media.gmp-gmpopenh264.abi: x86_64-gcc3
media.gmp-gmpopenh264.autoupdate: true
media.gmp-gmpopenh264.lastUpdate: 1508736353
media.gmp-gmpopenh264.version: 1.7.1
media.gmp-manager.buildID: 20180110221942
media.gmp-manager.lastCheck: 1515670785
media.gmp-widevinecdm.abi: x86_64-gcc3
media.gmp-widevinecdm.lastUpdate: 1506320808
media.gmp-widevinecdm.version: 1.4.8.1008
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.force-enabled: true
media.peerconnection.ice.default_address_only: true
media.peerconnection.ice.no_host: true
media.webrtc.debug.log_file: /tmp/WebRTC.log
network.cookie.prefsMigrated: true
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.cleaned-up: true
network.predictor.enabled: false
network.prefetch-next: false
places.database.lastMaintenance: 1515616447
places.history.expiration.transient_current_max_pages: 151654
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
plugin.state.libnplastpass: 2
print.print_bgcolor: false
print.print_bgimages: false
print.print_duplex: 0
print.print_evenpages: true
print.print_headerleft:
print.print_headerright:
print.print_margin_bottom: 0.5
print.print_margin_left: 0.5
print.print_margin_right: 0.5
print.print_margin_top: 0.5
print.print_oddpages: true
print.print_orientation: 1
print.print_page_delay: 50
print.print_paper_data: 0
print.print_paper_height: 11.00
print.print_paper_name: iso_a4
print.print_paper_size_type: 1
print.print_paper_size_unit: 0
print.print_paper_width: 8.00
print.print_resolution: 600
print.print_scaling: 1.00
print.print_shrink_to_fit: true
print.print_to_file: false
print.print_unwriteable_margin_bottom: 17
print.print_unwriteable_margin_left: 17
print.print_unwriteable_margin_right: 17
print.print_unwriteable_margin_top: 17
privacy.cpd.offlineApps: true
privacy.cpd.siteSettings: true
privacy.sanitize.migrateClearSavedPwdsOnExit: true
privacy.sanitize.migrateFx3Prefs: true
privacy.trackingprotection.enabled: true
privacy.trackingprotection.introCount: 20
security.webauth.softtoken_counter: 1
security.webauth.u2f: true
security.webauth.u2f_enable_softtoken: true
security.webauth.u2f_enable_usbtoken: true
security.webauth.webauthn: true
security.webauth.webauthn_enable_softtoken: true
services.sync.declinedEngines: forms,history,tabs
services.sync.engine.adblockplus: true
services.sync.engine.addresses.available: true
services.sync.engine.bookmarks.validation.lastTime: 1515660373
services.sync.engine.creditcards.available: true
services.sync.engine.history: false
services.sync.engine.prefs.modified: false
services.sync.engine.tabs: false
services.sync.lastPing: 1515660371
services.sync.lastSync: Thu Jan 11 2018 12:42:05 GMT+0100 (CET)
services.sync.numClients: 2
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1514990070

Important Locked Preferences
----------------------------

Places Database
---------------

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.18 Beta
Version in use: 4.18 Beta

NSS
Expected minimum version: 3.35 Beta
Version in use: 3.35 Beta

NSSSMIME
Expected minimum version: 3.35 Beta
Version in use: 3.35 Beta

NSSSSL
Expected minimum version: 3.35 Beta
Version in use: 3.35 Beta

NSSUTIL
Expected minimum version: 3.35 Beta
Version in use: 3.35 Beta

Experimental Features
---------------------

Sandbox
-------

Seccomp-BPF (System Call Filtering): true
Seccomp Thread Synchronization: true
User Namespaces for privileged processes: true
User Namespaces: false
Content Process Sandboxing: true
Media Plugin Sandboxing: true
Content Process Sandbox Level: 3
Effective Content Process Sandbox Level: 3

Rejected System Calls
---------------------

Internationalization & Localization
-----------------------------------

Application Settings
Requested Locales: ["en-US"]
Available Locales: ["en-US"]
App Locales: ["en-US"]
Regional Preferences: ["en-US"]
Default Locale: "en-US"
Operating System
System Locales: ["en-US"]
Regional Preferences: ["en-US"]

`

**Comment by romanstingler** [comment]
In FF 60 still not fixed
depending on the cursor position the view is rendered differently.
upside down, normal, most of the time zoomed and upside down, also zoom value changes just by moving the mouse a few pixles around

![screenshot from 2018-01-25 11-19-14](https://user-images.githubusercontent.com/5576250/35383282-1c3673e6-01c2-11e8-802f-36979edf6664.png)
![screenshot from 2018-01-25 11-18-35](https://user-images.githubusercontent.com/5576250/35383289-1ec907ea-01c2-11e8-9de8-692161cae53d.png)
![screenshot from 2018-01-25 11-18-29](https://user-images.githubusercontent.com/5576250/35383291-20e7d312-01c2-11e8-86c9-ed288ef5da02.png)

**Comment by dralley** [comment]
The bugzilla is marked "resolved fixed", can this be closed?

**Comment by kvark** [comment]
Thanks for triaging!
