### ISSUE TITLE
Use ARB_texture_storage for allocating textures

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2124]
It's not uncommon for drivers to require allocating an entire miptree when texture allocation is done with TexImage2D. Using TexStorage2D can avoid this problem. That might reduce the time spent in brw_blorp_copy_miptrees as seen in https://perfht.ml/2zNOsuE 

However, brw_blorp_copy_miptrees might not actually be doing miptree related work despite the name

**Comment by gw3583** [comment]
@bholley implemented this.
