### ISSUE TITLE
Bouncing balls demo doesn't clip properly

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#2125]
Test case: https://codepen.io/davide_ravasi/full/WbRKrY/

Screen shot:
![Screenshot](https://i.imgur.com/nhvLq5W.png)

The ball should be circular.

**Comment by jrmuizel** [comment]
FWIW, the ball is circular in Gecko

**Comment by pcwalton** [comment]
Oh, I bet it's the elliptical borders. Closing as likely a Servo issue.
