### ISSUE TITLE
Bug when converting a binary replay to a yaml file.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#2131]
This seems especially broken on Gecko replays, which make use of multiple pipelines.

If I comment out this line (https://github.com/servo/webrender/blob/master/wrench/src/yaml_frame_writer.rs#L328) I generally get usable replays (without it, only the main pipeline gets written out).

I don't think that's the *correct* fix, but I haven't looked deeply into the root cause, and that code is a bit tangled to understand as well.

**Comment by jrmuizel** [comment]
I think I've seen something like this as well. See also #1826
