### ISSUE TITLE
Transformed primitive rendering glitches

### ISSUE THREAD

**Issue by kvark** [servo/webrender#2133]
See https://github.com/servo/webrender/pull/2069#issuecomment-347914944 for original report.
Related bugzilla entries:
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1420748
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1420754
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1421526

**Comment by glennw** [comment]
@staktrace Thanks for tracking down the regression range. Self assigned for when I have time to look at this.

**Comment by staktrace** [comment]
While bug 1420748 appears to be fixed in the latest firefox nightly, the other two bugs are still happening. I'll open separate issues for them.
