### ISSUE TITLE
facebook-refresh is gpu bound on mstange's mbp

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2140]
https://jrmuizel.github.io/webrender/facebook-refresh.html
He gets 36ms swaps

**Comment by mstange** [comment]
Profile: https://perfht.ml/2iqcnZI

**Comment by kvark** [comment]
The problematic areas are, roughly:
  - clips
  - rectangles
  - blurs
  - text runs
  - poor batching

The clips/blurs are likely addressed by either #2146 or the follow-ups to it.
Poor batching will also partially be addressed by this PR, but more investigation is needed.

The rectangles... may be limited simply by the rasterizer, or at least that's what I saw on my GPU captures. More investigation is pending.

**Comment by mstange** [comment]
Screenshot with profiler and gpu-time-queries enabled:
<img width="1552" alt="screen shot 2017-12-01 at 1 25 07 pm" src="https://user-images.githubusercontent.com/961291/33497214-295baa7a-d69b-11e7-98d5-8c4f9321fcd9.png">

It's only showing 9ms GPU time even though SwapBuffers is taking 36ms. So there must be something else going on here that the profiler isn't picking up.

**Comment by gw3583** [comment]
This is running really well on my test machine now. CPU backend time is ~2ms, GPU time is ~4.3ms on an HD4600. Draw calls are 71.

I'll close this for now, but please feel free to re-open if still occurring on other machines.

**Comment by mstange** [comment]
I can confirm that this is running a lot better now. We still slightly struggle a bit when a blur filter is on the screen, but otherwise it's fine.
