### ISSUE TITLE
http://bennettfeely.com/gradients/ gets sluggish on the reference hardware

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2143]
I see this with both ANGLE and native GL

**Comment by jrmuizel** [comment]
Here's the largely uninteresting profile: https://perfht.ml/2AsXfBr

**Comment by kvark** [comment]
Would be great to check with `RendererOptions::scatter_gpu_cache_updates` enabled

**Comment by kvark** [comment]
Actually, this profile is taken from the code base that doesn't have the new texture upload fixes in place, so even just double-checking with the current `UploadMethod::Immediate` (set by default) can prove it's fixed.

**Comment by glennw** [comment]
This is running well now, I'm seeing ~5ms GPU time. It can still be improved a lot, but it easily runs at 60 fps now.

**Comment by glennw** [comment]
Ooops, commented on wrong bug - this page is still slow.

**Comment by gw3583** [comment]
Note to self: this is a great test page for performance when working on gradient caching.

**Comment by gw3583** [comment]
This seems reasonable now.
