### ISSUE TITLE
Mysterious Giant Image on Facebook

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2144]
As noted in https://github.com/servo/webrender/issues/2123#issuecomment-347728853

I'm gonna look into it unless someone points me in a more important direction.

**Comment by glennw** [comment]
I also see a very large image when I look at about:blank, and the GPU profiler reports most of the time drawing a single image. It might be unrelated or a false positive, but it might be worth looking at that too.

**Comment by jrmuizel** [comment]
So has anyone seen this on platforms other than Linux? If it's only on Linux it's likely https://bugzilla.mozilla.org/show_bug.cgi?id=1418361

**Comment by glennw** [comment]
I've only seen it on Linux so far (but I haven't recorded a profile of those pages on Windows/Mac) so it may well be that.

**Comment by Gankro** [comment]
I get many giant (>1000 width) non-opaque images when logging on macos.

**Comment by Gankro** [comment]
After turning on blob-images I don't see any large external images anymore. Might indeed be linux-only.

**Comment by glennw** [comment]
I don't think there's anything WR-related to be done here, it seems like this would be Gecko work. Please re-open if that's not right.
