### ISSUE TITLE
6+ ms of gpu time being spent on rogers site because of inset shadows

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2145]
yaml here: https://jrmuizel.github.io/webrender/rogers.zip

The gpu gets hit pretty hard here. I see power usage of around 60W

**Comment by glennw** [comment]
This looks to be caused by one *very* large inset box shadow:

```
          "box-bounds": [0, -872.4, 2692, 2790]
          offset: [0, 14]
          color: 177 178 180 1.0000
          "blur-radius": 30
          "spread-radius": 0
          "clip-mode": inset
```

We don't have any optimizations for inset box shadows that we have for outset box shadows, yet.

**Comment by glennw** [comment]
Broadly speaking, we need to apply the same kinds of optimizations (only target the part of the primitive that can be affected by the blur), but this is slightly trickier for inset box shadows. I expect these optimizations to leverage off the in-progress work for primitive segments.

**Comment by glennw** [comment]
GPU profile confirms that all the time is spent in drawing one massive mask (to blur), then blurring it, then a very large clip mask.

**Comment by glennw** [comment]
This seems quite reasonable to me now - I see GPU times ~2.9ms once the box shadow is cached.
