### ISSUE TITLE
Add basic documentation

### ISSUE THREAD

**Issue by cengizIO** [servo/webrender#215]
Hello!

*I'm extremely interested in learning rust and I just started exploring servo engine. I'd be very happy if I can contribute to webrender, servo or rust in general.*

As a newcomer, I'm having difficulties due to lack of basic documentation like instructions, requirements, assumptions or guides.

So, I think we should put some documentation into the repository.

Any suggestions?

**Comment by KiChjang** [comment]
@cengizIO If you're starting out on Rust and want to contribute to something easy, head over to http://servo.github.io/servo-starters to pick something that you'd like to work on. If you're talking specifically about webrender, the GitHub wiki page should have an overview of how WR works.

But I agree that WR should have more documentation. https://doc.servo.org/webrender is lacking quite a bit of documentation.

**Comment by glennw** [comment]
Some basic API documentation got added here https://github.com/servo/webrender/pull/317
