### ISSUE TITLE
serialize_fast is not being inlined

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2154]
and if I force it to be inlined the generated code is no good.

**Comment by kvark** [comment]
See also  #2151

**Comment by jrmuizel** [comment]
Actually reading the code more closely it doesn't seem so bad. I think we might have a bit of extra copying but it's probably not worse than what we had before. I'll read more and see.

**Comment by glennw** [comment]
@jrmuizel Should we keep this open?

**Comment by jrmuizel** [comment]
Yeah, it would still be good for us to do something about this. I was thinking about it a bit recently and have a better plan.

Currently, we serialize GenericDisplayItem<SpecificDisplayItem> I think we'd get better codegen if we broke out the common parts during serialization.

**Comment by pcwalton** [comment]
@jrmuizel Is this still relevant?

**Comment by jrmuizel** [comment]
Our codegen for serialization currently won't win any awards, but it's good enough that it doesn't really show up in profiles. This is probably still relevant but I don't feel strongly about it being open or closed.
