### ISSUE TITLE
Webrender fails to initialize w/ nvidia proprietary drivers on linux

### ISSUE THREAD

**Issue by xevrem** [servo/webrender#2157]
I have a nvidia GTX 1070 installed in my linux box and attempted to launch nightly, but the interface and content loaded black. I clicked the interface "hamburger" and it fell-back to OpenGL compositing. Checked my `about:support` and it mentioned that webrender failed to initialize. NOTE: previously i ran this box with an AMD rx580, and webrender in the latest ff-nightly worked perfectly (using all the recommended settings from [Mozilla Gfx Team Blog](https://mozillagfx.wordpress.com/))

Anywho, here is a dump of my `about:support`

[about:support gist](https://gist.github.com/xevrem/e031e1a03e847e0dc536fb47a79d40da)

**Comment by NoXPhasma** [comment]
It's a known issue and I've created a bug report a few month ago. You can follow it if you want: https://bugzilla.mozilla.org/show_bug.cgi?id=1401455

**Comment by glennw** [comment]
Bugzilla bug is fixed. We can re-open with more specifics if it happens again.
