### ISSUE TITLE
Implement at least one fast feedback testing mechanism

### ISSUE THREAD

**Issue by cengizIO** [servo/webrender#216]
Hello!

As I introduced myself earlier, I'm trying to understand and contribute to webrender.

I think there **must** be a way to test the library for regressions while fixing bugs, adding new features etc.

Maybe there are ways to test but I couldn't find them with my current rust/cargo expertise.

Any ideas?

**Comment by glennw** [comment]
Right now, we test for regressions by running the main Servo test suite (WPT) which has a lot of visual tests, however it probably does make sense to build a custom test suite for WR at some point in the near future.

**Comment by seanjensengrey** [comment]
I to would like to add tests directly to webrender itself w/o having to run a full servo build. Could it possibly be tied in with #315 ?

**Comment by glennw** [comment]
We've added reftest support to wrench now, and these are run on travis CI for each PR.
