### ISSUE TITLE
A lot of GPU time spent on clips in github's diff view.

### ISSUE THREAD

**Issue by nical** [servo/webrender#2163]
The screenshot below says it all. 60ms of GPU time each frame, a lot of which is dedicated to clipping.

![screenshot from 2017-12-04 23-04-49](https://user-images.githubusercontent.com/264854/33578728-d423cd9e-d947-11e7-9ffb-39255765a165.png)

Looks like it is pretty easy to reproduce (for me at least) while scrolling through large diffs, like: https://github.com/servo/webrender/commit/1fbc96b5295e03760e3863f78fd8b31e51e9284f

**Comment by glennw** [comment]
I'll test today if this is reproducible with current WR master, which has had several clip fixes land in the last week.

**Comment by glennw** [comment]
@nical This is what a diff view on GH looks like with Gecko built against current master WR:

![gh](https://user-images.githubusercontent.com/2350882/33691163-9b83fad0-db32-11e7-803b-aa02e0d6da8c.png)

Shall we close this now, or do you want to wait until it lands in Gecko and confirm on your machine?

**Comment by nical** [comment]
@glennw sorry I should have precised that this seem to happen with the split view rather than the unified one. Although if with the recent changes the split view also stays within 6ms of GPU time that's great and we shall close it.

**Comment by nical** [comment]
I tested again and it's a lot better now (split view included).
