### ISSUE TITLE
Need tests for fonts with embedded bitmaps

### ISSUE THREAD

**Issue by lsalzman** [servo/webrender#2166]
Issues #2164 and #2165 popped up recently related to buggy handling of bitmap fonts with FreeType. We could use some tests for bitmap fonts. That requires a suitably licensed bitmap font we can include in the tree as well.

**Comment by lsalzman** [comment]
The most appealing font I could find so far is Proggy Clean here: https://github.com/servo/webrender/pull/2165

The one is a monospaced bitmap ttf programming font that only has a disk size of 41K. License is MIT.

**Comment by jrmuizel** [comment]
You can also probably subset the font down to a smaller size.

**Comment by glennw** [comment]
This happened.
