### ISSUE TITLE
box shadows are weirdly clipped with border radius

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#220]
``` html
<style>
  div {
    border-radius: 50%;
    width: 100px;
    height: 100px;
    background: red;
    border: 10px solid black;
    box-shadow: 0 0 0px 10px red;
  }
</style>
<div></div>
```

<img width="599" alt="screen shot 2016-03-03 at 19 11 53" src="https://cloud.githubusercontent.com/assets/373579/13504375/74222f16-e174-11e5-870f-9c62bc13cefc.png">

**Comment by mrobinson** [comment]
I'm not seeing this any longer. There have been a lot of changes to clipping and border rendering. I think we can close this for now. Please feel free to reopen if it's still an issue.
