### ISSUE TITLE
Discussing Ideas for GPU Accelerated Path/Font Rendering

### ISSUE THREAD

**Issue by ejpbruel** [servo/webrender#223]
I have been very interested by the subject of GPU accelerated path/font rendering lately, and my understanding is that this is something that Servo badly needs.

I should point out that I'm still very new to Rust, and Servo in particular, and since path/font rendering is a complicated topic in itself, I doubt I'd be able to implement something like this on my own. Even so, I'd like to try and see if I can help.

I just had short conversation with gw on the #servo irc channel. He said that there are a lot of potential ideas for GPU rendering, and suggested I open an issue here as a central point for discussion. So here we go :-)

**Comment by glennw** [comment]
cc @pcwalton

**Comment by glennw** [comment]
http://wdobbie.com/post/gpu-text-rendering-with-vector-textures/ could be an interesting place to start some experiments from.

**Comment by ejpbruel** [comment]
Another interesting SDF based approach that significantly alleviates the problem of rounded corners is given here:
https://lambdacube3d.wordpress.com/2014/11/12/playing-around-with-font-rendering/

**Comment by LifeIsStrange** [comment]
There are also a lot of stuff on the chromium doc :
https://github.com/ds-hwang/wiki/wiki/GPU-Font-Rendering

**Comment by LifeIsStrange** [comment]
Also this : 
http://studentarbeten.chalmers.se/publication/176609-fast-text-rendering-on-embedded-gpus

**Comment by ruud-v-a** [comment]
[This presentation](https://vimeo.com/83732058) about [Glyphy](https://github.com/behdad/glyphy) is worth watching.

**Comment by blissdev** [comment]
Saw this today:
https://medium.com/@evanwallace/easy-scalable-text-rendering-on-the-gpu-c3f4d782c5ac#.s1dqbybiu

**Comment by LifeIsStrange** [comment]
Next libreoffice release will have a text rendering implementation through opengl. 

http://phoronix.com/scan.php?page=news_item&px=LibreOffice-Better-GL-Text

**Comment by glennw** [comment]
Closing since this doesn't have anything actionable. The links are still useful to keep around, though the work @pcwalton is doing on PF should cover this.
