### ISSUE TITLE
Capture: save images as PNG

### ISSUE THREAD

**Issue by kvark** [servo/webrender#2234]
It would be useful for debugging to be able to look at the images being used by a frame. It would also reduce the size of captures, in case those are shared on the web.

Not clear how to handle non-RGBA8 formats for this. There is always an option to leave them as raw binaries, and this is what we can start with.

Another issue is the extra dependencies dragged with PNG encoder. Having `capture` enabled by default in Firefox build would then less feasible. Perhaps, we can find an alternative encoder than piston-image?

**Comment by glennw** [comment]
In previous embedded projects, I've used TGA images as a really simple format for debug output. The encoder is just writing a header plus the image data (e.g. http://www.paulbourke.net/dataformats/tga/). It supports 24-bit and 32-bit, and is readable by most applications. A complete TGA writer is typically less than 50 lines of code.

Alternatively, we could port a minimal PNG writer, such as https://github.com/nothings/stb/blob/master/stb_image_write.h (or even just compile and call via FFI).

**Comment by jrmuizel** [comment]
I wrote a minimal uncompressed png writer that should be easy to port https://github.com/jrmuizel/minpng/blob/master/minpng.h. That being said, Firefox already ships with all of libpng so we could just set up a simple callback api that receives the data to be encoded and returns encoded data. When not in Gecko this could use piston-image.

**Comment by kvark** [comment]
Note that uncomressed PNG/TGA defeats one of the pro points I mentioned in the issue. Still a good thing to get though.

**Comment by kvark** [comment]
Implemented in #2326
Switched on by "png" feature.
