### ISSUE TITLE
zoomed in blurred text shadows generate garbage bounding box fragments

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2252]
Try zooming in and out on this page:

```
data:text/html,<meta charset="utf-8"><span style="text-shadow: 2px 2px 1px red"><div>Blur<span style="color: blue">%F0%9F%8E%89</span><span style="color: rgba(0,0,0,0.7)">%F0%9F%8E%89</span><span style="color: rgba(0,0,255,0.4)">%F0%9F%8E%89</span><span style="color: transparent">%F0%9F%8E%89</span><span style="text-shadow: 2px 2px 2px red"></span></div><div>Blur<span style="color: blue">A</span><span style="color: rgba(0,0,0,0.7)">A</span><span style="color: rgba(0,0,255,0.4)">A</span><span style="color: transparent">A</span></div></span>
```

![screen shot 2018-01-03 at 4 10 48 pm](https://user-images.githubusercontent.com/1136864/34540011-e92f1a8e-f0a0-11e7-8133-036958bfa805.png)

**Comment by Gankro** [comment]
Can't repro on windows.

**Comment by Gankro** [comment]
Note the example is extra complicated just to make it easier to see, and to rule out some things. This also demonstrates the issue:

```
<span style="color: transparent; text-shadow: 2px 2px 1px black">A</span>
```

**Comment by Gankro** [comment]
In theory this makes `reftests/text/shadow-single.yaml` sufficient to demonstrate the issue but it seems like zoom is somehow relevant, and wrench can't do it.

**Comment by Gankro** [comment]
Actually hmm I can see this on some unzoomed characters sometimes?

**Comment by Gankro** [comment]
Or not? Seems like reset-zoom was just acting janky?

**Comment by Gankro** [comment]
Ok I spent some more time on this, and I've reproduced it on linux, macos, and windows. I wasn't seeing it initially on windows or wrench because it appears to be based on global effects on the cache: you need to launch a few tabs to social media sites first and then load the example and it will work. I was able to reproduce this in a binary recording in wrench as well, although if you export any one frame as a yaml it won't reproduce the issue!

**Comment by Gankro** [comment]
I have shown @kvark how to reproduce this locally, hopefully they can figure this out >.>

**Comment by glennw** [comment]
@kvark Possibly a good use case for your new capturing WIP ? :)

**Comment by kvark** [comment]
@glennw ^_^ exactly what I was telling @Gankro :)
This needs built-frame level of capturing, which is still to implement. I'll try to make this happen after the pending PRs are done.

**Comment by glennw** [comment]
I was unable to reproduce this on Linux - either via Gecko or replaying the recording in wrench. Might only appear on mac?

**Comment by Gankro** [comment]
Confirmed that I can't reproduce this on firefox nightly anymore (macos).
