### ISSUE TITLE
macos: synthetic bold not working

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2269]
On my [text stress test](https://gankro.github.io/blah/webtests/text.html), the synthetic bold case doesn't seem to be working:

![screen shot 2018-01-08 at 2 11 51 pm](https://user-images.githubusercontent.com/1136864/34687898-351766fa-f47e-11e7-9ecb-756895d845f6.png)

left: vanilla firefox 
right: webrender-firefox

The html is (problematic parts are the ones with "basic" as the font):

```html
<p style="font-weight: bold">
Lorem ipsum dolor sit amet, consectetur adipiscing elit,
<span style="color: rgba(0,0,0, 0.5)">
sed do eiusmod tempor incididunt ut labore et
</span>
<span style="font-family: &quot;basic&quot;">
dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
</span>
<span style="font-family: &quot;basic&quot;; color: rgba(0,0,0, 0.5)">
ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
</span>
<span style="font-family: -apple-system, sans-serif">
velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
</span>
sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
```

"basic" is a font I'm loading from Adobe Edge Fonts which doesn't provide a bold variant.

**Comment by Gankro** [comment]
Confirmed this works fine on windows.

**Comment by Gankro** [comment]
(Is there a way to test synthetics in wrench?)

**Comment by lsalzman** [comment]
You just need to use synthetic-bold: true

**Comment by Gankro** [comment]
Seems to work in wrench, probably a gecko bindings issue?

**Comment by lsalzman** [comment]
If you disable WR, does that case work?

**Comment by Gankro** [comment]
Yes, the screenshot shows it working without wr.

**Comment by Gankro** [comment]
Bugzilled since it seems like a gecko issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1428874
