### ISSUE TITLE
Webrender scrolls at <1 frame per second using integrated graphics on mid-2010 macbook

### ISSUE THREAD

**Issue by gregkatz** [servo/webrender#227]
Using servo in webrender mode with integrated graphics on a mid-2010 macbook does not work well. Using discrete graphic card works much better.

Steps to reproduce:
1. Build servo using `brew install --HEAD servo/servo/servo`
2. Lock graphics to integrated mode using gfxCardStatus (available at [https://gfx.io/](https://gfx.io/))
3. Launch servo using webrender with `servo -w http://www.reddit.com`
4. Attempt to scroll the page

**Comment by paulrouget** [comment]
Can you please run with `-w -Z wr-stats` and post a screenshot here?
Do you get the same result with firefox.com?

**Comment by gregkatz** [comment]
Here's a few screenshots showing the difference between discrete and integrated graphics. The first shot is on discrete. All the others are on integrated. The last shot shows what happens when I try to scroll the page...even slower.

![firefox - discrete](https://cloud.githubusercontent.com/assets/3066927/13692381/195f4b0e-e70f-11e5-8617-739f0b08a747.png)
![firefox_com - integrated](https://cloud.githubusercontent.com/assets/3066927/13692384/19631630-e70f-11e5-993e-19288965e795.png)
![reddit - integrated 2](https://cloud.githubusercontent.com/assets/3066927/13692383/19610c50-e70f-11e5-81c9-9f9c17140184.png)
![reddit - integrated](https://cloud.githubusercontent.com/assets/3066927/13692382/1960e5ae-e70f-11e5-90ae-2b9441fe789d.png)

**Comment by pcwalton** [comment]
Hmm, it would be nice to have the GPU profiling stats in there…

Still, "CPU (compositor)" being so high leads me to believe it isn't the power of the GPU that's the problem (a good sign). We're hitting some kind of driver stall or something.

**Comment by gregkatz** [comment]
Is there some way I can include the GPU profiling stats in the screen shot?

**Comment by pcwalton** [comment]
It should be there if you have the most up-to-date WebRender (using a cargo override).

**Comment by gregkatz** [comment]
For what it's worth, here's integrated and discrete screen shots with the GPU info included.

![firefox-integrated](https://cloud.githubusercontent.com/assets/3066927/13797888/11f7f042-eae7-11e5-8c6d-2ec4e10b64e7.png)
![firefox-discrete](https://cloud.githubusercontent.com/assets/3066927/13797887/11f5acce-eae7-11e5-98dc-4c1eebb691e5.png)

**Comment by glennw** [comment]
I believe this is resolved now, please re-open if you can still reproduce.
