### ISSUE TITLE
regression: Image rendering and transform artifacts

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2273]
Filing for https://bugzilla.mozilla.org/show_bug.cgi?id=1421526 - there are two regressions noted in the bug, this issue is specifically about the second one which "destroyed the images of GET EARLY ACCESS." I never did actually confirm the regression range for it but I'll try to do that today.

**Comment by staktrace** [comment]
I've managed to narrow down the range to this:

```
*   02d9b6d9 Auto merge of #2078 - kvark:rtree, r=glennw
|\
| * 08a32a9e RenderTaskTree refactor
* |   0cc47eb8 Auto merge of #2072 - nical:dbg-flags, r=glennw
|\ \
| * | b32c990d Make servo-tidy happy.
| * | 72161329 Add toggle_debug_flags.
| * | 1365e063 Properly handle debug flags when creating the renderer.
| * | 0d934778 Use DebugFlags for time and sample queries.
|  /
* |   e83612df Auto merge of #2069 - glennw:xf, r=kvark
|\ \
| * | 0aebe2b7 Address review comments
| * | 8253bbb3 Remove manual interpolation of local space in transform shaders.
|  /
* | 00e70b3c Auto merge of #2077 - kvark:pass-kind, r=glennw
|/
* 40349b38 Strong typing for the main framebuffer pass
```

To narrow it down any further would require a lot of work and new custom builds so I probably won't do that unless we really need it.

**Comment by glennw** [comment]
@staktrace No worries, thanks! It's almost certain to be 8253bbb3, so I think this is close enough.

**Comment by gw3583** [comment]
Related bugzilla bug is closed.
