### ISSUE TITLE
regression: oblique background on https://superhuman.com/ gets drawn on chrome

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2283]
WR issue for https://bugzilla.mozilla.org/show_bug.cgi?id=1429235 and https://bugzilla.mozilla.org/show_bug.cgi?id=1429428 (which was duped to the first one). bug 1429428 has a reduced test case courtesy of Markus.

I narrowed down the regression range for this issue to this:

```
*   45dc6a3a Auto merge of #2244 - glennw:dual-source-blending, r=kvark
|\
| * 5f6b3868 Add dual-source blending path for subpixel text when supported.
* 97479a41 Auto merge of #2242 - glennw:gen-seg8, r=kvark
* 9423cf20 Address review comments
* 6ef9d025 Adding edge flags to unit tests
* 479e48f5 Fix borders with pre-built segments not checking clip mask kind.
* fdac2304 Extend segment building to handle clip in/out, multiple clip regions.
```

So it's either #2244 or #2242. /cc @glennw

**Comment by Darkspirit** [comment]
I think this got fixed by #2324. (https://bugzilla.mozilla.org/show_bug.cgi?id=1429235#c5)
