### ISSUE TITLE
[RFC] Filters: Add color transform matrix filter

### ISSUE THREAD

**Issue by eeejay** [servo/webrender#2297]
The primary usecase would be accessibility. We are looking for a way to apply a [full-viewport color filter](https://wiki.mozilla.org/Accessibility/ColorFilters) with little performance overhead.

Besides accessibility, this can also be offered as a fast path for SVG color matrix filters (although issue #1880 would address that more holistically).

The public API change would be an extension of the FilterOp type:
```rust
#[derive(Clone, Copy, Debug, PartialEq, Deserialize, Serialize)]
pub enum FilterOp {
    Blur(f32),
    Brightness(f32),
    Contrast(f32),
    Grayscale(f32),
    HueRotate(f32),
    Invert(f32),
    Opacity(PropertyBinding<f32>, f32),
    Saturate(f32),
    Sepia(f32),
    DropShadow(LayoutVector2D, f32, ColorF),
    ColorMatrix([f32; 20]),
}
```

**Comment by nical** [comment]
Sounds good to me although we should box the matrix to prevent it from making all filter ops ~88 bytes.

**Comment by eeejay** [comment]
> we should box the matrix

I don't know how to do that while keeping the FilterOp copyable. Total Rust newb here.

**Comment by glennw** [comment]
This happened.
