### ISSUE TITLE
Wrench deadlocks when a transaction contains scrolling operations.

### ISSUE THREAD

**Issue by nical** [servo/webrender#2303]
For some reason wrench does not wake the event loop up if there is a scrolling operation in a transaction.
see https://github.com/servo/webrender/blob/d3f72e1f4f13cc1b470fa7518710bd8e845f3e72/wrench/src/main.rs#L295

That's kinda confusing and error prone. This was probably done to avoid taking the snapshot in the middle of the updates when several things scroll, but we can better support this type of situation by grouping all scrolling updates inside the same transaction.

If we need anything more complicated, then wrench should do what gecko does: explicitly wait for specific epochs to be rendered before taking the snapshot.

**Comment by glennw** [comment]
@nical Is this resolved now? (via https://github.com/servo/webrender/pull/2410)

**Comment by nical** [comment]
Yep!
