### ISSUE TITLE
<tr> backgrounds aren't drawn correctly

### ISSUE THREAD

**Issue by KwanEsq** [servo/webrender#2309]
Other browsers seem to render `tr { background-color: black }` the same as  `tr > th, tr > td { background-color: black }`.  Servo does not. (Not sure where that's spec'ed, or even if it is)

Testcase: http://kwan.perix.co.uk/mozilla/tableRowBackgroundTest.html
(Correct rendering emulated on hover using cell backgrounds)

Servo rendering:
![screenshot from 2018-01-16 22-50-32](https://user-images.githubusercontent.com/1735753/35016320-e4d40df4-fb0f-11e7-96e1-0f095e2b6aa8.png)

Firefox rendering:
![screenshot from 2018-01-16 22-51-31](https://user-images.githubusercontent.com/1735753/35016409-4a5a309a-fb10-11e7-87d6-c05ca1074665.png)

**Comment by glennw** [comment]
Thanks for the bug report!

I *think* this should probably be reported as an issue in the Servo repository. It seems more likely to be related to the display list that Servo is producing, rather than something in WR itself.

**Comment by KwanEsq** [comment]
@glennw ... darn it, I misread my location and thought I was _in_ servo/servo (which is where I was searching for potential duplicates.  Thanks for the heads-up! I'll re-file.
