### ISSUE TITLE
Using rusttype instead of freetype?

### ISSUE THREAD

**Issue by fschutt** [servo/webrender#2325]
Just a question, but is the webrender team aware of [rusttype](https://github.com/redox-os/rusttype)? Is there any reason why you are using freetype instead? Right now, you have to ship the freetype DLL with the binary, which complicates deployment. 

Is it planned to migrate to rusttype in the future or is the team not interested?

**Comment by jrmuizel** [comment]
Yep, we're aware. rusttype doesn't have enough features to give native looking fonts (e.g. it's missing hinting and opentype outline support).

You shouldn't need to ship freetype though, instead you can just use the system freetype.

**Comment by fschutt** [comment]
What do you mean by "system freetype"? On Windows, you still have to ship the DLL, or am I missing something?

**Comment by leeoniya** [comment]
isnt the plan to use pathfinder for glyph & path rendering? it already supports hinting and outlines i think.

https://github.com/pcwalton/pathfinder

**Comment by jrmuizel** [comment]
On Windows WebRender uses DirectWrite and on macOS it uses CoreGraphics so we don't need FreeType on those platforms.

Pathfinder doesn't have sufficient hinting support to replace the OS stuff yet, we're not exactly sure what are our plan to deal with that will be.

**Comment by jrmuizel** [comment]
We'll close it for now and can file something new if rusttype becomes more mature.
