### ISSUE TITLE
regression: white bars on tabs when loading whatsapp

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2327]
Filing for https://bugzilla.mozilla.org/show_bug.cgi?id=1431575

Narrowed the regression range down to:

```
*   4e6310e8 Auto merge of #2257 - zakorgy:patch-1, r=nical
|\
| * 9066f565 Remove legacy shader part from build_shader_strings
*   92959212 Auto merge of #2255 - glennw:fix-3dxf, r=kvark
|\
| * c66209e1 Make incompatible coordinate system detection more conservative.
* 3a905e7e Auto merge of #2251 - Gankro:deserialize_in_place, r=glennw
* 52c3ecef Stop using the serde_derive feature for no good reason
* f879af5f Update serde to 1.0.27, removing some of the patch hacks
```

Let me know if you want it narrowed down further, I'll have to do builds.

**Comment by glennw** [comment]
No need to narrow it down further, that's a big help already, thanks!

**Comment by Darkspirit** [comment]
I think this got fixed: https://github.com/servo/webrender/compare/30f2cd5e648bbcadbe8200d479de3f7d76089d0b...e7c95ae9fb6b7f8d973ae5106a1ba8be6adea007

**Comment by glennw** [comment]
Yep, definitely plausible - there's a couple of patches in WR that may have fixed it, or it could also have been the external clip ID fix in Gecko that fixed it.

**Comment by glennw** [comment]
Oh, it could also be the partial rendering PR from that commit range you referenced above.

**Comment by Darkspirit** [comment]
That's the fix range I found. The visual issue was gone afterwards. So this issue could get closed.
