### ISSUE TITLE
SetGradientStops missing with debug-serialization

### ISSUE THREAD

**Issue by pyfisch** [servo/webrender#2328]
Hi,
I found that serializing a BuiltDisplayList with the "debug-serialization" feature omits the `SetGradientStops` items.

BTW I am curious to hear why the gradient stops are separate items instead of being part of gradient and radial gradient.

* [serialized display list](https://gist.github.com/pyfisch/29af74e0ebffc2d6287ef806143c3cd4)
* Rendering: ![simple-gradient](https://user-images.githubusercontent.com/2781017/35195795-f20ca302-fec8-11e7-96d7-58f0a9254a44.png)

cc @kvark

**Comment by kvark** [comment]
This appears to be blocking a scene-rebuild after loading any WR capture with gradients:
```
thread 'WRRenderBackend#0' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'WRRenderBackend#0' panicked at 'Can't allocate zero sized blocks!', webrender/src/gpu_cache.rs:287:18
```
The 0 count of blocks come from a gradient primitive that failed to load the stops:
```
(gdb) f 6
#6  0x000055555655987b in webrender::prim_store::PrimitiveStore::prepare_prim_for_render_inner (self=0x7fffed81b628, 
    prim_index=PrimitiveIndex = {...}, prim_run_context=0x7fffedfea288, pic_state_for_children=PictureState = {...}, pic_context=0x7fffedfea6d0, 
    pic_state=0x7fffedfea670, frame_context=0x7fffedff1910, frame_state=0x7fffedff1968) at webrender/src/prim_store.rs:1439
1439	                        }
(gdb) info locals
stops_handle = 0x7fffed8d2000
gradient_index = CachedGradientIndex = {0}
stops_range = ItemRange<webrender_api::display_item::GradientStop> = {start = 0, length = 0, 
  _boo = PhantomData<webrender_api::display_item::GradientStop>}
reverse_stops = false
brush = 0x7fffecbc7f98
metadata = 0x7fffec9b2220
```
This is quite a major blocker for investigating a set of cases like #2567 where scene rebuild-ing is needed to figure out what and when went wrong.

**Comment by glennw** [comment]
As a temporary workaround, I've been manually editing the RON files to remove gradients when I need to load and rebuild the scene. It's not ideal - it would be great to get this fixed :)
