### ISSUE TITLE
regression: broken images on https://testpilot.firefox.com/experiments

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#2334]
https://testpilot.firefox.com/experiments
Regressed by #2243.
https://bugzilla.mozilla.org/show_bug.cgi?id=1432685

**Comment by glennw** [comment]
@Darkspirit I think this looks correct now - are you able to verify?

**Comment by Darkspirit** [comment]
Still reproducible for me. Screencast: [bug 1432685 comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1432685#c1)

**Comment by Darkspirit** [comment]
This was duped to #2584.
Fixed by and verified in #2588.
