### ISSUE TITLE
regression: tab label alpha gradient is showing incorrectly

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2336]
Filing for https://bugzilla.mozilla.org/show_bug.cgi?id=1432101 - there are STR in comment 4 of that bug.

Regression range is:
```
*   8811f69c Auto merge of #2316 - kvark:capture-fix, r=staktrace
|\
| * 3befcf77 Capture: workaround for cbindgen parsing failure
* e5514a40 Auto merge of #2311 - glennw:seg-bs, r=kvark
* 9b939a40 Optimize box-shadow rendering (use segments for pictures).
```

So #2311 seems to be the culprit here.

**Comment by Darkspirit** [comment]
This has been fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1432101#c18
