### ISSUE TITLE
"CreateWindowEx function failed: The operation completed successfully"

### ISSUE THREAD

**Issue by SimonSapin** [servo/webrender#2356]
After building WebRender on Windows 10, if I run wrench or one of the example applications I get this output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("CreateWindowEx function failed: The operation completed successfully. (os error 0)")', src\libcore\result.rs:906:4
```

The code that creates this `Result::Err(…)` value is:

https://github.com/servo/glutin/blob/v0.14.0/src/api/win32/init.rs#L162-L174
```rust
        let handle = CreateWindowExW(ex_style | WS_EX_ACCEPTFILES,
            class_name.as_ptr(),
            title.as_ptr() as LPCWSTR,
            style | WS_CLIPSIBLINGS | WS_CLIPCHILDREN,
            x.unwrap_or(CW_USEDEFAULT), y.unwrap_or(CW_USEDEFAULT),
            width.unwrap_or(CW_USEDEFAULT), height.unwrap_or(CW_USEDEFAULT),
            ptr::null_mut(), ptr::null_mut(), GetModuleHandleW(ptr::null()),
            ptr::null_mut());

        if handle.is_null() {
            return Err(OsError(format!("CreateWindowEx function failed: {}",
                                       format!("{}", io::Error::last_os_error()))));
        }
```

Any idea what could cause this? Are there per-requisites for running WebRender on Windows?

**Comment by jrmuizel** [comment]
I can reproduce this. I'm not sure what's wrong.

**Comment by jrmuizel** [comment]
I can, in fact, reproduce by just trying to run the 'window' example from the servo-glutin repository.

**Comment by jrmuizel** [comment]
@sotaroikeda can we switch back to regular glutin from servo-glutin? It looks like servo is dropping support for servo-glutin: https://github.com/servo/servo/pull/19895

**Comment by glennw** [comment]
I've been running wrench successfully on Win10 without any issues for a couple of months, I'm not sure what the different here is. Nonetheless, switching us to use upstream glutin makes sense to me - if there's an issue with that, we should probably try to resolve it and stop using servo-glutin, which is (mostly) unmaintained.

**Comment by SimonSapin** [comment]
This appears to be a bug in servo-glutin, since using glutin 0.7 instead works. (0.7 because WebRender’s examples don’t compile with more recent versions)

**Comment by SimonSapin** [comment]
*Downgrading* servo-glutin from 0.14.0 to 0.13.4 also works. I tried that based on @jdm’s comment at https://github.com/servo/servo/issues/19901#issuecomment-361590184.

Commit range: https://github.com/servo/glutin/compare/servo-v0.13.4...v0.14.0. The winapi update looks relevant: https://github.com/servo/glutin/commit/1887503ba1a1b919c1aeb1e6dfc283540f739b24 but it’s a fairly big diff.

**Comment by jdm** [comment]
All of the changes in the winapi diff look like they're just removing prefixes in names, unfortunately. It may be an issue in the actual winapi implementation somewhere :(

**Comment by SimonSapin** [comment]
@retep998, other than the `as LPCWSTR` cast which I’ve verified is unnecessary, do you see anything suspicious around the `CreateWindowExW` call in this diff?

https://github.com/servo/glutin/pull/140/files#diff-337839224920efa7748d62b99d666952R162

**Comment by kvark** [comment]
As a random thought, we could compare the API calls with something like this: http://jacquelin.potier.free.fr/winapioverride32/

**Comment by sotaroikeda** [comment]
> @sotaroikeda can we switch back to regular glutin from servo-glutin? It looks like servo is dropping support for servo-glutin: servo/servo#19895

It seems possible now.  It was changed since glutin was broken for several months for refactoring.

**Comment by o01eg** [comment]
Same issue.
```
     Running `target\release\examples\basic.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("CreateWindowEx function failed: Операция успешно завершена. (os error 0)")', sr
c\libcore\result.rs:906:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::result::unwrap_failed<glutin::CreationError>
             at C:\projects\rust\src\libcore\macros.rs:23
   9: basic::boilerplate::main_wrapper<basic::App>
             at .\webrender\examples\common\boilerplate.rs:322
  10: basic::main
             at .\webrender\examples\basic.rs:170
  11: panic_abort::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_abort\lib.rs:38
  12: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  14: BaseThreadInitThunk
error: process didn't exit successfully: `target\release\examples\basic.exe` (exit code: 255)
```

But when I test examples from original glutin they works:
```
     Running `target\release\examples\multiwindow.exe`
OpenGL version 3.1.0 - Build 9.17.10.4229
OpenGL version 3.1.0 - Build 9.17.10.4229
OpenGL version 3.1.0 - Build 9.17.10.4229
```
