### ISSUE TITLE
masks need better snapping?

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2371]
keep forgetting to file this properly so I'm just gonna dump this so I don't forget.

The fade-out masks on firefox tabs sometimes fail out by a pixel or a half on the right. More snapping required?

<img width="83" alt="screen shot 2018-02-01 at 7 39 37 pm" src="https://user-images.githubusercontent.com/1136864/35715862-0fa2a474-07a3-11e8-8c89-1708b4dde746.png">

cc @mstange

**Comment by glennw** [comment]
@Gankro I suspect this will be fixed by #2618, which has landed in WR. Could you re-test this next time a WR update occurs in Gecko?

**Comment by Gankro** [comment]
I don't think I've seen this for a while, but sure I'll keep an eye out.

**Comment by gw3583** [comment]
I believe this is fixed now - we can reopen if we come across it again.
