### ISSUE TITLE
regression: tab loading animations are broken

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#2372]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435129
Regression range: https://github.com/servo/webrender/compare/87c6a6ba7e75d8ed0b2ddeeb5fa4e363482f7f86...e772c3cb8ea0a35e6477e9dc8dd2144e2de87b56

![screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8947686)

**Comment by glennw** [comment]
I *think* this is a gecko-side bug related to the external scroll ID change. cc @mrobinson

**Comment by glennw** [comment]
(and maybe @staktrace too)

**Comment by Darkspirit** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435143#c8
