### ISSUE TITLE
regression: Nextcloud menu tooltip backgrounds are broken

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#2373]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435143
[Testcase](https://bugzilla.mozilla.org/attachment.cgi?id=8947704)
Regression range: https://github.com/servo/webrender/compare/87c6a6ba7e75d8ed0b2ddeeb5fa4e363482f7f86...e772c3cb8ea0a35e6477e9dc8dd2144e2de87b56

![screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8947705)

**Comment by glennw** [comment]
I *think* this is a gecko-side bug related to the external scroll ID change. cc @mrobinson

**Comment by glennw** [comment]
(and maybe @staktrace too)

**Comment by staktrace** [comment]
It was my understanding that the external scroll ID change would be a no-op from the gecko point of view (i.e. it was just shifting some code around, no functional changes intended). @mrobinson can you confirm? If so then it shouldn't have exposed any latent gecko bugs assuming that's what happened.

**Comment by Darkspirit** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435143#c8
