### ISSUE TITLE
WebRender doesn't respect ClearType settings

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [servo/webrender#2377]
It looks like WebRender on Windows completely ignores the fact that ClearType is disabled, and tries to blur/antialias fonts anyway. I'm not sure if skipping those steps would have any performance benefits, but that'd surely deliver a more expected rendering.

Testcase:
data:text/html,abcdefghijklmnopqrstuvwxyz

WebRender off:
https://i.imgur.com/zluOSV8.png

WebRender on:
https://i.imgur.com/GO2tiMX.png

OS: Windows 10
GPU: Nvidia GeForce GTX 970

**Comment by glennw** [comment]
cc @lsalzman

**Comment by lsalzman** [comment]
How are you disabling cleartype? Via a registry key or via the cleartype settings menu in Windows?

**Comment by automatedbugreportingfacility** [comment]
Control Panel -> Fonts -> Adjust ClearType text -> uncheck "Turn on ClearType" in the ClearType Text Tuner.

**Comment by lsalzman** [comment]
So after you do this, and if you restart Firefox, it does not pick up the ClearType settings change?

**Comment by automatedbugreportingfacility** [comment]
I've had ClearType disabled since I installed and configured Windows about a year ago. Firefox was installed after that, i.e. WebRender doesn't consider the configuration, not just a change.

**Comment by lsalzman** [comment]
This is just a bug in Gecko itself, not WebRender. As such I've filed a Gecko bug for this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1436265

There is a patch there to fix this. We were just never updating ClearType settings inside Gecko for the WR layers case, so it always showed up as enabled.

**Comment by glennw** [comment]
Let's close this, since there is no WR work to do. This will be fixed when the patch linked above lands in a nightly. Thanks!
