### ISSUE TITLE
ClipChain with two clips descending from mask has mask applied twice

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2388]
I was reworking the gecko clipping glue to use the ClipChain APIs and ran into a problem. (I had asked @mrobinson about it on IRC, but upon further investigation it turns out the scenario is a little different from what I described to him).

Not entirely sure if this behaviour is expected or not, but the scenario is as follows:
- there is a clip with a mask image that has a 0.5 opacity (id 6)
- there are two clips that are descendant clips of that one (id 7 and id 10)
- there is a ClipChain containing those two clips (id 11)
- there is a rect that uses the ClipChain

In this scenario the mask image gets applied to the rect twice so the rect ends up with opacity 0.25. Whereas I'm expecting it to have an opacity of 0.5 (because the mask would be "deduplicated" from the set of clips that apply to the rect, and only get applied once).

Here's the yaml and mask image:
[yaml_frames.zip](https://github.com/servo/webrender/files/1700823/yaml_frames.zip)

The zip contains both my reduced version (frame-4.yaml) and the original unreduced version which was generated from a recording of `layout/reftests/w3c-css/submitted/masking/mask-opacity-1a.html` in mozilla-central.

**Note**: One thing that might be relevant is that in the original unreduced version, clips "7" and "10" were not in the same ClipChain, but in two chains linked by a parent reference. That is, chain id=11 just contained clip 10 but pointed to a parent chain id=9 which contained clip 7.

**Comment by mrobinson** [comment]
Odd! In this case, I would expect that the mask does not get applied at all. ClipChains should only apply the clips specified by the clips themselves and not any of their parents.

**Comment by mrobinson** [comment]
I will try to take a look at this issue next.
