### ISSUE TITLE
Window decorations and resizing broken for examples after switch to upstream Glutin

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#2395]
![screenshot from 2018-02-08 12-09-43](https://user-images.githubusercontent.com/13536/35970022-0ba44082-0cc9-11e8-957c-7cfe0d37ce97.png)

Typically I see normal Gnome window decorations, but now there are some simple shapes representing window controls. The example starts full screen and when I resize it, the content area stays larger than the window boundaries. I'm running Wayland and XWayland.

cc @kvark

**Comment by glennw** [comment]
I did some basic testing with upstream glutin + wayland + wrench, but there's actually quite a bit more broken than I had noticed :(

As a workaround, for now I am doing this:
```
export WINIT_UNIX_BACKEND=x11
```

This tells glutin/winit to run wrench using xwayland, while still having the desktop running a wayland session.

**Comment by glennw** [comment]
Closing for now - there's a workaround in the comment above, and it's not clear there is anything we can do in WR itself for this. Please re-open if there is work to be done in WR.
