### ISSUE TITLE
Messed up ui after exiting sleep.

### ISSUE THREAD

**Issue by zaxdo** [servo/webrender#2418]
On mac os 10.13.3 (17D47), firefox nightly 60.0a1 (2018-02-13) the whole ui is messed up after exiting sleep. 
The gpu is Intel HD Graphics 3000 384 MB.

![wtf-1](https://user-images.githubusercontent.com/6116464/36203433-9e34edd8-1198-11e8-970b-2affa9002221.png)

**Comment by glennw** [comment]
@jrmuizel @nical I wonder if this is more a gecko-related bug than WR? Do we need some kind of notification that the context was re-created and WR should recreate all resources, perhaps?

**Comment by glennw** [comment]
@jrmuizel @staktrace Any thoughts on the comment above?

**Comment by staktrace** [comment]
>  firefox nightly 60.0a1 (2018-02-13)

This is a month-old build. Please update.

**Comment by gw3583** [comment]
@zaxdo Any updates on whether this still occurs?

**Comment by zaxdo** [comment]
No longer able to reproduce

**Comment by gw3583** [comment]
Thanks for checking!
