### ISSUE TITLE
[RFC] Rework Frame / FrameBuilder organization

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#2419]
Currently the frame.rs / frame_builder.rs organization is a little confusing.

During display list flattening FrameContext creates both a FlattenContext and a FrameBuilder to assist in display list flattening. After flattening, which reaches between the FrameContext, the FlattenContext, and the FrameBuilder, the FlattenContext is destroyed and the product is the FrameBuilder (which is created at the beginning of this process). Later the FrameBuilder is combined with the FrameContext to produce a Frame.
 
It seems like we should start reworking these structs into ones that have separate concerns. An example of this might be three data structures: FrameContext, DisplayListFlattener, and FrameBuilder. The first step would be to move everything involved in flattening the display list in DisplayListFlattener, which will produce a FrameBuilder as a final product.

cc @kvark @glennw

**Comment by mrobinson** [comment]
Perhaps the right organization here is:
 * Document
 * FrameFlattener
 * FrameBuilder

It seems like a lot of the work of FrameContext is to simply pass through commands from Document to the ClipScrollTree which is a property of the FrameContext.

**Comment by glennw** [comment]
Sounds good to me - cc'ing @nical too since any changes here may overlap with what he is working on.

**Comment by mrobinson** [comment]
I think it is okay to close this now. We have Document, DisplayListFlattener, and FrameBuilder. Document calls DisplayListFlattener to create a FrameBuilder.
