### ISSUE TITLE
Box shadows tank performance on Samsung (but not Nexus) tablets?

### ISSUE THREAD

**Issue by larsbergstrom** [servo/webrender#242]
I'm working with the spheres.html demo. It gets ~60fps on an Android Nexus 9, but a Samsung Galaxy Tab S2 (with much better h/w and graphics chipset) only gets ~5fps, unless I remove:
`box-shadow: 0 0 5px 5px rgba(61, 178, 206, 0.2);`

**Comment by larsbergstrom** [comment]
I should add that, with `wr-stats` up, the issue seems to be time spend in "CPU (compositor)", which has a Mean time of 110+ms.

I'll try to root the tablet and get a profiler pointed at it next week.

**Comment by glennw** [comment]
This should be resolved now with the box-shadow caching changes. Please re-open if you can reproduce again.
