### ISSUE TITLE
Eliminate as many calls to Transform3D::inverse() as possible

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#2434]
This operation consistently appears in CPU profiles, but most web pages are not using 3D transforms. For example see the profiles generated in #2363. A general plan for this would be to extend TransformOrOffset to handle all the operations we need from Transform3D. For instance, `inverse()` would often turn into the creation of a new TransformOrOffset with negative offsets. We would then replace every Transform3D with TransformOrOffset. I have a feeling this would make `inverse()` disappear from the profile for most pages.

**Comment by glennw** [comment]
Another thing I noticed recently is that the ```is_2d``` method that determines if we have a transform or offset is very conservative. It doesn't use an epsilon so any floating point error that accumulates and results in 1.0000001, for example, makes it treat it as a transform. If we make this method apply an epsilon, we may end up with a lot more transforms that can be treated as offsets.

**Comment by mrobinson** [comment]
This was fixed by #2444 and the suggestion from @glennw is tracked in #2457.
