### ISSUE TITLE
"Port ps_blend to be a brush shader" regressions

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#2438]
Regression range: https://github.com/servo/webrender/compare/38df48c62c929a3603f3c6e6393c2be8f1c88903...d69bd28a055e2afb2ad234eea297dd45f9b4b4e5 ([webrender update](https://bugzilla.mozilla.org/show_bug.cgi?id=1437572))

- [x] [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1439059) | tab loading animation is broken ([Screencast](https://bug1439059.bmoattachments.org/attachment.cgi?id=8951824))

**Edit:**
Also affected:
- [x] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1439083) | https://vuetifyjs.com/en/components/buttons (click on a button, "become a patron" on the top left and on a menu item on the left)
    - [ ] Reopened: Black glitch ([screencast](https://bugzilla.mozilla.org/attachment.cgi?id=8955567), [about:support](https://bugzilla.mozilla.org/show_bug.cgi?id=1439083#c5))
- [x] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1440087) | http://www.senecacollege.ca/campuses/janelocation.html (click plus/minus to zoom the map)
    - [ ] Reopened: Black boxes ([screencast](https://bug1440087.bmoattachments.org/attachment.cgi?id=8955573))
- [x] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1439257) | https://www.facebook.com/search/str/Firefox/keywords_search ([example screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8952016))
  - [ ] Reopened: Black boxes ([screencast](https://bug1439257.bmoattachments.org/attachment.cgi?id=8955578))
- [x] https://web.whatsapp.com (file sending menu; not 100% sure)
- [x] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1440158) | Google Calendar animations show junk data (untested; not sure about the regression range, but it sounds similar to the other regressions)
- [x] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1440179) | https://www.akamai.com/us/en/cdn/ + [this theme](https://addons.mozilla.org/en-US/firefox/addon/quantum-lights-dynamic/) = drawn on chrome ([screenshot](https://bug1440179.bmoattachments.org/attachment.cgi?id=8952922))
  - [ ] Reopened: Black stripes ([screencast](https://bugzilla.mozilla.org/attachment.cgi?id=8955565), [about:support](https://bugzilla.mozilla.org/show_bug.cgi?id=1440179#c4))

**Edit 2:**
It seems that only the tab loading animation and whatsapp's file sending menu(?) are fixed by servo/webrender#2443.

-----
**Black boxes**  (Intel Sandybridge Mobile on Linux)

**Edit 3:**
I can't reproduce them, but the reporter confirmed the same regression range and that they aren't fixed in the try build from #2477.
- [ ] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1441025) | Byline/date text on [humphd.org](https://blog.humphd.org/what-happens-when-you-contribute-revisited/) shows bad text rendering and erroneous black background ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8953853))
  - [ ] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1442134) | Most of [chick-fil-a.com](https://www.chick-fil-a.com/) is black ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8955023) | [expected appearance](https://bugzilla.mozilla.org/attachment.cgi?id=8955024) | [wr-capture.7z](https://bugzilla.mozilla.org/attachment.cgi?id=8955025))
(His forward button is always black and has the same regression range.)
  - [ ] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1442386) | [Startpage SERP](https://www.startpage.com/do/dsearch?query=test) hamburger menu is visually corrupted ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8955286) | [expected appearance](https://bugzilla.mozilla.org/attachment.cgi?id=8955287))

  **Edit 4:**
  - [ ] [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1442828) | [Google News](https://news.google.com/news/?ned=us&gl=US&hl=en) hamburger menu, search box, app switcher visually corrupted ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8955735))
  - [ ] from another user: [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1442864) | Black boxes on YouTube and around icons ([screencast](https://bugzilla.mozilla.org/attachment.cgi?id=8955761), [about:support](https://bugzilla.mozilla.org/show_bug.cgi?id=1442864#c0))

**Comment by kvark** [comment]
I want all the issues to come in like this :heart_eyes:

**Comment by Darkspirit** [comment]
[WR @ b53cf7799a0f5861dfa928ee0ccc66e8d0b78758 try build](https://bugzilla.mozilla.org/show_bug.cgi?id=1440664#c10)
> mozregression --repo try --launch d115c4c11850c1b1d0b1c847eefc3d959efe0b12 --pref gfx.webrender.all:true

I can reproduce all remaining issues.

**Comment by glennw** [comment]
I'll investigate these this week, thanks for the detailed report!

**Comment by glennw** [comment]
I can repro the akamai bug locally here (even without the theme activated). I'll see if I can narrow that down to a small repro case. Hopefully fixing one of those will get the rest of them, this time.

**Comment by glennw** [comment]
This https://github.com/servo/webrender/pull/2477 fixes the akamai test case above. I haven't tested against the other cases yet, but I expect it will probably fix them all. I need to do a try run first to see if it breaks anything else.

**Comment by glennw** [comment]
I tested https://vuetifyjs.com/en/components/buttons and http://www.senecacollege.ca/campuses/janelocation.html with this change, and I didn't see any obvious issues.

**Comment by Darkspirit** [comment]
> mozregression --repo try --launch [b6987fdf2f5cad510d74179bb7196829fec1e00e](https://github.com/servo/webrender/pull/2477#issuecomment-369137962) --pref gfx.webrender.all:true
* vuetifyjs buttons + menu are fixed
* gmaps looks mostly fine. I saw another issue when Ctrl+Scrolling on it where my whole UI died. I will file a seperate bug for that.
* facebook is fixed
* akamai is fixed
-----
* google calender was possibly the same as the tab loading issue and is fixed. ([Fix range](https://bugzilla.mozilla.org/show_bug.cgi?id=1440158#c5))

-----

That webrender update had one more regression: https://bugzilla.mozilla.org/show_bug.cgi?id=1441025
I couldn't reproduce that. (He always had his own special text bugs.) Hopefully that is gone too, but I don't know.

**Comment by Darkspirit** [comment]
This is the last remaining regression:
I can't reproduce this, but the reporter confirmed the same regression range and that it isn't fixed in the try build from #2477.
[bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1441025) | Byline/date text on [humphd.org](https://blog.humphd.org/what-happens-when-you-contribute-revisited/) shows bad text rendering and erroneous black background ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8953853))

**Comment by Darkspirit** [comment]
Recently reported. Regression range is not confirmed yet, but this seems to be the same as the humphd bug:
[bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1442134) | Most of https://www.chick-fil-a.com/ is black ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8955023) | [expected appearance](https://bugzilla.mozilla.org/attachment.cgi?id=8955024) | [wr-capture.7z](https://bugzilla.mozilla.org/attachment.cgi?id=8955025) )
Note that the forward button in black in both bugs.

**Comment by Darkspirit** [comment]
I deleted my previous two comments. Things have been confirmed now:

I can't reproduce them, but the reporter confirmed the same regression range and that it isn't fixed in the try build from #2477.
* [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1441025) | Byline/date text on [humphd.org](https://blog.humphd.org/what-happens-when-you-contribute-revisited/) shows bad text rendering and erroneous black background ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8953853))
* [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1442134) | Most of [chick-fil-a.com](https://www.chick-fil-a.com/) is black ([screenshot](https://bugzilla.mozilla.org/attachment.cgi?id=8955023) | [expected appearance](https://bugzilla.mozilla.org/attachment.cgi?id=8955024) | [wr-capture.7z](https://bugzilla.mozilla.org/attachment.cgi?id=8955025))
 (His forward button is always black and has the same regression range.)

**Comment by Darkspirit** [comment]
The user who reported these "things are black" regressions still see issues on already fixed websites:
His screencasts: [akamai](https://bugzilla.mozilla.org/attachment.cgi?id=8955565), [gmaps](https://bug1440087.bmoattachments.org/attachment.cgi?id=8955573), [facebook](https://bug1439257.bmoattachments.org/attachment.cgi?id=8955578)
His Akamai issue is different from my initial report: Only the outer right part is drawn - in black - on his chrome. Hopefully this makes it easier for you to narrow down the source of this problem.

**Comment by Darkspirit** [comment]
Both users affected by black glitches have this graphics card: Mesa DRI Intel(R) Sandybridge Mobile

**Comment by glennw** [comment]
My guess is that Sandybridge drivers don't get updated much anymore, if at all. So we'll probably need to get hold of some hardware with that GPU, and find a workaround for what appears to be a driver bug.

**Comment by glennw** [comment]
@Darkspirit I think all the remaining issues were related to the Sandybridge GPU only, which is fixed by https://github.com/servo/webrender/pull/2530. Are you fine with closing this one off?

**Comment by Darkspirit** [comment]
:hourglass: [Awaiting confirmation](https://bugzilla.mozilla.org/show_bug.cgi?id=1441025#c25)

**Comment by Darkspirit** [comment]
:sunny: [Verified fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1441025#c27): All Sandybridge issues are gone.
