### ISSUE TITLE
Incorrect box-shadow rendering with large border radii and negative spread radius

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2467]
http://tests.themasta.com/box-shadow-playground/#blue_red_outset_64_77_200_200_140x140_60x60_60x60_140x140_275_81_3_-46

**Comment by glennw** [comment]
I tested this with latest nightly and it appears to be visually correct. It's possible this was fixed with the change to render box shadows as clip sources recently. @mstange could you confirm?

**Comment by Darkspirit** [comment]
Fix range: https://github.com/servo/webrender/compare/0da6c839b3a0e165f1115fb9fe286be7540c24ed...f3af2632723f62eb7973a87bfaece43a675cefb5
Fixed by #2487.

![screenshot_20180314_132131](https://user-images.githubusercontent.com/17962859/37402642-a6358f92-278c-11e8-9403-c5d5c9e849af.png)

**Comment by Darkspirit** [comment]
I am sorry. I found something. :-/
Nightly 61 x64 20180314102135 de_DE @ Debian Testing (KDE, Radeon RX480, 2560x1440)
![screenshot_20180314_221237](https://user-images.githubusercontent.com/17962859/37431603-ff40bdd4-27d5-11e8-8cf0-5622a25cf73d.png)

**Comment by glennw** [comment]
Hmm, this probably just needs an extra condition to skip the minimal rect computation if the corner radii overlap, or something like that.

**Comment by glennw** [comment]
@Darkspirit Could you describe how to reproduce that issue above?

**Comment by Darkspirit** [comment]
1a) Opening the test case with Nightly (fresh profile with gfx.webrender.all;true).
1b) Opening it with the latest wr-future-update [try build](https://bugzilla.mozilla.org/show_bug.cgi?id=1444946#c5): mozregression --repo try --launch 71bad4a9edb6ebe30ae86a3b70e563eebc5f9510 --pref gfx.webrender.all:true startup.homepage_welcome_url:"http://tests.themasta.com/box-shadow-playground/#blue_red_outset_64_77_200_200_140x140_60x60_60x60_140x140_275_81_3_-46"
2. zooming out to 90%, 80% and less.
3. Screenshot.

**Comment by glennw** [comment]
Ah, interesting - that's what I had tried but was not able to see the bug. When I adjusted the ```layout.css.devPixelsPerPx``` setting to 1.0 I am now able to see the bug. Thanks!
