### ISSUE TITLE
Deadlock when sending a transaction

### ISSUE THREAD

**Issue by asajeffrey** [servo/webrender#2478]
This is (I think) the cause of https://github.com/servo/servo/issues/20127

The problem is that WR serializes transactions by first serializing the payload. then the transaction https://github.com/servo/webrender/blob/d7735c7da9844775d4a3e6ec8b6cea25fb0b0486/webrender_api/src/api.rs#L897-L903

Since IPC send is blocking if the buffer is full, sending the payloads can block before the transaction is sent, causing deadlock.

cc @glennw @antrik @jdm @pcwalton

**Comment by asajeffrey** [comment]
The easiest fix would be to include the payloads in the `UpdateDocument` message, but presumably there's a good reason why they're using a separate channel!

**Comment by jrmuizel** [comment]
This seems like a mismatch between the semantics of ipc-channel and mpsc. Gecko isn't using ipc-channel so we don't run into this. ipc-channel will need to figure out what it wants it's semantics to be and we can work from there.

**Comment by asajeffrey** [comment]
Yes, but there's no easy fix to make ipc send non-blocking without spinning up a thread to do the sending, which is a bit expensive :/ Last time we looked at this, we ended up accepting that ipc send was blocking, hence https://github.com/servo/servo/blob/af92c06223a65fee3037b64b29ed9f089ef87310/components/constellation/constellation.rs#L80-L90

https://github.com/servo/servo/issues/14704

**Comment by asajeffrey** [comment]
On IRC, https://mozilla.logbot.info/servo/20180228#c14378689, @pcwalton confirms that the reason for transactions and payloads being on separate channels is to avoid extra serialization/deserialization.

**Comment by antrik** [comment]
Yeah, last time IPC blocking came up, I concluded that buffering receiver-side by forwarding to an MPSC channel is the most logical solution... It's a shame the existing router mechanism doesn't work with `IpcBytesReceiver` :-(

**Comment by asajeffrey** [comment]
@antrik I am tempted to change the API to make the distinction between possibly-blocking send and guaranteed-not-to-block send explicit. I appear to have to page this back in about once a year :)
