### ISSUE TITLE
Can we *please* remove the need to sort use statements alphabetically?

### ISSUE THREAD

**Issue by nical** [servo/webrender#2486]
This lint gets in my way all the time. I find it pointless, and whatever sorting the lint requires is neither of sublime text's two alphabetical line sorting methods.

**Comment by glennw** [comment]
I have no issue disabling it. I don't find it useful either.

**Comment by mrobinson** [comment]
It doesn't seem like a big issue to disable this lint to me.

**Comment by glennw** [comment]
This happened.
