### ISSUE TITLE
Wrench command line option to force X11

### ISSUE THREAD

**Issue by kvark** [servo/webrender#2494]
Glutin has a number of sever issues on Wayland, and RenderDoc doesn't even recognize a GL context we create there, so it's desirable for us to be able to force Glutin to go X11 route in Wrench (at least).

See https://docs.rs/glutin/0.13.0/i686-unknown-linux-gnu/glutin/os/unix/trait.EventsLoopExt.html#tymethod.new_x11

**Comment by mrobinson** [comment]
It seems for the moment, when XWayland is running, wrench should always just use X11. Do you think it is possible to do this automatically?

**Comment by kvark** [comment]
@mrobinson yes, that `new_x11` method would error if X11 is not available. We can just always try it first on Unix systems.

**Comment by glennw** [comment]
Yup, that will mean we don't need to set the env var that I've been using to force X11 for glutin. Sounds good to me.

**Comment by kvark** [comment]
@glennw wait, what was that environmental variable? Maybe we should just close the issue then, if it's as easy now.

**Comment by glennw** [comment]
See here for more info https://github.com/servo/webrender/issues/2395#issuecomment-364297849

**Comment by glennw** [comment]
Let's close this for now, given the workaround above. Please re-open if there is work to be done here.
