### ISSUE TITLE
"Mozilla’s Servo team joining Mixed Reality"

### ISSUE THREAD

**Issue by leeoniya** [servo/webrender#2506]
Hey guys,

Can anyone elaborate on what the recent VR announcement [1] means for Webrender, Pathfinder, etc? The blog post and related HN thread [2] has a respectable level of vague corporate strategy / restructuring speak but not much in the way of concrete "what's the future of Servo". It all has an eerily similar feel to the B2G wind-down, an OS i was excited to use someday : (

cc @glennw @kvark @mrobinson @pcwalton 

[1] https://blog.servo.org/2018/03/09/servo-and-mixed-reality/
[2] https://news.ycombinator.com/item?id=16555572

**Comment by larsbergstrom** [comment]
Hey, @leeoniya! No changes at present - we're still planning to continue to both have the Mozilla Servo staff work on Webrender and Pathfinder and the Firefox team investigate its use inside of that product. One big thing it does mean is that we're also looking really hard into in addition is whether we can also use Webrender & Pathfinder in VR and AR headsets!
