### ISSUE TITLE
Tab switching to Julia Evans' blog is slow

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2519]
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1444767

Here's a profile of a tab switch to https://jvns.ca/blog/2018/01/26/mac-memory-maps/ : https://perfht.ml/2twMA6Q

There's a composite that takes 132ms.
 - 33ms glBufferData
 - 35ms glTexSubImage3D
 - 37ms glGenerateMipmap
 - 12ms memmove inside glDrawElements

**Comment by jrmuizel** [comment]
So for the glGenerateMipmap, I'm wondering if we actually need to do this. High quality downscaling should actually be being handled on the Gecko side. @glennw was this not happening for some reason?

**Comment by glennw** [comment]
The mip map generation code was added for this bug (https://github.com/servo/webrender/issues/2023) and the bugzilla bug referenced in that. We can definitely consider removing it or adding a flag on each image to give Gecko explicit control over whether to generate mips, if that would help?

**Comment by mstange** [comment]
Here's another profile of slow `glGenerateMipmap`: https://perfht.ml/2Gv42LJ
Particularly interesting is the part where `_gleMakeMipmapDataNPOT` is doing the downscaling on the CPU.

I encountered this one after during the animation that plays after clicking the "Begin expedition" button on https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/variable-fonts/ .

**Comment by glennw** [comment]
I'm guessing from the name of that function your GPU / driver falls back to CPU mipmap generation if the size is non power of two?

**Comment by mstange** [comment]
Yes, that's what it looks like.

The image that's causing the slowness is the fallback item for a border image: the diagonal stripes on the side which cover the whole length of the page. Is this blob image rasterized in its entirety, or in tiles? Do we mipmap the entire thing or do we mipmap the tiles individually?

**Comment by mstange** [comment]
This is fixed now that mipmaps are disabled by default.
