### ISSUE TITLE
Scrolling simple pages is still slow on my integrated GPU

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2532]
I've been using WebRender on my main Firefox profile for a while now, but I've always had to pin my machine to the discrete GPU in order to get acceptable performance. With my integrated GPU, performance is still not good enough.

For example, scrolling [this github page](https://github.com/mstange/macos-compositing/blob/master/iosurface-compositing/OpenGLContextView.m#L61-L67) only gets around 30fps. Profile: https://perfht.ml/2tNf5gI
Most of the composite times in the profile are between 25ms and 36ms.

The compact profiler overlay shows:
FPS: ~30 fps, Backend: 1.26ms, Compositor: 1.73ms, GPU: 4.52ms.

I would expect the GPU time to show something higher here, if we end up blocking for 30ms on flushBuffer.

A big part of the problem is probably the fact that the Window Server considers our window to be transparent, and composites all the other windows underneath Firefox every time it draws the Firefox window. But this is an existing issue that we also have without WebRender, and scrolling with our old OpenGL compositor is noticeably smoother, it gets around 44 fps. (Which is still tragically bad...)

But 44fps = 22.7ms per composite. If we assume that non-WebRender creates 0ms of GPU work, and we add WebRender's 4.52ms of GPU work to that, we'd expect composites to take 27.2ms which would be 37fps. But in reality we only get 30fps. So there's still a part of the cost to WebRender that hasn't been accounted for.

**Comment by pcwalton** [comment]
Yeah, I've noticed this too. I wonder if using Core Animation can help us here. There's something really funny going on.

**Comment by glennw** [comment]
I know this is anecdata, but that page scrolls smoothly at 60fps on my integrated GPU on Linux. I have a mac here with a similar integrated GPU to the Linux laptop, so I can do some comparisons.

**Comment by pcwalton** [comment]
Yeah, whenever I've dug into these kinds of issues they've typically turned out to be annoying Mac-specific things that involve some form of synchronization mismatch between the app, Cocoa, the WindowServer, and the GL driver.

This is why I'm ready to give up and move to Core Animation :)

**Comment by glennw** [comment]
<img width="1680" alt="mac" src="https://user-images.githubusercontent.com/2350882/37494526-1caf411c-28a1-11e8-8839-f5f8dabb2040.png">

This is what I see on my mac. It *is* an HD630, but I wouldn't expect *that* much difference? On this machine it's easily holding 60 fps. ```about:support``` reports that the Intel GPU is active, and gfx.io says it is running in integrated mode, from what I can tell. Perhaps it's somehow switched to discrete and that's not reported in Gecko?

**Comment by pcwalton** [comment]
> Perhaps it's somehow switched to discrete and that's not reported in Gecko?

From my experience with gfxCardStatus.app, that seems unlikely. I think there's something strange going on here, probably graphics-chip-specific.

**Comment by mstange** [comment]
When I set the GL context as opaque, I get a frame rate between 55 and 60fps. (However, this breaks the tab bar vibrancy effect, and makes the window's top left and top right corners flicker between square and rounded.)

**Comment by mstange** [comment]
With the transparent context, and webrender enabled, going to about:blank and then loading https://jwatt.org/tmp/load-never-finishes.php in the tab has the same issue: The animated throbber should animate at 60fps but it only manages 30fps. Forcibly hiding the navigation toolbar increases the frame rate to ~38fps. So just drawing the browser chrome has some noticeable impact.

**Comment by gw3583** [comment]
@mstange Is this still relevant on your machine, or should we close this?
