### ISSUE TITLE
regression: Mac IOSurface of WebGL is not rendered

### ISSUE THREAD

**Issue by sotaroikeda** [servo/webrender#2546]
On my mac, WebGL was not rendered with the following link with firefox nightly. The problem might happen only with specific intel Mac.
  http://learningwebgl.com/lessons/lesson03/index.html

[Bug 1447245](https://bugzilla.mozilla.org/show_bug.cgi?id=1447245)

**Comment by sotaroikeda** [comment]
By [Bug 1447245 Comment 4](https://bugzilla.mozilla.org/show_bug.cgi?id=1447245#c4), the problem seemed to happen within the following change.
 https://github.com/servo/webrender/compare/4ccaede43b3944199f89a42f49093d93409c7f61...f5cf72c6196ec0a7743d9d626cdc360ec0c569a1

**Comment by sotaroikeda** [comment]
When I commented out the following in webrender/res/brush_image.glsl, the problem was addressed. The code seems to cause the problem.

>    color.a *= point_inside_rect(vUv.xy, vUvClipBounds.xy, vUvClipBounds.zw)

**Comment by glennw** [comment]
@sotaroikeda I have an idea what may cause this.

https://github.com/servo/webrender/blob/7767f53a43c20c33ea499d85d16d0e4e98c4043d/webrender/res/brush_image.glsl#L97

This code should disable the vUvBounds, but it will fail in the case that ```WR_FEATURE_TEXTURE_RECT``` is defined (which I believe is true for a Mac IOSurface).

What happens if you set that value to ```(0, 0, textureSize.xy)``` when ```WR_FEATURE_TEXTURE_RECT``` is enabled?

**Comment by glennw** [comment]
Unfortunately we have no test coverage for textureRect in wrench. We should add support for that.

**Comment by sotaroikeda** [comment]
> What happens if you set that value to (0, 0, textureSize.xy) when WR_FEATURE_TEXTURE_RECT is enabled?

It also addressed the problem!

**Comment by sotaroikeda** [comment]
> This code should disable the vUvBounds, but it will fail in the case that WR_FEATURE_TEXTURE_RECT is defined (which I believe is true for a Mac IOSurface).

We always use WR_FEATURE_TEXTURE_RECT for  IOSurface.

**Comment by glennw** [comment]
Fixed by #2558
