### ISSUE TITLE
Cookie Clicker displays all messed up

### ISSUE THREAD

**Issue by drbluetongue** [servo/webrender#2553]
http://orteil.dashnet.org/cookieclicker/
Using latest FF nightly (20/03/2018) on nVidea GTX970. Latest driver, Windows 10.
It should display the upgrades on the right hand side, but with webrender enabled it doesn't. It also flickers.

**Comment by kvark** [comment]
@drbluetongue seems to work for me on Intel/Linux. Could you double check? It's been almost a month.

**Comment by gw3583** [comment]
This also appears to be working for me in current nightly. @drbluetongue could you check if you're still seeing issues with this site?

**Comment by gw3583** [comment]
Closing since this appears to be working for @kvark and me. Please re-open if you're still having issues on your machine.
