### ISSUE TITLE
Tall shadow exceeds texture size limit, crashing renderer

### ISSUE THREAD

**Issue by heftig** [servo/webrender#2561]
With some help from @glennw I've found a probable cause for the crashes tracked in Firefox [bug 1442921](https://bugzilla.mozilla.org/show_bug.cgi?id=1442921).

WR tries to draw box shadows by stretching a 9-patch shadow mask across the entire shadow. For this it needs to calculate the minimum size of such a mask, so that blurring the corners doesn't affect the other patches. For this it only needs the border radii and the blur radius: https://github.com/servo/webrender/blob/277e35f7d6a7b39c59d02313aed5badbfb44e5e2/webrender/src/clip.rs#L166-L191

However, in the case that this 9-patch drawing is not applicable, WR falls back to drawing the entire shadow mask: https://github.com/servo/webrender/blob/277e35f7d6a7b39c59d02313aed5badbfb44e5e2/webrender/src/clip.rs#L205-L214 Note that if *either* `width` *or* `height` is smaller than the minimum, `Simple` mode is chosen.

The issue appears when one dimension is smaller than the minimum, but the other is large enough to exceed texture size limits. In my case I happened upon a shadow that was 400×25743 px in size, with 200 px corner radii and a 60 px blur. The latter result in a minimum size of 580×580 px.

WR will attempt to allocate an alpha texture for the entire shadow, which is clipped to the maximum 16384 px tall. Afterwards it runs into an assertion due to the size mismatch.

**Comment by heftig** [comment]
Possible solutions could be adding modes for one-dimensional 3-patch stretching or treating one-dimensional stretching as a degenerate case of two-dimensional stretching. As a stop-gap measure not rendering the shadows would be preferable to crashing.

**Comment by glennw** [comment]
Fix is https://github.com/servo/webrender/pull/2563

**Comment by heftig** [comment]
Applying the fix to Firefox indeed resolves the crashes, thanks!
