### ISSUE TITLE
Slow opacity when applied to fixed elements with scrolled clips

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2567]
https://bugzilla.mozilla.org/show_bug.cgi?id=1448509

This testcase is very slow to scroll on my machine and sometimes displays glitches: [Testcase](https://bug1448509.bmoattachments.org/attachment.cgi?id=8961980)

**Comment by kvark** [comment]
This is a very interesting performance issue from the GPU point of view:
  - we have around 200 draw calls, which is by itself not bad, but we should optimally aim for ~50.
  - our render task RGBA8 cache has 35 layers of size 2K by 2K. Each layer contains 2 clip masks.
  - the main brush blend call has 70 instances, each sampling from separate clip region but rendering to the full screen.

also cc @staktrace for being assigned to bugzilla's counterpart

**Comment by kvark** [comment]
The clip item for each element knows about the actual 100x100 size:
```
item: Clip((
    id: Clip(58, (1, 246)),
    image_mask: None,
), [
]),
clip_and_scroll: (
    scroll_node_id: Clip(1, (1, 246)),
    clip_node_id: None,
),
info: (
    rect: ((778, 338), (100, 100)),
    clip_rect: ((778, 338), (100, 100)),
    is_backface_visible: true,
    tag: None,
),
```
But the actual item refers to it by `scroll_node_id`:
```
item: Gradient((
    gradient: (
        start_point: (856, 0),
        end_point: (856, 845),
        extend_mode: Clamp,
    ),
    tile_size: (1712, 845),
    tile_spacing: (0, 0),
)),
clip_and_scroll: (
    scroll_node_id: Clip(58, (1, 246)),
    clip_node_id: None,
),
info: (
    rect: ((0, 0), (1700, 845)),
    clip_rect: ((0, 0), (1700, 845)),
    is_backface_visible: true,
    tag: None,
),
```
So the computed local clipping rect ends up not including those? cc @mrobinson

**Comment by mrobinson** [comment]
@kvark I'm not sure I understand the question exactly. A None value in the clip_node_id means that the item will be both scrolled and clipped by the scroll_node_id, so I think the None there is a red herring. It could be that the clip isn't being applied properly at some other point in WebRender though.

**Comment by kvark** [comment]
@mrobinson essentially, my high level question was: why do we render the full-screen clip mask per element given we know that it should be within 100x100 rectangle? Judging from your answer, this is just a bug on our side (not taking all the code paths into account properly when computing the screen bounding rect).

**Comment by mrobinson** [comment]
@kvark It sounds like you are right. To be honest, I'm not sure why masks are even generated at all. Perhaps this is something to do with the gradient implementation?

**Comment by mstange** [comment]
The original page on which I encountered this issue used an image. I replaced the image with a gradient when I reduced the testcase, so that it wouldn't require an external file. I think this problem should still be reproducible if you replace the gradient with an image again.

**Comment by kvark** [comment]
@glennw what happens here is that the picture spawned by a composite (opacity filter) stacking context doesn't take the clipped bounding box of it's children for determining it's truly required size.
