### ISSUE TITLE
Support processing the shaders at build time

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2580]
Shader compilation time is a big problem on all platforms. We hit this every time you open a new window.

On Windows I'm hoping that we can precompile the shaders to D3D bytecode. This seems to mostly fix the problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1391159#c8.

On Mac we don't have any lower level ir and so need to use glsl. We also don't currently have a good way to reuse shaders across different windows. (This can be fixed by switching to CoreAnimation because we can bind the gl context to different IOSurfaces) I'm hoping that using a glsl optimizer will be sufficient to get things under control here.

On Linux the situation is similar to Mac, but we should be able to use glProgramBinary to reuse the shader between windows.

**Comment by glennw** [comment]
It sounds like Windows support required is to do the D3D bytecode compilation at build time, and then use glProgramBinary at startup.

**Comment by sotaroikeda** [comment]
It seems not simple to precompile shaders to D3D bytecode on windows. ANGLE translator has a capability to translate GLSL to HLSL. But ANGLE modifies the translated HLSL source before compiling to bytecode.  It is done by [DynamicHLSL::generateShaderLinkHLSL](https://dxr.mozilla.org/mozilla-central/source/gfx/angle/checkout/src/libANGLE/renderer/d3d/DynamicHLSL.cpp#452). Actually, The following info are used to modify the HLSL source.
- RendererD3D::getWorkarounds()
- RendererD3D::getVertexComponentType()
- RendererD3D::getVertexConversionType()
- RendererD3D::getMajorShaderModel()
- RendererD3D::getShaderModelSuffix()

ProgramBinary generation is done by [ProgramD3D::save](https://dxr.mozilla.org/mozilla-central/source/gfx/angle/checkout/src/libANGLE/renderer/d3d/ProgramD3D.cpp#1152).

I quickly created related ANGLE parts diagrams.
https://github.com/sotaroikeda/firefox-diagrams/blob/master/gfx/gfx_ANGLE_ProgramD3D_61.pdf
https://github.com/sotaroikeda/firefox-diagrams/blob/master/gfx/gfx_ANGLE_ShaderD3D_61.pdf

**Comment by sotaroikeda** [comment]
And ANGLE ProgramD3D::save() saves device id to ProgramBinary. Then it might not a good idea to use ProgramBinary.
https://dxr.mozilla.org/mozilla-central/source/gfx/angle/checkout/src/libANGLE/renderer/d3d/ProgramD3D.cpp#1152

**Comment by jrmuizel** [comment]
FWIW, here's Chrome's implementation of the shader disk cache: https://cs.chromium.org/chromium/src/gpu/ipc/host/shader_disk_cache.cc?q=disk_cache+shader&sq=package:chromium&l=99

**Comment by sotaroikeda** [comment]
Yea, it helps to figure out necessary capabilities.

**Comment by gw3583** [comment]
I think this is all in place now - the bugzilla bug is marked fixed. Please reopen if there's further work relevant to this bug, or perhaps open new bugs for specific platform fixes?
