### ISSUE TITLE
Box-shadow has wrong corner radius in this testcase

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2581]
It looks correct without a blur, but as soon as you add 1px of blur, things start to go wrong.

http://tests.themasta.com/box-shadow-playground/#blue_red_outset_0_1_265_265_250x250_0x0_0x0_250x250_350_0_1_-80

This is also broken in non-webrender Firefox, but in different and exciting ways.

**Comment by pcwalton** [comment]
Still broken.

<img width="1029" alt="screen shot 2018-09-17 at 1 38 36 pm" src="https://user-images.githubusercontent.com/157897/45649042-0b6b6280-ba7f-11e8-8bd4-8a52c482efaf.png">

**Comment by mstange** [comment]
After the fix, this shadow is still a lot smaller than if you give it zero blur.

**Comment by pcwalton** [comment]
OK, reopening so I can investigate.

**Comment by mstange** [comment]
(In the box-shadow-playground tool, you can manipulate the blur radius by dragging the corners of the red boxes in the left half of the screen.)

**Comment by mstange** [comment]
Oh, maybe the build I'm running doesn't have this fix yet.

**Comment by mstange** [comment]
Yes I was. This is indeed fixed. Thanks!
