### ISSUE TITLE
Sometimes preserve3d items don't get drawn

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2587]
I have two captures that show the difference. @kvark can debug when he gets a chance.

**Comment by gw3583** [comment]
@jrmuizel Do you have any information / test cases for this bug?

**Comment by jrmuizel** [comment]
I had a test case derived from http://snapsvg.io/demos/#game. That page works better than it did. I still see a flicker sometimes on one of the faces of the dice and there seem to be seems that you can see through.

**Comment by kvark** [comment]
I'm still seeing occasional flicker on the dice rotating, even after #3093
This is not a precision issue, it's something else.

**Comment by gw3583** [comment]
@jrmuizel @kvark Still relevant?

**Comment by jrmuizel** [comment]
This has been fixed
