### ISSUE TITLE
Rendering glitches/flickering for rotating element

### ISSUE THREAD

**Issue by Zirro** [servo/webrender#2590]
This [test case](https://bug1449904.bmoattachments.org/attachment.cgi?id=8963545) includes an element with border-radius and a dotted border. When its rotated using the rotate()-transform in an animation, significant rendering glitches appear.

I can reproduce this in Firefox Nightly with WebRender enabled, as well as the latest nightly build of Servo. This is on a MacBook Pro (Early 2013) with Intel HD Graphics 4000 and a NVIDIA GeForce GT 650M, with both GPUs displaying the glitches.

Here's a screen recording showing the issue (caution - includes rapid flickering): https://bug1449904.bmoattachments.org/attachment.cgi?id=8963546

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1449904

**Comment by Darkspirit** [comment]
![screenshot_20180329_151246](https://user-images.githubusercontent.com/17962859/38091243-41b9d91c-3365-11e8-9b90-65b187a231f2.png)
Regression range: https://github.com/servo/webrender/compare/e3dd85359580074f4ca4a554d9a3c85779f8de64...b7714b1d4348c00682b5643ea0e3f0b15adaeda5
Partial fix range: https://github.com/servo/webrender/compare/1142dfc557c319119a5117450718c5b67a93cb9f...a422f907be948b92bf5c7003a01f7744391a795e

[Screencast](https://bugzilla.mozilla.org/attachment.cgi?id=8963567): main profile, dark theme: It looks like a black(?) rotating rectangle is drawn on the penultimate tab, hiding parts of the tab title.
The reporter's screencast shows something similar on the right side of the location bar.

**Comment by Zirro** [comment]
This case looks like another manifestation of the same issue, while showing the cause more clearly: https://rawgit.com/Zirro/03f0e2d19b087db29b1f069e014e3ee5/raw/0f32535d70e56185e01e4f9be860afc4dc4fec79/fireworks.html

The glitches seem to appear when the transformation extends the element outside the viewport. In the original test case, the flickering boxes don't show up if the element is given some margin.

**Comment by Zirro** [comment]
I can no longer reproduce these issues in either of the test cases with latest WebRender 🎉
Presumably due to the merging of https://github.com/servo/webrender/pull/2795.
