### ISSUE TITLE
Redraw bugs during scrolling, after async scene building landed

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2624]
https://bugzilla.mozilla.org/show_bug.cgi?id=1446626

 1. Go to https://github.com/devtools-html/perf.html/projects/4
 2. Move your mouse into the "In Sprint" box, between the left edge of the box and the left edge of the white cards within the box.
 3. Quickly scroll up and down.

During scrolling, sometimes parts of the cards' white backgrounds are missing.

This is a regression from #2362 and was not fixed by #2568.

cc @nical

**Comment by gw3583** [comment]
Corresponding bugzilla bug is fixed.

**Comment by mstange** [comment]
It was fixed by #2859.
