### ISSUE TITLE
Run rawtests in CI

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2632]
It looks like we somehow forgot to do this.

**Comment by jrmuizel** [comment]
Also, when the notifier stuff changed it looks like they got racy

**Comment by jrmuizel** [comment]
This was broke by #1904. Previously rawtest and perf would only draw when receiving a new_frame_ready() event. Now they draw when getting a wakeup event.

**Comment by gw3583** [comment]
This is done, as far as I know. Please re-open if there's more work to do here.
