### ISSUE TITLE
Background leaking through at edges of element

### ISSUE THREAD

**Issue by Zirro** [servo/webrender#2658]
In some cases when border-radius or a transformation is applied to an element, the background seems to leak through the edges and make it visible against surrounding shapes like a box-shadow.

I can reproduce it in Servo and Firefox Nightly with WebRender enabled. I also see a less pronounced version of it in Firefox with WebRender disabled, but not in other browsers on the same machine. The following test case includes three variations:

https://cdn.rawgit.com/Zirro/c393b61ab9833ed7bc895f2f1f374bc2/raw/906589b3c804134845a4422009e0b5d6c032cbe9/background-leaks.html

<img width="952" alt="background-leaks-screenshot" src="https://user-images.githubusercontent.com/3169418/38738906-9cdac0ac-3f33-11e8-96d6-e1eb2cf7353a.png">

**Comment by gw3583** [comment]
This looks the same for me in Gecko without WR as it does with WR (with some very small anti-aliasing differences). Could you confirm if they look the same to you? If so, it would probably be best to close this and open a general bug in bugzilla about this.

**Comment by Zirro** [comment]
Closing this since the underlying issue also shows without WR enabled, per the comment above. It seems to be covered by https://bugzilla.mozilla.org/show_bug.cgi?id=1417750 and https://bugzilla.mozilla.org/show_bug.cgi?id=1084604 on Bugzilla.
