### ISSUE TITLE
Filtered elements are clipped if their bounds change via animated properties

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2668]
https://bugzilla.mozilla.org/show_bug.cgi?id=1454763

\>> [Testcase](https://bug1454763.bmoattachments.org/attachment.cgi?id=8968651) <<

In this testcase, the rounded border is sometimes not rendered completely. The testcase applies a filter to a stationary element which wraps an element whose transform is animated. The bounds of the filter surface are dependent on the animated property.

**Comment by glennw** [comment]
I'll look at this today.

**Comment by Darkspirit** [comment]
I think this is a downstream regression.

**Comment by mstange** [comment]
The downstream change has exposed an existing WebRender bug.
