### ISSUE TITLE
BlendMode::SubpixelWithBgColor text rendering should still be allowed inside transparent groups

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2670]
With the default theme on Mac, overflowing tab titles no longer use subpixel AA. However, the text in the tab titles uses a font smoothing background color, and `BlendMode::SubpixelWithBgColor` is able to render onto transparency without any problems. So I think we need to adjust the logic that disables subpixel AA in this case, so that SubpixelWithBgColor text blending is still allowed.

**Comment by glennw** [comment]
Fix is https://github.com/servo/webrender/pull/2701.
