### ISSUE TITLE
Intermittent async-scrolling/bg-fixed-in-css-filter.html == async-scrolling/bg-fixed-in-css-filter-ref.html | image comparison, max difference: 1, number of differing pixels: 59

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2675]
This is a high-frequency intermittent in gecko CI, which was introduced by #2651

https://bugzilla.mozilla.org/show_bug.cgi?id=1454794 has details. A sample reftest-analyzer link is https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=https://queue.taskcluster.net/v1/task/VCHCkoRZQNShc48pyTwWRw/runs/0/artifacts/public/logs/live_backing.log&only_show_unexpected=1

For now I'm going to fuzz it on the gecko side but we should fix it properly too.

**Comment by staktrace** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1454817 appears to be the windows equivalent. Same test, different set of pixels.

**Comment by gw3583** [comment]
Closing this since it's tracked by bugzilla now.
