### ISSUE TITLE
Scrolling on Twitter is slow after mousing over some links

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#268]
STR on Mac:
1. Load http://twitter.com/pcwalton with my upcoming patch to fix clears applied
2. Enter full screen mode by clicking the green traffic light button
3. Scroll, observe smoothness
4. Mouse over links rapidly
5. Scroll, observe jank
6. Keep scrolling; eventually the scroll will turn smooth.

The CPU time continues to spike during the janky scrolling, which leads me to believe this is not some weird driver issue.

**Comment by glennw** [comment]
This seems to work OK for me on Linux + Mac. Please re-open if you can still reproduce.
