### ISSUE TITLE
WebRender has a hard time on https://www.digitalocean.com/

### ISSUE THREAD

**Issue by nical** [servo/webrender#2684]
Go to https://www.digitalocean.com/ and scroll down.

**Comment by Gankro** [comment]
Appears to be Bugzilled as: https://bugzilla.mozilla.org/show_bug.cgi?id=1456555

**Comment by mstange** [comment]
Also as https://bugzilla.mozilla.org/show_bug.cgi?id=1454810

**Comment by glennw** [comment]
From a quick profile, some issues with clips performance around halfway down the page. At the bottom of the page there are a number of large radial gradients which are very slow, for some reason. The rest of the page runs fine. We'll need to investigate those two parts of the page in more detail to see what is going on.

**Comment by glennw** [comment]
Oh, interesting. In the middle of the page the GPU time is not a problem at all. There are huge times in the backend thread (~28ms) and the display list timing code (~15ms). Are these blob related, perhaps?

**Comment by glennw** [comment]
(The primitive count is quite low - only ~300 primitives, so it must be something unusual for the backend thread / DL time to be that high).

**Comment by Gankro** [comment]
I believe radial gradients are known to be very slow in blobs

**Comment by jrmuizel** [comment]
The big problem with this page is the blob image. The main solution to this problem is async blobs images.

**Comment by jrmuizel** [comment]
The blob image is mostly blocked on SVG filtering. Once we support SVG filters in WebRender we'll be able to run this on the GPU which should help a lot.

**Comment by nical** [comment]
They changed the page and we have plenty of blob performance items on file, closing.
