### ISSUE TITLE
Having images swicth between non-tiled and tiled does not work. 

### ISSUE THREAD

**Issue by nical** [servo/webrender#2686]
We support updating the size of an image, and automatically tile very large images, but we currently assert that the tiled-ness we see when doing tile decomposition during scene building matches the one we see when resolving texture cache requests during frame building. The thing is image updates (that can change the size) can happen between the two in some cases.

This should be fixed by the work of moving tile decomposition to frame building but I'm filing this because it's currently causing some crashes.

**Comment by nical** [comment]
cc @staktrace

**Comment by staktrace** [comment]
(Related bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1455387)

**Comment by gw3583** [comment]
The tile-decomposition-in-frame-building has landed, and the associated bugzilla bug is resolved fixed.
