### ISSUE TITLE
Wrench DPI scaling is wrong when loading capture

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2697]
I have taken a WR capture on HiDPI Mac. Loading the capture in wrench shows a number of problems:

 1. The window is twice the width that it should be.
 2. Only the top left quadrant of the scene is rendered, the rest of the wrench window is white.
 3. The vertical offset is wrong - parts at the top are clipped away, and the rendered scene moves down if I reduce the height of the window.

**Comment by kvark** [comment]
The OSX hiDPI story has recently been fixed in `winit`, so it might be fixed when we update to latest `glutin/winit`.
