### ISSUE TITLE
drop-shadow() filter is not updated in response to off-main-thread animations

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2721]
https://bugzilla.mozilla.org/show_bug.cgi?id=1458661

[Testcase 1](https://bug1458661.bmoattachments.org/attachment.cgi?id=8972679)
[Testcase 2](https://bug1458661.bmoattachments.org/attachment.cgi?id=8972680)
[Testcase 3](https://bug1458661.bmoattachments.org/attachment.cgi?id=8972944) (works correctly but might still be worth confirming with once the bug is fixed)

In these testcases the black shadow lags behind. In the second testcase, the shadow gets squeezed and stretched in funny ways as the bounds of the filter input change.

**Comment by mstange** [comment]
So it looks like the shadow rendering is updated when the size of the input changes, but not when only the position of the input changes. And when the size of the input changes, the updated shadow is drawn into a rectangle that was computed based on the non-updated bounds.

**Comment by gw3583** [comment]
Fix is https://github.com/servo/webrender/pull/2799.
