### ISSUE TITLE
 Blue vertical line on Github.com

### ISSUE THREAD

**Issue by klausenbusk** [servo/webrender#2729]
As reported here https://bugzilla.mozilla.org/show_bug.cgi?id=1456514 and tested with the latest Servo nightly on Linux. I'm seeing a blue vertical line on:
https://github.com/servo/webrender 
![image](https://user-images.githubusercontent.com/1080056/39627315-c6b03920-4fa5-11e8-811a-0d00cd6bbcb0.png)
https://github.com/servo/webrender/issues/2706
![image](https://user-images.githubusercontent.com/1080056/39627351-e5fd0e0c-4fa5-11e8-8521-f463b140674f.png)
https://twitter.com/firefoxnightly
![image](https://user-images.githubusercontent.com/1080056/39627375-f1eb3cf2-4fa5-11e8-86b8-190ec3781f4c.png)

I assume it is some kind of driver issue, as starting Firefox or Servo with `LIBGL_ALWAYS_SOFTWARE=true` "solve" the issue.

```
$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD SUMO (DRM 2.50.0 / 4.16.4-1-ARCH, LLVM 6.0.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.0.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by klausenbusk** [comment]
After a bit of trail and error I ended up with the following small HTML file, which cause the issue on my system (tested with latest Servo nightly).
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <style>
      blockquote {
        border-left: 10px solid white;
      }
    </style>
  </head>
  <body>
    <blockquote>
    foo
    </blockquote>
  </body>
</html>
```
![image](https://user-images.githubusercontent.com/1080056/39628857-a2dc7842-4faa-11e8-86bf-89415d76aaaf.png)

**Comment by kvark** [comment]
Can't repro with either Firefox or Servo at revision 7af725bff0faacadb6f6e4ff4a88157d8fed0562
Would be great to have a capture taken from this (Ctrl+Shift+3, see https://github.com/servo/servo/pull/20315)

**Comment by klausenbusk** [comment]
> Would be great to have a capture taken from this (Ctrl+Shift+3, see servo/servo#20315)

Nothing happens if I press Ctrl+Shift+3, but taking a screenshot in Firefox with Firefox screenshot I get the expected result:
![screenshot_2018-05-04 screenshot](https://user-images.githubusercontent.com/1080056/39630071-8268e4d4-4fae-11e8-96a6-15c307539798.png)

**Comment by klausenbusk** [comment]
> Would be great to have a capture taken from this (Ctrl+Shift+3, see servo/servo#20315)

Currently broken on Linux/win per: https://github.com/servo/servo/issues/20746#issuecomment-389300407

**Comment by nkestrel** [comment]
The blue left border just recently changed to pink for me on latest Nightly with Radeon HD after the webrender update ([Bug 1461342](https://bugzilla.mozilla.org/show_bug.cgi?id=1461342)). 

Test case:
https://bugzilla.mozilla.org/attachment.cgi?id=8975316

Capture:
https://we.tl/7JC7Ju4Xcx

**Comment by klausenbusk** [comment]
> The blue left border just recently changed to pink for me on latest Nightly with Radeon HD after the webrender update (Bug 1461342).

I can confirm that.

**Comment by nkestrel** [comment]
This is fixed for me on latest Nightly since [Bug 1463416](https://bugzilla.mozilla.org/show_bug.cgi?id=1463416) landed.

**Comment by klausenbusk** [comment]
> @klausenbusk could you check if it's fixed for you as well?

I can confirm that issue is fixed in Nightly but I still see the issue in the latest servo nightly.

**Comment by kvark** [comment]
I guess Servo nightly is not updating the WR dependency as often.

**Comment by gw3583** [comment]
Updating WR in Servo is currently blocked on a rustc compiler bug :tada:

**Comment by gw3583** [comment]
There's a pending WR update PR for Servo here https://github.com/servo/servo/pull/20892.

I'll close this for now, since it appears to be fixed in WR. Please feel free to re-open if you see again.
