### ISSUE TITLE
Linux task cluster CI seems broke

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2734]
All of my jobs fail now:
https://tools.taskcluster.net/groups/QEj19Fv5SyCy55iYCAjLIw

@staktrace blames intermittent network problems.

**Comment by staktrace** [comment]
https://mozilla.logbot.info/taskcluster/20180504#c14712962

At least one bad worker has been terminated. So tell bors to retry, and maybe complain in #taskcluster if you see it again?

**Comment by gw3583** [comment]
This seems resolved. We can re-open if it occurs again.
