### ISSUE TITLE
Rasterize blob images during scene building

### ISSUE THREAD

**Issue by nical** [servo/webrender#2759]
Blob images can some times take forever to rasterize and blocking scrolling on it looks bad.

There is a variety of things we can do to improve this but I'll focus here on the short-term solution that can be improved upon later: During scene building, clip blob images against the display port (which is relatively small at the moment) and rasterize them directly. This should get rid of the majority of cases where we rasterize blobs during frame building.

To do this we need clips and transforms, so I'll split the clip scroll tree update into the part that resolves transforms/clips and the part that makes gpu cache requests so that the former can be done in the scene builder to figure out blob images.
Then we'll see how things go from there.

**Comment by nical** [comment]
> The visible rect gets computed and stored on each display item during display list building. We can send the visible rect of the outer display item to webrender [...]

Nice! sounds like we could clip the bounds of the image display items to this visible rect. you are referring to nsDisplayItem::mVisibleRect, right?

**Comment by gw3583** [comment]
@nical Can this be closed now?
