### ISSUE TITLE
async scene building: cache collisions from reused picture ids

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2769]
On my linux machine with async-scene-building, if I open this in one tab:

```
data:text/html,<div style="width: 400px;text-shadow: 1px 1px 2px green;">Hello there my name is alexis and this is my amazing test-case for shadows being broken under async scene building
```

and then open this in a second tab (identical except the shadow is red):

```
data:text/html,<div style="width: 400px;text-shadow: 1px 1px 2px red;">Hello there my name is alexis and this is my amazing test-case for shadows being broken under async scene building
```

the second tab has a green shadow, as it is using the cached shadow picture (really the final blur picture) from the other tab.

The issue is that async scene building repeatedly creates new `FrameBuilder::empty()`'s, resetting the picture id to 0 *and* that the picture cache doesn't factor in scene/document id's.

**Comment by kvark** [comment]
To clarify, our render task caching is susceptible to the following key collisions:
  - between different documents
  - between different epochs (counts of the scene rebuilds) of the same document

Could be trivially solved by tracking the document epoch and adding it as well as the document ID itself to the cache task key.

**Comment by Gankro** [comment]
bugzilled https://bugzilla.mozilla.org/show_bug.cgi?id=1458177

**Comment by gw3583** [comment]
Ah, I had not realized there was a frame builder per document. A simple solution might be to just make it a global atomic u64 that we use to get the next picture id?
