### ISSUE TITLE
WebRender forgets about the contents of blob images without updating the dirty rect

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2771]
STR:
1. draw a blob image
2. draw the blob image offscreen
3. update the blob with a small dirty rect and draw it on screen
In the rendering request for 3. the dirty rect is that of the update, but WebRender has forgotten about the rest of the content of the blob image.

There's a raw test that shows off this behaviour here: https://github.com/jrmuizel/webrender/commit/c85dab43518ecccdc2f74e23c74857920ee1ffae

**Comment by jrmuizel** [comment]
Maybe we need to hook up something like the eviction_notice stuff to know when to reset the dirty_rect?
@glennw or @nical thoughts?

**Comment by jrmuizel** [comment]
Note: this is causing https://bugzilla.mozilla.org/show_bug.cgi?id=1463792

**Comment by kvark** [comment]
@jrmuizel thoughts have been expressed in #2774 :D
