### ISSUE TITLE
Multiple Renderers on the same thread?

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#2782]
### Context
I'm working on porting WebRender to be the underlying graphics renderer for a UI framework I contribute to.
I'm at the point where I need to add support for pop ups (Drop downs, Context Menus, etc). The framework implements these as separate top level Windows.

### Problem
The popup windows share the same UI thread as the main window.
What I'm trying to do is spawn a `Renderer` for each Window, but I'm hitting an assert `profiler.borrow().is_none` in [thread_profiler](https://github.com/glennw/thread_profiler/blob/94fff1d66adabf84c38f3ecf3414e998a75f470e/src/lib.rs#L89)

This is because WR calls `register_thread_with_profiler` in `Renderer::new(..)` [here](https://github.com/servo/webrender/blob/52ba1165be4f69b84cbd35fdcf8841bff28822fa/webrender/src/renderer.rs#L1518)

Is it possible to have this assertion relaxed and just bail out if the thread has already been registered?

**Comment by nical** [comment]
Gecko uses the same thread for all of its renderers, so this should work for you as well. The assertion you pointed to doesn't seem to exist on WebRender's master branch, is there a reason you are referring to Glenn's fork instead of the main repository?

**Comment by nc4rrillo** [comment]
Updating WR to master took care of this for me. 🤷‍♂️
