### ISSUE TITLE
Corrupted rendering after suspend on Linux.

### ISSUE THREAD

**Issue by nical** [servo/webrender#2792]
There have been several reports of rendering being corrupted when resuming from suspended state on linux. I believe there is a bugzilla entry for that but I haven't found yet.

gbs pointed out on irc that for nvidia with glx there is an extension which would be helpfull to address the issue: https://www.khronos.org/registry/OpenGL/extensions/NV/NV_robustness_video_memory_purge.txt

The best would probably be to add an api to clear all gpu-side caches and let gecko's render thread query the extension to detect gpu memory purges.

**Comment by kvark** [comment]
The WR API command [ClearCaches](https://github.com/servo/webrender/blob/5e4f257d9f3cdb5691ac62f3affe2e9189d66447/webrender_api/src/api.rs#L579) is already there, just need to be called by Gecko on resume.

**Comment by gw3583** [comment]
Is there WR work to be done here or can this be closed?

**Comment by nical** [comment]
Let's wait until there is a Bugzilla entry for this before closing otherwise we'll lose the info. I'll try to remember to do that next time I'm in front of a computer.

**Comment by nical** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1469496
