### ISSUE TITLE
Reduce the amount of extra work needed for hit testing

### ISSUE THREAD

**Issue by kvark** [servo/webrender#2807]
#2797 enabled rendering on async scene rebuilds. AFAIK, hit-testing should only need the results of `build_layer_screen_rects_and_cull_layers` function, and don't actually care about the batches and render task graph. Thus, we can save a few cycles here.

cc @staktrace @nical @gw3583

**Comment by staktrace** [comment]
That seems reasonable to me. I thought it would be complicated to extract the bits of the render process that hit-testing needs, but if it's straightforward then that would be a nice optimization.

And just to be explicit, we we need to ensure that this "slimmed down render" at the very least does the sampling (currently [here](https://github.com/servo/webrender/blob/c1f0e07f9639b3b9bc997314a25aa8fff256512f/webrender/src/render_backend.rs#L1022), applies those messages (which are going to be `ScrollNodeWithId` and `AppendDynamicProperties` messages), before going on to update the clip scroll tree and rebuild the hit-tester.

**Comment by staktrace** [comment]
I wrote a patch for this and on the firefox talos perf tests it improved perf by a bit on displaylist_mutate but regressed tresize a bunch, so I need to look into it a bit more.

**Comment by staktrace** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=2ca252df2d41df06d36a1c04843f3b6d71bce09a is the try push, and https://treeherder.mozilla.org/perf.html#/compare?originalProject=mozilla-central&newProject=try&newRevision=2ca252df2d41df06d36a1c04843f3b6d71bce09a&framework=1&filter=qr&showOnlyImportant=1&selectedTimeRange=172800 is the perf delta

**Comment by staktrace** [comment]
Rebased: https://treeherder.mozilla.org/#/jobs?repo=try&revision=ca9520ec0b1ea14f97f7260d58ff5ccfd7860200

Still hurts tresize quite a bit on windows: https://treeherder.mozilla.org/perf.html#/compare?originalProject=mozilla-central&newProject=try&newRevision=ca9520ec0b1ea14f97f7260d58ff5ccfd7860200&framework=1&showOnlyImportant=1&selectedTimeRange=172800

**Comment by jrmuizel** [comment]
Do we know why?

**Comment by staktrace** [comment]
When I investigated it previously I came to the conclusion that the first render happens before the vsync and makes the second render (post-vsync) cheaper. Visualization is in https://bugzilla.mozilla.org/show_bug.cgi?id=1478566#c9

I'm not sure if the same thing is still happening now; I can check to see if it is.

**Comment by staktrace** [comment]
I looked at it again today and found a number of different issues. But the important one was bug 1479075. I'll do another talos run with the fix for that.

**Comment by staktrace** [comment]
Try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=393c31424b29530c20aa39d655541c787f4b6cef

Perf: https://treeherder.mozilla.org/perf.html#/compare?originalProject=mozilla-central&newProject=try&newRevision=393c31424b29530c20aa39d655541c787f4b6cef&framework=1&showOnlyImportant=1&selectedTimeRange=172800

The regressions are all from bug 1479075 so that's good.

**Comment by staktrace** [comment]
This should be fixed by #3052 (which got reverted and relanded as #3092)

**Comment by kvark** [comment]
Fixed by #3092
