### ISSUE TITLE
First call to set_output_document has no effect

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#2820]
The frame output example stopped working some time ago. 

The issue seems to be that frame messages (which contain `EnableFrameOutput` are processed after the call to `build_scene` resulting in an empty list of `output_pipelines` getting passed to the `FrameBuilder`.

Moving the processing of frame messages to before the call to `build_scene` fixes the issue. There is a separate issue where nothing is rendered in the example.

**Comment by hgallagher1993** [comment]
I'll pick this up :+1:

**Comment by hgallagher1993** [comment]
This can be closed :+1:
