### ISSUE TITLE
Gradient rendering disconuity

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2833]
WR bug for https://bugzilla.mozilla.org/show_bug.cgi?id=1459195

STR: Load https://bug1459195.bmoattachments.org/attachment.cgi?id=8975631 and scroll down to see the gradient. It should be a smooth gradient, but in WR it has a discontinuity on the right side halfway down. On mac the top left corner is also a big flat rect but I suspect that's the same as #2773.

**Comment by staktrace** [comment]
After #2824 this renders fine on Windows but on mac the entire thing is just one black rect.

**Comment by gw3583** [comment]
Marked fixed in bugzilla.
