### ISSUE TITLE
Support tiled clip images

### ISSUE THREAD

**Issue by kvark** [servo/webrender#2852]
When we request image for a clip source that is an image, we never supply a tile:
```rust
                ClipSource::Image(ref mask) => {
                    resource_cache.request_image(
                        ImageRequest {
                            key: mask.image,
                            rendering: ImageRendering::Auto,
                            tile: None, // <---------- HERE
                        },
                        gpu_cache,
                    );
                }
```
This breaks the resource cache expectations that a tiled image would only be requested with specific tiles.
cc @nical @aosmond

**Comment by nical** [comment]
Drawing the tiles into an an intermediate surface and using the latter as the clip source would make sense here.

**Comment by gw3583** [comment]
I haven't thought about this too deeply, but I don't think we need an intermediate surface. I think to support this, we need to:

(1) Determine which of the image tiles overlap the clip mask bounds (we should be able to reuse some of the current tile visibility code for this).
(2) In the clip batcher, loop over each of those tiles and draw them into the clip mask at the appropriate location.

**Comment by nical** [comment]
I think that the clip mask and what I called the intermediate surface are the same thing in my head (I haven't touched the masking code much so I'm a bit fuzzy about the terminology)

**Comment by emilio** [comment]
Will take a look at this.
