### ISSUE TITLE
Properly segment brushes which have clips with different positioning nodes

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#2858]
We currently choose to not include clips with different positioning nodes, but compatible coordinate systems. If we do this, we would need to resegment during scrolling, perhaps looking at the ancestry of the positioning nodes to see if it is necessary.

**Comment by gw3583** [comment]
At least for now, we plan to only segment during a new scene build, so we can close this for now. We can revisit if we run into performance issues on specific sites where this may be beneficial.
