### ISSUE TITLE
Change framebuffer_size for doument

### ISSUE THREAD

**Issue by fasihrana** [servo/webrender#2861]
I'm working on a toy window system based on webrender. I'm trying to resize the window but I'm finding that the initial framebuffer_size does not resize with the window resize. How do I change this size on window resize?

In the examples [common/boilerplate](https://github.com/servo/webrender/blob/196908f2e9aa24233d932c8cc7c4590215f74a3c/examples/common/boilerplate.rs) I see the initial framebuffer_size is used throughout the life of the window/renderer.

```    let framebuffer_size = {
        let (width, height) = window.get_inner_size().unwrap();
        DeviceUintSize::new(width, height)
    };
    let notifier = Box::new(Notifier::new(events_loop.create_proxy()));
    let (mut renderer, sender) = webrender::Renderer::new(gl.clone(), notifier, opts).unwrap();
    let api = sender.create_api();
    let document_id = api.add_document(framebuffer_size, 0);
```

Maybe I'm not calling the right function but I'm following the example [multiwindow](https://github.com/servo/webrender/blob/196908f2e9aa24233d932c8cc7c4590215f74a3c/examples/multiwindow.rs)

**Comment by nical** [comment]
I think that what you are looking for is [set_window_parameter](https://github.com/servo/webrender/blob/master/webrender_api/src/api.rs#L170).

**Comment by fasihrana** [comment]
This solves the problem, but as a result I can't extend the window beyond the size of the monitor the window is displayed on.

**Comment by fasihrana** [comment]
Weird, it limits the size of the window to the combined resolution of the monitors. Probably not webrender's issue?

**Comment by kvark** [comment]
I'm missing something here. `set_window_parameter` tells WR how to work with the window, it doesn't change the window parameters of `winit` in any ways. If you can't get the actual window size beyond the monitor area, the answer should be somewhere in `winit`.

**Comment by fasihrana** [comment]
@kvark You're right, this definitely seems to be a winit issue. Just that I stumbled upon it specifically working on my [webrender example](https://github.com/fasihrana/webrender_example).

**Comment by nical** [comment]
Alright, sounds like we can close this then. Excited to see webrender used in various places, good luck!
