### ISSUE TITLE
Bottom left border radius isn't drawn correctly (on macOS 10.12)

### ISSUE THREAD

**Issue by qezz** [servo/webrender#2862]
Hi, I'm trying to use webrender as a window renderer.

So, here is an example I use to render a square window with the transparent rounded borders (corners):

https://github.com/qezz/webrender-bottom-left-border-issue/blob/master/src/main.rs

It appears to happen on mac only.

**Expected output:**

* all borders are rounded

**Actual output:**

* Bottom left border isn't rounded

<img width="421" alt="screen shot 2018-07-02 at 17 34 03" src="https://user-images.githubusercontent.com/5172876/42171262-83d87e46-7e21-11e8-8a4d-72b0847d4620.png">

(The black background is a terminal window provided just for the demonstration. Top-left, top-right, and bottom-right borders are rounded and the corners are transparent)

**Configuration**

* MacBook Pro (Retina, 13-inch, Early 2015)
* macOS 10.12.6 (Sierra)
* Intel Iris Graphics 6100 1536 MB
* webrender std output:
```
OpenGL version 4.1 INTEL-10.25.19
Shader resource path: None
Device pixel ratio: 2
```
* **EDIT2**: webrender version: `rev = "34a498f7e46c385a189299e7369e204e1cb2060c"`

**EDIT:** Probably related issues: 

* #2754 
* https://github.com/servo/servo/issues/20922

**Comment by kvark** [comment]
I'm able to repro (on Mac only), looking into it...
