### ISSUE TITLE
Google fonts are rendered too thick

### ISSUE THREAD

**Issue by GoGoris** [servo/webrender#2867]
Google Fonts like Roboto, Droid Sans, etc are rendered too thick on Windows 10. It looks like the Cleartype settings are not being applied. The problem becomes more noticeable with smaller font sizes (<20px).

On the right: Firefox Nightly 63.0a1 (webrender)
On the left: Firefox Developer Edition 62.0b5
![webrender_fonts_too_thick](https://user-images.githubusercontent.com/2930063/42311768-e9b70286-803e-11e8-923a-754be6041c9c.PNG)

Test page: https://fonts.google.com/

**Comment by automatedbugreportingfacility** [comment]
Could be a duplicate of #2407.

**Comment by GoGoris** [comment]
Sorry I could not find it, they are probably related. It is weird though that some fonts are not impacted. Google for example uses arial which looks fine. Could the reason be that Arial is not a direct write font or because it is included in Firefox?

**Comment by mstange** [comment]
@GoGoris Is this fixed now? #2896 might have fixed it.

**Comment by GoGoris** [comment]
Yes, the problem is gone in the latest nightly build. Keep up the good work!
