### ISSUE TITLE
RFC - Tweaks to the texture cache eviction heuristics

### ISSUE THREAD

**Issue by nical** [servo/webrender#2868]
After #2785 lands, blob images mostly won't restrict rasterization to the dirty rect. This is because with async rasterization we don't have the guarantee that blob images will still be in the cache by the time rasterization is done and therefore the result of the rasterization must contain the whole image or tile that may have to upload.
In order to restore this dirty rect optimization I propose to make the following two changes to the texture cache eviction rules:

A) Make blob images special in the texture caches and never evict them based on epoch.
B) Eagerly evict blob images (and other image types) as soon as their image keys are destroyed.

We could also nuance rule (A) by counting the number of in-flights transactions in the scene builder thread and never evict blob images from the texture cache *if there is one or more transaction in flight*.

Yay or nay ?

cc @kvark @glennw @Gankro

**Comment by kvark** [comment]
As discussed on the extended call today, B) should be applied to all images. In general, our eviction logic could see a lot of fine-tuning and improvement (take the available memory budget into account).
As for A), we can prevent blob image eviction if we know there is an async scene building happening now in general, or this particular image is being asyncly built.

**Comment by gw3583** [comment]
@bholley and @nical have done a lot of work on texture cache eviction strategies.
