### ISSUE TITLE
Missing new line from feature strings in angle_shader_validation

### ISSUE THREAD

**Issue by zakorgy** [servo/webrender#2872]
There is a missing new line when creating feature definitions for shaders in the angle shader validation: 
https://github.com/servo/webrender/blob/311c20eaa156a4e0816e2d9db8469d3e30b67c25/webrender/tests/angle_shader_validation.rs#L111

This should be 
```rust
features.push_str(&format!("#define WR_FEATURE_{}\n", feature));
```
However adding the missing new line here brings out an error, because the validation fails at the `brush_yuv_image` shader with the `"YUV_NV12,TEXTURE_RECT"` configuration:
```
thread 'validate_shaders' panicked at 'Shader compilation failed: brush_yuv_image
ERROR: 0:172: 'GL_ARB_texture_rectangle' : extension is not supported
ERROR: 0:172: 'sampler2DRect' : unsupported type
ERROR: 0:173: 'GL_ARB_texture_rectangle' : extension is not supported
ERROR: 0:173: 'sampler2DRect' : unsupported type
ERROR: 0:174: 'GL_ARB_texture_rectangle' : extension is not supported
ERROR: 0:174: 'sampler2DRect' : unsupported type
```
Maybe the reason this error didn't show before, that the feature definitions were in line, and just the first one get processed? Because if I change the order of those features ("TEXTURE_RECT,YUV_NV12") this error also occurs (without the new line).

I could send a PR to fix this with some other small things in the `angle_shader_validtaiom.rs` (e.g. the `TRANSFORM` [variant](https://github.com/servo/webrender/blob/master/webrender/tests/angle_shader_validation.rs#L23) of primitive shaders doesn't exist anmyore).

**Comment by zakorgy** [comment]
I don't know if these are known errors, but a similar fail happens if `TEXTURE_EXTERNAL` feature is enabled:
```
thread 'validate_shaders' panicked at 'Shader compilation failed: brush_yuv_image
ERROR: 0:20: 'GL_OES_EGL_image_external_essl3' : extension is not supported
ERROR: 0:176: 'GL_OES_EGL_image_external' : extension is not supported
ERROR: 0:176: 'samplerExternalOES' : unsupported type
ERROR: 0:177: 'GL_OES_EGL_image_external' : extension is not supported
ERROR: 0:177: 'samplerExternalOES' : unsupported type
ERROR: 0:178: 'GL_OES_EGL_image_external' : extension is not supported
ERROR: 0:178: 'samplerExternalOES' : unsupported type
ERROR: 0:1226: 'GL_OES_EGL_image_external_essl3' : extension is not supported
```
and there is also an error if the `DUAL_SOURCE_BLENDING` feature is enabled:
```
thread 'validate_shaders' panicked at 'Shader compilation failed: ps_text_run
ERROR: 0:21: 'GL_ARB_explicit_attrib_location' : extension is not supported
```

**Comment by kvark** [comment]
I looked at a YUV shader code via a GPU capture:
```glsl
#version 150
// brush_yuv_image
#define WR_VERTEX_SHADER
#define WR_MAX_VERTEX_TEXTURE_WIDTH 1024
#define WR_FEATURE_TEXTURE_2D
#define WR_FEATURE_YUV_PLANAR
#define WR_FEATURE_YUV_REC601
...
```
All the newlines are in place, as expected.

**Comment by zakorgy** [comment]
So to clarify, this problem is only related to [webrender/tests/angl_shader_validation.rs](https://github.com/servo/webrender/blob/master/webrender/tests/angle_shader_validation.rs) , where we generate shaders with a specified feature set using `build_shader_strings`, and we pass a wrongly formatted `features` parameter to the function. @kvark I assume you ran a `wrench` test case with angle, because the yuv color space features (YUV_REC601 and YUV_REC709) are not used in the validation file, just the following combinations: 
`["", "YUV_NV12", "YUV_PLANAR", "YUV_INTERLEAVED", "YUV_NV12,TEXTURE_RECT"]`. In the case of wrench there should not be any problem with the newlines.

**Comment by zakorgy** [comment]
Here is the top of the generated shader string for the `"YUV_NV12,TEXTURE_RECT"` features from the validation:
```glsl
#version 300 es
// brush_yuv_image
#define WR_VERTEX_SHADER
#define WR_MAX_VERTEX_TEXTURE_WIDTH 1024
#define WR_FEATURE_YUV_NV12#define WR_FEATURE_TEXTURE_RECT/* This Source Code Form is subject to the terms of the Mozilla Public
...
```
