### ISSUE TITLE
Text in perspective transform not rendering correctly

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2876]
I was looking at [bug 1415272](https://bugzilla.mozilla.org/show_bug.cgi?id=1415272), where in the [parallax demo](https://belen-albeza.github.io/scroll-demos/parallax.html) page doesn't behave correctly in Firefox. There's a number of issues with the page so I reduced it to focus on one problem at a time. The reduced page is at https://mozilla.staktrace.com/bug/1415272-1.html.

The page is supposed to show the text "Payun-payun" in the top-left corner, but doesn't. If I change the scale in the .layer transform property from scale(10) to scale(1) the text is supposed to show up in the center of the page, and it does. On my mac, scales up to 1.32 work fine, but as soon as I change it to 1.33 or higher the text disappears. (The exact scale values will depend on your window size). At first I thought it was due to some clipping getting applied, but I inspected a capture and that doesn't seem to be the case.

Here are two captures, one with the scale at 1.32 where the text is visible [wr-capture-visible.tar.gz](https://github.com/servo/webrender/files/2171910/wr-capture-visible.tar.gz) and one with the scale at 1.35 where the text is not visible [wr-capture-hidden.tar.gz](https://github.com/servo/webrender/files/2171909/wr-capture-hidden.tar.gz).

The scene files in the two captures are pretty much identical except for a few numbers in the transform (modulo id rotation), so I would expect them to behave similarly. In both captures the text is at local rect `((-2, 5), (370, 66))`.

**Comment by gw3583** [comment]
This test case also seems buggy in normal Gecko (on Linux at least). As I zoom in I see the text get weirdly clipped, then disappear, then reappear.

**Comment by gw3583** [comment]
Marked fixed in bugzilla.
