### ISSUE TITLE
Switch to winit = "0.16"

### ISSUE THREAD

**Issue by ekicyou** [servo/webrender#2877]
In webrender, winit = "0.13" is used, but "0.16" is already used in upstream servo.

As I noticed at #2838, in "0.16" there are many destructive changes to the API, and the organization of functions has advanced. Since PR currently related to winit is difficult, I would like to switch.

**Comment by kvark** [comment]
Note that WebRender itself doesn't care about `winit`. It's the `Wrench` and examples that use it, and they are perfectly safe to update without breaking anything else.

**Comment by atouchet** [comment]
This was done in #2878.
