### ISSUE TITLE
WebRender crashes when asked to render a border on a giant rect

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2884]
Simple test page: https://searchfox.org/mozilla-central/source/layout/generic/crashtests/large-border-radius-dashed.html

Causes WebRender to blow up. Specifically from this border display item in the display list:

BorderDisplayItem { widths: BorderWidths { left: 20.0, top: 10.0, right: 20.0, bottom: 10.0 }, details: Normal(NormalBorder { left: BorderSide { color: ColorF { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }, style: Dashed }, right: BorderSide { color: ColorF { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }, style: Dashed }, top: BorderSide { color: ColorF { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }, style: Dashed }, bottom: BorderSide { color: ColorF { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }, style: Dashed }, radius: BorderRadius { top_left: 5000000.0×5000000.0, top_right: 5000000.0×5000000.0, bottom_left: 5000000.0×5000000.0, bottom_right: 5000000.0×5000000.0 } }) }

The numbers in it are large, and it ends up trying to allocate a too-large texture.

bugzilla tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1474885

**Comment by nical** [comment]
The size of the render task items we generate for borders depends directly [on the size of the border radii](https://github.com/servo/webrender/blob/3a85116a17eee9fe203bcff10299de1f3efef2bf/webrender/src/border.rs#L682).
Looking at other render task types this is not the only place where we have this problem.

It would be good to be able to render the borders in screen space rather if they are bigger than a certain size.

**Comment by gw3583** [comment]
Fixed by #2916.
