### ISSUE TITLE
FPS counter of profiler does not count number of frame generation

### ISSUE THREAD

**Issue by sotaroikeda** [servo/webrender#2887]
With gecko, there is a case that the FPS counter become 120 fps like [Bug 1474595](https://bugzilla.mozilla.org/show_bug.cgi?id=1474595) and [Bug 1470327](https://bugzilla.mozilla.org/show_bug.cgi?id=1470327). In these cases, gecko requests to generate frame by 60fps. But FPS counter shows 120fps.

**Comment by sotaroikeda** [comment]
It seems to related to number of  Renderer::render_impl(). The function was called from Renderer::update() and from Renderer::render().

**Comment by kvark** [comment]
Fixed by  #2889
