### ISSUE TITLE
Image not getting rendered during animation

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2900]
Filing for https://bugzilla.mozilla.org/show_bug.cgi?id=1459760#c19 - the capture there shows a frame during the bookmark star animation in Firefox where the image doesn't get rendered properly. It's supposed to be visible to the right of the pocket icon at the end of the URL bar, but instead there's just a gray area.

In the scene-1-0.ron file, the relevant display item is the one with `image_key: ((1), 40)`. It's an external image with 20 "sprites" and the image is horizontally translated by 33 CSS pixels (66 device pixels) each frame to produce the animation effect. The raw image is in externals/38, and I verified that all the sprites appear in the raw data.

Note also that the display item following the relevant one is a blob image that sits over top of the image we care about, but it's fully transparent and so shouldn't really affect anything. It matters if you try chasing though, because the `chase_id` will get updated to the primitive for that blob image instead of the external image we care about, as they both have the same LocalRect. So you have to patch the code that assigns `chase_id` to not clobber a previous `chase_id` in order to properly chase it.

As far as I can tell from the chase output the image should be getting rendered, but it's not.

**Comment by kvark** [comment]
> In the scene-1-0.ron file, the relevant display item is the one with image_key: ((1), 40)
> As far as I can tell from the chase output the image should be getting rendered, but it's not.

Man, it warms my heart to see capturing infrastructure used together with chasing :heart: 
But for the matter, sounds like we are reaching the rendering but getting culled or clipped by something. GPU capture would be the next step.

**Comment by staktrace** [comment]
What is this GPU capture of which you speak?

**Comment by kvark** [comment]
@staktrace renderdoc/PIX/NSight/etc. Since the draw call is passing through, you'd see it in the GPU capture, and it would show if it's placed incorrectly, clipped, culled, rejected by whatever reason.

**Comment by staktrace** [comment]
Is there one of these tools that works on macOS? I can't really repro the problem on my Windows or Linux machines.

**Comment by kvark** [comment]
[apitrace](https://github.com/apitrace/apitrace) works on macOS

**Comment by staktrace** [comment]
Turns out the issue is fixed now (see https://bugzilla.mozilla.org/show_bug.cgi?id=1459760#c22) so we can close this.

That being said, the composition counter thing did work; the composition count I got from firefox was one less than what apitrace reported, so I was able to narrow it down to one or two frames in the apitrace. But it's moot now.

**Comment by kvark** [comment]
The question about GPU debugging tools for WR on MacOS is still in the air though. I recall a thing within XCode that allowed capturing and investigating OpenGL but it appears to be deprecated now... Apitrace apparently has issues with Firefox captures.

**Comment by staktrace** [comment]
According to http://apitrace.github.io/#links there are a couple of tools by Apple: `Xcode GPU Tools` and `OpenGL Profiler` but I'm not sure if either/both are deprecated or where to get them (I didn't look).
