### ISSUE TITLE
How to set the offset of a document

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#2921]
I'm trying to setup a document that has a 50x50 top left offset, but I think WR doesn't actually take the offset into account.

A simple way to reproduce is to apply this patch to Servo:

```diff
diff --git a/ports/servo/glutin_app/window.rs b/ports/servo/glutin_app/window.rs
index aeebf28ef4..3c448077c1 100644
--- a/ports/servo/glutin_app/window.rs
+++ b/ports/servo/glutin_app/window.rs
@@ -709,7 +709,8 @@ impl WindowMethods for Window {
                 let LogicalSize { width, height } = window.get_inner_size().expect("Failed to get window inner size.");
                 let inner_size = (TypedSize2D::new(width as f32, height as f32) * dpr).to_u32();

-                let viewport = DeviceUintRect::new(TypedPoint2D::zero(), inner_size);
+                // let viewport = DeviceUintRect::new(TypedPoint2D::zero(), inner_size);
+                let viewport = DeviceUintRect::new(TypedPoint2D::new(50,50), TypedSize2D::new(300,300));

                 EmbedderCoordinates {
                     viewport: viewport,
```

I'm assuming that all that is necessary. The size is sent via `set_window_parameter`. End result:

<img width="1136" alt="screen shot 2018-07-20 at 16 49 12" src="https://user-images.githubusercontent.com/373579/43009038-df639254-8c3c-11e8-8b18-575fb3780dce.png">

If I'm not mistaken, this used to work a few months ago.

**Comment by kvark** [comment]
This still works in our `document` example, notice the offset use here: https://github.com/servo/webrender/blob/9f21ee5dba0694818a1e2e46d95734ede281447c/examples/document.rs#L66

**Comment by paulrouget** [comment]
This example doesn't correctly with the version of WR used in Servo. I guess we just need to update WR. Thanks.
