### ISSUE TITLE
Glyph rasterization on Mac is dominated by not rasterizing glyphs

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2929]
We have a bunch of overhead caused by how we interact with CoreGraphics. I suspect it wouldn't be too much work to reduce this substantially.

Here's a profile during tab switch:
https://perfht.ml/2v2wuPT

Rayon also doesn't seem to be working spectacularly.

**Comment by mstange** [comment]
duplicate of #2406

**Comment by jrmuizel** [comment]
Quite so
