### ISSUE TITLE
Is there a way to achieve backdrop-filter blur (aka frosted glass effect) using Webrender?

### ISSUE THREAD

**Issue by fasihrana** [servo/webrender#2938]
I know this has been an outstanding issue for Mozilla [Bug 1178765](https://bugzil.la/1178765), but is this going to be looked at in Webrender? Alternatively, is there a way to achieve the effect in Webrender by using existing builder/pipeline funtions?

**Comment by kvark** [comment]
I know a person who would know without investigation. cc @gw3583

**Comment by gw3583** [comment]
It's not currently supported. I *think* it's probably not a huge amount of work (although I haven't read the bug in detail) - my guess is we could base it on the ```mix-blend-mode``` code which does a readback, and then feed that into a blur task? Either way, it's probably going to be low priority in the short term though.

**Comment by fasihrana** [comment]
I think the arguments to function `push_stacking_context` would need to be changed to something as follows:

```
pub fn push_stacking_context(
        &mut self,
        info: &LayoutPrimitiveInfo,
        clip_node_id: Option<ClipId>,
        transform_style: TransformStyle,
        mix_blend_mode: MixBlendMode,
        back_drop_filters: Vec<FilterOp>,
        filters: Vec<FilterOp>,
        glyph_raster_space: GlyphRasterSpace,
    )
```

This would allow more filters to be accessible using the "backdrop-filter" css property. I'm not sure how `mix_blend_mode` argument would be affected though or if it can be removed altogether?

**Comment by Darkspirit** [comment]
(Alexandre Dieulot from [bug 1178765 comment 45](https://bugzilla.mozilla.org/show_bug.cgi?id=1178765#c45))
> Chrome is now working on that feature.
> https://bugs.chromium.org/p/chromium/issues/detail?id=497522#c134
> 
> Three months ago:
> > While we can't promise when the feature will be added, I wanted to let you know that we did hear your comments. We're going to try to make progress on this feature in the next few months.
> 
> Three weeks ago:
> > We may restart work on this feature soon, please stay tuned. The next step is to fix an error in the specification.
> 
> Today it was assigned to someone.

**Comment by dralley** [comment]
The attached BZ was marked RESOLVED FIXED
