### ISSUE TITLE
TimeProfileCounter tries to access unlocked OpenGL textures

### ISSUE THREAD

**Issue by fschutt** [servo/webrender#2940]
This is a problem I've run into partly due to the lack of documentation: When exactly is it safe to assume that an external OpenGL texture isn't going to be used anymore by webrender? What I assumed is that when `ExternalImageHandler::unlock()` is called, webrender is done with the texture: https://github.com/maps4print/azul/blob/5fd584297601086916950c5e734a8d2d02be3bfe/src/compositor.rs#L73-L75

After the display has been drawn and swapped, I remove any not-in-use-by-webrender OpenGL textures. I thought that after the display has been drawn and swapped, there wouldn't be any use in these textures... but apparently I was wrong, because `TimeProfileCounter` still needs them? 

And this worked well, up until a few weeks ago (the first problems appeared somewhere after https://github.com/servo/webrender/commit/9cee890300b7c7d42f3f61f7cb665b057e0edf99). Apparently, the `TimeProfileCounter` now tries the access OpenGL textures, which were previously marked as "unlocked".

Of course, when the `TimeProfileCounter` tries to look up the keys of these now-removed textures, it crashes.

```
core::option::Option<azul::compositor::ActiveTexture*>::expect<azul::compositor @ option.rs:302
std::collections::hash::map::{{impl}}::index<webrender_api::image::ExternalImageId,webrender_api::image::ExternalImageId,azul::compositor::ActiveTexture,core::hash::BuildHasherDefault<twox_hash @ map.rs:1514
azul::compositor::{{impl}} @ compositor.rs:62
webrender::renderer::Renderer @ renderer.rs:3438
webrender::renderer::Renderer @ renderer.rs:2525
webrender::renderer::{{impl}}::render_impl @ renderer.rs:2357
webrender::profiler::TimeProfileCounter @ profiler.rs:204
webrender::renderer::Renderer @ renderer.rs:2315
webrender::renderer::Renderer @ renderer.rs:2261
azul::app::render_inner<debug @ app.rs:701
azul::app::render<debug @ app.rs:687
azul::app::App<debug::MyAppData>::run_inner<debug @ app.rs:275
azul::app::App<debug::MyAppData>::run<debug @ app.rs:179
debug @ debug.rs:323
```

So my question is: When exactly is it safe to throw away an OpenGL texture? After the frame has been redrawn? After it has `ExternalImageHandler::unlock()` has been called? The documentation suggest the latter, but maybe it's just out of date.

Lastly, could there be a way to disable the `TimeProfileCounter` and any profiling? I noticed that this crash even happens in release builds, meaning that the `TimeProfileCounter` is active even in release mode - I think it should be possible to turn off this feature if it's not necessary.

**Comment by kvark** [comment]
`TimeProfileCounter` is a super basic/generic thing that doesn't touch any textures by itself. What you are seeing is the whole rendering loop wrapped into a [time profiled closure](https://github.com/servo/webrender/blob/691063334823467a71af27d39cc3b6dcb68763fa/webrender/src/renderer.rs#L2315-L2377).

>  When exactly is it safe to assume that an external OpenGL texture isn't going to be used anymore by webrender?

The renderer will need to access all the resources of the current scene for as long as any frames from the scene are in flight. It needs to be able to re-render the current scene for a number of reasons, e.g. scrolling. The user is expected to [ask WR](https://github.com/servo/webrender/blob/691063334823467a71af27d39cc3b6dcb68763fa/wrench/src/wrench.rs#L533) for the pipeline epochs once in a while.

Based on the removed/updated pipelines, the user is able to figure out which resources (associated with the pipelines that are no longer used) are not going to be used any more. The user provides an epoch in [set_display_list](https://github.com/servo/webrender/blob/cf9b780325f67c32637deac1256375492e81b4d2/webrender_api/src/api.rs#L144) to compare with later.

> Lastly, could there be a way to disable the TimeProfileCounter and any profiling?

It could be useful, but at this point all the use of those counters is super light and low frequency, so it's not a target for optimization.

**Comment by fschutt** [comment]
Okay. There are multiple things I don't understand when using this pattern:

- Is it a bug that the `pipeline_info.epochs` sometimes returns an empty list of epochs? I mean, it can't be that there are no epochs active! At least one epoch must always be active, unless I'm misunderstanding the concept of an epoch.
- `pipeline_info.epochs` does not contain all active epochs. Instead it contains the **oldest** active epoch. I tried removing textures just based on `pipeline.epochs` (i.e. "remove all textures that are not in the `pipeline.epochs` hashmap). And it crashed, for example:
    - The textures for Epoch 40, 41, 42, and 43 were active
    - `cleanup_opengl_textures()` (my function) is called
    - `pipeline.epochs` just contains "Epoch(42)"
    - Trusting this, I remove all textures from all other epochs, leaving only Epoch(42)
    - Next thing I now, webrender asks for a texture from Epoch(43), boom, crash.

I'm not sure if this is a bug or not. I could fix it by removing all epochs **lower** than the lowest epoch in `pipeline.epochs`. Meaning, if I got `Epoch(42)`, then I'd remove Epoch 40 and 41 (because they are older than 42).

This seems to work:

```rust
fn clean_up_unused_opengl_textures(pipeline_info: PipelineInfo) {

    use compositor::ACTIVE_GL_TEXTURES;

    if pipeline_info.epochs.is_empty() {
        return;
    }

    let oldest_to_remove_epoch = pipeline_info.epochs.values().min().unwrap();

    let mut active_textures_lock = ACTIVE_GL_TEXTURES.lock().unwrap();

    // Retain all OpenGL textures from epochs higher than the lowest epoch
    active_textures_lock.retain(|key, _| key > oldest_to_remove_epoch);
}
```

Is this the intended behaviour or am I missing something?

**Comment by kvark** [comment]
> Is it a bug that the pipeline_info.epochs sometimes returns an empty list of epochs?

`flush_pipeline_info` is taking the current state of epochs and giving it to you. A subsequent call would yield no entries, until the render backend does a new frame build and publishes the epochs data (which populates the `pipeline_info`). You can see this logic in [update_document](https://github.com/servo/webrender/blob/c939a61b83bcc9dc10742977704793e9a85b3858/webrender/src/render_backend.rs#L1000).

> remove all textures that are not in the pipeline.epochs hashmap

The logic you are supposed to have is:
  - go through each entry in this flushed epoch map
  - for a pipeline, free all resources associated with *earlier* epochs than the one returned

Note that epochs are monotonically increased. The flushed pipeline infos provide you with the cut-off epoch, below which everything is no longer used. In the example you provided, instead of doing this:

> Trusting this, I remove all textures from all other epochs, leaving only Epoch(42)

You need to remove all textures from all previous epochs, i.e. 40 and 41.

> I could fix it by removing all epochs lower than the lowest epoch in pipeline.epochs

Oh, I guess you figured this out :) :+1:

**Comment by fschutt** [comment]
Sadly, that doesn't fix it. Even when I remove earlier epochs, I **still** get the TimeProfileCounter asking for textures that were removed earlier.

```
Error information:
Missing OpenGL texture

core::option::expect_failed @ option.rs:960
<azul::compositor::Compositor as webrender::renderer::ExternalImageHandler>::lock
webrender::renderer::Renderer::prepare_gpu_cache
webrender::profiler::TimeProfileCounter::profile
webrender::renderer::Renderer::render_impl
webrender::renderer::Renderer::render
<azul::app::App<'a, T>>::run
debug::main
```

Now I'm really confused because theoretically this should have worked.

**Comment by kvark** [comment]
@fschutt is there a way for me to reproduce? Gecko relies heavily on being able to remove unused resources, so this logic must be working.

**Comment by fschutt** [comment]
@kvark I have the impression that this may have been my mistake. Essentially what I did was to compare the previous frame tree with the current frame tree and only call `DisplayListBuilder::finalize()` if the contents were different. This could have led to different epochs being used in the submitted display list and therefore the crash.

I haven't experienced this after I fixed that, so I'm closing this issue for now. However, I'd really appreciate it if this "please ask webrender for the epochs" was expressed in the documentation so that future users don't need to ask.

Thanks for the response!

**Comment by fschutt** [comment]
Ironically, right after I closed this issue it appeared again - it seems that the issue has something to do with how I handle minimizing / maximizing windows, i.e. it crashes if you minimize the window, then maximize it again it crashes. This probably isn't a webrender issue, just thought it was funny.
