### ISSUE TITLE
Panic in util::calculate_screen_bounding_rect

### ISSUE THREAD

**Issue by nical** [servo/webrender#2957]
This one currently ranks 4th in the list of [crashes with webrender in the signature](https://crash-stats.mozilla.com/search/?signature=~webrender&product=Firefox&date=%3E%3D2018-08-01T15%3A24%3A46.000Z&date=%3C2018-08-08T15%3A24%3A46.000Z&_sort=-date&_facets=signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature) (or 5th if we merge the oom signatures).

[Crash reports](https://crash-stats.mozilla.com/signature/?product=Firefox&signature=static%20union%20core%3A%3Aoption%3A%3AOption%3CT%3E%20webrender%3A%3Autil%3A%3Acalculate_screen_bounding_rect&date=%3E%3D2018-08-01T17%3A24%3A46.000Z&date=%3C2018-08-08T17%3A24%3A46.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_sort=-date&page=1#reports)

Looks like we panic while unwrapping an `Option` in `calculate_screen_bounding_rect`, not sure which. @kvark you probably know this code best, anything obvious? The reported crashes have your fix from #2913 applied.

**Comment by kvark** [comment]
The only `unwrap` I see in `calculate_screen_bounding_rect` is in this piece:
```rust
        WorldRect::from_points(&[
            homogens[0].to_point2d().unwrap(),
            homogens[1].to_point2d().unwrap(),
            homogens[2].to_point2d().unwrap(),
            homogens[3].to_point2d().unwrap(),
        ])
```
We only go there if the following condition is false:
```rust
if homogens.iter().any(|h| h.w <= 0.0) {
```
Meaning that all `homogens[?].w > 0.0`, and thus `to_point2d()` should succeed.

**Comment by gw3583** [comment]
I think this was probably fixed by https://github.com/servo/webrender/pull/3006. Closing for now, but please re-open if it's still occurring.
