### ISSUE TITLE
SVGs and PNGs that don't have any alpha should go into the opaque pass when possible

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#2958]
This is hurting performance on my reveal.js presentation, because I have some big images that are opaque and it's causing overdraw.

**Comment by kvark** [comment]
Isn't this a problem downstream (in Gecko/Servo)? The `ImageDescriptor` struct passed to `add_image` has [is_opaque](https://github.com/servo/webrender/blob/0634d020dd50ed8d93d99e51a7d057bb1e2ec2c9/webrender_api/src/image.rs#L83) field which determines if we can use the opaque path for rendering it.

**Comment by pcwalton** [comment]
OK, I diagnosed this problem with the shiny new "show overdraw" view I wrote and found that the issue is localized to SVGs.

**Comment by pcwalton** [comment]
This also happens with RGBA PNGs that don't actually have any alpha pixels in them.

**Comment by pcwalton** [comment]
Have a Gecko patch for this for PNG, just need to clean it up.

**Comment by kvark** [comment]
@pcwalton any reason to keep this open if this is a purely downstream issue?

**Comment by pcwalton** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1485534 so we can close this.
