### ISSUE TITLE
Mac window should be opaque, not transparent

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#2959]
This is tricky. Basically, WR always records that it's hitting 60 FPS, but it often doesn't actually get the frames to the display and we drop to 30. My reveal.js presentation triggers this (slides will be posted after I give the talk today).

It *does* actually hit 60 if the GPU time is extremely low, on the order of 2 ms. But we should have a lot more leeway than that.

It seems to be worse on the integrated GPU than the discrete GPU, but that might just be the higher fill rate.

**Comment by pcwalton** [comment]
I suspect this may have to do with the WindowServer compositor handling our window inefficiently.

**Comment by pcwalton** [comment]
Quartz Debug.app shows that our window is considered fully transparent, as opposed to Safari for example (which easily hits 60). This may be the problem, or at least part of it.

**Comment by pcwalton** [comment]
cc @mstange -- did we ever decide how to go about making our window opaque?

**Comment by jrmuizel** [comment]
Yes. Hosting in CoreAnimation can give us a opaque window with round corners. https://bugzilla.mozilla.org/show_bug.cgi?id=1429522

**Comment by mstange** [comment]
Couple of points here:

 - WindowServer compositing slowness can't make us overreport the fps count. SwapBuffers will block our thread until the WindowServer is done with the previous frame. I hope we're calculating FPS based on the time between composites and not based on the time that the draw calls for each composite take...
 - The plan is to have opaque CoreAnimation IOSurface layers for the opaque pieces of the window, and use Cocoa's default window clipping to get the rounded corners on the window. This matches what Safari is doing but is slightly less efficient on 10.12 than having an opaque GLContext.

**Comment by mstange** [comment]
Oh, and:

 - As far as I can tell, our inefficient compositing puts a fixed tax on the GPU time of each frame. We should aim to have WebRender be no slower than the non-WebRender compositor, which is usually able to hit 60fps even with the extra tax.

**Comment by nical** [comment]
What can happen is that frames get generated at a solid 60fps but scene updates go asynchronously at a lower frequency which means that scrolling looks smooth while some JS driven animations don't hit 60fps. Not sure if that's what the reveal.js slide deck is running into.

**Comment by kvark** [comment]
> As far as I can tell, our inefficient compositing puts a fixed tax on the GPU time of each frame. We should aim to have WebRender be no slower than the non-WebRender compositor, which is usually able to hit 60fps even with the extra tax.

This goes in line with:
> It does actually hit 60 if the GPU time is extremely low, on the order of 2 ms. But we should have a lot more leeway than that.
> It seems to be worse on the integrated GPU than the discrete GPU, but that might just be the higher fill rate.

So it does sound like we are GPU limited here, and the extra tax is hurting us (therefore) much more than non-WebRender path (which wasn't as much GPU limited, I assume).

**Comment by pcwalton** [comment]
Changed this issue title from something vague to something actionable.

**Comment by kvark** [comment]
@pcwalton  This isn't actionable on WR side, I suggest it to be closed.

**Comment by pcwalton** [comment]
Is there a Bugzilla bug?

**Comment by jrmuizel** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429522

**Comment by kvark** [comment]
Thanks Jeff for the link! Since WR is an upstream dependency of Gecko, we keep bugzilla issues opened to mirror WR issues. But there is no point in doing it the other way around.
