### ISSUE TITLE
https://beta.observablehq.com/@redblobgames/delaunator uses a lot of memory

### ISSUE THREAD

**Issue by nical** [servo/webrender#2967]
Just ran into this on a linux/intel laptop. On this page with webrender my entire session freezes for seconds (including mouse pointer, etc).

**Comment by kvark** [comment]
Interesting, I'm not observing any freezes on that website.

**Comment by kvark** [comment]
The page also suffers from updated display lists (due to animated images), similar to #3044

**Comment by gw3583** [comment]
Tested locally and it seems to be running well. Please reopen if you can still reproduce this.
