### ISSUE TITLE
Publish webrender on crates.io

### ISSUE THREAD

**Issue by friktor** [servo/webrender#2970]
Please publish a webrender on crates.io. There are projects using webrender, but because the project does not exist on crates - users can not publish their own crates depending on webrender.
For example, I have several projects that use webrender. One project uses webrender as an optional feature for converting types. But I can`t publish the project because it has a dependency in git (webrender). Another my project recently had an confuse situation - when people created a project with the same name, simply because it was not in the crates - and I could not publish the project also simply because I have a dependency of a webrender. (Fortunately the confuse was solved and I got an empty crate back)

**Comment by Pzixel** [comment]
It's currently a blocked in many cases.

Looking forward soonest resolution.

**Comment by kvark** [comment]
@gw3583 IIRC, the biggest blocker was renaming `webrender_traits`, which happened. Are there any concerns now before we start publishing?

**Comment by friktor** [comment]
@kvark there is no problem, @psilon meant that the absence of a webrender in crates is a problem that blocks the development of other projects.

**Comment by nical** [comment]
I think that we need pathfinder on crates.io for this to happen but I totally agree we should publish webrender.

**Comment by kvark** [comment]
@pcwalton how do you feel about publishing the current pathfinder version, no matter how incomplete it is?

**Comment by pcwalton** [comment]
Sure, let's do it. It's fontkitified, so it's presently incompatible with
WebRender, however. I have a WIP patch to fix it on WR's side.

**Comment by gw3583** [comment]
Opened a PR that resolves some of the existing cargo publish issues - https://github.com/servo/webrender/pull/2971.

Once that lands, I can publish ```webrender_api``` and then we'll need to solve the pathfinder issues mentioned above before publishing ```webrender```.

**Comment by gw3583** [comment]
I have published ```webrender_api``` from the repository, and a placeholder for ```webrender```. Once we get the pathfinder issues above sorted, we can publish ```webrender``` from the repo.

**Comment by friktor** [comment]
Hello everybody. Already quite a lot of time has passed since the create of issue, and now is no progress on publish crate (except for reserving names on crates). As I understand the problem in pathfinder - at least in the name, because there is already a rather popular crate with the same name. @pcwalton when pathfinder will be published, and not slow down the webrender publish?

**Comment by fasihrana** [comment]
@gw3583 Since pathfinder is now on [crates.io/pathfinder](https://crates.io/crates/pathfinder) is it possible to publish webrender as a crate as well?

**Comment by kvark** [comment]
@fasihrana this isn't the pathfinder you are looking for (unfortunately)

**Comment by fasihrana** [comment]
I’d use the —force if I could to make it so.

:(

**Comment by nical** [comment]
I pushed a version of WebRender without pathfinder to crates.io: https://crates.io/crates/webrender/0.58.0

**Comment by fasihrana** [comment]
I'm getting the following error:

```
error[E0432]: unresolved import `webrender::renderer`
  --> src\lib.rs:27:5
   |
27 | use webrender::renderer;
   |     ^^^^^^^^^^^^^^^^^^^ no `renderer` in the root
```

**Comment by nical** [comment]
@fasihrana sounds about right since you seem to be trying to import a private module. Some of the types in renderer.rs are reexported in the root of the webrender crate (for example Renderer and RendererOptions if that's what you are after).

**Comment by fasihrana** [comment]
Aah! I found the issue. I used `webrender = "*"` in the Cargo.toml file. When I replaced that with `webrender = "^0.58"`, that error went away.

For some reason `webrender = "*"` is bringing back `webrender v0.0.0` back.
