### ISSUE TITLE
Panic in DisplayListFlattener::add_primitive (unexpected image brush with shadow)

### ISSUE THREAD

**Issue by nical** [servo/webrender#2981]
[Bugzilla entry](https://bugzilla.mozilla.org/show_bug.cgi?id=1485274)

Panic at https://hg.mozilla.org/mozilla-central/annotate/3b5452b3778153f6f223bb2177235835b2314eb6/gfx/webrender/src/prim_store.rs#l1252

Top 10 frames of crashing thread:

```
0 std::panicking::rust_panic_with_hook src/libstd/panicking.rs:521
1 std::panicking::begin_panic<str*> src/libstd/panicking.rs:445
2 webrender::display_list_flattener::DisplayListFlattener::add_primitive display_list_flattener.rs:896
3 core::option::Option<webrender_api::display_list::BuiltDisplayListIter> webrender::display_list_flattener::DisplayListFlattener::flatten_item display_list_flattener.rs:610
4 webrender::display_list_flattener::DisplayListFlattener::flatten_items display_list_flattener.rs:297
5 core::option::Option<webrender_api::display_list::BuiltDisplayListIter> webrender::display_list_flattener::DisplayListFlattener::flatten_item display_list_flattener.rs:619
6  @0x4aae03c6af 
7 webrender::display_list_flattener::DisplayListFlattener::flatten_items display_list_flattener.rs:297
8 webrender::display_list_flattener::DisplayListFlattener::flatten_root display_list_flattener.rs:260
9 core::option::Option<webrender_api::display_list::BuiltDisplayListIter> webrender::display_list_flattener::DisplayListFlattener::flatten_item display_list_flattener.rs:644
```

crash signatures:
 - https://crash-stats.mozilla.com/signature/?signature=static%20void%20webrender%3A%3Adisplay_list_flattener%3A%3ADisplayListFlattener%3A%3Aadd_primitive
 - https://crash-stats.mozilla.com/signature/?signature=webrender%3A%3Adisplay_list_flattener%3A%3ADisplayListFlattener%3A%3Aadd_primitive

It is currently the highest crash volume over the last 7 days with "webrender" in the signature.

**Comment by gw3583** [comment]
@jrmuizel @nical 

This is caused by the way that text runs now use images for missing glyphs. The shadow context code doesn't expect images to be added, so we'll need to add support for this. DanG is working on this now.

**Comment by gw3583** [comment]
cc @djg

**Comment by djg** [comment]
I've investigated [Bugzilla 1485274](https://bugzil.la/1485274) and it's caused by the rendering of unknown glyph "tofu" using border for the surrounding box. The shadow code didn't expect a border.

I've extended PrimitiveContainer::create_shadow() to handle BrushKind::Border and BrushKind::Image and the panic!() goes away.
