### ISSUE TITLE
Failures on try as of 816ff14c1805c145ccd60d0227d82b1541fc24eb

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2985]
Perhaps clipping related?
https://treeherder.mozilla.org/#/jobs?repo=try&revision=b17e866822a1941e45235d52a9a16b09009fb95c&selectedJob=195806367

**Comment by gw3583** [comment]
I guess it must be - strange since there were try runs for all the clipping related PRs this week. I'll investigate first thing Monday.

**Comment by zptan** [comment]
There is a cron job created by Kartikaya Gupta runs try daily, it looks OK today:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=8089acb880e43634ef3c1f46c5b652091f893688&filter-resultStatus=testfailed&filter-resultStatus=busted&filter-resultStatus=exception&filter-classifiedState=unclassified

**Comment by jrmuizel** [comment]
Indeed perhaps there's just some fuzz on needed on border-radius/clipping-4-canvas.html

**Comment by jrmuizel** [comment]
Yep. I've landed the update in https://bugzilla.mozilla.org/show_bug.cgi?id=1485791. Hopefully, it sticks.

**Comment by gw3583** [comment]
Closing based on above comment - we can re-open with specific info if needed.
