### ISSUE TITLE
Weird clipping of blob images during scrolling

### ISSUE THREAD

**Issue by nical** [servo/webrender#2987]
For example go to https://www.digitalocean.com/ and scroll slowly. You'll see the bottom of svg elements clipped if scrolling down and the top the svg clipped when scrolling up.

This wasn't happening when I was working on async blobs so the regression is at most a 5 weeks old.

**Comment by jrmuizel** [comment]
@Darkspirit do you mind trying to find a regression window for this?

**Comment by Darkspirit** [comment]
Regressed with [bug 1485691](https://bugzilla.mozilla.org/show_bug.cgi?id=1485691), probably by #2977.
Fixed in [bug 1485791 comment 5](https://bugzilla.mozilla.org/show_bug.cgi?id=1485791#c5), probably by #2980.

**Comment by gw3583** [comment]
Should this be closed?

**Comment by nical** [comment]
Yes indeed!
