### ISSUE TITLE
upgrade dwrote dependency to 0.5.0

### ISSUE THREAD

**Issue by froydnj** [servo/webrender#2988]
This depends on servo/dwrote-rs#14, and would be useful for Firefox eliminating dependencies on `winapi` 0.2.8.

**Comment by atouchet** [comment]
dwrote 0.5.0 has now been published to crates.io.

**Comment by zakorgy** [comment]
I think this can be closed, since the current `dwrote` version is `0.5.1`: https://github.com/servo/webrender/search?l=TOML&q=dwrote
