### ISSUE TITLE
Consider removing `flat varying` for ANGLE

### ISSUE THREAD

**Issue by djg** [servo/webrender#3004]
Using `flat varying` between vertex shader and fragment shader causes ANGLE to generate a geometry shader per draw prim category for those programs.

Discussing the issue with @gw3583, it was suggested to experiment removing flat in all cases or just special casing it for ANGLE.

**Comment by jrmuizel** [comment]
I was curious why this geometry shader was needed and found: https://chromium-review.googlesource.com/c/angle/angle/+/309155 and https://bugs.chromium.org/p/angleproject/issues/detail?id=754
"OpenGL ES3 does not use the same 'provoking vertex' for flat shading as Direct3D 11. See Table 2.12 of the ES3 spec, versus the 'leading vertex' illustrated in http://msdn.microsoft.com/en-us/library/windows/desktop/bb205124(v=vs.85).aspx"

**Comment by gw3583** [comment]
The way we use ```flat``` attributes is an optimization hint in most cases, and (I think) easily worked around in other cases. So we can probably just not use ```flat``` at all (at least in the case of ANGLE).

**Comment by kvark** [comment]
@jrmuizel thanks for those links. This is just sad... I think they should give us an option to say "I don't give a heck about provoking vertex". And since they are at it, also write down some documentation about the performance pitfalls.

**Comment by nical** [comment]
I documented this in the [platform/driver bag of sadness](https://github.com/servo/webrender/wiki/Driver-issues#3004-slow-flat-varying-implementation-in-angle).

**Comment by pcwalton** [comment]
Note that there is a `glProvokingVertex()` function in GL 4.x (extension in 3.x I think) that is designed to solve this problem: https://www.khronos.org/opengl/wiki/Primitive#Provoking_vertex

 I don't know if ANGLE supports it, though.

**Comment by djg** [comment]
Talking this issue over with @gw3583 and asking my friendly GPU expert, `flat` is a possible improvement on unified shader architectures. Ideally, we'd like ANGLE not to use geometry shaders and to keep the `flat` specifier.

**Comment by djg** [comment]
Discussion with @gw3583, we decided not to move ahead with this.
