### ISSUE TITLE
Implement border-image-repeat: round

### ISSUE THREAD

**Issue by pyfisch** [servo/webrender#3005]
Currently only repeat and stretch are implemented and round is handled the same as stretch.

https://github.com/servo/webrender/blob/5e1f9b9a5b2dbb61e30811195f1070f87d15a1ba/webrender/src/display_list_flattener.rs#L1598

**Comment by dralley** [comment]
BZ marked as resolved/fixed

**Comment by dralley** [comment]
@kvark I think this can be closed?

**Comment by nical** [comment]
Yup!
