### ISSUE TITLE
Cache Composition of Pictures

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#3016]
Although we cache text-shadow pictures, if a piece of text has *many* shadows (some pages have ~100 to create a certain effect), then we are still swamped by compositing all those cached pictures together. We need to somehow detect this and cache their actual composition into another "super picture".

This is considered a blocker for webrender riding the firefox trains: https://bugzilla.mozilla.org/show_bug.cgi?id=1422567

**Comment by gw3583** [comment]
We got some picture caching code, eventually.
