### ISSUE TITLE
Consider clearing instead of filling with large solid colors

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#3019]
According to AMD's ["Depth in Depth" paper], "a similar technique [to tile-based Z-buffer clearing] is used for color buffers as well to reduce bandwidth requirements". This means that we could potentially accelerate large solid color clears, at least on some hardware.

The main benefit of this would be to make problematic cases in which we overdraw over large solid color areas (#3017, #3018) less problematic. If we did this right, we wouldn't suffer as much penalty for the overdraw in cases like those, because most of the overdraw would just be overdrawing over a fast color buffer clear instead of overdrawing over fully shaded pixels.

["Depth in Depth" paper]: http://swiborg.com/download/dev/pdf/(amd)-depth-in-depth.pdf

**Comment by kvark** [comment]
I don't think this is applicable to us. When it's not the full screen covered, in order to use clearing we'll have to enable scissor. Last time I checked AMD doesn't try to fast-clear the color tiles that are within the scissor rect, it instead falls back to regular quad drawing anyway.

**Comment by pcwalton** [comment]
Yeah, I'd like to keep this open though because there should be *something* we can do for issues like this, even if it's not scissor and clear.

**Comment by kvark** [comment]
I believe there is a bit of confusion here. The linked issues are for transparent overdraw, while this issue is about solid colors. For solids, our earlier measurements indicate that the depth buffer rejection is good enough. Roughly, the cost of rejection is 1/7 of the color fill cost across the hardware.

**Comment by pcwalton** [comment]
I guess I'll close this.
