### ISSUE TITLE
High GPU cache row count for relatively simple page with GIFs

### ISSUE THREAD

**Issue by aosmond** [servo/webrender#3044]
![screenshot from 2018-09-11 10-19-32](https://user-images.githubusercontent.com/1681373/45380653-29454d00-b5d1-11e8-917e-5664b0714bd3.png)

As revealed in the profiles from https://bugzilla.mozilla.org/show_bug.cgi?id=1447351#c14, when the user scrolls around some large animated images, there is some jank. It appears we are spending a good amount of time updating the GPU cache on the renderer thread. From the screenshot above, one can see the GPU cache rows are nearly 400, which kvark indicated is quite high for such a simple page.

https://github.com/rcoh/angle-grinder

Note that the time spent uploading the textures is a separate problem, and we can do better with animated images in general to help mitigate this. I wouldn't worry about that part of the profiles too much as a result (see comment 15 in the aforementioned bug).

**Comment by kvark** [comment]
On a page where there is no scrolling, and just gifs playing, there is just a tiny bit of GPU blocks that need to be updated but they end up dirtying 100 rows, which isn't ideal. We end up spending 6% of Renderer time uploading those rows.

**Comment by kvark** [comment]
The reason for this GPU block update count is because we get a new display list every frame. So logically there are two ways to resolve this:
  1. make Gecko to update an image instead of changing the display list
  2. make our scene building to re-use the by-products of the previous scene more aggressively

**Comment by fschutt** [comment]
A question - this only happens for images, doesn't it? Other content usually affects the layout, so a new rebuild of the display list is necessary. But GIFs or videos, which are very common, don't affect the layout at all, so what webrender could do is to have an api to exchange an image key for another, i.e.:

```rust
if frame_only_updates_images {
     // only update the rectangle where previously the key 4 
    // was it should now draw the image with key 5, while reusing everything 
    // else from the old display list
    transaction.update_image_key(ImageKey(4), ImageKey(5));
} else {
    let display_list = build_display_list();
    transaction.push_display_list(display_list);
}
```

This way the the display list building step could be skipped. GIFs and videos are simply very common - they only need a texture update, not an update of the whole display list.

**Comment by aosmond** [comment]
I'll be doing that work in https://bugzilla.mozilla.org/show_bug.cgi?id=1428558 next week (hopefully).

**Comment by gw3583** [comment]
Marked fixed in bugzilla.
