### ISSUE TITLE
Left side of the first letter of every line in a reddit comment gets cut off slightly 

### ISSUE THREAD

**Issue by hgallagher1993** [servo/webrender#3055]
[Nightly+Webrender enabled](https://i.imgur.com/pqueDLh.png) ----- [Nightly+Webrender disabled](https://i.imgur.com/iRX3inF.png).

Edit: I'm on Linux Mint 18.3 as well if it makes a difference.

**Comment by kvark** [comment]
I wonder if this is fixed by #3048
cc @lsalzman

**Comment by hgallagher1993** [comment]
Looking at the attachments in the Bugzilla link in the pull request it looks like it could be the same issue. After looking around some more I found the same problem in other places like comments on youtube videos and in the title of videos in the right sidebar as well.

**Comment by gw3583** [comment]
I believe this is fixed - please reopen if still reproducible.
