### ISSUE TITLE
Need to be less aggressive at border caching.

### ISSUE THREAD

**Issue by emilio** [servo/webrender#3058]
This is what is preventing us from landing #3049 or #3056. This is of course already broken on trunk, see the following page for sadness: https://crisal.io/tmp/wr-border-caching.html

[Here's a YAML thingie which also shows the issue](https://github.com/servo/webrender/files/2380794/out.txt), though less exacerbated because there's less garbage in the GPU memory I guess.

The upshot is that as of right now nothing based on something like the available size should change the output of segments, which means that the optimization we were trying to land in those PRs breaks so hard.

Now, doing that for solid borders (and anything non-dashed-or-dotted, really) might be feasible (we'd still need to decide if we want to pay the price of generating those zero-size instances, but I suspect it might be possible). However for those it's not.

I had a very hacky patch which fixed all those issues, which looks something like that (note that I haven't verified that the first change is needed):

```diff
diff --git a/gfx/webrender/src/prim_store.rs b/gfx/webrender/src/prim_store.rs
index 5b65764173a3..3e07b343f16a 100644
--- a/gfx/webrender/src/prim_store.rs
+++ b/gfx/webrender/src/prim_store.rs
@@ -2845,17 +2845,17 @@ impl Primitive {
             // TODO(gw): When drawing in screen raster mode, we should also incorporate a
             //           scale factor from the world transform to get an appropriately
             //           sized border task.
             let world_scale = LayoutToWorldScale::new(1.0);
             let mut scale = world_scale * frame_context.device_pixel_scale;
             let max_scale = BorderRenderTaskInfo::get_max_scale(&border.radius, &widths);
             scale.0 = scale.0.min(max_scale.0);
             let scale_au = Au::from_f32_px(scale.0);
-            let needs_update = scale_au != cache_key.scale;
+            let needs_update = scale_au != cache_key.scale || true;
             let mut new_segments = Vec::new();
 
             if needs_update {
                 cache_key.scale = scale_au;
 
                 *task_info = BorderRenderTaskInfo::new(
                     &self.metadata.local_rect,
                     border,
@@ -2863,17 +2863,17 @@ impl Primitive {
                     scale,
                     &mut new_segments,
                 );
             }
 
             *handle = task_info.as_ref().map(|task_info| {
                 frame_state.resource_cache.request_render_task(
                     RenderTaskCacheKey {
-                        size: DeviceIntSize::zero(),
+                        size: task_info.size,
                         kind: RenderTaskCacheKeyKind::Border(cache_key.clone()),
                     },
                     frame_state.gpu_cache,
                     frame_state.render_tasks,
                     None,
                     false,          // todo
                     |render_tasks| {
                         let task = RenderTask::new_border(
```

In any case, we need to figure out how we want to make this caching work, and if we want to do something different for solid borders than for dashed borders (I guess so).

/cc @glennw

**Comment by emilio** [comment]
Note that of course that patch is not landable, at least the first change is clearly a hack.

**Comment by Darkspirit** [comment]
Bugzilled: https://bugzilla.mozilla.org/show_bug.cgi?id=1491124

**Comment by emilio** [comment]
IRC log for my own reference: https://mozilla.logbot.info/gfx/20180913#c15309963
