### ISSUE TITLE
3d-perspective makes webrender sad

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#3068]
Pretty nasty results:

corrupted rendering / clobbering the chrome: https://bugzilla.mozilla.org/show_bug.cgi?id=1491911

jumping apz: https://bugzilla.mozilla.org/show_bug.cgi?id=1415272

**Comment by nical** [comment]
cf. #3073

**Comment by gw3583** [comment]
Fixed by https://github.com/servo/webrender/pull/3073
