### ISSUE TITLE
Regression in Servo /css/css-backgrounds tests

### ISSUE THREAD

**Issue by kvark** [servo/webrender#3078]
Caused by #2992, according to https://github.com/servo/servo/pull/21725#issuecomment-422282806
cc @nical 
Presumably, the following tests fail:
* /css/css-backgrounds/background-attachment-local/attachment-local-positioning-2.html
* /css/css-backgrounds/background-attachment-local/attachment-scroll-positioning-1.html
* /css/css-backgrounds/scroll-positioned-multiple-background-images.html

@pyfisch is this correct and complete?

**Comment by pyfisch** [comment]
I think /css/CSS2/floats-clear/clear-on-parent-and-child.html is missing from the list.
