### ISSUE TITLE
Deformed and glichy terminal on stripe.com (at 280+% zoom)

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#3087]
Bugzilla: [bug 1492525](https://bugzilla.mozilla.org/show_bug.cgi?id=1492525)
URL: https://stripe.com/terminal
Probably regressed by: #3030

Using try build from [bug 1492389 comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1492389#c1) (which fixed [bug 1492016](https://bugzilla.mozilla.org/show_bug.cgi?id=1492016)):
[Screencast](https://bugzilla.mozilla.org/attachment.cgi?id=9010327)

**Comment by Darkspirit** [comment]
With latest Nightly it's no longer deformed like in the screencast for me, so the mentioned regression range might be obsolete. But there is still some flicker on the left side of the purple terminal if you zoom in.

**Comment by emilio** [comment]
This was fixed by #3187.
