### ISSUE TITLE
Support complex clipping regions with multiple nested rounded corner clipping regions

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#309]
If you have the intersection of multiple nested border corners, we don't render that right. We need to.

**Comment by kvark** [comment]
I believe @glennw proposal to #498 will address this (pasting the relevant text from email here):
> My idea is to remove that viewport_rect code, and introduce a new struct, which is a ClipRegionStack or something similar. As we traverse the tree in cull_layers() we would push the mask rect / transform into that as needed. This could return some kind of identifier for the clip region that applies to this part of the tree (perhaps store in the Layer structure?).

**Comment by jrmuizel** [comment]
Here's an example: https://people-mozilla.org/~jmuizelaar/servo/border.html

**Comment by glennw** [comment]
@kvark Yes, the plan for the clip region stack we've discussed should cover this case too.

**Comment by glennw** [comment]
This happened. There are still some bugs and edge cases, but we can open specific issues for those as we encounter them.
