### ISSUE TITLE
Gecko's displaylist_mutate talos test is slow

### ISSUE THREAD

**Issue by mattwoodrow** [servo/webrender#3116]
Looking at profiles, it appears that both the scene builder and render backend thread take a very long time, mostly within resizing vectors.

This test has a large number of elements (10k), and they're mostly the same every frame, so is testing the overhead of unchanged elements.

I'm going to have a go at preallocating things where possible, and using SmallVec for the ones that are usually small.

**Comment by gw3583** [comment]
@mattwoodrow made a lot of allocation improvements here. There's still work we can do here, but we can open specific bugs next time we profile it.
