### ISSUE TITLE
Panic with large blur radius generating big render tasks

### ISSUE THREAD

**Issue by nical** [servo/webrender#3118]
Bugzilla entry:  https://bugzilla.mozilla.org/show_bug.cgi?id=1493917

We should put a limit to the blur radius, and maybe also cap the render task size itself.

**Comment by pcwalton** [comment]
This should fall out of my blur work, which I'm currently landing in stages.

**Comment by nical** [comment]
@pcwalton will your work make us robust about crazy blur radii or should we put some limits saner at the scene builder level in addition?
