### ISSUE TITLE
has_2d_inverse is broken

### ISSUE THREAD

**Issue by kvark** [servo/webrender#3119]
It returns true even for an identity matrix:
https://github.com/servo/webrender/blob/7af2936b736c5582f6bacc659aee3ed210a5b929/webrender/src/util.rs#L227
Introduced in #2058, seems to only affect the fonts. cc @lsalzman

**Comment by lsalzman** [comment]
How is it broken? The goal is just to see if the determinant of the 2D subset of the matrix is non-zero, so that if you truncate the matrix to 2D, that truncated matrix can be inverted. So at least it should behave correctly according to that. For an identity matrix, it is supposed to be true.

**Comment by kvark** [comment]
@lsalzman I read it wrong, thank you and @mstange for clarifying!
