### ISSUE TITLE
WebRender seems to be holding on to tiles outside of a blob's visible area

### ISSUE THREAD

**Issue by mstange** [servo/webrender#3125]
[Bug 1494173](https://bugzilla.mozilla.org/show_bug.cgi?id=1494173)

\>> [Testcase](https://bug1494173.bmoattachments.org/attachment.cgi?id=9012020) <<

In this testcase, the display port does not cover the entire scrollable area of the page. Consequently, if you scroll to the bottom of the page, the parts of the blob image that are at the top of the page should be discarded. As you scroll back up, they should be repainted.

However, both blob.paint-flashing and the "Texture data, kb" measurement in the WebRender profiler show that tiles are rasterized on demand when scrolling down, but no new tiles get rasterized when scrolling back up: The tiles at the top seem to be kept around.

This is unexpected. Tiles outside of a blob's visible area are invalid and should be discarded by WebRender.

Making the testcase wider and taller (and thus using more tiles) causes tiles to be discarded as expected. But at this blob size (and at my screen size and my 2x device pixel ratio), no discarding seems to happen.

**Comment by nical** [comment]
Fixed in https://github.com/servo/webrender/pull/3250.
