### ISSUE TITLE
Use rayon's global thread pool

### ISSUE THREAD

**Issue by nical** [servo/webrender#3130]
Having a webrender-specific thread pool isn't buying us anything right now and it is even adding some overhead from the unnecessary amount of thread and more importantly I can't find a way to use parallel iterators on the thread pool without blocking the scene builder thread and dispatching the parallel work on the thread pool.
What we really want is to start work on the scene builder and let the workers steal work, otherwise we pay for another couple of thread switches which is expensive when the CPU is busy, and cause the high-priority scene builder to have to wait if the thread pool is busy. I naively thought that ThreadPool::install was just running the callback on the calling thread and overriding the choice of the thread pool but it turns out it actually dispatches a blocking call to one of the workers.

The downside is it's convenient to look at the worker threads in the profiler and know that they only do webrender work, but we pay a high price for that.

**Comment by gw3583** [comment]
@nical We decided we don't want to pursue this, is that right?

**Comment by nical** [comment]
We could if we want to but it wouldn't address the issue that motivated this issue. I'll close for now,
