### ISSUE TITLE
Test WR with SwiftShader

### ISSUE THREAD

**Issue by glennw** [servo/webrender#315]
This may provide a fallback solution for systems without a viable GPU (e.g. old machines, headless CI, virtual machines).

https://blog.chromium.org/2016/06/universal-rendering-with-swiftshader.html

I have cloned SwiftShader, built it on Linux and successfully run the example application. The next step is to try and get WR running with SS and see if it works / what functionality is missing that we rely on.

As far as I know, SS doesn't support desktop GL - but it supports all of OpenGL ESv2 and it appears to support most of ES3.

So there's two questions to answer:
 - Does SS implement enough of ES3 yet for it to be viable (or can we reduce the ES3 features that WR relies on to be able to use SS).
 - What is the simplest way to run the ES3 rendering code path on desktop code - right now, it's only enabled on Android via #cfg() flags - could we instead use cargo features or something like that?

**Comment by larsbergstrom** [comment]
oooooooooooooo!

**Comment by glennw** [comment]
I did eventually get WR working with Swiftshader (after changing the way our shaders work). However we're not using it for CI testing, since it takes a very long time to compile some of our shaders (> 5 seconds). It looks like they are working on updating their codegen (which was stuck at an old version of LLVM when I last checked), so it may be worth benchmarking SS vs OSMesa again once that work lands.
