### ISSUE TITLE
Error in cargo locked Winit v0.16.2

### ISSUE THREAD

**Issue by fasihrana** [servo/webrender#3166]
Hi, I'm randomly getting the following error when running an example program.

```
thread 'main' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', C:\Users\frana\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.16.2\src\dpi.rs:273:9
error: process didn't exit successfully: `target\debug\examples\mainexample.exe` (exit code: 101)
```

Apparently this has been fixed in Glutin 0.18. [assertion failed: validate_hidpi_factor(dpi_factor)](https://github.com/tomaka/winit/issues/607)

When will glutin version be bumped in webrender?

**Comment by atouchet** [comment]
WebRender is now using glutin 0.21. Is this issue fixed?
