### ISSUE TITLE
https://facebook.github.io/immutable-js/ does not scroll down correctly

### ISSUE THREAD

**Issue by marcenuc** [servo/webrender#3171]
If you scroll down the page, the word "IMMUTABLE" overlaps with the page's text.

Disabling Webrender fixes the problem.

I am using latest Nightly on Ubuntu 18.04 with Intel driver.

**Comment by Darkspirit** [comment]
Bugzilled: [bug 1495791](https://bugzilla.mozilla.org/show_bug.cgi?id=1495791)

**Comment by emilio** [comment]
Was fixed by https://github.com/servo/webrender/pull/3315.

I'll land a test for this in Gecko.
