### ISSUE TITLE
Add support for filters in linear color space

### ISSUE THREAD

**Issue by nical** [servo/webrender#3175]
Bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1485512

This would be a small subset of #1880. Some SVG filters are very similar to the some of the CSS filters that we already implement. However, SVG filters operate in linear color space by default instead of sRGB and it appears that SVG filters in the wild rarely opt into sRGB. Still, it would be great to get these filters to run on the GPU instead of the software blob image fallback (especially blurs).

We could do this by having shaders to convert between the two spaces or teach some of the shaders to support different input and output color spaces (I don't know what's best long term and/or short term).

**Comment by dralley** [comment]
The bugzilla is marked "resolved fixed", can this be closed?

**Comment by kvark** [comment]
Thanks for triaging!
