### ISSUE TITLE
3d CSS cube demo is broken again

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#3194]
[bug 1498639](https://bugzilla.mozilla.org/show_bug.cgi?id=1498639)
[Screencast](https://bug1498639.bmoattachments.org/attachment.cgi?id=9016733)
URL: https://3dtransforms.desandro.com/cube
Regressed by #3173.

**Comment by kvark** [comment]
cc @staktrace 
looks like we'll need a 3rd version of this PR :)

**Comment by Darkspirit** [comment]
Also affected: https://superhuman.com/ ([Screencast](https://bugzilla.mozilla.org/attachment.cgi?id=9020609))

**Comment by gw3583** [comment]
Fixed in bugzilla.
