### ISSUE TITLE
NoAvailablePixelFormat error on Windows RDP

### ISSUE THREAD

**Issue by fasihrana** [servo/webrender#3242]
Is there a way to get webrender working when running applications via RDP? I understand that this comes with the fact that glutin is being used, though another question I suppose is that, can webrender fallback to a software renderer and how? [llvmpipe](https://www.mesa3d.org/llvmpipe.html) perhaps?

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', libcore\result.rs:945:5

note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
```

**Comment by nical** [comment]
We use llvmpipe in the CI (on linux at least). It's mostly a matter of how you create the opengl context that WebRender will use.

**Comment by fasihrana** [comment]
Is there an example I can see?

You can see my example [here](https://github.com/fasihrana/skryn/blob/master/src/gui/window.rs#L137).

**Comment by nical** [comment]
By the look of https://github.com/servo/webrender/blob/master/wrench/script/headless.py#L52 we appear to just be using environment variables and letting the OS figure the rest out. Other than that I don't know how to help you, all I know is that WebRender is agnostic to whether the underlying context is using the GPU or a software implementation (if that's any comfort).

**Comment by nical** [comment]
I my opinion you should try to get a working OpenGL context without webrender first. Once you have a simple triangle on screen using the adequate gl version, apply whatever you did to make it work in your app/library that uses WebRender.
WebRender itself doesn't choose or know anything about the type of OpenGL context or how it was created, it just uses the one that is current on the thread where the Renderer lives.

**Comment by fasihrana** [comment]
OK, will try that and report back.

**Comment by gw3583** [comment]
I don't think there's anything to be done in WR for this, please reopen if still relevant.
