### ISSUE TITLE
Hit test fails for blank lines/padding in text nodes

### ISSUE THREAD

**Issue by jdm** [servo/webrender#3261]
When I load https://gist.github.com/jdm/8598518d32d2ab1f3eae7f230decb25b in Servo and scroll the text node, scrolling halts whenever the mouse is positioned over a blank line between paragraphs or the initial padding at the top of the text node. This is because Servo scrolls with the `scroll` API instead of `scroll_with_node_id`, so WR performs a hit test at the cursor position to find the nearest scrollable ancestor. The hit test does not pick the text node when the cursor is positioned over a blank line, so the node does not get scrolled appropriately.

**Comment by mrobinson** [comment]
In the past, Servo included a large transparent rectangle in the display list which was big enough to include all of the scrolled contents. That rectangle was added in the hit test tree, but not included in the final list of rendered primitives. It's possible that one of these three things is true:
1. There is a bug in how this rectangle is calculated. 
2. The rectangle is not included in the display list that Servo is sending.
3. WebRender is accidentally optimizing away this rectangle.

**Comment by jdm** [comment]
Yeah, this looks like something we need to fix in Servo.
