### ISSUE TITLE
webrender adjusts gamma wrong if frame contains an OpenGL texture

### ISSUE THREAD

**Issue by fschutt** [servo/webrender#3262]
If I push an OpenGL texture (via `push_image` like [here](https://github.com/maps4print/azul/blob/395067496d0cde03b54b4cc4c9cff16632d3ac8a/src/display_list.rs#L687-L698)), the background color of all other elements get noticably lighter. If I don't push an OpenGL color, it displays the actual correct color. My assumption is that this has to do with gamma adjustment logic inside of webrender.

Without an OpenGL texture (here the red rectangle is drawn via webrender), it displays correctly:

![gamma_adjust_without_opengl](https://user-images.githubusercontent.com/12084016/47867663-6fb16e00-de02-11e8-9163-6ff21b34496c.PNG)

With OpenGL (the red rectangle is an OpenGL texture, the background is drawn by webrender):

![gamma_adjust_with_opengl](https://user-images.githubusercontent.com/12084016/47867673-7c35c680-de02-11e8-931c-0d27df4e8f99.PNG)

Comparison on the same screen with the Google color picker:

![gamma_adjust_comparison_with_chrome](https://user-images.githubusercontent.com/12084016/47867922-3a595000-de03-11e8-8c6d-f9f8b91e1958.PNG)

As you can see, the resulting color is much lighter - technically, whether the texture exists or not should not affect the outcome. If I debug this in renderdoc, the lighter color is drawn, so the bug happens somewhere before the actual drawing stage. I don't do any gamma adjustment myself, except for box-shadow, so I don't think that this is a bug in azul, but rather in webrender.

## Steps to reproduce

```
git clone https://github.com/maps4print/azul
git checkout webrender_bug
cargo run --example webrender_bug
```

See the `/src/webrender_bug.rs` for a test case.

**Comment by fschutt** [comment]
The bug is definitely in webrender, if I print the display list, I get the correct color, but that color doesn't end up on the screen. Since this only happens with OpenGL, not with regular images, I wonder if this relies on webrender having some special OpenGL texture or shader active and maybe the OpenGL drawing messes with that? Here is the display list if I print it out:

```rust
// Background, color is correct
GenericDisplayItem {
    item: Rectangle(
        RectangleDisplayItem {
            color: ColorF {
                r: 0.18431373,
                g: 0.19215687,
                b: 0.21176471,
                a: 1.0
            }
        }
    ),
    clip_and_scroll: ClipAndScrollInfo {
        scroll_node_id: Spatial(1, PipelineId(0, 0)),
        clip_node_id: None
    },
    info: PrimitiveInfo {
        rect: TypedRect(800.0×600.0 at (0.0,0.0)),
        clip_rect: TypedRect(800.0×600.0 at (0.0,0.0)),
        is_backface_visible: false,
        tag: None
    }
}

// Hit-testing containing rectangle for the OpenGL texture
GenericDisplayItem {
    item: Rectangle(
        RectangleDisplayItem {
            color: ColorF {
                r: 0.0,
                g: 0.0,
                b: 0.0,
                a: 0.0
            }
        }
    ),
    clip_and_scroll: ClipAndScrollInfo {
        scroll_node_id: Spatial(1, PipelineId(0, 0)),
        clip_node_id: None
    },
    info: PrimitiveInfo {
        rect: TypedRect(100.0×100.0 at (0.0,0.0)),
        clip_rect: TypedRect(100.0×100.0 at (0.0,0.0)),
        is_backface_visible: false,
        tag: None
    }
}

// Actual OpenGL texture
GenericDisplayItem {
    item: Image(
        ImageDisplayItem {
            image_key: ImageKey(
                IdNamespace(
                    1
                ),
                4
            ),
            stretch_size: 100.0×100.0,
            tile_spacing: 0.0×0.0,
            image_rendering: Auto,
            alpha_type: Alpha,
            color: ColorF {
                r: 1.0,
                g: 1.0,
                b: 1.0,
                a: 1.0
            }
        }
    ),
    clip_and_scroll: ClipAndScrollInfo {
        scroll_node_id: Spatial(1, PipelineId(0, 0)),
        clip_node_id: None
    },
    info: PrimitiveInfo {
        rect: TypedRect(100.0×100.0 at (0.0,0.0)),
        clip_rect: TypedRect(100.0×100.0 at (0.0,0.0)),
        is_backface_visible: false,
        tag: None
    }
}
```

**Comment by nical** [comment]
I had a look at this and compared the good/bad cases using apitrace and the only differences are in commands emitted outside of WebRender. The most suspicious one being `glEnable(GL_FRAMEBUFFER_SRGB)` at the following stack:

```
#0  glium::gl::Gl::Enable (self=0x7fffe33174d0, cap=36281) at build/glium-24c3eb7df3762c1d/out/gl_bindings.rs:6400
#1  0x0000555556230472 in glium::ops::clear::clear (context=0x7fffe33174d0, framebuffer=Some = {...}, rect=None, color=Some = {...}, color_srgb=false, depth=core::option::None, stencil=core::option::None)
    at glium-0.22.0/src/ops/clear.rs:39
#2  0x0000555555663ccd in <glium::framebuffer::SimpleFrameBuffer<'a> as glium::Surface>::clear (self=0x7fffffff8350, rect=None, color=Some = {...}, color_srgb=false, depth=core::option::None, 
    stencil=core::option::None) at glium-0.22.0/src/framebuffer/mod.rs:272
#3  0x00005555556d7b50 in glium::Surface::clear_color (self=0x7fffffff8350, red=1, green=0, blue=0, alpha=1) at glium-0.22.0/src/lib.rs:687
#4  0x00005555556d7dd3 in webrender_bug::render_opengl_texture (_ptr=0x7ffff567a090, info=WindowInfo<webrender_bug::WebrenderTestCase> = {...}, dimensions=HidpiAdjustedBounds = {...})
    at examples/webrender_bug.rs:35
#5  0x00005555556159d9 in azul::display_list::push_opengl_texture (info=0x7fffffff8978, rectangle=DisplayListRectParams<webrender_bug::WebrenderTestCase> = {...}, referenced_content=0x7fffffff9268, 
    referenced_mutable_content=0x7fffffff9288) at display_list.rs:666
#6  0x0000555555616998 in azul::display_list::displaylist_handle_rect (bounds=TypedRect<f32, webrender_api::units::LayoutPixel> = {...}, rectangle=DisplayListRectParams<webrender_bug::WebrenderTestCase> = {...}, 
    referenced_content=0x7fffffff9268, referenced_mutable_content=0x7fffffff9288) at display_list.rs:613
#7  0x000055555561797c in azul::display_list::push_rectangles_into_displaylist (solved_rects=0x7fffffff9110, epoch=Epoch = {...}, z_ordered_rectangles=ZOrderedRectangles = {...}, 
    referenced_content=0x7fffffff9268, referenced_mutable_content=0x7fffffff9288) at display_list.rs:450
#8  0x000055555561a77a in <azul::display_list::DisplayList<'a, T>>::into_display_list_builder (self=0x7fffffff93e0, app_data=Arc<std::sync::mutex::Mutex<webrender_bug::WebrenderTestCase>> = {...}, 
    pipeline_id=PipelineId = {...}, current_epoch=Epoch = {...}, window_size_has_changed=true, render_api=0x7ffff5651df8, parsed_css=0x7ffff5751ea0, window_size=0x7ffff5651258, fake_window=0x7ffff56fdf80, 
    app_resources=0x7fffffffb610) at display_list.rs:244
#9  0x0000555555628787 in azul::app::render (app_data=Arc<std::sync::mutex::Mutex<webrender_bug::WebrenderTestCase>> = {...}, has_window_size_changed=true, ui_description=0x7ffff5751e40, ui_state=0x7ffff5756f40, 
    parsed_css=0x7ffff5751ea0, window=0x7ffff5651000, fake_window=0x7ffff56fdf80, app_resources=0x7fffffffb610) at app.rs:808
#10 0x0000555555626178 in <azul::app::App<T>>::run_inner (self=0x7fffffffb5d8) at app.rs:324
#11 0x000055555562489c in <azul::app::App<T>>::run (self=App<webrender_bug::WebrenderTestCase> = {...}, window=...) at app.rs:209
#12 0x00005555556d7f91 in webrender_bug::main () at examples/webrender_bug.rs:42
```

WebRender assumes the input textures in srgb color space while GL_FRAMEBUFFER_SRGB tells the driver to assume input colors in linear space and do the conversion.

Glium appears to have a way to override it's default stance towards color spaces by specifying for each program whether it outputs srgb: https://docs.rs/glium/0.22.0/glium/program/enum.ProgramCreationInput.html
Which probably means some internal state tracking that toggles the thing on and off upon receiving each program. You could make sure to have *all* glium usage specify the correct flag there but that sounds error prone. You could also manually disable GL_FRAMEBUFFER_SRGB before calling into WebRender but that will probably mess with glium's internal state tracking.

My take on this is that glium isn't very friendly to sharing access to the gl context. You'll probably run into similar issues with other of the many global states if you try using glium alongside something else that also accesses the same context.

**Comment by nical** [comment]
@kvark perhaps we should add some debug only code that queries global states such as GL_FRAMEBUFFER_SRGB at the beginning of each frame and warns/panics if they aren't the value we expect (after having explicitly set it during initialization for good measure).

**Comment by kvark** [comment]
@nical that would be fine, yeah
