### ISSUE TITLE
Scrolling issues

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#327]
These are some of the issues that we ran into in Firefox:
http://keithclark.co.uk/articles/pure-css-parallax-websites/demo3/ 
https://bug1148582.bmoattachments.org/attachment.cgi?id=8585108

**Comment by mrobinson** [comment]
The second case is working well in Servo now, but the first one definitely has clipping issues.

**Comment by nical** [comment]
The second test case now works in gecko as well, the first one is still broken.

**Comment by glennw** [comment]
As far as I can tell, these are both working correctly in Gecko + WR now.

**Comment by staktrace** [comment]
When scrolling the first link on macOS firefox nightly, I see artifacting at certain points. For example at the moment where the "Base Layer" text aligns with the "Background Layer" text things go weird, with a rect of a different color showing up and some of the tabs backrounds going partially green. This looks an awful lot like the issues in #2133, so we should probably track it there.
