### ISSUE TITLE
[feature request] Supporting > 60hz displays ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/webrender#3280]
I believe that Firefox currently with or without webrender, limit the vsync to 60hz,
Which mean that ~90% of all new screens are experiencing 60hz in Firefox instead of what is the new standard: 75hz. That is a big low Hanging Fruit.
Secondly 90hz to 240hz screens are a real thing since many years and dramatically improve the feeling of rendering.
And, mozilla want to be the best suited browser for VR, which often use 90+hz !

Also the smartphone world evolve quickly,  sharp phones, the Asus rog phone and the Razer phone have high refresh rate display, and the last iphones have 120hz display too ! As always, when the iPhone add a new technological feature, 1 year later every Phone maker will copy it, thus it is highly likely that high refresh rate phones become the norm in 2019,just like 2k phones became the norm in 2018 New phones. 

I am personally going to buy a razer-phone 2 (120hz) so I will be able to test Firefox support, on android. 

I guess the implementation would be straightfroward, that is changing the vsync from an hardcoded 60hz to $SCREEN_FREQUENCY. 
A value that should be manually settable in about:config. 
And the default value should be gettable from many apis I guess. 
For example, here How to get it on Windows : 
https://stackoverflow.com/questions/4110731/how-to-get-the-screen-refresh-rate
Vresfresh could also be used ? https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-getdevicecaps

But I guess https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_KHR_get_display_properties2 is the cross platform way.
All of this is for setting the right vsync for constant refresh rate displays.

A parralel feature, better ? for and only for adaptative refresh rate screens like freesync, gsync and qualcomm qsync would be to allow to turn off vsync.

**Comment by emilio** [comment]
This request probably should live in bugzilla instead of on the WR repo.

**Comment by staktrace** [comment]
Also, firefox does use hardware vsync where possible.

**Comment by jrmuizel** [comment]
Yep. Firefox with or without WebRender runs at the screen frequency today.
