### ISSUE TITLE
Create scroll clip with non-zero scroll delta

### ISSUE THREAD

**Issue by Yatekii** [servo/webrender#3294]
Is there a possibility to initialize a scroll clip I push onto the stack with a non-zero scroll delta?
Scrolling by the desired amount via a transaction is not that I want/can use.

**Comment by kvark** [comment]
@Yatekii you are providing the display list in a transaction anyway (via `set_display_list`), so might as well set the scroll offsets there. It's not like you have to use a separate transaction for this.

**Comment by gw3583** [comment]
Closing, since it sounds like this has been answered. Please reopen if there is further discussion required.

**Comment by Yatekii** [comment]
Actually it has not been answered, I was just too busy to ask again: That's exactly my question: How do I do that without a separate transaction? Because atm there is no initial scroll delta i can add when creating the scrollclip.
