### ISSUE TITLE
Rendering broken when running on GLES

### ISSUE THREAD

**Issue by rmader** [servo/webrender#3319]
When enabling webrender on wayland, some users (including me)[ see broken rendering](https://bugzilla.mozilla.org/show_bug.cgi?id=1500415).
The wayland backend uses EGL, which is currently restricted to GLES. When [enabling desktop GL on EGL](https://bugzilla.mozilla.org/show_bug.cgi?id=1474281), the problem went away (for me). The problem first arised about a month ago, it used to work previously.

![screenshot from 2018-10-19 14-17-37](https://user-images.githubusercontent.com/6313774/48628301-19722c80-e9b7-11e8-8ea4-6b0c69a13fe5.png)

So far it has been observed on the intel and radeon driver

**Comment by dralley** [comment]
The bugzilla is marked as resolved, should this issue be closed?

**Comment by rmader** [comment]
Yep :)
