### ISSUE TITLE
Flatten the transforms of non-preserve-3d contexts

### ISSUE THREAD

**Issue by kvark** [servo/webrender#3394]
When a transform (or perspective) is specified on on a reference frame for a stacking context that's not `Preserve3D`, we are currently still applying the transform unchanged and ignore the Z component. The problem case arises when there are multiple 3D transforms stacked up, since we'd innocently multiply the transformation matrices, and Z coordinates would start to affect the positioning, which is undesirable for `Flat` style contexts.

What we should be doing is erasing/resetting the Z row of the transformation if its style is `Flat`.

cc @mattwoodrow @emilio

**Comment by emilio** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1512537 for this :)
