### ISSUE TITLE
drop-shadow() filter is clipped if its size changes in response to property animations

### ISSUE THREAD

**Issue by mstange** [servo/webrender#3423]
https://bugzilla.mozilla.org/show_bug.cgi?id=1514384

[Testcase 1](https://bug1458661.bmoattachments.org/attachment.cgi?id=8972679)
[Testcase 2](https://bug1458661.bmoattachments.org/attachment.cgi?id=8972680)

The animated elements get clipped during the animation. They should always be completely visible

**Comment by dralley** [comment]
The linked bugzilla is marked "resolved fixed", should this bug be closed?
