### ISSUE TITLE
preserve scroll state

### ISSUE THREAD

**Issue by cztomsik** [servo/webrender#3476]
Hey, I'm doing very thin node.js + reactjs prototyping platform based around webrender and I'm currently stuck with scrolling - it works fine until I send new transaction with display list (`preserve_frame_state = true`)

I was looking into `examples/scrolling.rs` and it seems to have the same problem (scroll state is not preserved).

I was looking into servo too but I couldn't find anything helpful - I've found `get_scroll_node_state()` but I'm not sure if that value is actually used anywhere

What has to be satisfied in order to preserve scroll state?

**Comment by nc4rrillo** [comment]
Are you passing an `ExternalScrollId` to your call to `define_scroll_frame`? The scrolling offsets are stored in a HashMap keyed off of that ID and applied after a scene is built.

**Comment by cztomsik** [comment]
that helped, thx!
