### ISSUE TITLE
export frames

### ISSUE THREAD

**Issue by wellorange** [servo/webrender#3541]
Hello, I didn't find a way to export frames. Just like skia's bitmap.getPixels(), can anyone help me? I hope the author can add a demo that exports png images through the frame.

**Comment by nical** [comment]
You can run some code after `Renderer::render` which does a read-back of the framebuffer using `renderer.device.read_pixels`. This is what Wrench, Gecko and Servo do for reference testing.

**Comment by kvark** [comment]
See where [Wrench does it](https://github.com/servo/webrender/blob/918dcca08ff680387497b8c59d3872bcba39473f/wrench/src/reftest.rs#L551).

**Comment by wellorange** [comment]
I followed the wiki's debugging steps and the following error occurred.

orange@DESKTOP-5LMR3CV MINGW64 ~/Documents/code/rust/webrender (master)
$ cd wrench/
orange@DESKTOP-5LMR3CV MINGW64 ~/Documents/code/rust/webrender/wrench (master)
$ cargo run show reftests/image/tile-size.yaml --features 'webrender/debugger'
warning: C:\Users\orange\Documents\code\rust\webrender\Cargo.toml: unused manifest key: patch.crates-io.serde_derive.feature
warning: C:\Users\orange\Documents\code\rust\webrender\Cargo.toml: unused manifest key: workspace.license
   Compiling webrender_api v0.58.0 (C:\Users\orange\Documents\code\rust\webrender\webrender_api)
   Compiling webrender v0.59.0 (C:\Users\orange\Documents\code\rust\webrender\webrender)
   Compiling wrench v0.3.0 (C:\Users\orange\Documents\code\rust\webrender\wrench)
    Finished dev [unoptimized + debuginfo] target(s) in 57.25s
     Running `C:\Users\orange\Documents\code\rust\webrender\target\debug\wrench.exe show reftests/image/tile-size.yaml --features webrender/debugger`
error: Found argument '--features' which wasn't expected, or isn't valid in this context

USAGE:
    wrench.exe show [FLAGS] [OPTIONS] <INPUT>

For more information try --help
error: process didn't exit successfully: `C:\Users\orange\Documents\code\rust\webrender\target\debug\wrench.exe show reftests/image/tile-size.yaml --features webrender/debugger` (exit code: 1)

orange@DESKTOP-5LMR3CV MINGW64 ~/Documents/code/rust/webrender/wrench (master)
$

**Comment by nical** [comment]
You need to add `--` between `carg run` and `show` so that cargo forwards the dash arguments to wrench instead of trying to interpret them. I updated the wiki page.

**Comment by wellorange** [comment]
The problem still exists.

orange@orange:~/work/rust/webrender/wrench$ cargo run -- show reftests/image/tile-size.yaml --features 'webrender/debugger'
warning: /home/orange/work/rust/webrender/Cargo.toml: unused manifest key: patch.crates-io.serde_derive.feature
warning: /home/orange/work/rust/webrender/Cargo.toml: unused manifest key: workspace.license
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `/home/orange/work/rust/webrender/target/debug/wrench show reftests/image/tile-size.yaml --features webrender/debugger`
error: Found argument '--features' which wasn't expected, or isn't valid in this context

USAGE:
    wrench show [FLAGS] [OPTIONS] <INPUT>

For more information try --help

**Comment by staktrace** [comment]
Try dropping the `--features webrender/debugger` since that feature should be included in a default wrench build. But if it's needed, it would go before the `--` because it's a argument for `cargo`

**Comment by wellorange** [comment]
@staktrace  Ok, thank you, you can run it.

**Comment by kvark** [comment]
I suppose the issue is resolved then. Please feel free to re-open otherwise.
