### ISSUE TITLE
Mirrored textures

### ISSUE THREAD

**Issue by max-frai** [servo/webrender#3544]
With latest nightly and enabled webrender I see mirrored textures on some extensions popups and sometimes on pages:

![screen shot 2019-02-08 at 12 47 12 pm](https://user-images.githubusercontent.com/24208746/52474003-e9928980-2b9f-11e9-95f2-0cb5761469d0.jpg)

**Comment by gw3583** [comment]
Hi, there is a fix for this landed in the last few hours [1]. It should be in the next nightly. Having said that, I could only ever reproduce on popups, I've never seen it on pages. In the next nightly, could you confirm if that fixes it on popups and/or page content?

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1525740

**Comment by gw3583** [comment]
Could you also report what OS you are running, and what the URL(s) are that show this bug on page content, and I'll see if I can reproduce.

**Comment by max-frai** [comment]
Can't reproduce it again on pages. It was like thin line through the page.
Mac os x. With latest update everything works ok. Thank you.

**Comment by gw3583** [comment]
OK, I'll close for now. Please re-open if you see this again. Thanks!
