### ISSUE TITLE
Update to Serde 1.0.87

### ISSUE THREAD

**Issue by Yoric** [servo/webrender#3555]
I'm having difficulties updating Firefox third-party dependencies because webrender locks serde to `1.0.8` while the latest 1.0 version is `1.0.87`, which is used by other crates in Firefox.

Would it be possible to update `webrender_api` to use either `1.0.87` or `^1.0`?

**Comment by nical** [comment]
cc @Gankro

**Comment by staktrace** [comment]
Somebody needs to push a new `deserialize_from_enums10` branch to `servo/serde` that is the same as `deserialize_from_enums9` but rebased to upstream `serde 1.0.87`. Then we can update WR to use that.

@Eijebong did this last time I think

**Comment by staktrace** [comment]
I rebased and pushed a `deserialize_from_enums10` branch. Will post a m-c patch to bump webrender to it.

**Comment by staktrace** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1529117 for it. We can close this issue and continue over there.

**Comment by staktrace** [comment]
So the new branch causes a failure in the webdriver test suite in gecko. So either I screwed up the rebase somewhere (which is quite likely since it was nontrivial) or serde has changed something internally.

**Comment by atouchet** [comment]
WebRender is now using serde 1.0.88. Can this be closed now?

**Comment by Eijebong** [comment]
It can, yeah. Thanks
