### ISSUE TITLE
Remove SHA256 dependency (since it's only used for hashing shaders)?

### ISSUE THREAD

**Issue by fschutt** [servo/webrender#3586]
Right now webrender has a dependency on sha256 which is only used once, to verify the unique-ness of an OpenGL source string (by hashing the vertex and the fragment shader together):

https://github.com/servo/webrender/blob/607ce5d4ee77ffaafc6dc418d9b0dc37836d6026/webrender/build.rs#L36

This is the only place where the sha256 dependency is used - only during build time, i.e. the performance of the hasher itself doesn't really matter, just that the resulting program hash is unique. In my fork of webrender, I've removed this dependency in favor of  `std::hash::DefaultHasher` (replacing the `[u32;8]` sha256 hash with a simple `u64`) and haven't noticed any impact on functionality (but reduced the dependencies by about 10 crates). So I wanted to ask if it would be possible to remove the `sha256` dependency, because `DefaultHasher` is good enough. Another alternative would be to ditch the hashing approach altogether (since webrenders vertex / fragment shaders are always the same, they don't change at runtime), and give each vertex + fragment shader a unique `VertexShaderId` / `FragmentShaderId`.

**Comment by cztomsik** [comment]
Here's related commit https://github.com/maps4print/azul-dependencies/commit/1f2ce1775fe72687bf460bb176407c88f72c3131

@fschutt are you going to do PR? I'd like to reduce deps too so I'm wondering if this will get merged or if I should do my own fork (I'd like to use your fork but it's monorepo and I'm a bit puzzled how to use it)

**Comment by dralley** [comment]
@fschutt Are you going to make a PR?

**Comment by fschutt** [comment]
oh yeah, forgot about this, I'm currently a bit busy. I'll do the PR when I upgrade webrender.

**Comment by dralley** [comment]
@fschutt Will that happen soon or would you mind if I ported the diff?

**Comment by fschutt** [comment]
@dralley I'm currently working on un-vendoring dependencies for azul, and getting it ready for publishing. I'm planning to upstream my changes tomorrow, because I have some free time then. I can't just rebase the old commit, because a lot has changed, also I think hashing the source isn't even neccessary, since you can just assign a unique ID to every shader source file. I'll do it tomorrow, don't worry.
