### ISSUE TITLE
add_image encourages copies of image data

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#359]
add_image() currently takes a vec<u8> this means that if owners of the image data want to keep it around they have to make a copy. This is what currently happens with servo. It would be much better for add_image to take a reference to this data to avoid the copy.

**Comment by nical** [comment]
Note that ImageData now stores an ```Arc<Vec<u8>>``` instead of a ```Vec<u8>``` which means servo does not need to copy the image buffer anymore (unless the api sender is in a different process in which case it's a more complicated story).

**Comment by kvark** [comment]
For IPC, `Arc` still implements serialization, but the whole vector will be transferred over regardless, so there is not much benefit.

**Comment by glennw** [comment]
We now have the external image API, which can be used to supply images with zero-copy overhead.
