### ISSUE TITLE
Update to Glutin 0.21.0

### ISSUE THREAD

**Issue by ZeGentzy** [servo/webrender#3612]
Hey folks. Glutin v0.21.0 is out.

**Comment by staktrace** [comment]
We're still using glutin 0.17. There was an attempt to update to 0.19 (#3546) but it was never completed. Testing an update to 0.21.0-rc2 at this point would be a bit time-consuming as there's a bunch of stuff that would need to be fixed up, although you're welcome to try!

**Comment by atouchet** [comment]
There was a WIP PR to update glutin to 0.19 in #3343 but it apparently stalled as @djg [wasn't sure how to implement swap_buffers](https://github.com/servo/webrender/pull/3338#issuecomment-441411147).

**Comment by atouchet** [comment]
This was done in #3699.
