### ISSUE TITLE
Add support for background-repeat: space;

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#363]
This does not seem expressible with the current display items.

**Comment by glennw** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat
https://drafts.csswg.org/css-backgrounds-3/#the-background-repeat

**Comment by glennw** [comment]
The webrender work is here - https://github.com/servo/webrender/pull/414 - still needs the servo-side changes to parse those types and pass them through the display lists.

**Comment by glennw** [comment]
This landed https://github.com/servo/servo/pull/13331
