### ISSUE TITLE
Python bindings? 

### ISSUE THREAD

**Issue by stuaxo** [servo/webrender#3660]
Are there going to be python bindings for Web render.

I implement a python creative coding app (shoebot) and need a new graphics core.

Web render seems to implement things in the way I want, can I drive it from python?

(cffi would be best as it has a good Pypy story)

**Comment by kvark** [comment]
I don't know the details of Python-Rust interop, but perhaps [webrender_bindings](https://searchfox.org/mozilla-central/source/gfx/webrender_bindings) from Gecko would be useful if you need to cross C boundary?

**Comment by stuaxo** [comment]
Cheers, I will have a look - so I guess there isn't anything yet, and definitely a while until there is something I can install from pip.
