### ISSUE TITLE
Artifacts appearing around signup text boxes on github.com

### ISSUE THREAD

**Issue by dralley** [servo/webrender#3703]
Firefox Nightly 70, 2019-07-13
Windows 10
AMD Vega 56 w/ driver 19.7.1
gfx.webrender.all = True

I navigated to www.github.com and selected the "username" text box to sign up, and began typing.  I was trying to reproduce a different problem that had been posted on reddit [0] (and was not able to do so) but found a different issue instead.

[0] https://www.reddit.com/r/firefox/comments/cbwwop/webrender_testing_help_wanted/

The halo/highlight around the text box would get white artifacts that flickered into and out of existance.  They seemed to occur more frequently when typing into the text box, but they also occasionally happened without any keyboard or mouse activity.

Video: https://media.giphy.com/media/Y1NANdLhYRfZBVFM5a/giphy.gif

They most frequently appeared on the left side of the text box, but did also appear on other parts of the text box.

The "password" and "email" text boxes had the same problem, not just the "username" one.

I attempted to reproduce on other text boxes on github.com by e.g. writing an issue, writing a comment, but did not see the same problem elsewhere.

**Comment by dralley** [comment]
If this needs to be re-filed as a bugzilla, I can do so.

**Comment by nical** [comment]
@dralley We'd appreciate if you did (we do a better job at tracking things on bugzilla). Thanks!

**Comment by dralley** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1566099

**Comment by dralley** [comment]
Fixed
