### ISSUE TITLE
``ImageFormat::R8`` rendered in red tints.

### ISSUE THREAD

**Issue by Kibouo** [servo/webrender#3706]
I have a greyscale image and added ``ImageFormat::R8`` to its descriptor. However, the image is rendered in red tints. The [docs](https://doc.servo.org/webrender_api/enum.ImageFormat.html#variant.R8) state that "[...] The 'red' doesn't map to the color red per se [...]", so I expected a greyscale as default instead.

The current solution I use is copying the greyscale values to fit RGB. This isn't memory efficient so I doubt it's the correct approach. 

Not sure whether this is a bug, or simply something that I don't know of that has to be set _somewhere_. Happy to provide extra info but I don't know what might be relevant.

**Comment by nical** [comment]
WebRender doesn't know how to render greyscale images to the screen. So if you use an R8 image in an image display item the image will be passed to a regular color shader, and the latter will trat it as RGB with zeroes in the green and blue channels, hence the tint.
R8 images are used in webrender to create alpha masks. If you want to render a greyscale image you first have to convert it to RGB before submitting it to WebRender.

**Comment by Kibouo** [comment]
That clears up the confusion. Thank you!
