### ISSUE TITLE
Degraded text quality due to full pixel alignment of glyphs on Linux

### ISSUE THREAD

**Issue by gh5681** [servo/webrender#3716]
On Linux, WebRender generates glyphs that use subpixel anti-aliasing. However, when selecting which glyph should be used next, WebRender apparently does not take subpixel advances into account but instead always chooses the same glyph, aligned to full pixel increments. This leads to degraded text quality, as can be seen in the images below.

`letter-spacing`:
![letter-spacing](https://user-images.githubusercontent.com/53127921/61584523-9c481a00-ab38-11e9-8865-62c60d441d2d.png)
`margin-left`:
![margin-left](https://user-images.githubusercontent.com/53127921/61584524-9e11dd80-ab38-11e9-837a-cfc85b7ff011.png)

This effect is most apparent on websites that use the `letter-spacing` CSS property (first image). Note that such websites can be found in the wild, for example [here](https://trailofbits.github.io/ctf/). This leads to letters "dancing around", as can be seen in the first image. Shifting text by a sub-pixel amount using the `margin-left` CSS property (second image) also suggests that the glyphs are always aligned to full pixel increments. The text starts at the next pixel as soon as it is shifted by >0.5 px;

Side notes:
Apparently Direct2D chooses from glyphs quantized to 1/4 subpixel increments, and WebRender also seems to quantize to 1/4 subpixel increments when building the atlas:
https://github.com/servo/webrender/blob/77ff7ab32728b864dc85500ad476ca52f929a339/webrender/src/glyph_rasterizer/mod.rs#L560-L581
Somehow this does not end up on the screen when rendering a text run. I have been looking over the WebRender source over the last couple of days, however, new to this codebase, I was not able to find the exact reason that is causing this.

I also tried changing the FreeType `hintstyle`, `lcdfilter` and `rgba` mode on my system, to no avail, there are of course visible changes with regard to the hinting and anti-aliasing but the horizontal glyph placement is the same in all cases. Please let me know if you can reproduce this behavior and whether this is the correct place to report this. 

If you want to replicate the results above, use the current Firefox, activate WebRender and use [this HTML file](https://github.com/servo/webrender/files/3414018/font-test.html.txt). (I installed the Microsoft Arial font on my Linux machine to get comparable results on Linux and Windows.)

**Comment by kvark** [comment]
Thank you for the great report @gh5681 and investigation!
Please file/copy the [bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Graphics%3A+WebRender) which serves as the main tracker now.
cc @lsalzman

**Comment by gh5681** [comment]
Thanks.
https://bugzilla.mozilla.org/show_bug.cgi?id=1568603

**Comment by dralley** [comment]
Marked "RESOLVED INVALID"

**Comment by dralley** [comment]
I assume that means this can be closed?
