### ISSUE TITLE
Figure out the bindings story for webrender

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#374]
We should figure out what we're going to do here. The simplest option that comes to mind is just maintaining hand written C bindings in the webrender repository. I'd be interested to hear what our other options are.

**Comment by metajack** [comment]
One other option might be to just communicate with it via IPC? I suppose you'd still need enough bindings to start the main two threads.

We've typically planned to do this by having a maintained C entry point, but we've never had any real consumers so this hasn't gotten off the ground except for our CEF bindings. It's not hard to do, and you might look at the rust-url binding @valenting is working on for an example: https://github.com/valenting/rust-url-capi

**Comment by jrmuizel** [comment]
Looking around and thinking more, it seems like the best thing to do here is just wrap the webrender api in C. It seems like that should be more workable than trying to have C++ on one side of the ipc pipe as we don't need to worry about any of the serialization.

The webrender api seems reasonably amenable to wrapping in C.

**Comment by glennw** [comment]
I agree, this seems like the simplest option.

**Comment by andreasgal** [comment]
Did anyone sketch out yet what the C API would look like?

**Comment by jrmuizel** [comment]
Gecko is currently using https://github.com/jrmuizel/webrender/blob/bindings/webrender/webrender.h and https://github.com/jrmuizel/webrender/blob/bindings/webrender/src/bindings.rs

These are currently pretty incomplete but we're probably just going to iterate them toward what we need.

**Comment by glennw** [comment]
@jrmuizel Should we close this, unless there is something actionable that needs to be done here?

**Comment by jrmuizel** [comment]
We can close this. See https://hg.mozilla.org/projects/graphics/file/tip/gfx/webrender_bindings

**Comment by jrmuizel** [comment]
Our handwritten bindings are going to be replaced by the generator from here: https://github.com/jrmuizel/wr-binding/
