### ISSUE TITLE
Text rendering broken (Firefox/Wayland)

### ISSUE THREAD

**Issue by myfreeweb** [servo/webrender#3759]
(FreeBSD 13-CURRENT, drm-v5.0, Mesa master, wlroots/Wayfire master, HiDPI displays; both RadeonSI (Vega) and Iris (Kaby Lake) are affected)

Everything was fine, then text stopped rendering (actually for some time in Firefox there were weird artifacts instead of glyphs, but in my Firefox build today it's also just completely text-less) :(

I was testing with the `multiwindow` example, git bisect found 58bf341d137d12252b897713b93def40b35f2259 as the culprit.

up until 90bdd7224738c246835da357fd36149a33966925, reverting 58bf341d137d12252b897713b93def40b35f2259 works fine, then the code changed and that "hack" was removed, but text's still gone.

**Comment by myfreeweb** [comment]
hm, at least in the example, seems HiDPI related. (HiDPI is actually a bit broken with winit+wayland)

**Comment by myfreeweb** [comment]
Replaying the [capture](https://send.firefox.com/download/217ff8ada5132aba/#hq7Q8gEIZBXlU20LZ1bs0g) with wrench master, same result

![wrbug](https://user-images.githubusercontent.com/208340/65244509-5e914e80-daf3-11e9-9134-d318733fac1e.png)

**Comment by kvark** [comment]
Thank you for the bug report! Would you mind copying/moving it to https://bugzilla.mozilla.org with "Graphics: WebRender" component?

**Comment by myfreeweb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1582485

**Comment by myfreeweb** [comment]
It broke in 94f434fc0239e925830a8d929f87300777f1f11d actually.

**Comment by dralley** [comment]
BZ marked duplicate, actual BZ is https://bugzilla.mozilla.org/show_bug.cgi?id=1578598

**Comment by myfreeweb** [comment]
Was related to `glxtest` not working without xwayland.
