### ISSUE TITLE
Rendering glitches on macOS Catalina

### ISSUE THREAD

**Issue by yaomtc** [servo/webrender#3783]
When I run Firefox with `gfx.webrender.all` set to `true`, much of the interface text becomes red or cyan and illegible, colors change, and things look generally messed up.
 
<img width="2011" alt="Screen Shot 2019-10-28 at 15 31 15" src="https://user-images.githubusercontent.com/5534045/67711273-07a35280-f998-11e9-9832-4789e9327e54.png">

**Comment by yaomtc** [comment]
<img width="2012" alt="Screen Shot 2019-10-28 at 15 35 33" src="https://user-images.githubusercontent.com/5534045/67711586-a62fb380-f998-11e9-968f-2546a1655583.png">
<img width="2012" alt="Screen Shot 2019-10-28 at 15 35 44" src="https://user-images.githubusercontent.com/5534045/67711587-a62fb380-f998-11e9-9c73-75cab1aef193.png">

**Comment by yaomtc** [comment]
Speciifications:

- MacOS Catalina (10.15 - 19A603)
- iMac (Retina 5K, 27-inch, Mid 2015)
- 3.3 GHz Quad-Core Intel Core i5
- 8 GB 1600 MHz DDR3
- AMD Radeon R9 M290 2 GB

**Comment by kvark** [comment]
I think this is https://bugzilla.mozilla.org/show_bug.cgi?id=1558167

**Comment by kvark** [comment]
@yaomtc please attach your "about:support"

**Comment by kvark** [comment]
The bugzilla report was closed because it's reported for the release Firefox, where the fix hasn't reached yet, but WR isn't enabled by default. You'd need to switch to nightly to get it, for now.
Going to close the issue, please re-open if you see it on Nightly!

**Comment by yaomtc** [comment]
Thanks, I forgot to check bugzilla!
