### ISSUE TITLE
Potential invariant broken in freelist

### ISSUE THREAD

**Issue by maxnordlund** [servo/webrender#3785]
I was browsing the source when I noticed that `clear` seems to break the invariant commented in `new` that the freelist is never completely empty. I don't know enough about this project, let alone Rust, to be able to understand if this needs fixing, but I thought I should at least make an issue.

https://github.com/servo/webrender/blob/918df6bfa7fc9f3c8ce87b8232702f7b46667ed3/webrender/src/freelist.rs#L155-L158

https://github.com/servo/webrender/blob/918df6bfa7fc9f3c8ce87b8232702f7b46667ed3/webrender/src/freelist.rs#L172-L176

**Comment by nical** [comment]
Nice catch! I filed a corresponding entry on bugzilla here https://bugzilla.mozilla.org/show_bug.cgi?id=1592225 and I'll submit a fix shortly.

Thanks!

**Comment by maxnordlund** [comment]
No problem, I copied over the code snippets to bugzilla for completeness sake.

**Comment by atouchet** [comment]
This is now marked as RESOLVED FIXED on Bugzilla. Was this done?

**Comment by nical** [comment]
Yep!
