### ISSUE TITLE
Update serde

### ISSUE THREAD

**Issue by nox** [servo/webrender#3798]
Now that derive_more 0.99 is out, derivative (through glutin, but latest glutin doesn't use derivative anymore) and serde_derive 1.0.88 are the only two remaining things that still depend on syn 0.15.

**Comment by nox** [comment]
Where is the documentation for why a patched serde is necessary, btw?

**Comment by jrmuizel** [comment]
@Gankra

**Comment by atouchet** [comment]
serde is no longer pinned to 1.0.88 as of 3bc0039880bfc4880e17da3cceccbec66178c7c2.

**Comment by Gankra** [comment]
the serde patch should have been removed months ago, fwiw. it was obsoleted when we shipped peek-poke.

**Comment by nox** [comment]
Nice, good to know.;
