### ISSUE TITLE
New crates.io release?

### ISSUE THREAD

**Issue by tiffany352** [servo/webrender#3829]
The last release was almost a year ago, and it seems like there's been some breaking changes since then, and a ton of work since then as well including important bugfixes.

I'm currently using a git revision because of how old the current release is, but if I ever want to publish my crate to crates.io it seems like I'd have to downgrade to an older version of webrender.

**Comment by kvark** [comment]
@tiffany352 I don't think making a crates release would harm, but it may involve some work, like making sure all the dependencies (e.g. peek-poke) are on crates io as well. So it's not a trivial thing to do. Hopefully, somebody finds time. @nical you want to volunteer?

**Comment by nical** [comment]
Yeah it's been a while, I'll look into it.

**Comment by jrmuizel** [comment]
The work is happening here: https://bugzilla.mozilla.org/show_bug.cgi?id=1609049

**Comment by atouchet** [comment]
This was done: https://crates.io/crates/webrender/0.61.0
