### ISSUE TITLE
Move peek-poke into a separate repo

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#4018]
Now that things outside WR are using peek-poke (e.g. wgpu-core) we should probably move peek-poke out of this repo so we don't have two (different) copies of it in the mozilla-central tree. If we split this out and publish to crates.io WR can pull it from there (and from third_party/rust in m-c).

**Comment by kvark** [comment]
Plot twist: wgpu-core no longer uses peek-poke. The lack of clarity on where it lives, why it depends on euclid, and total unsafety of peek-poke contributed to this decision.

**Comment by staktrace** [comment]
Ok, great. So then I guess the next wgpu-core import into m-c will remove third_party/rust/peek-poke and eliminate my source of confusion this morning.
