### ISSUE TITLE
add_raw_font eat too much memory on MacOS

### ISSUE THREAD

**Issue by Hankszhang** [servo/webrender#4033]
I use [font-kit](https://github.com/servo/font-kit) to load a system font called `Heiti SC Light`,  the font info shows as below:
![image](https://user-images.githubusercontent.com/13467398/88476445-eabd9f00-cf6a-11ea-806c-707926e54b51.png)

When I called `add_raw_font` to add this font_data into webrender , I got a memory issuse: on MacOS, the memory usage of my demo increased about 380 MB (**_nearly 7 times of my expectation_**),  while on Windows it just increased 60MB. 

- memory usage with font added:
![image](https://user-images.githubusercontent.com/13467398/88476695-222d4b00-cf6d-11ea-87db-a3e9401e032f.png)

- memory usage without that font added:
![image](https://user-images.githubusercontent.com/13467398/88476743-73d5d580-cf6d-11ea-8bc5-fdf79df0ae8c.png)

I've tested many other fonts,  all of them lead to the same result. 

Is this reasonable on MacOS?

**Comment by jrmuizel** [comment]
Does it help if you run with RAYON_NUM_THREADS=1

**Comment by Hankszhang** [comment]
> Does it help if you run with RAYON_NUM_THREADS=1
 
So sad , this configuration doesn't help

**Comment by kvark** [comment]
We are initializing the font context separately on every worker. This was done in an assumption (I think?) that the fonts don't weight as much, which is clearly not the case here.
