### ISSUE TITLE
Does webrender support partially update?

### ISSUE THREAD

**Issue by kaiwk** [servo/webrender#4046]
I'm using `WebRender` with `glutin`, I know little about graphics, so bear with me...

`DisplayListBuilder` has `push_xxx` methods, but not something like `update_xxx`. What if only some area in the window need update?  Or `WebRender` just update the whole window every time?

By the way, i found `wrench` is very useful as `examples` does, but it seems some `reftests` simply doesn't work. e.g.`cargo run -- show reftests/scrolling/xxxx.yml`, none of them can really scroll.

**Comment by nical** [comment]
At the moment webrender updates the entire representation of the scene every time something updates at the API level. However it is able to figure out frame after frame that some things haven't changed and can do partial updates when rendering if you set the right parameter in RendererOptions.
One way to avoid re-building the entire display list is to break the scene into multiple pipelines and put them together with the IFrame display item.
