### ISSUE TITLE
text shaping: HarfBuzz vs DirectWrite/Core Text

### ISSUE THREAD

**Issue by kaiwk** [servo/webrender#4074]
Hi, WR teams,

I found WebRender use DirectWrite/Core Text for text shaping,  but it looks like [servo use HarfBuzz](https://github.com/servo/servo/blob/9e6da58d7793a4576fef38446457e1073a19cd5e/components/gfx/text/shaping/mod.rs#L8).

Why prefer DirectWrite/Core Text, are they more performant than HarfBuzz?

**Comment by jrmuizel** [comment]
WebRender doesn't do any text shaping. The uses of DirectWrite and CoreText are for glyph rendering.
