### ISSUE TITLE
Support more sophisticated hit testing for scrolling touch action

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#411]
The touch-action property along with event listeners require us to be able to hit test at a display item level.

See: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
@staktrace

**Comment by staktrace** [comment]
The bugzilla bug that is tracking this issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1389149

**Comment by staktrace** [comment]
Note that I'm using this issue to specifically track putting touch-action/event listener info (together I refer to this as "event region info") into the WR display list. This also covers adding dummy display items where needed for content that is not user-visible but does affect hit-testing. Actually implementing the hit-test and exposing this information back out to the caller is covered by #1575.

**Comment by staktrace** [comment]
The changes in #1744 seem to be sufficient for what I wanted here. My plan is to use the u8 field in the ItemTag as a bitmask to store the touch-action information. We might need to expand it to a u16 later but for now a u8 should be ok. Closing this issue; the rest of the work is all gecko-side as far as I can tell.

**Comment by staktrace** [comment]
Oh, I can't actually close this issue. But somebody should.
