### ISSUE TITLE
Hangs at layout rendering

### ISSUE THREAD

**Issue by l4l** [servo/webrender#4182]
Using Firefox (82.0.3 from [arch repo](https://www.archlinux.org/packages/extra/x86_64/firefox/)) with WebRender compositor (i.e. `gfx.webrender.all` & `gfx.webrender.enabled` are set), simply clicking on "Add reaction" button at gitlab (for both self-hosted & cloud ones) freezes UI for ~7 seconds:

![Screenshot_2020 12 14_12:53:56](https://user-images.githubusercontent.com/5658339/102067089-b6f4f000-3e0b-11eb-958a-786e1adb6b24.png)

Full profile: [profile.json.zip](https://github.com/servo/webrender/files/5687943/profile.json.zip)

**Comment by kvark** [comment]
It's a bit weird that it hangs in Layout if it's related to WebRender. Are you sure this hang doesn't happen without WebRender?
Please file an issue to https://bugzilla.mozilla.org/ !

**Comment by l4l** [comment]
Hm, that's quite a weird coincidence, I've only found it once I switched to webrender. It seems that webrender is not the issue reason indeed. Switching back to basic compositing leads to the same issue.
