### ISSUE TITLE
Authoring and licensing concerns (glsl-to-cxx)

### ISSUE THREAD

**Issue by phaazon** [servo/webrender#4196]
Hello :wave:,

> Disclaimer: I come in peace :heart: 

It was brought to my ears that `glsl-to-cxx` uses my [glsl crate](https://crates.io/crates/glsl), which I find amazing. I was about to make a PR to bump your current version to support the latest (glsl-6.0) when I realized the content of the `hir.rs` file is largely a copy of the `syntax.rs` file of my crate. Even the comments are copied. Some examples for comparisons:

- [`ExprKind` from webrender](https://github.com/servo/webrender/blob/master/glsl-to-cxx/src/hir.rs#L1309-L1352) is an almost verbatim copy of [`Expr` from glsl](https://github.com/phaazon/glsl/blob/glsl-4.1.1/glsl/src/syntax.rs#L679-L719).
- [`TranslationUnit` from webrender](https://github.com/servo/webrender/blob/master/glsl-to-cxx/src/hir.rs#L1387-L1444)   is a verbatim copy of [`TranslationUnit` and its impls from glsl](https://github.com/phaazon/glsl/blob/glsl-4.1.1/glsl/src/syntax.rs#L809-L863)
- [`SimpleStatement` from webrender](https://github.com/servo/webrender/blob/master/glsl-to-cxx/src/hir.rs#L1495-L1552) is a verbatim copy of [`SimpleStatement from glsl](https://github.com/phaazon/glsl/blob/glsl-4.1.1/glsl/src/syntax.rs#L1004-L1076).

I’m not going to list them all because pretty much almost all the types are copied, along with their methods and helpers.

---

[My glsl crate](https://github.com/phaazon/glsl) is licensed under **BSD-3-Clause**, which first clause states:

> [* Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.](https://github.com/phaazon/glsl/blob/master/glsl/LICENSE#L8-L9)

I don’t consider _using_ a crate a problem, as redistribution is done correctly and automatically for use via cargo / crates.io, but here since you have copied a non-negligible amount of code from my `glsl` crate, I would kindly asked you to fix those licensing terms by adding everywhere it’s needed the BSD-3-Clause excerpt as written in the [glsl license](https://github.com/phaazon/glsl/blob/master/glsl/LICENSE) — the link points to the latest license, but it remained unchanged since the beginning of the history of the `glsl` project. I would also like to bring to your attention that if you use that much code of mine, I kind of qualify as a co-author for this current crate — `glsl-to-cxx`, so I would kindly ask you to add my as an author to your `Cargo.toml` file.

---

I regret I wasn’t informed earlier so much code was copied without respecting the license. I know that it can get confusing how to cope with licenses, especially since cargo / crates.io do all the work for use / redistribution, but modifying and distributing manually extracted portion of code of mine without mentioning my name is something we need to discuss.

**Comment by jrmuizel** [comment]
I've put up a change to fix this here: https://phabricator.services.mozilla.com/D100494. Let me know if this matches your expectations.

`glsl-to-cxx` was put together in a hurry and I think we just forgot to properly attribute this when we added the licensing headers. Sorry about that.

**Comment by phaazon** [comment]
It’s okay @jrmuizel, I completely understand this and I recall the time you told me about the project :slightly_smiling_face: . The hunk seems okay. Thanks a lot for the quick reaction and I’m glad about the resolution. :bow:
