### ISSUE TITLE
Can not show Gif with `UploadMethod::PixelBuffer(ONE_TIME_USAGE_HINT)` with Angle

### ISSUE THREAD

**Issue by kaiwk** [servo/webrender#4238]
Hi,

I use `image::codecs::gif::GifDecoder` (from [image_rs](https://github.com/image-rs/image)) to get GIF frames, and use `WebRender` API: `add_image，push_image (DisplayListBuilder)`, `update_image (Transaction)` to create/update image.  It works well on Windows with glutin, but when it comes to Angle(mozangle),  Gif will not show or only show one or two frames then get stuck (from the log I can see frames keep generated though).

Somehow I find there is [a comment](https://github.com/servo/webrender/blob/8c75d133eb494439a2568a25787bcc4ecec091d0/webrender/src/renderer/mod.rs#L5562-L5564) in `RenderOptions` : ) , and finally I found I have to set `upload_method` to `UploadMethod::Immediate`to get it work with Angle.

Is it a bug? I also want to know more about how these options will affect render's behavior, and advice on how could I make render works well with Angle. 

Thank you!

**Comment by kvark** [comment]
The problem is - D3D11 doesn't support buffer-to-texture copies. We (the graphics team) don't intend to try making this path (in Angle) more efficient, and instead we just recommend using `UploadMethod::Immediate` on Angle.
