### ISSUE TITLE
Where to store pipeline specific options for scrolling behavior

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#425]
We want to implement something like this: `iframe.setOverscrollOptions(options);`.

I managed to send this information to WebRender.

In render_backend.rs, I get this message: `ApiMsg::SetOverscrollOptions(pipeline_id, options)`.

Later, in frame.rs, in `scroll()`, I want to access these options.

I don't know in which struct I should store the options in render_backend.rs to make it accessible in frame.rs.

I only want these options to affect how the document of the pipeline scroll within the iframe. Not pipeline's inner scrollable layers.

**Comment by glennw** [comment]
Instead of a new message, could you pass it through as an extra parameter to SetRootStackingContext message? (This is called once per pipeline here - https://github.com/servo/webrender/blob/master/webrender/src/render_backend.rs#L152)

Then, you can easily store it in the scene pipeline struct here:
https://github.com/servo/webrender/blob/master/webrender/src/scene.rs#L201

Would that work for your requirements?

**Comment by paulrouget** [comment]
> could you pass it through as an extra parameter to SetRootStackingContext message

I could, but I want to be able to change the overscroll options anytime. When is  `SetRootStackingContext` called?

**Comment by paulrouget** [comment]
I stored the overscroll options in `ScenePipeline`. Now, in `frame.scroll()`, I need to access these options. It doesn't sound possible within `Frame` to reach the `scene`.

`RenderBacker`, where `scene` is accessible, calls `iframe.scroll()`, but at this point, we don't know which pipeline is about to get scrolled.

I'm stuck.

Should I pass `scene` as a paramater to `frame.scroll()`?

**Comment by glennw** [comment]
In general the idea is that there is a step which takes the relevant information from the Scene structure and builds the Frame from it. This is mostly handled in the flatten() method in frame.rs. There is a step in this recursive function where it encounters a new iframe / pipeline and extracts the information from the scene. This is probably the right place to put it.

Is your code in a branch pushed to GH? It might be useful to take a look and see how it's being used - how often will these overscroll options be changed? What is it that controls / defines the overscroll options?

**Comment by paulrouget** [comment]
> Is your code in a branch pushed to GH? 

See:
- https://github.com/servo/servo/commit/15c0c88d2f4dbb461b896425d8b111868781111c
- https://github.com/servo/webrender/commit/424f44bfcd5afd26b54b6c3b6c5d55ab2349fe84

> how often will these overscroll options be changed?

No often. Usually, after the user navigated (clicked on link or went back/fwd).

> What is it that controls / defines the overscroll options?

For now, the option tells *where* the user can overscroll (top, right, bottom, left). Later, we want to introduce some more complex options:

```
dictionary OverscrollOptions {
  boolean enabled;
  float minPanDistanceRatio;
  float springFriction;
  float springStiffness;
  float stopDistanceThreshold;
  float stopVelocityThreshold;
}
```

**Comment by glennw** [comment]
@paulrouget I think this can be closed now?

**Comment by paulrouget** [comment]
Yes. I might get back to this later. But as of now, it's not relevant anymore.
