### ISSUE TITLE
Question: Best way to access webrender layout geometry at runtime?

### ISSUE THREAD

**Issue by johnoneil** [servo/webrender#4264]
We've been using webrender and really enjoying it, but there's one area we suspect we may not be using it optimally.
Is there a recommended way to get the actual geometry (post layout) of components on the webrender page? I've seen some debug methods (saving the page to a file) but I suspect there's a better way.
Perhaps iterating over the display list? I haven't seen any example code in that area so it's a bit opaque. Or some part of the API I'm missing?
Currently we're keeping out own records and inferring the eventual dimensions of controls as we pass commands to webrender, but this seems like an interface inversion antipattern.
Any suggestions are appreciated.

**Comment by nical** [comment]
Hi, WebRender's API works by let you build a big display list that represents the scene that is then consumed by WebRender, so you don't have a way to retain this display list and get information from it.

Gecko first computes the layout (resulting in what we call the frame tree) and then uses it to build the WebRender display list.
If you need to be able to retain information about the size of the display items, you'll likely have to manage it with your own data structures.

Out of curiosity (and to make sure I understand what you are after): what information do you infer? WebRender doesn't do any layout computation as far as I know so all of the layout information should already be know by the user of the API while building the display list.

**Comment by johnoneil** [comment]
Thanks for this info Nicolas.
From your answer I can see my thinking wasn't very clear on this. As webrender offers a "hit test" as part of its api I was expecting that it might be the best ground truth for layout information, but If i'm understanding you correctly that best source would probably be our layout engine api.
Appreciate it and I'll close this.
