### ISSUE TITLE
Border radius issue on linux + intel

### ISSUE THREAD

**Issue by glennw** [servo/webrender#434]
It may not be specific to linux/intel, but I can repro it here.

The following test:

```
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <div style="border: 1px solid red; border-radius: 32px; height: 400px; width: 400px;"></div>
  </body>
</html>
```

The rounded corners don't show up at all. If I make the border radius larger, the corners do start to show up but they are incorrect width.

**Comment by glennw** [comment]
cc @mrobinson

**Comment by splav** [comment]
Just to confirm minimal case: Linux AMD/Mesa - corners appear normally.

P.S. may be tile size matters?

**Comment by mrobinson** [comment]
They show up for me with Mesa 11.2.0 on Ubuntu 16.04.1 on Intel Skylake GT2, though the corners look slightly too wide with no hidpi scaling.

@glennw, do you happen to have a screenshot of the incorrect case?

**Comment by glennw** [comment]
@mrobinson I think it's related to newer versions of mesa / intel drivers. I was using the xorg-edgers PPA to run latest mesa on ubuntu 16.04, and I could see it then. Having disabled the PPA and gone back to the mesa that ships with ubuntu 16.04, it's now showing up fine for me. It's probably not a huge priority given that, although we'll need to investigate at some point. It was also affecting gradients from what I could tell, so it may well just be a mesa bug. cc @anholt

**Comment by jrmuizel** [comment]
http://output.jsbin.com/surane/quiet renders wrong for me on Ubuntu 16.10 on Sandybridge

**Comment by kvark** [comment]
Potentially fixed by #444 ? There was an UB case (see #443), which may had affected the border radius.

**Comment by emilio** [comment]
With the patch in #443 I can still repro, unfortunately.

**Comment by emilio** [comment]
I have a fix for this in #446 (not totally sure it's correct though). The test case @jrmuizel posted renders wrong for me too (though it renders nicely with `LIBGL_ALWAYS_SOFTWARE=1`, so I guess it's also an Intel-specific bug, sigh).

**Comment by mrobinson** [comment]
Is this still an issue with the various border shader refactors?

**Comment by glennw** [comment]
I don't believe so - let's close it and it can be re-opened if anyone else can still repro it.
