### ISSUE TITLE
group opacity can bring webrender to its knees

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#442]
http://people.mozilla.org/~jmuizelaar/webrender/synthetic/opacity.html has 100 layers of group opacity. It renders incorrectly and scrolling is very slow in Servo.

**Comment by demo99** [comment]
I will work on it. I created a bug 1330945 [1] for QR. Currently my idea is sending opacity value with ClipRegion to MaskCacheInfo and then do the group opacity operation.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1330945

**Comment by jrmuizel** [comment]
Can you elaborate on what you mean. Group opacity works in webrender it can just be really slow in extreme cases.

**Comment by glennw** [comment]
This seems like a bug / missing optimization in WR - it's creating a huge number of render targets for this test case.

**Comment by gw3583** [comment]
The URL with the test case no longer exists, but this should be handled by picture caching.
