### ISSUE TITLE
What do you guys think of ANARI? 

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/webrender#4515]
Since it is high level/has a scene graph and can be optimized by drivers, this next gen API *might* enable new state of the art performance for some rendering tasks
https://www.phoronix.com/scan.php?page=news_item&px=Khronos-ANARI-1.0-Provisional

**Comment by kvark** [comment]
This is targeted at still images for high quality rendering. WebRender is in a very different category.

**Comment by LifeIsStrange** [comment]
Hmm OK thanks!
