### ISSUE TITLE
Remove UBO usage.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#457]
Instead of using UBOs for submitting primitive instances and using gl_InstanceID, with the recent changes to prim_store, it would be better now to submit the PrimitiveInstance structures as instanced vertex attributes.

**Comment by glennw** [comment]
This may not be worth doing - it seems that instanced vertex attributes are only available in GL3.3+, and we want to support GL 3.1 for some older Intel GPU systems. If that's correct, then we can close this and stick with using UBOs. @jrmuizel or @kvark does that sound correct to you?

**Comment by kvark** [comment]
@glennw I disagree.

I don't think `ARB_instanced_arrays` support requirement limits us in any way. On Intel, 5th gen GPUs only support GL 2.1 (according to https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units), while 6th gen (Sandy Bridge, starting 2011) already fits our needs:
>3.1 on Windows
3.3 on OS
3.3 on Linux

On Windows we are using Direct3D anyway, which has [InstanceDataStepRate field](https://msdn.microsoft.com/en-us/library/windows/desktop/bb205316(v=vs.85).aspx) as of version 10. And on Linux/OSX we got GL 3.3 core support.

In general, if we are talking about GL extensions and not core GL versions, I haven't seen a system that would support instanced draw calls but not instanced arrays.

As for GLES, version 3.0 has our stuff included.
