### ISSUE TITLE
Extract glyph rasterizer?

### ISSUE THREAD

**Issue by leontepe** [servo/webrender#4575]
Several code comments in [font-kit](https://github.com/servo/font-kit) point to the font rendering here as being more complete and mature. If that is the case, are there any efforts to extract the `glyph_rasterizer` here into a standalone library? Since @pcwalton quit his work on font-kit, this might be sensible.

If no such effort exists, I would gladly receive advice on how to go about such an effort from people that know more about the code organization of webrender and it's font renderer than I do (which is, to say, basically nothing).

**Comment by nical** [comment]
I don't think anyone is working on extracting the glyph rasterizer at the moment, but I agree it would be a valuable thing to do.
If you want to give it a go, a good place to start is moving `webrender/src/glyph_rasterizer` and `webrender/src/platform` out of the webrender crate into another crate, for example a `wr_glyph_rasterizer` crate, and see what breaks. There's probably going to be a few types that will need to be pulled into the new crate or duplicated, but most of the glyph rasterization logic is in these two folders.

**Comment by jrmuizel** [comment]
I also think that it would be very good to have glyph_rasterizer as a standalone crate and would appreciate any work that you're able to do toward that.

Currently the glyph rasterizer code has a dependency on the `webrender_api` font.rs code. I'd suggest pulling that code out into a separate crate that could become the webrender font crate.

**Comment by leontepe** [comment]
@jrmuizel
> Currently the glyph rasterizer code has a dependency on the `webrender_api` font.rs code. I'd suggest pulling that code out into a separate crate that could become the webrender font crate.

So, are you saying completely removing the `font.rs` module from `webrender_api` and moving it to the new `wr_glyph_rasterizer` crate? Is there no other code inside `webrender_api` using the `font` module that would depend on it?

Was thinking making the `font` module a `pub use` instead of a `use` would fix the problem here. Am I mistaken?

**Comment by leontepe** [comment]
It actually seems like the `webrender_api` crate is outdated on crates.io. Last release 2 years ago. What's the move here? Would you guys push a new version?

**Comment by nical** [comment]
I've been a bit lazy but I can push new versions

**Comment by jrmuizel** [comment]
Yes, I was imagining that font.rs would move to the new `wr_glyph_rasterizer` crate and `webrender_api` would depend on `wr_glyph_rasterizer`

Yeah, the webrender crates on crates.io are pretty old. We could publish new versions as needed.

**Comment by leontepe** [comment]
> I've been a bit lazy but I can push new versions

Would be great :-)

**Comment by keiya01** [comment]
Does anyone work on this issue?

**Comment by lsalzman** [comment]
This was successfully dealt with in https://bugzilla.mozilla.org/show_bug.cgi?id=1804193

Thank you, Sasaki Keiya.
