### ISSUE TITLE
Support subpixel antialiasing of text

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#464]
Getting this done is will be important for getting more accurate performance numbers as it has a potentially negative impact on performance.

**Comment by jrmuizel** [comment]
So to support this we need to do blending with a rgb mask. There are some different strategies to do so:
1. glBlendColor(textColor), glBlendFunc(GL_CONSTANT_COLOR, GL_ONE_MINUS_SRC_COLOR)
2. dual source blending
3. frame buffer read using GL_EXT_shader_framebuffer_fetch/GL_NV_texture_barrier
4. A two pass approach described here http://anholt.livejournal.com/32058.html

Skia will use any of 1-3 depending on the capabilities of the hardware. Cairo uses 4.

**Comment by jrmuizel** [comment]
I confirmed today that Direct2D uses approach 1.

**Comment by glennw** [comment]
I'll start on this next week.

**Comment by kvark** [comment]
Seems like an exciting task to do! If our goal is just to measure performance, we might as well just enable blending and output all the text as non-opaque for the worst case, as a quick test.

**Comment by jwilm** [comment]
Not sure if it's available on the systems webrender is targeting, but the `GL_ARB_blend_func_extended` extension could work here. Sounds like option 2 in the above list. With the extension, the blend function can be configured like this:

```rust
gl::BlendFunc(gl::SRC1_COLOR, gl::ONE_MINUS_SRC1_COLOR);
```

and then a per-channel mask can be output from the fragment shader in addition to the fragment color.

**Comment by glennw** [comment]
The initial implementation of this has landed in WR/Servo now - enable with -Z enable-subpixel-aa to test. @jrmuizel Are you fine with closing this and we'll open more fine grained issues for the remaining subpixel work?

**Comment by jrmuizel** [comment]
Yep.
