### ISSUE TITLE
Add support for glObjectLabel

### ISSUE THREAD

**Issue by glennw** [servo/webrender#469]
It would be good to call this around our resource objects (shaders, textures etc) so that debug info from the driver can provide more useful information.

That task itself is fairly straightforward. However, I _think_ the gleam bindings for GL are statically generated right now, which might make things tricky since glObjectLabel is a GL4+ only function.

**Comment by kvark** [comment]
This is typically solved by checking for the extension string and only using the functions if the extension (KHR_Debug, if I'm not mistaken) is supported, so shouldn't be a problem with `gleam`.

**Comment by emilio** [comment]
FWIW, in servo, even though the bindings are statically generated but they get loaded at runtime (except for android), and this can be checked with `gl::foo::is_loaded()`.

**Comment by emilio** [comment]
I think that even though the bindings are statically generated, we still
load the symbols dynamically in non-android systems, see
<https://github.com/servo/servo/blob/f96718d03da969510dc992699cb6f25c2e21ae1e/ports/glutin/window.rs#L330>

**Comment by glennw** [comment]
I don't think this is really necessary or useful now. The vast majority of images end up in a shared texture cache, negating the usefulness of this. We insert comments in the shader source code specifying which shader this is.

**Comment by kvark** [comment]
In other words, we have hacked the GL object model so much that labeling those objects doesn't make sense any more :)
Seriously though, I'd keep it open with a low-priority tag or something. Labeling graphics resources is just a good hygiene, similar to how you expect the code to be commented.
