### ISSUE TITLE
Figure out font sanitizing with webrender

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#477]
Currently webrender passes font data from the content process directly to OS font APIs. We can't trust this data so we'll probably need to sanitize it again in the webrender process.

**Comment by glennw** [comment]
@jrmuizel How does Gecko handle this now? Is there an existing library we could rely on for this?

**Comment by jdm** [comment]
Servo's currently using fontsan: https://dxr.mozilla.org/servo/rev/efc0a185c4e11097e89c8c565565579c05c5aded/components/gfx/font_cache_thread.rs#258

**Comment by jrmuizel** [comment]
We use OTS (https://github.com/khaledhosny/ots) which fontsan is a wrapper around. We only need to sanitize once in the content process though because that's the only place that hands fonts to the native apis

**Comment by glennw** [comment]
@jrmuizel What's the status of this? Do we need to do anything inside WR itself?

**Comment by jrmuizel** [comment]
Yes we still need to hook this up. Nobody's looked at it yet though.

**Comment by glennw** [comment]
@jrmuizel  It seems like Gecko will already have that code in place and could validate it in the GPU process but before it's passed to WR? This might be simpler than handling an extra dependency with rust bindings and doing it inside WR?

**Comment by gw3583** [comment]
I don't think we plan to do this inside WR - please re-open if there is work to be done here.
