### ISSUE TITLE
Move the resources folder to the repo root

### ISSUE THREAD

**Issue by kvark** [servo/webrender#481]
It would look much better as `root/shaders` instead of `root/webrender/res`

**Comment by glennw** [comment]
I'm not sure if this is a good idea. If / when we start to publish webrender on crates.io, I think this would mean the shaders directory doesn't get included in the published crate. Additionally, when we start using a build step / macro to include the shaders into the crate binary, it seems more logical to have the shaders underneath the crate root directory. Thoughts?

**Comment by glennw** [comment]
Closing for aforementioned reasons.

**Comment by nical** [comment]
Is there a plan to facilitate packaging the shaders? Having them in webrender/res does not bother me at all, but webrender not being able to handle them by itself does. And if I understand correctly, cargo does not let you package non-rust files (i'd love to see webrender on crates.io).

**Comment by emilio** [comment]
@nical: No worries! I think eventually, if cargo doesn't allow packaging them as files, we can stick them in the binary using `include!`, though that's a pain for development I guess.

**Comment by kvark** [comment]
I can't see anything about included files being rust only in the cargo guide. Their own example includes Cargo.toml, which is not exactly rust.

**Comment by metajack** [comment]
@nical What do you mean by packaging them? Cargo includes them in its package unless specifically excluded I think. The issue isn't getting them in, it is getting them out. There is nothing like include paths in C such that Servo or Gecko can reference resources relative to a depedency. So the build script would have to figure out where they were under `target/` and then copy them somewhere sane or reference them there somehow.

An example of where this is done currently in Servo is hte browser.html code which is a zero-Rust Cargo crate: https://github.com/servo/servo/blob/master/python/servo/post_build_commands.py#L88-L105
