### ISSUE TITLE
Virtual cursor support

### ISSUE THREAD

**Issue by dhavalbc** [servo/webrender#4819]
there is no way to enable virtual cursor using webrender.
Please consider adding this as a feature.

**Comment by jrmuizel** [comment]
Can you elaborate what you mean by virtual cursor?

**Comment by dhavalbc** [comment]
virtual cursor enables us overlay a cursor image on webcontent that is being rendered,
this will be helpful for systems that are using webrender as rendering engine(Firefox OS) overlay a cursor image when pointing device is connected.
so, webrender can consider adding api to set a cursor image and an api to set x, y coordinates where the cursor has to be rendered.
and if this feature is enabled, webrender can overlay the mouse cursor over the webcontent.

**Comment by QingzhongGuo** [comment]
do we already have progress for this virtual cursor issue?

We use Firefox Gecko engine for OS used in non-touch device.  We need enable virtual cursor in browser so that consumer can move the virtual cursor to select different contents by D-PAD

**Comment by mrobinson** [comment]
Isn't this beyond the scope of WebRender? If your application needs a virtual cursor you can add this to WebRender's display list or move a window over the application itself.

**Comment by dhavalbc** [comment]
Yes agreed, you can close this request as we have implemented the same.

**Comment by QingzhongGuo** [comment]
Clear,  thanks

**Comment by QingzhongGuo** [comment]
Dear All:

Not sure if my email can reach you or not.

Can I ask some support for webrender?

We are using Gecko123 (together with WebRender) as our OS framework (KaiOS which derive from Firefox OS).

Now we met some issue for display problem.
Seems all texture can not be shown anymore,  as attach file (first one which we extract from framebuffer),  at the same time,  screen should be shown at 2nd picture (we use software composer to re-render).

Do we have any way to debug what happen?

Best wishes,
Qingzhong

**Comment by mrobinson** [comment]
@QingzhongGuo It's difficult to know what is going on without more information. That said, the problem you are seeing is more related to upstream WebRender (which is in the Gecko repository) than this downstream one (which is currently only used in Servo).
