### ISSUE TITLE
Coordinate spaces of things needs documenting

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#482]
When creating things like a stacking context or pushing things in DisplayListBuilder, the caller has to provide various rects/clip regions/transforms/etc. These are all undocumented - although the names are useful, it would be great to have documentation on what coordinate space these things are in - relative to what origin and in what units.

**Comment by kvark** [comment]
WR uses `euclid` for it's coordinate types, which features strong typing for the coordinate systems:
> A collection of strongly typed math tools for computer graphics with an inclination towards 2d graphics and layout.

So for this issue we need to actually use those `TypedPoint2D`/`TypedSize2D` semantics (instead of default `Point2D`/`Size2D`), parametrized by the target coordinate system (phantom) types, like in the [documentation](http://doc.servo.org/euclid/) example (I tweaked that code a bit):
```rust
pub enum ScreenSpace {}
pub type ScreenPoint = TypedPoint2D<f32, ScreenSpace>;
pub type ScreenSize = TypedSize2D<f32, ScreenSpace>;
pub enum WorldSpace {}
pub type WorldPoint = TypedPoint3D<f32, WorldSpace>;
pub type ProjectionMatrix = TypedMatrix4D<f32, WorldSpace, ScreenSpace>;
```

This strong typing will be more useful than documentation for being compiler-assisted.

**Comment by staktrace** [comment]
Agreed, if we can get strongly-typed units that would be even better. We'll still need documentation to define the spaces - e.g what "screen space" and "world space" are in your example.

**Comment by glennw** [comment]
We can certainly add typed units to at least the webrender_traits types as a start point. This would help users of the API at least. I'll try to add some documentation as a first step to webrender_traits today. Almost everything that gets supplied is in a coordinate space local to the containing stacking context, and assuming zero scroll offset.

**Comment by glennw** [comment]
Added some initial docs here - https://github.com/servo/webrender/pull/486. We will also start to document the methods that don't follow the normal convention mentioned in that PR.

**Comment by glennw** [comment]
Let me know if that doesn't make sense or needs more information!

**Comment by glennw** [comment]
@staktrace Should we close this now that the README has been updated and @nical has landed the typed units work?

**Comment by staktrace** [comment]
Sorry for the delay. But yeah I think we can close this for now. If I run into things that need further clarification I can file more specific issues for those, or just submit PRs. Thanks!
