### ISSUE TITLE
[Feature] Enable Angle on Linux Platform

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [servo/webrender#4852]
Is possible to enable angle on linux in the same of windows for platforms with vulkan drivers and OpenGLES up to 3.1?
Angle can be really good to render using Vulkan on platforms that not had opengl native support.

**Comment by mrobinson** [comment]
This repository tracks the downstream port of WebRender that is mainly used in Servo. Large design changes and feature development are done in the Gecko project. I recommend looking there for new features, though I'm not sure how intrusive this change would be.
