### ISSUE TITLE
ask help to debug display issue 

### ISSUE THREAD

**Issue by QingzhongGuo** [servo/webrender#4862]
This is one question to ask help,  not issue for Webrender.   I do not find where to mark this one as question , sorry for that.

We are using Gecko123 as framework for our OS,  so we use webrender (hardware GPU based) version with that gecko version.
We met some display issue as below picture.   
Nok one is the one what we extract from framebuffer (rendered by GPU webrender).
Reference one is the one what we get with software rendering for the same contents.

We refer debug.rs to implement one virtual cursor inside webrender.
In most time, it can work normally.

but sometime it will bring display nok and we do not know yet reason why it trigger this nok.

When Nok happened,  seems all text can not be display,  seems most of hardware rendering stop to work and I do not find error log related..
Can we get some guide how to debug this kind of issue?

![2024-10-11-14-48-32](https://github.com/user-attachments/assets/c33ba9ca-c96c-48ff-8eff-1de33163d3c5)
![screen1](https://github.com/user-attachments/assets/fd1d9170-90b7-436e-8b4e-976011e37a52)

**Comment by mrobinson** [comment]
This repository is a downstream fork of the one used in Gecko. I think you'd probably have more success talking with the Mozilla graphics folks.
