### ISSUE TITLE
`gl::tex_image_3d` not available on Android

### ISSUE THREAD

**Issue by mmatyas** [servo/webrender#487]
#478 started using `gl::tex_image_3d`, which is [disabled on Android](https://github.com/servo/gleam/blob/master/src/gl.rs#L460) (the `_2d` version has the same `FIXME` but that's [not disabled](https://github.com/servo/gleam/blob/master/src/gl.rs#L406)).

(part of servo/servo#13154)

**Comment by kvark** [comment]
Hmm, I wonder why it's disabled in `gleam` though. WR is currently targeting GLES 3.0, which has `glTexImage3D`, so these calls should be valid.

**Comment by kvark** [comment]
I think it's an upstream issue: https://github.com/servo/gleam/issues/92

**Comment by glennw** [comment]
I think this can be closed now - the fix has landed in gleam. Although a gleam update in the servo repo may still be necessary.
