### ISSUE TITLE
Use a u64 for the scrollid instead of usize

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#489]
Right now webrender uses a usize for the scroll id (the thing inside `ScrollLayerInfo::Scrollable`) I would prefer it use a u64 as that would match what Gecko does, and make it easier to map from the C++ value directly to the rust value. It also seems kind of odd to have the size of this field be platform-dependent, but I guess that doesn't really matter too much.

/cc @mrobinson

**Comment by mrobinson** [comment]
Okay. I should be able to do this once multiple scrolling layers per scrolling area/root are supported.

**Comment by glennw** [comment]
@mrobinson @staktrace Is this still relevant?

**Comment by mrobinson** [comment]
If this is still a useful change, it should be pretty easy to do.

**Comment by staktrace** [comment]
Yes, please. I think it would still be useful.

**Comment by staktrace** [comment]
Thanks!
