### ISSUE TITLE
Reftests broken with the gl -> device change.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#490]
Unfortunately this PR https://github.com/servo/webrender/pull/480 breaks a number of the reftests in the tests/wpt/mozilla/tests/css/ directory.

**Comment by glennw** [comment]
It's probably something simple like an incorrect blend mode being set somewhere.

cc @kvark

**Comment by kvark** [comment]
I have one piece in mind. Do reftests include alpha for comparison?

**Comment by glennw** [comment]
Fixed now
