### ISSUE TITLE
Add support for an external (C++) logging system.

### ISSUE THREAD

**Issue by nical** [servo/webrender#493]
Gecko has some special logging tools (gfxCriticalError/gfxCriticalNote, etc.) that get bundled in the crash reports. This is very useful and it would be good to be able to use that from within rust code. It may not make sens to have it in the webrender crate, but it could be in a separate gecko_log crate that would be used by webrender when needed.

**Comment by gw3583** [comment]
I believe we have supported what we need to for logging / crash reports.
