### ISSUE TITLE
Fix layer / stacking context namining inconsistencies

### ISSUE THREAD

**Issue by glennw** [servo/webrender#496]
The use of layer as a term is inconsistent between the cpu and gpu portion of webrender. Very confusing...

**Comment by kvark** [comment]
Could be seen as a sub-task of #482

**Comment by nical** [comment]
I propose using the "layer" terminology for the moving things that webrender bases its internal transforms on (like layers::Layer), and consistently use "stacking context" for things that map "1 to 1" to actual css stacking contexts.
Layers would be only scroll roots today, but if/when we are to support async animations and other fancy features, such elements would probably generate layers as well.

I'd appreciate if we wait for PR #568 to land before writing code for this to avoid ugly merge conflicts.

**Comment by glennw** [comment]
This can be considered complete with the removal of ClipScrollGroup and PackedLayer.
