### ISSUE TITLE
Investigate the multi-viewport approach to tile rendering

### ISSUE THREAD

**Issue by kvark** [servo/webrender#499]
https://www.opengl.org/registry/specs/ARB/viewport_array.txt
Core in GL-4.1, the viewport/scissor are selected at the GS stage.

Allows us to assign a separate viewport/scissor pair per tile, effectively zeroing the need for shaders to know anything about tiles. Clipping would be done by the scissor automatically, which would potentially allow us to get rid of the separate "transform" shader variants.

The downside is - the need for GS stage. It's considered bad for performance in general, although in our case the GS is guaranteed to do 1:1 transformation of the primitives, so maybe the overhead is not going to be that big. At the very least, we are not transforming that many vertices, more concerned about PS/fillrate performance.
In that regard, this may turn out as not just shader simplification, but also an optimization. Currently PS of transformed primitives run on larger area than the primitives occupy, and cut off regions by using the alpha. With multiple scissors, we'll see less PS executions as well as potentially less discards/blends.

**Comment by kvark** [comment]
Actually, AMD has an extension to run the viewport arrays code without GS:
https://www.opengl.org/registry/specs/AMD/vertex_shader_viewport_index.txt

That would be terrific for performance, and it's supported on my (Gen9) Intel GPU, so there is a chance it's supported on a significant market share. We can basically get away without modifying the code much - just have a different shader define to be used for the extension-enabled code path, plus some preparation work on the Rust side. Obviously, this would be an optional code path only for clients that support the extension.

**Comment by jrmuizel** [comment]
Is there equivalent functionality in Direct3D?

**Comment by kvark** [comment]
@jrmuizel 
Viewport/scissor arrays are [supported](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476478(v=vs.85).aspx) by D3D11. However, I don't see any way to set the `SV_ViewportArrayIndex` without using geometry shader there.

**Comment by glennw** [comment]
No longer relevant.
