### ISSUE TITLE
Use depth buffer for tile slicing

### ISSUE THREAD

**Issue by kvark** [servo/webrender#501]
Currently, the depth buffer is not used by WR. If we don't have other (more important) applications, we could utilize it trivially for tile cutting. Similarly to #499, and with the same benefits, but using depth buffer in a specific way would allow for automatic scissoring of the primitives to the tile regions, hence without extra hardware requirements or driver bugs:
- have a specific unique value (between 0 and 1) assigned to each tile (like, `tile_id` / `total_tile_count`)
- fill up the depth buffer once with those values (either by drawing a rectangle per tile, or by writing the depth from a pixel shader), never modify afterwards
- use the `GL_EQUAL` test for the depth when rendering any primitives, and output the `gl_Position.z` corresponding to the assigned primitive tile (assuming, `w == 1`).

Such rendering is supposed to utilize the HW early-Z for effectively scissoring primitives to tiles (without actual scissor tests in place). Note: on some configurations, the early-Z gets disabled when using pixel shader discards, so we might need to be careful with that.
Also, it allows for the hierarchical-Z test to be done by the HW, which would be especially efficient if HW hiZ tiles are aligned with our WR tiles (almost guaranteed to be true, given our tiles are large enough and pow2 size).

**Comment by glennw** [comment]
Discussed briefly on IRC. I do have some ideas for depth buffer usage (primarily related to using it for an opaque + alpha pass to get per-pixel z-culling and hi-z usage). We think that both of these ideas are probably compatible and could work together.

**Comment by glennw** [comment]
No longer relevant.
