### ISSUE TITLE
[meta] Efficient tile clipping

### ISSUE THREAD

**Issue by kvark** [servo/webrender#503]
Multiple ways to do it:
- (current) Compute the screen-space BB in the vertex shader, clip it, output an aligned quad, then discard pixels outside of the transformed region in the pixel shader
- (#499) Multiple viewports/scissors, with (possibly required) geometry shader used for selection
- (#501) Use the depth buffer
- Use `gl_ClipDistance[]`
- Generate real splits in the geometry shader

Thanks @lsalzman for the last two proposals!

**Comment by kvark** [comment]
As @glennw noted, our current requirement on mobile is GLES 3.0, which doesn't support either geometry shaders or even the clip distance. That leaves us with only the current and the depth solutions available.

**Comment by glennw** [comment]
No longer relevant.
