### ISSUE TITLE
Add WR data structure dumping

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#521]
It would be really useful for debugging to have some way of dumping out the WR internal data structures. So e.g. after set_root_stacking_context is called it would be nice to be able to dump the out the full tree of stacking contexts and display items. Also as webrender processes these things into layers and packed layers and primitives it would be nice to be able to dump those out as well. I had started on [a patch](https://github.com/staktrace/gecko-dev/commit/27386cec9bcc8bd54ed1557f8e819ef1cb58f32a) but have to pause on that for now. @jrmuizel also mentioned that @vvuk has a [wrench](https://github.com/vvuk/wrench/) tool which has some textual representation of webrender internal data structures, and it might be good to make the dumping compatible with that. I haven't looked into that closely.

**Comment by glennw** [comment]
We have support for this via the web debugger now. We can open specific bugs for adding new pieces of information to the debugger.
