### ISSUE TITLE
scrollable <div> not showing on page

### ISSUE THREAD

**Issue by gterzian** [servo/webrender#531]
While trying to rebase https://github.com/servo/webrender/pull/465, I've encountered a problem trying to test using this page: https://output.jsbin.com/lukiye, running `RUST_LOG="webrender=debug" ./mach run -d  -- https://output.jsbin.com/lukiye`

Using Servo at https://github.com/servo/servo/commit/516be8f85c0c79b16c3841c60d887661abe91e81 when I build with webrender at https://github.com/servo/webrender/commit/8cc857486888b14110ac78943f485b04d8d77f01 I can see the scrollable `<div>` on the page, however if I use a later commit (tried both https://github.com/servo/webrender/commit/73afce391c117eacce12227913744fccff6d0efd and https://github.com/servo/webrender/commit/c5eb15a9b8030bbad15809aba7dd1b5906d96397) the scrollable child element seems to disappear(the element contains another scrollable child element by the way). 

@mrobinson It seems to happen right after https://github.com/servo/webrender/pull/517 was merged, please let me know if you have any ideas or if I am perhaps missing something in the way I build or run servo...

**Comment by gterzian** [comment]
UPDATE: the element 'seems' to be there, because when I point on where I think it should be, the outer layer stops scrolling...

**Comment by mrobinson** [comment]
@gterzian I'm still doing some final testing on the Servo bit of the patch. If you want to test, you can find it at: https://github.com/mrobinson/servo/tree/scroll_root_2.

**Comment by gterzian** [comment]
@mrobinson are you also getting those build errors: `error: no field `has_stacking_contexts` on type `&mut webrender_traits::StackingContext``?

**Comment by emilio** [comment]
That's #518

**Comment by emilio** [comment]
(that also needs a servo update, I guess)

**Comment by gterzian** [comment]
@emilio thanks, actually it seems those have already been solved on the main servo/master (I previously built with the latest servo, and the latest webrender), but I am getting those errors now when using @mrobinson branch at https://github.com/mrobinson/servo/tree/scroll_root_2

**Comment by gterzian** [comment]
Ok I can confirm that if you rebase https://github.com/mrobinson/servo/tree/scroll_root_2 off of the upstream master, it builds.

Also, the problem is now different then mentioned above: The outer scrollable element shows up, however it is now the inner scrollable child element that is invisible.

**Comment by mrobinson** [comment]
Thanks for pointing this out. The latest version of the branch should fix this issue. It doesn't seem that the subframe is scrolling properly, but that is almost certainly an issue with my WebRender changes.

**Comment by mrobinson** [comment]
Considering that, perhaps this bug should be closed.

**Comment by gterzian** [comment]
@mrobinson thanks, yep I can confirm that with the latest version, the inner element shows up, however I can't scroll it...  Perhaps we should open this as a separate issue? Although I'm not sure if it indeed relates to webrender...
![screen shot 2016-11-06 at 12 54 06 pm](https://cloud.githubusercontent.com/assets/2792687/20035458/39aff9c0-a420-11e6-8aff-c4f9134e7928.png)

**Comment by gterzian** [comment]
closing this as `scrollable <div> not showing on page` is solved, however we could consider opening a separate issue about `nested scrollable <div> not scrollable`.
