### ISSUE TITLE
http://robert.ocallahan.org/ scrolls slowly either due to iframes or CPU load

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#55]
WebRender reports its typical very fast timings (1-2 ms) on http://robert.ocallahan.org/ but scrolling is still slow. Servo goes into an endless loop of reflows, saturating most of the CPU on this site, but WebRender should still be fast. Unfortunately, it seems to be slow, even though the reported timings are fast.

I suspect that either (a) the iframes are hurting our FPS somehow; (b) the OS scheduler is penalizing WebRender for the bad behavior of layout.

**Comment by glennw** [comment]
Doesn't occur with wr2.
