### ISSUE TITLE
Store images in the renderer instead of the render backend

### ISSUE THREAD

**Issue by nical** [servo/webrender#559]
I'm looking into removing the image copy that takes place every time an item is added to the texture cache (every time we've optimized away image copies it has paid off in gecko). It happens because the images are stored in the resource cache owned by the render backend thread and the pixels have to be sent to the renderer thread for uploads.

In theory the images are mostly read from the renderer when doing the uploads and the render backend should be able to work mostly with the image metada (size, stride, etc). In practice there are some places where the render backend reads the pixels (for example TextureCache::insert which copies the top/bottom/left/right-most pixels of the image and generates extra blit jobs for these borders).

I'm not cvertain how to deal with TextureCache::insert. An easy way out could be to use atomic ref-counting for the buffers but I am sure we can figure out a way to not need to share this data on multiple threads.

**Comment by nical** [comment]
I have a work in progress attempt at moving the image data off the resource/texture cache (most of the effort is moving the border inflation code to the renderer and passing image keys around instead of buffers). It should also help with removing needless copies of the inflated image borders as well. I am thinking of leaving the glyphs out of this change (I don't know yet whether it makes sense to keep them on the cpu at all once they have been uploaded, and I don't want to collide too much with other glyph-related work).

I am surprised to see that we also do the border inflation (the 4 extra blits) for each glyph, is it necessary? Considering how small glyphs usually are we might be better off just copying the cpu-side glyph in a slightly bigger buffer that includes the inflated border (initialized to the transparent color) and do only one upload per glyph (we already copy the glyph when calling TextureCache::insert).

cc @glennw @kvark

**Comment by glennw** [comment]
@nical Sounds good. Indeed, we could probably make the way the glyph borders are done a lot better, as you suggested. The copy_pixel stuff was mostly a quick hack to fix those bilinear sampling issues, it's definitely due to be done properly :)

**Comment by nical** [comment]
I had a chat with @glennw and the plan is going to use Arc to share the pixels to the renderer, while still having the backend thread manage it. Closing since the original proposal is not what we are going for, I'll open another issue or PR as I get to implementing the solution based on Arc.
