### ISSUE TITLE
Have DisplayListBuilder keep track of its own AuxiliaryListsBuilder

### ISSUE THREAD

**Issue by vvuk** [servo/webrender#574]
Now that everything is flattened, it doesn't look like there's any need to keep track of a separate aux lists builder and pass it around -- the DisplayListbBuilder should be able to keep track of one internally and use it as needed. @mrobinson any reason to not do this?

**Comment by mrobinson** [comment]
@vvuk Definitely correct. I was planning on doing this after landing: https://github.com/servo/webrender/pull/567
