### ISSUE TITLE
Update Servo for webrender 0.10.0

### ISSUE THREAD

**Issue by gterzian** [servo/webrender#579]
Just wanted to give the heads up on the work I am doing in https://github.com/servo/servo/pull/14286 

It's actually the first time I'll do such an update of servo, please let me know if I'm totally wrong, or if someone is already in the process of doing this.

**Comment by dignifiedquire** [comment]
Referenced PR was merged, can this be closed @gterzian?

**Comment by emilio** [comment]
Yup, thanks for the heads-up @dignifiedquire!
