### ISSUE TITLE
25-30% of en-us wikipedia render() time is spent in Device::init_texture

### ISSUE THREAD

**Issue by vvuk** [servo/webrender#588]
Doing a `render()` loop of the wikipedia english main page gives me this:

![2016-11-22 16_13_17-wrench - microsoft visual studio](https://cloud.githubusercontent.com/assets/194965/20542210/9f6b93e0-b0ce-11e6-86c1-1293fb6dbe48.png)

I think we should be able to significantly reduce this.

**Comment by glennw** [comment]
@vvuk Yup, we should be able to reduce this very significantly. Right now, the vertex textures are re-uploaded containing the data for the entire scene (this includes primitives that are not on-screen, it's literally the entire scene). Once we have support for updating these incrementally, the vertex texture uploads will contain (a) only the data for the visible primitives on screen and (b) in the case of scrolling, only the modified primitive data for that frame. I expect this will drop that quite drastically.

**Comment by glennw** [comment]
This is no longer a problem, with the use of the GpuCache that supports incremental updates.
