### ISSUE TITLE
List the tools that work with WebRender

### ISSUE THREAD

**Issue by nical** [servo/webrender#593]
...in the README.md.
A list of useful development tools with short description of what it can help with and possibly the steps required to get it to work.

For example:

- The various debugging tools embedded in WR itself
- replay
- wrench
- apitrace(?)
- renderdoc(?)
- ?

I found myself re-implementing part of wrench because I vaguely knew it existed but thought it was providing a different thing.

**Comment by kvark** [comment]
Good idea!
I think that falls into a general "document things" category, perhaps being one of the top items in there.
@glennw believes we should have in-tree documentation of some sort. I've got a few topics to document, like the task lifetime and clip processing,

Also please note that `apitrace` replay may crash unless using my https://github.com/apitrace/apitrace/pull/495.

**Comment by glennw** [comment]
@nical I think we wrote this stuff up - did it get published somewhere?

**Comment by nical** [comment]
yep https://github.com/servo/webrender/wiki/Links-to-useful-resources#useful-tools
