### ISSUE TITLE
Serialize displaylists from Servo to use as benchmarks/testcases

### ISSUE THREAD

**Issue by Manishearth** [servo/webrender#6]
Currently measuring the performance impact of a change requires one to recompile servo and then run testcases with `-w` and scroll/do things. However, such tests don't produce consistent results, so it's hard to compare things.

We should add some infrastructure to Servo that lets us dump display lists to a file, and then add a bench/test harness to webrender that can read these files and measure performance (similar to what we do for [clipping](https://github.com/Manishearth/webrender/commit/d1885b639cc3d5137c0e5eae90a2a352c06840c6).

**Comment by glennw** [comment]
This is done now.
