### ISSUE TITLE
Allowing for transparent background color (to be allowed)

### ISSUE THREAD

**Issue by jaredpetker** [servo/webrender#601]
I am trying to use webrender itself outside of the context of servo, and found that there isn't currently a way to simply have a fully transparent root background color. There seems to be some [comments around such things here](https://github.com/servo/webrender/blob/master/webrender/src/frame.rs#L640).

It seems like handing in a fully transparent root background color is not allowable at the moment, basically my use case is drawing on top of something else with webrender, so I don't actually want to a) draw any background color or b) clear the background color at all, I just want to draw on top of some other stuff.

Any thoughts on adding some option which would allow for such behavior or how such behavior would like to be added? I've no issue adding the feature myself to help.

**Comment by nical** [comment]
I think that it should be fine to remove the forced white background and make sure that servo specifies an opaque background color for its root stacking context to get the same effect. Gecko will eventually also need to be able to draw on top of a semi-transparent widget.

What do you thing @kvark?

**Comment by kvark** [comment]
Yes, that should be fine.

**Comment by glennw** [comment]
@jaredpetker Yup, adding optional functionality to skip any clear / background rect sounds good to me.

For now, it could probably just be a field in the RendererOptions struct that gets passed to WR during initialization. This would allow you to get the functionality working, and then we could consider a public API for it later if we ever want to change that option dynamically?

**Comment by jaredpetker** [comment]
I can go with that. I've found everywhere that seems to do clearing (the initial stacking context bounds rect, tiling, etc), will do, thanks.

**Comment by glennw** [comment]
I think this is fixed now - feel free to re-open if further work is required.
