### ISSUE TITLE
Font Rendering looks strange on Windows

### ISSUE THREAD

**Issue by nc4rrillo** [servo/webrender#617]
<img width="912" alt="servo-edge" src="https://cloud.githubusercontent.com/assets/17953668/20861700/7b0ad120-b964-11e6-8a73-9c877e3c8b21.png">
Edge on the left and Servo on the right. 
Intel GPU on Windows

**Comment by nc4rrillo** [comment]
<img width="165" alt="servo-edge-nytimes" src="https://cloud.githubusercontent.com/assets/17953668/20861729/5e073162-b965-11e6-8720-a3fe462d914f.png">
also really visible on nytimes.com

**Comment by jrmuizel** [comment]
Yeah, this sort of a known issue. The Windows font support is really new and has a bunch of known issues like lacking gamma correction.

**Comment by glennw** [comment]
cc @vvuk

**Comment by glennw** [comment]
@vvuk Is this resolved now?

**Comment by vvuk** [comment]
I think so -- there are certainly additional fixes needed, like Jeff mentioned, but we should have issues on the specific problems instead.
