### ISSUE TITLE
PushStackingContext has its own bounds field, instead of using common DisplayItem rect

### ISSUE THREAD

**Issue by vvuk** [servo/webrender#619]
push_stacking_context sets DisplayItem::rect to Rect::zero() always, and has its own bounds inside StackingContext.  I think this is a leftover from when SC's were converted to push/pop; we should be able to get rid of the inner bounds, right?

**Comment by mrobinson** [comment]
@vvuk This seems reasonable to me.

**Comment by glennw** [comment]
@mrobinson Is this still relevant?

**Comment by mrobinson** [comment]
@glennw This shouldn't be an issue any longer because now stacking contexts just have a bounds and no longer a clip bounds as well. That bounds is stored in the common DisplayItem struct, so I'll just close this.
