### ISSUE TITLE
Try out Software Occlusion Culling to replace tiling

### ISSUE THREAD

**Issue by kvark** [servo/webrender#621]
Tiling allows to completely avoid drawing certain areas that we know are being occluded. Instead, we could run a software rasterizer of a small resolution target, draw big opaque occluders there, and cull out all other primitives based on it.

Removing the tiles would reduce the number of drawn instances. It would also allow us to greatly simplify the primitive transformation shaders, potentially merging it with non-transformed paths.

**Comment by glennw** [comment]
The initial prototype of using the z-buffer works well with this, and seems to provide very good performance. A hybrid between these two could be ideal, if we can work out the clip + tile issue we discussed.

Additional benefits of this approach:
 * Can draw non axis-aligned input geometry segments.
 * Can easily work with depth buffer + front-to-back pass for quick per-pixel rejection of opaque primitives.
 * Relatively small change to make to existing code.
 * Occlusion culling can be its own module, potentially run on GPU in the future.
 * Post effect shaders such as stacking context blur become a lot simpler.
 * Easy to multi-thread.
 * Can apply to only large occluders and occludees to minimize any work for small primitives that are unlikely to benefit.

**Comment by glennw** [comment]
No longer relevant.
