### ISSUE TITLE
Webrender should be able to display a ligature with two different colors.

### ISSUE THREAD

**Issue by emilio** [servo/webrender#622]
Asked @glennw about this today, and decided that it was worth to open an issue.

I don't know who the relevant Gecko person is to know about this, maybe @jrmuizel?

This is one of the most annoying WebKit/Blink bugs I've ever found, there are multiple test cases in:

 * https://bugs.chromium.org/p/chromium/issues/detail?id=6122
 * https://bugs.webkit.org/show_bug.cgi?id=6148

Reference test case: http://jsfiddle.net/xs5knzzd/5/

**Comment by jrmuizel** [comment]
I'm not sure how this works in Gecko. @jfkthame probably knows or could more easily say where to look.

**Comment by jfkthame** [comment]
Gecko collects text from a list of frames into a single textrun for shaping, so effects like ligatures can still occur across frame boundaries; see the BuildTextRunsScanner class in layout/generic/nsTextFrame.cpp. We'll only start a new textrun (and therefore interrupt shaping) if styles that would impact shaping don't match, such as the various `font-*` properties, `text-transform`, etc.; see BuildTextRunsScanner::ContinueTextRunAcrossFrames. In particular, a change in `color` does *not* make ContinueTextRunAcrossFrames return false, and so adjacent spans that differ only in color will be backed by a single continuous textrun, and shaped as a single unit.

**Comment by jfkthame** [comment]
When it comes to *rendering* the ligature at such a boundary (a separate issue from whether the ligature is formed at all, which is the problem those webkit/blink bugs are about), we have code in gfx/thebes/gfxTextRun.cpp to render partial ligatures when the range to be drawn (i.e. the section of the textrun corresponding to a particular element with a certain color) includes part of a ligated cluster of characters at the beginning or end. See gfxTextRun::Draw and its helper gfxTextRun::DrawPartialLigature.

**Comment by glennw** [comment]
The plan is for the client code to do this with clip rects. Please re-open if anything is needed from WR to handle this.
