### ISSUE TITLE
Error: No matching overload for function 'textureLod' found

### ISSUE THREAD

**Issue by mmatyas** [servo/webrender#628]
When running Servo on Android, the following shader compile error occurs (after applying the previous two Android patches, #626 and #627):

```
D/RustAndroidGlueStdouterr(22216): DEBUG:webrender::device: compile "ps_rectangle"
D/RustAndroidGlueStdouterr(22216): DEBUG:webrender::device: compile "ps_rectangle"
D/RustAndroidGlueStdouterr(22216): Failed to compile shader: "ps_rectangle"
D/RustAndroidGlueStdouterr(22216): WARN:servo: Panic hook called.
D/RustAndroidGlueStdouterr(22216): 0:715: S0001: No matching overload for function 'textureLod' found
D/RustAndroidGlueStdouterr(22216): ERROR:servo: -- Shader compile failed - exiting --
```

[Here](https://github.com/servo/webrender/blob/56255e673ad6cea81bc3d939af4e1a5bc7b9a3cc/webrender/res/prim_shared.glsl#L674)'s the `textureLod` call. The problem occurs on an Odroid XU3, running Android 4.4.4.

Related: servo/servo#13154

**Comment by glennw** [comment]
That's interesting - as far as I can see textureLod is part of es3. @kvark We could change this to a texture(Offset) right? (even if just as a workaround for now).

**Comment by kvark** [comment]
Oh, I think we just need to pass `0.0` for the LOD (instead of `0`), since it's a `float` parameter on all overloads of this function.

**Comment by glennw** [comment]
Ah, that makes sense.

**Comment by mmatyas** [comment]
Thanks; at the moment I don't have the Odroid at hand, but I will try it tomorrow (GMT+1).

**Comment by mmatyas** [comment]
Using `0.0` fixed the problem, thanks!
