### ISSUE TITLE
Dynamic opacity and scaling

### ISSUE THREAD

**Issue by kvark** [servo/webrender#640]
We support scrolling for asynchronous operations, but we also need opacity changes as well as scaling.

**Comment by glennw** [comment]
Could you expand a little bit on what this involves and what the use case is?

**Comment by jrmuizel** [comment]
This is required for off main thread animations. i.e. a web page can set up an animation on a div that changes it's transform or opacity and we should be able to deal with that entirely in webrender.

**Comment by glennw** [comment]
@jrmuizel OK, that makes sense. How does gecko currently match up the opacity for a given div with a layer in the compositor right now? That's probably the only tricky part to this task. Do you have any thoughts on what the API would look like to make it easy to integrate into gecko?

**Comment by howareyou322** [comment]
About off main thread animations, gecko will sample new animation value for a given div(usually maps to a containerlayer) during every vsync. I assume we still keep the logic of sample animation in gecko, but tell webrender an animation effect change on one div. Am I right?

**Comment by glennw** [comment]
This is supported now via https://github.com/servo/webrender/pull/832 - we can open more specific issues for bugs / extra features.
