### ISSUE TITLE
Support source blending to the final framebuffer

### ISSUE THREAD

**Issue by kvark** [servo/webrender#643]
https://bugzilla.mozilla.org/show_bug.cgi?id=1391322

See `CAIRO_OPERATOR_SOURCE` from https://www.cairographics.org/operators/

~~Not entirely sure this is needed. We may use this issue as a space for discussion and close it afterwards.~~
Gecko would provide us with a list of rectangles, which we would then need to ensure are not affected by any rendering. This can be done by rendering them with an opposite alpha from what our framebuffer is cleared with, right after the clear, and then compositing the otherwise final picture onto it with blending that excludes those areas.

**Comment by glennw** [comment]
Could you expand a little bit on the use case for this?

**Comment by jrmuizel** [comment]
This is used for making parts of the back buffer transparent for the vibrancy effect on OS X and cutting out the spots for window controls on Windows.

**Comment by glennw** [comment]
@jrmuizel Thanks - does this require anti-aliasing around the edges, or is it a straight in/out mask?

**Comment by jrmuizel** [comment]
I think pixel aligned rectangles are probably sufficient for our needs.

**Comment by glennw** [comment]
@jrmuizel OK - I wonder if it makes sense to just use the stencil buffer for this then?

**Comment by jrmuizel** [comment]
Possibly but that nearly feels like overkill. Let's look more closely at what an appropriate solution will be once we hook up the gecko side.

**Comment by glennw** [comment]
Sure, sounds good.

**Comment by mstange** [comment]
This is superseded by #1926 and can be closed.
