### ISSUE TITLE
Enable wrench tests to run on travis.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#647]
We want to run some tests inside the WR repo on each commit, instead of when updating to Servo. To do this, we'll need OSMesa available on travis so that we have a GL3 compatible rasterizer.

This file contains the config that travis uses to test each commit https://github.com/servo/webrender/blob/master/.travis.yml#L13.

We have the OSMesa that we use to test Servo packaged up as a cargo dependency here - https://github.com/servo/osmesa-src.

To make this available to wrench, just add it as a dependency to the Cargo.toml for wrench. See https://github.com/servo/servo/blob/4eb653817f87e5fb47de34356f558eb76ecbca9f/ports/glutin/Cargo.toml#L27 for an example of how we do this in Servo.

This means that libOSMesa.so will be built as part of the process of building wrench.

Then, you need to find the location of the OSMesa library, and add it to the dynamic library path. We use python code via mach to do this for servo (see https://github.com/servo/servo/blob/75c869d508231a216413808d80d6e02dec3ced6c/python/servo/command_base.py#L216 and https://github.com/servo/servo/blob/75c869d508231a216413808d80d6e02dec3ced6c/python/servo/command_base.py#L51), but it should be possible to do with a bash script that travis can run.

With that done, it should be possible to edit the travis.yml file to set those environment variables and run wrench tests.

**Comment by glennw** [comment]
cc @jrmuizel

**Comment by glennw** [comment]
@jrmuizel I've pushed a WIP branch to https://github.com/servo/webrender/pull/649.

On my local machine, I can use ./run_tests.sh <yaml file> and it will run wrench in an OSMesa headless context, wait one second, and then save the output to screenshot.png.

It's very hacky, but it should be a good start towards this task. I haven't tested it on mac - there might be a couple of issues with the run_tests.py file which sets the environment variables.

It probably needs some work to run correctly on travis (e.g. I haven't modified travis.yml to install LLVM or any other mesa dependencies yet).

**Comment by jrmuizel** [comment]
This branch should mostly work on travis. It does the llvm install and also builds glx so there's not a conflict with the system one.

https://github.com/jrmuizel/webrender/tree/wrench-osmesa

**Comment by jrmuizel** [comment]
This is happening now.
