### ISSUE TITLE
Should we do something about platforms where glTexSubImage2D behaves badly?

### ISSUE THREAD

**Issue by nical** [servo/webrender#650]
WebRender relies pretty heavily on grouping images in its texture cache and using glTexSubImage2D to add or update elements in the cache. On some mobile GPUs (like adreno) glTexSubImage2D does pathologically stupid things. In gecko we disable partial texture updates and always upload the full texture on these systems (works because we always have a cpu representation of the texture, webrender does not).

One solution could be to pack all uploads for a given frame in a new texture that is created every frame where we need to update the cache, and have a pass that copies from that texture into the texture cache.

For reference: http://searchfox.org/mozilla-central/rev/09ae31fddfbc229ef1b8f1a3ccd87ad05680e695/gfx/gl/GLUploadHelpers.cpp#86

**Comment by kvark** [comment]
There is always a path to simply force our software backend on those exclusive platforms. I don't see an easy workaround, and it would be much cleaner to work in WR with an assumption that we can do sub-texture updates without storing copies all around.

**Comment by glennw** [comment]
@kvark Do we need this open still? I think we have an additional upload method, and we could perhaps open specific issues if/when we have profile data?

**Comment by kvark** [comment]
I think this needs clarification from @nical . Does the "bad" behavior of Adreno (and others) apply to the upload methods we have implemented? More generally, does it apply to PBO uploads?

**Comment by nical** [comment]
In a nutshell the badness is: "glTexSubImage2D is a horror-show" On some devices.
I haven't looked at the various upload strategies we have in detail but I think that PBO is fine at least with respect to the horror stories I have in mind.

**Comment by kvark** [comment]
Great!
