### ISSUE TITLE
Deal with giant textures more gracefully than panicking

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#652]
There's a couple of gecko reftests that crash when run with WebRender because they fail the assertion at https://hg.mozilla.org/projects/graphics/file/73bdd29461ae/gfx/webrender/src/texture_cache.rs#l648. We should handle that scenario more gracefully. Mozilla bug for this issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1322816

**Comment by nical** [comment]
I started looking into this.

The approach I am taking is to split the large image into smaller tiles, upload the ones that are visible on screen to the texture cache and generate a primitive for each visible tile instead of just one for the image.

**Comment by glennw** [comment]
@nical I think this can be closed now?
