### ISSUE TITLE
Sample gaussian instead of calculating it

### ISSUE THREAD

**Issue by Manishearth** [servo/webrender#66]
For gaussian blurs, we [calculate the gaussian value for every fragment](https://github.com/glennw/webrender/blob/master/res/blur.fs.glsl#L3).

It might be better to create a single 1D texture which we sample and transform for calculating the gaussian.

(Not sure how this all works on the Rust side, filing as a placeholder)

**Comment by Manishearth** [comment]
@wenderen Want to look into this?

**Comment by wenderen** [comment]
Sure, it looks interesting. Thanks for pointing it out!

**Comment by Manishearth** [comment]
Nah, this was an idea I brought up the other day, which sounded interesting but nobody's working on it right now.

It probably won't produce a significant perf increase since webrender's GPU perf makes it mostly CPU bound. But it should help for software renderers and make hardware rendering just a bit faster.

**Comment by Manishearth** [comment]
@pcwalton Do we have any good test cases for gaussian blur?

**Comment by pcwalton** [comment]
I just use a simple Web page with a text shadow.

**Comment by Manishearth** [comment]
@wenderen `text-shadow: 5px 5px 10px #FF0000;` works pretty nicely as a test case, then.

To test, compile [this branch](https://github.com/glennw/servo/tree/webrender), and run with `-w`. See if there's any difference between existing blurs and and the blurs after your change.

**Comment by glennw** [comment]
I think this is resolved now - we run the shader only on the minimal area required, and then stretch / mirror the blur across the primitive. The box shadow shader cost is negligible on all sites I've tested recently.
