### ISSUE TITLE
init_texture() does not care format change on arm

### ISSUE THREAD

**Issue by sotaroikeda** [servo/webrender#661]
On arm, ImageFormat::A8 uses GL_FORMAT_BGRA. Then init_texture() need to expand data like update_texture(). By it, debug_render's rendering seems to be broken on my nexus5X with quantum graphic branch.
  https://bugzilla.mozilla.org/show_bug.cgi?id=1323612

device.rs defines the following, but it seems not used.
  >#[cfg(any(target_arch = "arm", target_arch = "aarch64"))]
  > const GL_FORMAT_A: gl::GLuint = gl::ALPHA;

**Comment by glennw** [comment]
This was fixed in https://github.com/servo/webrender/pull/779.
