### ISSUE TITLE
Add CI for testing other shader compilers

### ISSUE THREAD

**Issue by larsbergstrom** [servo/webrender#665]
One issue that we've noticed (especially @dati91 and @mmatyas) is that WebRender shader changes often run afoul of the various "interesting" shader compilers on ODROID, Android, etc. e.g., #653 and #654 but also several Android fixes in the past.

Is it feasible to, say, create some VM images of various platforms that we think are likely to be representative of likely to have fragile shader code and run them as extra TravisCI builders?

Or is there a really solid shader verifier that we could be running as a build step?

cc @glennw

**Comment by jrmuizel** [comment]
There are a couple of options here:

1. https://github.com/KhronosGroup/glslang is the reference compiler.
2. Once we get some basic testing up (#647) I'd like to get running on top of ANGLE. ANGLE should have a reasonably strict glsl compiler.

**Comment by glennw** [comment]
@larsbergstrom Yup, I *think* that running one of the shader validator tools / ANGLE on CI will catch these errors, and be the simplest change to implement. But we could definitely consider having a VM to test android shader compiles on, if these errors are still not being caught.

**Comment by kvark** [comment]
Speaking of glslang - #616

**Comment by emilio** [comment]
Also, we have angle bindings for WebGL. They're far from complete, but we use them for compiling and validating shaders, so they should be usable for this purpose.

They live in https://github.com/servo/angle, and you can see how we use them in https://github.com/servo/servo/blob/master/components/script/dom/webglshader.rs

**Comment by kvark** [comment]
Here is an example of integrating `glslang` into Travis CI: https://android.googlesource.com/platform/external/shaderc/shaderc/+/ndk-r11/.travis.yml

**Comment by glennw** [comment]
We do shader validation on CI now.
