### ISSUE TITLE
Fix `wrench` compile warnings

### ISSUE THREAD

**Issue by kvark** [servo/webrender#669]
See the following Travis log for the reference:
https://travis-ci.org/servo/webrender/jobs/186253950

**Comment by joemccall86** [comment]
I'll take a swing at this. WIP is here if anyone is interested: https://github.com/joemccall86/webrender/tree/gh-669

**Comment by kvark** [comment]
@joemccall86 thanks! Beware of the incoming large #660 too.

**Comment by joemccall86** [comment]
Thanks, I'll hold off until that's complete, as many of the warnings came from those affected files.

**Comment by kvark** [comment]
@joemccall86 please proceed if still interested
