### ISSUE TITLE
Standalone texture allocation id's are freed in render_backend but not in renderer

### ISSUE THREAD

**Issue by rlhunt** [servo/webrender#676]
The CacheTextureId for standalone texture allocations is returned to the free list in the render_backend when it is freed [1], but no message is sent to sync this change to renderer. When that id is reused. this assert [2] is triggered.

I was able to trigger this by using ImageRendering::Pixelated which causes TextureFilter::Point which causes standalone texture allocations.

Either not returning the id to the free list or adding a new TextureUpdateOp to free from the cache_texture_id_map worked for me. I'm not sure if there are any side effects we'd need to be concerned about with freeing from cache_texture_id_map, but I think that'd be the way to go.

[1] https://github.com/servo/webrender/blob/master/webrender/src/texture_cache.rs#L880
[2] https://github.com/servo/webrender/blob/master/webrender/src/renderer.rs#L867

**Comment by glennw** [comment]
@rlhunt This is fixed now, right?

**Comment by kvark** [comment]
Yeah, closing.
