### ISSUE TITLE
Change API to only publish a frame explicitly (via generate_frame).

### ISSUE THREAD

**Issue by glennw** [servo/webrender#702]

**Comment by excaliburHisSheath** [comment]
Is there more information available for this? I'd like to work on it, but it might need to be fleshed out more (I'll try to investigate it some myself but without any experience with webrender there's no telling if I'll get anywhere).

**Comment by jrmuizel** [comment]
Basically this just involves moving the code for build_scene(), render(), etc. out of SetRootDisplayList and SetRootPipeline into GenerateFrame() and then fixing up the callers of SetRoot* to generate the GenerateFrame messages in addition to their current messages.

**Comment by excaliburHisSheath** [comment]
Thanks for the info! I'll give it a shot.
