### ISSUE TITLE
wrench show doesn't seem to work on macOS anymore

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#720]
I'm pretty sure this used to work for me.

**Comment by jrmuizel** [comment]
It looks like 55af167c3477439094997814e4937f32b5775130 broke this.

**Comment by jrmuizel** [comment]
Something like https://github.com/jrmuizel/webrender/tree/fix-event-loop improves things but I think is not quite right as we get stuck blocking.

**Comment by emilio** [comment]
Probably upgrading glutin to 0.7 helps?

**Comment by jrmuizel** [comment]
Upgrading glutin to 0.7 does not seem to help

**Comment by glennw** [comment]
@jrmuizel I don't have access to a mac right now, but we can debug this tomorrow on your mac.

**Comment by jrmuizel** [comment]
It looks like this is an issue in how winit handles the user event. I'll come up with a patch.

**Comment by glennw** [comment]
@jrmuizel This is resolved now, isn't it?

**Comment by kvark** [comment]
AFAIK, wrench crashes when zooming in on a mac, but is generally usable.
