### ISSUE TITLE
support external "image buffer" in Webrender

### ISSUE THREAD

**Issue by JerryShih** [servo/webrender#723]
@glennw @nical @kvark 
Currently, webrender could resolve a gl texture id from a external texture id through the externalImage callback api[[1]](https://github.com/servo/webrender/pull/636/commits/1cb9ab2ade29d210cc9b04eac5ac5cec57ecb206). Then, webrender could use that gl texture id for rendering.

I think we could also pass raw buffer to webrender, and let webrender to upload this buffer into gl texture. In this way, webrender might use texture atlas for this texture uploading. That could have a better performance in drawing with batching.

We can't just use the wr_add_image() api directly, that api implies some memory copy operations. That's not a good practice for a large image.

I will attach my patch here if I fix the crash in my WIP.

[1]
https://github.com/servo/webrender/pull/636/commits/1cb9ab2ade29d210cc9b04eac5ac5cec57ecb206

**Comment by kvark** [comment]
So there is going to be at least 3 ways to provide the texture contents:
  1. Data to be consumed by WR via `wr_add_image`
  2. Shared data to be used by WR without copying (this issue)
  3. Pure Texture ID

**Comment by JerryShih** [comment]
@kvark 

Yes, there will have 3 different ways to set the texture to WR.
1. Data to be consumed by WR via wr_add_image(we already have that).
2. Shared data to be used by WR without copying (this issue. WR will try to get the raw-buffer through the ExternalImageCallback)
3. Pure gl texture id(we already have that)
