### ISSUE TITLE
Update wrench code to use assert!() instead of if ... { panic!(..) }

### ISSUE THREAD

**Issue by glennw** [servo/webrender#727]

**Comment by hgallagher1993** [comment]
Ya I could pick this up. . .does it need a custom error message or just `assert!(nums.len() != 16)`?

**Comment by mrmiywj** [comment]
I can pick this up.

**Comment by igilham** [comment]
Looks like this can be closed.

**Comment by kvark** [comment]
@igilham right, thanks for triaging!
Fixed by #1023
