### ISSUE TITLE
Fix texture update stalls in WR

### ISSUE THREAD

**Issue by glennw** [servo/webrender#728]
When running with INTEL_DEBUG=perf there are a number of performance warnings about CPU being blocked the driver due to updating resources. We should identify the cause of these and fix them. These will explain at least some of the spikes we sometimes see in the GPU profiler.

**Comment by kvark** [comment]
Is this still a problem?

**Comment by glennw** [comment]
There are other stalls present, yes. I'm not sure if they are textures or something else.

**Comment by glennw** [comment]
I don't see these problems any more.
