### ISSUE TITLE
Support opaque rgba.

### ISSUE THREAD

**Issue by nical** [servo/webrender#732]
24 bits rgb is not very well supported by most opengl drivers and not supported at all in D3D. Gecko pretty much only uses 32 bit RGBA surfaces some of which being flagged as opaque and we need WebRender to handle the latter efficiently.
We should also uses this as an occasion to make the format names match the actual representation (for example RGBA should actually be BGRA, or maybe B8G8R8A8 to avoid confusion (for example it's not obvious whether RGB means 24 bits rgb or 32 bits rgb with the alpha channel ignored which is more commonly used).

**Comment by leeoniya** [comment]
...or BGRA8, assuming they wouldn't vary per channel?

**Comment by nical** [comment]
I have a preference towards sticking to the vulkan/DXGI convention (B8G8R8A8) which has no ambiguity and can describe all formats, including the ones where channels have different bit depths (we don't use them at the moment but might as well keep the door open). It's also the naming convention that Gecko uses so there's incentive to not have to jungle between several naming conventions.

**Comment by nical** [comment]
ImageDescriptor now has an opaque boolean flag, which means we can use 32bpp image formats while keeping the opaque optimizations.
