### ISSUE TITLE
Separate stacking context and scroll root concepts.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#742]
The eventual solution may be quite different to the title of this bug - but we can use this as a tracking bug anyway.

**Comment by glennw** [comment]
cc @mrobinson @kvark @nical @jrmuizel

**Comment by glennw** [comment]
See https://github.com/servo/servo/issues/13530

**Comment by mrobinson** [comment]
I think this is complete now.

**Comment by glennw** [comment]
\o/
