### ISSUE TITLE
Document the development history of WR

### ISSUE THREAD

**Issue by kvark** [servo/webrender#744]
It would be great to have a wiki page showing off the main development milestones that WR has passed through as well as the key decisions/changes made on the way.
Of the latest changes, the removal of tiles is the most controversial, which we need to document (reasoning, cons/pros, new internal architecture, future expansion, etc)

**Comment by kvark** [comment]
Tile removal chapter is up - https://github.com/servo/webrender/wiki/History#tile-removal

**Comment by glennw** [comment]
I think we can close this since it's not really actionable by itself - we can open issues for documenting specific parts or decisions.
