### ISSUE TITLE
Smarter mask keys for repeated masks

### ISSUE THREAD

**Issue by kvark** [servo/webrender#760]
We don't need to generate 2 different masks for two primitives if they both are the same rounded cornered rectangle. This doesn't affect the real-use websites as much as it affects the benchmarks.

Basically, our key is currently either a primitive index, or a stacking context index, so it doesn't allow re-using the same mask between primitives if it's not in the stacking context. We could special-case the key to contain the parameters of the rounded cornered rectangle.

cc @glennw

**Comment by glennw** [comment]
@kvark See http://browserbench.org/MotionMark/developer.html - Animometer tests and also the 1st and 3rd HTML tests.

**Comment by kvark** [comment]
The benchmark has these interesting numbers:
> Style Recalc                          no           yes     http://browserbench.org/Motion         68.8947
> Script JS Evaluate                      no           yes     http://browserbench.org/Motion         28.7000

So we are far from being render-bound, borderline to having this issue closed ;)

**Comment by glennw** [comment]
No longer relevant.
