### ISSUE TITLE
Remove pipeline_size_changed callback

### ISSUE THREAD

**Issue by jdm** [servo/webrender#766]
Since https://github.com/servo/servo/pull/15129 merged in Servo, this callback is now unused. We should remove it and update the version number in Cargo.toml to show that this is a breaking change.

**Comment by hgallagher1993** [comment]
Ya I could take this, is it just to remove it from the `RenderNotifier` trait? and should the traits toml just be bumped up 1. . .0.11.0 -> 0.12.0?

**Comment by jdm** [comment]
Correct and correct. There may be more code we can remove when we look at the code that invokes the method, since it may be doing unnecessary work at that point.

**Comment by hgallagher1993** [comment]
:+1:

**Comment by glennw** [comment]
This happened.
