### ISSUE TITLE
MixBlendMode::{Darken, Lighten} doesn't work

### ISSUE THREAD

**Issue by rlhunt** [servo/webrender#777]
Specifying a mix-blend-mode darken or lighten causes an element to appear yellow.

Adding new cases in ps_composite.fs.glsl seems to work. I think Darken and Lighten should also be able to be implemented using a gl blend function. (they're just a min and max operator).

I could add cases in ps_composite.fs.glsl, but I would need guidance on how webrender composites for using gl blend functions.

**Comment by glennw** [comment]
I think it's fine to implement as a shader operation, for now. We can file a follow up / optimization issue to use blend modes where applicable.

**Comment by glennw** [comment]
This got fixed.
