### ISSUE TITLE
Investigate the RGBA / BGRA weirdness in internal formats.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#809]
Make this more consistent, which will involve sorting out PackedTexel struct. This could be part of the larger "make the image formats more sane" task.

**Comment by kvark** [comment]
We explicitly use BGRA as an internal format only on GL ES, where there is `GL_BGRA_EXT` that we require. We implicitly assume that RGBA8 internal format on GL is actually BGRA, thus we expect the incoming data to always be BGRA for performance reasons (so that the driver doesn't need to swizzle).

**Comment by nical** [comment]
Fixed in #1360.
