### ISSUE TITLE
The backdrop component of a MixBlendMode composite is always white

### ISSUE THREAD

**Issue by rlhunt** [servo/webrender#838]
Right now the backdrop color used by ps_composite.fs.glsl is fixed to rgb(255, 255, 255). This breaks mix blend mode. Sadly the only test for mix-blend-mode in wrench passes with that.

I did a git bisect to find when this regressed and got 'Include the clipping rectangle of a stacking context into the clip stack', SHA: dacef46e42dcf070eedc33b37a25bfe63072b373

You can test this by switching the mix-blend-mode of reftests/blend/multiply.yaml to difference. The inner square should be rgb(0,0,0) but it's rgb(255,0,255)

@kvark

**Comment by kvark** [comment]
> Right now the backdrop color used by ps_composite.fs.glsl is fixed to rgb(255, 255, 255). This breaks mix blend mode.

My change didn't touch either the shader or the color, it only affected the clipping.

**Comment by rlhunt** [comment]
Yes, so I don't have any idea why it would have caused this. But if I run it before and after your patch the behavior changes. Could something be clipped too much in an intermediate step?

**Comment by kvark** [comment]
> You can test this by switching the mix-blend-mode of reftests/blend/multiply.yaml to difference. The inner square should be rgb(0,0,0) but it's rgb(255,0,255)

I tested it on master, and the inner square is black.

**Comment by rlhunt** [comment]
You're right, I retested on master (512b4a1433a7827ef7cfd121d2f99fdd91ecf80e) and it works. The commit before that is failing.

**Comment by kvark** [comment]
Sweet, thanks @rlhunt
