### ISSUE TITLE
StackingContext clipping to masks is gone

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#841]
We depended on this in Gecko and doesn't really seem possible anymore. It looks like this is causing a bunch of reftest failures when trying to update webrender in Gecko.

**Comment by jrmuizel** [comment]
It looks like it should be possible to replicate this with scroll layers. I'm going to make sure that works out.

**Comment by glennw** [comment]
cc @mrobinson

**Comment by mrobinson** [comment]
@jrmuizel Sorry about the breakage! You're correct that the "right" way to do this ATM is with ScrollLayers or by applying the clip to every item. Eventually it will be possible to define a mask and have it mask any item. If these things don't sound like what you need let's chat about what the best design is.

**Comment by glennw** [comment]
I believe this is resolved (for now)? Let's re-open with more details if needed.
