### ISSUE TITLE
Figure out the StackingContext bounds semantics

### ISSUE THREAD

**Issue by kvark** [servo/webrender#859]
Since we move the `ClipRegion` from StackingContext to ScrollLayer, SC can no longer clip contents, so the bounds seem to lack the function.

@mrobinson 
> They still update the transformation because items are positioned relatively to stacking contexts. They also play a part in properly sizing render tasks for blends and such.

Sounds like we need an offset there on the API side, and the actual size would be computed internally as an implementation detail.

**Comment by glennw** [comment]
I agree - it makes sense for this to become an offset / origin. We should handle the bounds internally.

**Comment by mrobinson** [comment]
Long-term perhaps it makes sense to move to an API where there are effect groups and transformations and everything is positioned relatively to the nearest transformation ancestor. I haven't really decided what kind of API is better myself.

**Comment by glennw** [comment]
@mrobinson Is this still relevant?

**Comment by mrobinson** [comment]
I think with the elimination of all stacking context-based clipping, we can close this. If we ever reintroduce it, it will probably look different than what we had before.
