### ISSUE TITLE
reftest failures metabug

### ISSUE THREAD

**Issue by glennw** [servo/webrender#86]
This has a list of the remaining reftest failures, and any details on what needs to be fixed.

**Comment by glennw** [comment]
PASS (previously FAIL):
- [ ] /css-color-3_dev/html4/t425-hsla-values-b.htm
- [ ] /css21_dev/html4/abspos-overflow-010.htm

**Comment by glennw** [comment]
cc @pcwalton

**Comment by pcwalton** [comment]
I investigated `canvas_linear_gradient_a.html` against a script that draws the gradient with essentially infinite precision and WebRender gets the color of every pixel exactly right. So I believe that, if there is a bug here, it's in Skia and not in WebRender.

I also ran the test in Firefox: http://i.imgur.com/X7jAhQ8.png
And in Chrome: http://i.imgur.com/Tr5zd0N.png

Both browsers fail the test as written. So I think this test is probably not worth fixing, given that (a) it seems the precision bug is in Skia and (b) nobody else passes it anyway.

**Comment by glennw** [comment]
@pcwalton Cool! I'll mark it as fixed above based on that :)

**Comment by pcwalton** [comment]
I looked at `borders_a.png`.

WebRender's current rendering: http://i.imgur.com/UkH5r04.png
Firefox's rendering: http://i.imgur.com/5YwwraX.png
Chrome's rendering: http://i.imgur.com/luW3bAh.png

Issues:
* The left part of the top border is not drawn by WebRender. Blink and Gecko draw it. **Likely WebRender bug**, so needs fixing.
* The green/red/black dashed border corner is drawn as a triangle in WebRender and Blink but is not in Gecko. **WebRender agrees with Blink.**
* Dots are drawn as circles in WebRender and Gecko but as squares in Blink. **WebRender agrees with Gecko.**
* The next two lines are black and green in WebRender and Blink but green and light green in Gecko. **WebRender agrees with Blink.**
* The next line is 85,85,0 in WebRender, 170,170,0 in Blink, and 179,179,0 in Gecko. **All engines disagree**; possible WebRender bug.
* The next two lines are the same shade of yellow and green in WebRender and Blink but different in Gecko. **WebRender agrees with Blink.**
* The next line is 0,85,0 in WebRender, 0,90,0 in Blink, and 0,44,0 in Gecko. **All engines disagree**; possible WebRender bug.
* The next two lines are the same shades of yellow in WebRender and Blink but different in Gecko. **WebRender agrees with Blink.**
* The next line is, again, 0,85,0 in WebRender, 0,90,0 in Blink, and 0,44,0 in Gecko. **All engines disagree**; possible WebRender bug.
* The last three lines are the same shades of yellow and green in WebRender and Blink but are lighter colors in Gecko. **WebRender agrees with Blink.**

**Comment by pcwalton** [comment]
`linear_gradients_lengths_a.html` actually seems to be both a bad test and a Servo bug. I've submitted a fix here: https://github.com/servo/servo/pull/9171

**Comment by pcwalton** [comment]
I investigated `filter_sepia_a.html`.

Gecko, WebKit/Safari, and old Servo give 147,133,103.
Blink and WebRender give 148,132,103.

So ***WebRender agrees with Blink.*** I'll work out the matrix myself.

**Comment by pcwalton** [comment]
@glennw `image_rendering_auto_a.html` doesn't work because the texel snapping that you added in 02ec327eeee304a9990b6e41bc1fa936bd717141 has the effect of removing bilinear filtering. Any ideas as to how you'd like to fix this?

**Comment by glennw** [comment]
css/inline_stacking_context.html - seems to have regressed.
css/list_item_overflow.html - new failure?
css/text_shadow_blur_a.html - seems to have regressed.

**Comment by pcwalton** [comment]
I think the problem with `css/text_shadow_blur_a.html` may be that it isn't loading Ahem properly.

**Comment by glennw** [comment]
These got fixed.
