### ISSUE TITLE
Properly follow semver

### ISSUE THREAD

**Issue by nox** [servo/webrender#864]
Even if WR isn't published on crates.io, it's extremely difficult to follow along which PRs are introducing breaking changes, and it makes any crate bump such as serde more difficult than they are already.

PRs should properly bump version numbers, at least when they include breaking changes.

**Comment by kvark** [comment]
That's a general rule that we've been trying to keep up with so far. I don't think it makes sense to leave this issue open though, since it's not clear when it can be closed.

**Comment by nox** [comment]
That is true.
