### ISSUE TITLE
Support border-image

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#879]
We need this for rendering Gecko's chrome. We should first come up with an idea of what the interface needs to be.

See also https://github.com/servo/servo/issues/13003

**Comment by glennw** [comment]
@jrmuizel Do you already have something in mind for the interface to this?

**Comment by jrmuizel** [comment]
I do not.

**Comment by glennw** [comment]
I've had a brief look at the specification. It seems like we could modify the existing ```BorderDisplayItem``` from:

```
pub struct BorderDisplayItem {
    pub left: BorderSide,
    pub right: BorderSide,
    pub top: BorderSide,
    pub bottom: BorderSide,
    pub radius: BorderRadius,
}
```

to something like:

```
pub struct NormalBorder {     // What should this be called?
    pub left: BorderSide,
    pub right: BorderSide,
    pub top: BorderSide,
    pub bottom: BorderSide,
    pub radius: BorderRadius,
}

pub struct ImageBorder {
    pub image_key: ImageKey,
    // image slice, repeat params etc
    // border widths
}

pub enum BorderDisplayItem {
    Normal(NormalBorder),
    Image(ImageBorder),
}
```

Does that seem reasonable?

**Comment by glennw** [comment]
We'd also extend the ImageBorder to be able to specify a gradient or an image key - by extracting the parts of GradientDisplayItem into a standalone Gradient struct.

**Comment by mephisto41** [comment]
Anyone working on this? Can I take this? Thanks.

**Comment by jrmuizel** [comment]
@glennw has it largely implemented here: https://github.com/servo/webrender/pull/895
You can coordinate with him to do the unimplemented bits or start hooking it up to Gecko

**Comment by mephisto41** [comment]
Great! Didn't notice it. I'll hook it up to gecko. Thanks for the info.

**Comment by glennw** [comment]
This has landed now.
