### ISSUE TITLE
Add Taskcluster CI for webrender

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#880]
@jrmuizel wanted to try running webrender CI on taskcluster instead of travis to maybe speed things up. Doing this is fairly straightforward, see http://code.v.igoro.us/posts/2017/02/taskcluster-github-improvements.html and https://tools.taskcluster.net/quickstart/.

I built a docker image and taskcluster script to try this out, and have a sample CI run currently in progress at https://tools.taskcluster.net/task-inspector/#Xq6XN5JFS5qX2gV6BeFp5A/0 - if that goes well we should turn on the taskcluster-github integration and land the .taskcluster.yml file into the repo. That will get us CI running on taskcluster, and we can then work on optimizing it further by splitting up the tests to run in different tasks, trying to cache more build artifacts from dependencies, etc.

**Comment by staktrace** [comment]
The CI run took 34 minutes and completed successfully.

**Comment by staktrace** [comment]
I also tried splitting the debug vs release tests. You can see it in the task group at https://tools.taskcluster.net/task-group-inspector/#/MVjO8EHCQUS1FVfM8Bb6uA - the debug stuff took ~17 minutes and the release-mode build and reftests took ~35 minutes. So splitting it doesn't seem to really help much, at least on taskcluster.

**Comment by kvark** [comment]
And since this is about using docker, we might want to CI build for Android as well:
https://github.com/tomaka/android-rs-glue#with-docker

**Comment by glennw** [comment]
Are we still wanting to explore this?

**Comment by staktrace** [comment]
Let's close it for now. If somebody cares enough they can reopen it.
