### ISSUE TITLE
Add two rectangle structures to prim_shared.glsl

### ISSUE THREAD

**Issue by glennw** [servo/webrender#887]
We should have two Rect structures in prim_shared.glsl - one for (p0, p1) form and one for (p0, size) form.

Update all our shader code and structs to use them instead of vec4.

Using these would avoid error prone shader calculations involving rectangles.

**Comment by mephisto41** [comment]
May I try to do this?

**Comment by glennw** [comment]
Yep, go for it!

**Comment by glennw** [comment]
This can also be done incrementally - we don't necessarily need to update all the shaders in one go.

**Comment by glennw** [comment]
This happened.
