### ISSUE TITLE
panic in handle_primitive_run

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#894]
http://people.mozilla.com/~jmuizelaar/tmp/scroll-frame-crash.zip panics at
https://github.com/servo/webrender/blob/master/webrender/src/frame_builder.rs#L1194

cc @mrobinson

**Comment by glennw** [comment]
@jrmuizel says this isn't super urgent, as the failing tests can be disabled for now.

**Comment by jrmuizel** [comment]
This was discovered here: https://bugzilla.mozilla.org/show_bug.cgi?id=1332688
