### ISSUE TITLE
Deduplicate dependencies

### ISSUE THREAD

**Issue by nox** [servo/webrender#899]
There are three versions of `core-graphics-rs` referenced in `Cargo.lock`.

**Comment by kvark** [comment]
Another offender:
> 1519: "checksum yaml-rust 0.3.4 (git+https://github.com/vvuk/yaml-rust)" = "<none>"
 1520: "checksum yaml-rust 0.3.5 (registry+https://github.com/rust-lang/crates.io-index)" = "e66366e18dc58b46801afbf2ca7661a9f59cc8c5962c29892b6039b4f86fa992"

**Comment by waywardmonkeys** [comment]
I've submitted https://github.com/MSleepyPanda/rust-font-loader/pull/7 to help move this along.
