### ISSUE TITLE
Don't pull dwrote-rs from githuh

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#900]
Cset 4f14ec7 changed webrender/Cargo.toml to use dwrote-rs from github instead of crates.io. This prevents us pulling webrender into m-c because we can't vendor dwrote-rs, and the build fails. @nox, was there any particular reason you made this change? We would much rather have a new version of dwrote-rs published to crates.io, and then depend on that new version.

**Comment by nox** [comment]
Do you mean that `cargo vendor` doesn't support Git dependencies? Damn I didn't know that.

**Comment by nox** [comment]
We did that because nobody published `dwrote-rs` on crates.io.

**Comment by SimonSapin** [comment]
Either

* Someone with access to https://crates.io/crates/dwrote (meaning @vvuk or @changm) can publish version 0.2.0, or give publishing access to the Servo team (`cargo owner -a github:servo:cargo-publish dwrote`)
* Or if we don’t want to wait for that, we can publish the new version under another name like `servo-dwrote`. (Hopefully this will be temporary and we can switch back to `dwrote` later.)

**Comment by nox** [comment]
@staktrace I can definitely do the latter of what @SimonSapin said if there is absolutely no workaround and you want to unblock this now.

**Comment by SimonSapin** [comment]
We can change the package name (for crates.io, Cargo, and `[dependencies]`) without changing the crate name (for rustc and `extern crate`).

**Comment by SimonSapin** [comment]
https://crates.io/crates/servo-dwrote

**Comment by staktrace** [comment]
Yikes, sorry I wasn't more clear - I didn't need this resolved immediately. It's not actively breaking the build, it would just break our build the next time we try to pull a webrender update into mozilla-central. So as long as it gets resolved before that, all is good. I'm sure @vvuk would have no issue with giving servo-team permission to push new versions.

**Comment by nox** [comment]
Better safe than sorry, and we didn't want you people to have a bad Monday morning. Then let's all go back to weekending!

**Comment by vvuk** [comment]
No problem at all. I'll do it when I'm at my computer next.
