### ISSUE TITLE
Add wrench vs image comparison test mode.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#911]
Initially this could be exact pixel comparison only, but eventually we'll need to work out some support for "fuzzy" tests that differ slightly depending on the rasterizer.

**Comment by nical** [comment]
Should this be closed now that we have initial support for fuzzy reftests? Or did you also mean some syntax to compare directly against an image directly without creating a yaml file?

**Comment by kvark** [comment]
Yes, we still need the test against image logic. Fuzzy tests are pre-requisite.
