### ISSUE TITLE
Texture pages are not properly reused or deallocated

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#914]
When running the gecko webgl mochitest suite, WR memory usage climbs into multiple gigabytes (see https://bugzilla.mozilla.org/show_bug.cgi?id=1341745). I traced this down to the fact that WR periodically allocates a new TexturePage but never goes back and reuses old texture pages or deallocates them if they are empty. I checked with @kvark and he agreed that this appears to be a bug. Quoting him from IRC:

> I don't see TexturePage objects being de-allocated. Also, they are not re-used properly. As in - 
> allocation only checks for the last page, while other pages may have more free space if they got 
> some content removed from them
> so I think 2 modifications need to be done: 1) removal of the last page in a vector if it becomes 
> empty, and 2) check for all the pages when allocating

**Comment by kvark** [comment]
Note the comment:
> // TODO(gw): Actually free items from the texture cache!!

**Comment by glennw** [comment]
```committed on 29 Oct 2015```

I guess it's time to fix that!

**Comment by kvark** [comment]
I guess I shouldn't try to actually remove the `TexturePage` from the arena then? Since doing so would potentially allow for a test case to constantly create and destroy textures each frame, and the real reason for the leak is that 2015 missing feature.

**Comment by glennw** [comment]
It'd probably be worth adding some profile counters that track some of the texture cache stats (e.g. total bytes allocated, page count etc) so that we can visually see if something is leaking in the future.

**Comment by staktrace** [comment]
@kvark thanks, the fix seems to work!
