### ISSUE TITLE
Debug WR builds panic on shutdown due to Renderer::drop

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#915]
See e.g. https://treeherder.mozilla.org/logviewer.html#?job_id=79439278&repo=try&lineNumber=1723

The drop implementation added to Renderer in #913 tries to call deinit_texture, but that function has a debug assertion that `self.inside_frame` is true. Which it isn't, when drop() is called.

This blocks updating WR in the graphics branch as all the debug test jobs will crash.

**Comment by glennw** [comment]
cc @kvark

**Comment by kvark** [comment]
oops, that was a last-minute change. Looking now
