### ISSUE TITLE
Support BlobImages as masks

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#918]
It seems like this would be valuable.

**Comment by glennw** [comment]
What stops this working now?

**Comment by jrmuizel** [comment]
Maybe it does just work. I hadn't tried.

**Comment by glennw** [comment]
In *theory* it should work - blob images are created via ImageKey, which can be specified as a clip mask. They get requested the same way as images, so it may just work.

**Comment by nical** [comment]
Yep it works as long as the BlobImageRenderer implementation recognizes ImageFormat::A8 (the dummy implementation in the sample does so you can try it out).

**Comment by kvark** [comment]
Ok, so just leaving this open until we try it out and verify that it's ~~broken~~ good.

**Comment by nical** [comment]
I did verify it already :)

**Comment by kvark** [comment]
Thanks!
