### ISSUE TITLE
method needed for initializing gl

### ISSUE THREAD

**Issue by zmike** [servo/webrender#933]
Servo's CEF interface provides the initialize_compositing() method, which is used by an application to run all the GL initialization code after the application has set up its GL contexts/surfaces.

Ideally this should be able to be tested by building and running https://github.com/zmike/ecef, though I haven't tested the application with GLES3 in a long time so I can also be available for some testing if you run into issues on the application side.

cc @glennw

**Comment by glennw** [comment]
I *think* what we need to do here is basically add an init() method to Renderer and Device, and ensure that any GL calls are moved from the constructors to here. It's probably a little more complicated than it sounds, but I think that will work well. That will also allow us to make the init() method fallible in case of bad hardware, shader compile errors etc.

**Comment by kvark** [comment]
Is there any point in creating `wr::Renderer` prior to being able to initialize the GL stuff at all? Can the client (Servo) just call `Renderer::new` when it's ready?

**Comment by zmike** [comment]
Has there been any progress with this?

**Comment by glennw** [comment]
Not yet, no.

**Comment by nical** [comment]
Servo's CEF isn't a thing anymore I'm told.
