### ISSUE TITLE
Inspire from different game engine implementations ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/webrender#94]
You say on the wiki that webrender is like à game engine, so why not watch and inspire from the source code of existing game engine ? 
You could win a lot of time ! 

Here the godot engine : https://github.com/godotengine/godot
And the wiki for understunding : https://github.com/godotengine/godot/wiki

For the unreal engine : https://github.com/EpicGames/Signup (the code is not full free and need an account) 

The ogre engine : http://www.ogre3d.org/

The love engine (2d only) : https://love2d.org/

Also a very interesting project, a game engine for HTML 5, the cube engine : https://github.com/Nurgak/Cube-engine

A list of others html5 game engine : https://html5gameengine.com/

A list of all standard game engine : https://en.m.wikipedia.org/wiki/List_of_game_engines

Sorry for my bad english.

**Comment by glennw** [comment]
These are interesting links, but I'll close this since it's not an actionable issue.
