### ISSUE TITLE
Handle image format changing in WR

### ISSUE THREAD

**Issue by JerryShih** [servo/webrender#943]
@glennw @kvark @nical @sotaroikeda

In gecko, we can set different video source to a HTMLMediaElement. Then, the compositor will receive various formats of image(rgb or yuv) for composition.
In current WR, we should push different display item for different image format(add_image() for rgb and add_yuv_image() for yuv format in frame_builder.rs). When the format changes, we should push the corresponding display item again and re-build the whole frame data. For the performance purpose, it's good to have a universal display item type which could handle both yuv and rgb format. Then, we could use the similar webrender animation api(https://github.com/servo/webrender/pull/832) or other different api to update the final properties(e.g. the image format and external image id) for that universal video image display item.

**Comment by sotaroikeda** [comment]
gecko has a special path to render Images via ImageBridge. In this path, Updating images happens off main thread ways. It is used for video playback, WebRTC and plugin rendering. The following change could happen at any timing. 
 - size change
 - format change
 - video frame clear
It would be nice if we could have a place holder of Image and could update Image without new DisplayItem. On current gecko, it is handled by ImageLayerComposite.

**Comment by sotaroikeda** [comment]
Even when if there is not format or size change, we need a way to update rendering video images without pushing new DisplayList.

**Comment by kvark** [comment]
> When the format changes, we should push the corresponding display item again and re-build the whole frame data. For the performance purpose, it's good to have a universal display item type which could handle both yuv and rgb format. 

I don't consider this a performance issue, since I don't assume you change the format/size every frame.

**Comment by nical** [comment]
> Even when if there is not format or size change, we need a way to update rendering video images without pushing new DisplayList.

I am not certain about _needing_ to update the format without changing updating the display list.

If the format changes often within a given video stream, I agree. If it only happens occasionally while switching between decoders or source, I would not say that rebuilding the display list is that much of an issue (as opposed to rebuilding the display list each frame). Remember that we rebuild display list when anything significant changes on the page (hover over something, etc.).

I don't want to dismiss adding a universal image display item in WR, but doing so isn't necessarily easier or cleaner than handing these format switches in gecko. We can still consider both options.

**Comment by nical** [comment]
It is maybe a silly idea but if we are worried about the cost of rebuilding the display list when a video changes its format, how about isolating video elements in their own pipeline? This would make it very cheap to build and serialize the small display list that only contains the video, although it would not affect the cost of re-building batches when the format changes.

**Comment by nical** [comment]
We can now change the format of an image in update_image (but not switch between rgb and yuv since yuv is composed of three images). Gecko now uses a pipeline per video.
