### ISSUE TITLE
Support tiling gradients

### ISSUE THREAD

**Issue by rlhunt** [servo/webrender#968]
Linear and radial gradients can be repeated or tiled when used as a background-image. I think it makes sense to support this in a single GradientDisplayItem. Glancing at ImageDisplayItem, it looks like it's already implemented.

**Comment by jrmuizel** [comment]
That sounds reasonable to me.

**Comment by rlhunt** [comment]
From a discussion on irc with @nical , I think there are two ways to implement this,
1. Adding support in the gradient shaders
2. Painting the gradient into an image and using ImageDisplayItem's repeat feature

I think it would probably be easiest to do in the shader, although I haven't looked into it yet.

**Comment by rlhunt** [comment]
This was fixed.
