### ISSUE TITLE
Seperate out Fonts from their particular variations

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#979]
Currently in Gecko we have a distinction between a gfxFontEntry and a gfxFont. To over simplify, gfxFontEntry can be thought of as font file and gfxFont as a reference to the gfxFontEntry as well as some collection of state about how to render it. This state varies depending on the platform and can include size, transform, synthetic bolding, hinting mode, subpixel mode, open type variations, etc.

Cairo calls these two kinds of things unscaled_fonts and scaled_fonts.

Pushing this distinction into WebRender looks like it will be necessary for making the management of fonts work with Gecko. Having this separation will allow Gecko to manage the lifetime of the webrender objects so that they line up with gfxFontEntry and gfxFont.

**Comment by glennw** [comment]
That seems reasonable and relatively simple to add (although will take a little while due to the cross platform nature of the font code).

**Comment by glennw** [comment]
@jrmuizel @lsalzman What's the best way to proceed here? Would it be best for you to sketch out what such an API might look like? Otherwise, I can try to sketch something out - but it's quite likely I'll miss some important details that are relevant to gecko.

**Comment by jrmuizel** [comment]
We'll come up with a sketch/implementation this week.

**Comment by glennw** [comment]
We have a plan here https://github.com/servo/webrender/issues/1431.
