### ISSUE TITLE
Validate the webrender display list that we get from the child

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#980]
Currently we just cast the bag of bytes to a slice of DisplayItem. This is obviously not safe if the bytes are controlled by an attacker.

I've been thinking about how to best to implement this while minimizing the performance and the best candidate that I've been able to come up with is a to implement a custom derive that 'serializes' these structs to a form that matches how Rust lays things out natively. This works around that fact that we have no way of getting the layout or discriminants of enums from the compiler. Once we are able to 'serialize' to a known form we can validate the things that we need to like enum discriminators and bools. Since the serialization should match the native form and we can do it item by item, I'm hoping the compiler will be able to optimize most of it away.

We don't need this urgently, so I'm thinking it might be a good starting project for @Gankro when he starts in April.

**Comment by SimonSapin** [comment]
Does serde + bincode serialization really have so much overhead that reducing it is worth playing with memory safety fire?

**Comment by jrmuizel** [comment]
> Does serde + bincode serialization really have so much overhead that reducing it is worth playing with memory safety fire?

That should certainly be confirmed with data before embarking on this task.

**Comment by nical** [comment]
Can we close this now that display lists use serde + bincode?

**Comment by Gankro** [comment]
Yes
