### ISSUE TITLE
Make it possible to enable/disable debug and profiler anytime

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#985]
*This issue is part of an effort to improve Servo's embedding story. See https://github.com/paulrouget/servoshell/projects/2*

At the moment, it's only possible to enable debug and profiler at init via `RendererOptions`. Can we make it so it's possible to change `wr-stats` and `wr-debug` via the wr api?

**Comment by glennw** [comment]
There is an existing API on the Renderer object for enabling / disabling the profiler - see https://github.com/servo/webrender/blob/master/webrender/src/renderer.rs#L1767. The wr-debug option doesn't currently do anything useful, but when we hook that up again we'll also add an API for it.

**Comment by paulrouget** [comment]
Can you add `ApiMsg` to set that up? I'm not sure how I'm supposed to access the Renderer object from `RenderApi`.

**Comment by paulrouget** [comment]
ok - scratch that. I understand now. Thanks.

**Comment by paulrouget** [comment]
See https://github.com/servo/servo/pull/16030
