### ISSUE TITLE
Drawing two box shadows results in a wierd second drawing

### ISSUE THREAD

**Issue by changm** [servo/webrender#990]
Test branch here - https://github.com/changm/webrender/tree/test

Just run the WR sample app

Some observations:
1) Rendering each of the box shadows independently works fine, its only when they are both drawn. Whichever box shadow is drawn second is the messed up one.
2) The cached box shadows look alright according to apitrace
3) The offsets / rects into the cached box shadow FBO look right
4) The segment rects here are correct and drawing into the right location

It almost seems like the top of the second box shadow is drawing the first cached box shadow, but at 1/4 scale which doesn't really make sense to me.

I'm kind of lost at this point, so any guidance would be helpful!

**Comment by changm** [comment]
<img width="1136" alt="untitled" src="https://cloud.githubusercontent.com/assets/1015726/24029950/3477e020-0a97-11e7-9a63-a4685a79be74.png">

Screenshot of the bug.

Screenshot from apitrace of the cached box shadows I think.

<img width="909" alt="apitrace" src="https://cloud.githubusercontent.com/assets/1015726/24029965/596d3506-0a97-11e7-8102-e6193b0a54b8.png">

**Comment by glennw** [comment]
@changm Fixed in https://github.com/servo/webrender/pull/992
